tooling/circle-scripts/publish.sh, tooling/jenkins-scripts/gate-jenkins.sh
=> fix(tooling): change readme hack to prevent npm from pointing latest at a canary release

Gruntfile.package.js
Fixes #30 
Trace only works on 4.5 or 6
https://github.com/AndreasMadsen/trace/blob/6bd45f36f8413ba64a436cf5e6df13c381fa043e/package.json#L36
=> use trace only on node 6 and up as it does not work for node v5

circle.yml, package.json, packages/example-phone/package.json, tooling/circle-scripts/publish.sh, tooling/jenkins-scripts/gate-jenkins.sh
1. They're more trouble than they're worth due to https://github.com/lerna/lerna/pull/287
2. Using the forked lerna version may be impacting gating jobs
=> Disable canary builds

src/client/mercury/mercury.js, src/client/mercury/socket/socket-base.js, src/client/services/board/realtime/realtime.js, test/unit/lib/mock-socket.js, test/unit/spec/client/mercury/mercury.js, test/unit/spec/client/mercury/socket.js, test/unit/spec/services/board/realtime.js
- Add the query bufferState to url so that we get buffer state everytime
- Register handler to socket messages before opening socket so what we won't miss the buffer state message
Code changes only in legacy as current plugin-mercury already has it
=> Add bufferState to socket url and register handler to messages before opening socket

package.json
The latest version of lerna is beta28, which causes bootstrapping to fail.
=> chore: lerna version static

packages/generator-ciscospark/generators/package/templates/_package.json
The package generator fails on `npm install` due to version 0.6.0 of many packages not being available. This resolves it.
=> chore: package generator version to 0.7.0-alpha

src/client/services/board/board.js, src/client/services/board/persistence/persistence.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/board.js, test/unit/spec/services/board/persistence.js
Added the api for board listing, which is fairly straight forward.  The only controversial element of this PR is the fact that I "ported" the parseLinkHeaders function to es5 and added to the board object.  In parallel, the board service is being ported to the modular SDK, which will obviously have this function omitted in favor of using the the Page object.
=> feat(board): added API for listing boards by converstionId

packages/plugin-conversation/src/conversation.js
Fix for when creating a convo, if it's one on one, we can't pass additional options to the get method.
=> fix(plugin-conversation): Add support for options in one on one convo

packages/plugin-board/src/board.js, packages/plugin-board/src/index.js, packages/plugin-board/test/integration/spec/board.js, packages/plugin-board/test/unit/spec/board.js, src/client/services/board/persistence/persistence.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/persistence.js
To add a snapshot for a white board, we upload the snapshot image to spark files then attach metadata to a board.
Resolves #273
=> feat(plugin-board): add upload snapshot for board 

packages/plugin-board/package.json, packages/plugin-board/src/board.js, packages/plugin-board/src/index.js, packages/plugin-board/src/realtime.js, packages/plugin-board/test/integration/spec/board.js, packages/plugin-board/test/integration/spec/realtime.js, packages/plugin-board/test/unit/spec/board.js, packages/plugin-board/test/unit/spec/realtime.js, src/client/services/board/board.js, src/client/services/board/persistence/persistence.js, src/client/services/board/realtime/realtime.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/board.js, test/unit/spec/services/board/persistence.js, test/unit/spec/services/board/realtime.js
Newly created board will have its own ACL and encryption key instead of using conversation ID. A board's ACL parent will be the conversation ACL URL.
Changes made to
Persistence:
- createChannel - takes in conversation and use the aclUrl as aclUrlLink (parent acl)
- addContent - no longer needs conversation's encryptionKeyUrl but rather use board's encryptionKeyUrl instead
- addImage - uploads to a space created by board service instead of using conversation's space
- setSnapshotImage - same as addImage (upload to board space)
- getChannels - takes in conversation and query using aclUrl
Realtime:
- publish - now takes in channel as well (to get the encryption key)
=> feat(board): Board ACL Switch

packages/plugin-board/src/board.js, packages/plugin-board/src/realtime.js, packages/plugin-board/test/integration/spec/board.js, packages/plugin-board/test/integration/spec/realtime.js, packages/plugin-board/test/unit/spec/board.js, packages/plugin-board/test/unit/spec/realtime.js, src/client/services/board/board.js, src/client/services/board/persistence/persistence.js, src/client/services/board/realtime/realtime.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/board.js, test/unit/spec/services/board/realtime.js
Before we're adding file content to whiteboard as
```
{
type: 'FILE',
payload: {
mimeType: file.type,
fileSize: file.size,
displayName: encryptedDisplayName
scr: encryptedSCR
}
}
```
The server now requires type FILE to have `file` property:
```
{
type: 'FILE',
payload: { // now is metadata
displayName: encryptedDisplayName
},
file: {
mimeType: file.type,
fileSize: file.size,
scr: encryptedSCR,
url: scr.loc
}
}
```
=> feat(board): Support image file content

packages/common/package.json, packages/common/src/base64.js, packages/common/src/shims/atob.js, packages/common/src/shims/atob.shim.js, packages/common/src/shims/btoa.js, packages/common/src/shims/btoa.shim.js, packages/common/test/unit/spec/common.js
use urlsafe-base64 package as similar to node-jose
resolves #95
=> refactor(common): replace base64 methods implementation with package

packages/spark-core/src/interceptors/response-logger.js
the feature toggle list has gotten long enough that logging it has a
real perf burden and real build-size impact
=> refactor(spark-core): suppress feature toggle list in verbose network logs

packages/spark-core/src/interceptors/request-logger.js, packages/spark-core/src/interceptors/response-logger.js
I kept the `console` as a fall-back, just in case; AFAIK, `options.logger` was the wrong reference.
It's not the case (without the work of yet another interceptor) that the `logger` is on `options`.
Effectively, this meant (for us, and likely others) that logging would always fall-back to `console`.
IIRC, the interceptor's `this` reference has a `spark`, on which the `logger` plugin is registered.
Also cross-referencing #441 for an oft-related (and still existing, but minor) issue involving replacing the `logger`. We hacked around that issue by explicitly registering the stock `logger` plugin first, then replacing it with our own, which works for us since we never use the default instance.
=> fix(spark-core): interceptors ignore plugin-logger

package.json, packages/eslint-config/package.json, packages/eslint-config/react.js
The `no-marquee` rule was changed in 4.0.0. We need this update to come through because apparently we can't have 4.0.0 in the react repo and 3.X in the `@ciscospark/eslint-config` package.
=> chore(eslint-config): upgrade to jsx-a11y 4.0.0

Gruntfile.package.js, packages/plugin-board/src/board.js, packages/plugin-board/src/config.js, packages/plugin-board/src/realtime.js, packages/plugin-board/test/integration/spec/realtime.js, packages/plugin-board/test/integration/spec/sharing-mercury.js, packages/plugin-board/test/unit/spec/board.js, packages/plugin-board/test/unit/spec/realtime.js, packages/plugin-mercury/package.json, packages/plugin-mercury/src/index.js, packages/plugin-mercury/src/mercury.js, packages/plugin-mercury/src/socket/socket-base.js, packages/plugin-mercury/test/integration/spec/sharable-mercury.js, packages/plugin-mercury/test/unit/spec/mercury.js, packages/plugin-mercury/test/unit/spec/socket.js, packages/test-helper-mock-spark/src/index.js, src/client/mercury/mercury.js, src/client/mercury/socket/socket-base.js, src/client/services/board/board.js, src/client/services/board/persistence/persistence.js, src/client/services/board/realtime/realtime.js, test/integration/spec/services/board/actions.js, test/integration/spec/services/board/sharable-mercury.js, test/unit/spec/client/mercury/mercury.js, test/unit/spec/client/mercury/socket.js, test/unit/spec/services/board/board.js, test/unit/spec/services/board/persistence.js, test/unit/spec/services/board/realtime.js
For now, sharing web socket is hiding behind the feature toggle `web-shared-mercury`
Two changes are in this PR (let me know if I should split this into two PRs)
When `web-shared-mercury` is enabled, mercury will allow sharing its socket connection,
- webSocketUrl changes from having query parameter `bufferState=true` to `mercuryRegistrationStatus=true&registrationRefreshStatus=true` (`registrationRefreshStatus=true` is a server side toggle, which will be removed when we remove feature toggle)
- add two methods to allow adding and removing board bindings from mercury connection
- refactor connectByCreatingNewSocket by combining register() and connect() (before, sdk user needs to manually do those steps)
=> feat(mercury+board): sharing mercury web socket

package.json, packages/plugin-encryption/package.json
A critical vulnerability was found in many jose implementations.
node-jose@0.9.3 address the vulnerability.
=> fix(plugin-encryption): update to node-jose 0.9.3 or later

package.json, packages/common/package.json, packages/plugin-board/src/realtime.js, packages/plugin-board/test/unit/spec/realtime.js, packages/plugin-credentials/package.json, packages/plugin-mercury/package.json, packages/plugin-mercury/src/errors.js, packages/plugin-mercury/src/index.js, packages/plugin-mercury/src/mercury.js, packages/plugin-mercury/src/socket/socket-base.js, packages/plugin-mercury/test/integration/spec/mercury.js, packages/plugin-mercury/test/unit/spec/mercury.js, packages/plugin-mercury/test/unit/spec/socket.js, packages/plugin-metrics/package.json, packages/plugin-wdm/package.json, packages/plugin-wdm/test/integration/spec/device.js, packages/spark-core/package.json
This puts us in position to easily add support for additional codes once we have a complete plan of action for how to handle multiple sockets
Note: commented-out code blocks are intentional; the NotFound close code doesn't quite work as intended, but the rest of these changes are still helpful without it.
=> robust close codes

packages/node_modules/@ciscospark/plugin-board/src/board.js, packages/node_modules/@ciscospark/plugin-board/test/integration/spec/board.js, packages/node_modules/@ciscospark/plugin-board/test/unit/spec/board.js, packages/node_modules/@ciscospark/plugin-encryption/src/kms.js, packages/node_modules/@ciscospark/plugin-encryption/test/integration/spec/kms.js, src/client/services/board/persistence/persistence.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/persistence.js
Currently, KMS server also authorizes the resource creator, in this case it adds
the board creator to board KRO on `createChannel`, which we don't want. We want only
conversation KRO to be in the list of authorization. 
As a result, board creator can have access to board encryption key even after leaving the conversation.
This PR checks if the board creator is authorized, if so remove the auth.
KMS is making changes to this, however, we don't know when that happens.
=> fix(board): ensure board creator does not get authorized to board KRO

docker/builder/cmd.sh, packages/node_modules/@ciscospark/bin-sauce-connect/src/start.js, packages/node_modules/@ciscospark/plugin-calendar/README.md, packages/node_modules/@ciscospark/plugin-calendar/package.json, packages/node_modules/@ciscospark/plugin-calendar/src/calendar.js, packages/node_modules/@ciscospark/plugin-calendar/src/config.js, packages/node_modules/@ciscospark/plugin-calendar/src/index.js, packages/node_modules/@ciscospark/plugin-calendar/test/.eslintrc.yml, packages/node_modules/@ciscospark/plugin-calendar/test/index.js, packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
This is just a small update to Uday's approved PR https://github.com/ciscospark/spark-js-sdk/pull/383  to add a bump parameter to sauce connect in order for tests to run on Sauce via tunneling. Also updated code to work on latest sdk master.
@ianwremmel Please Review
There's some WIP work for updating this to use the new Whistler endpoint, but that's being blocked by a decryption bug in Calendar. Will add that to another PR when that is fixed.
=> Implement fetching meetings via calendar hybrid service

packages/node_modules/@ciscospark/plugin-board/test/integration/spec/board.js
Sometimes karma runs test multiple times on the same browser in
parallel, which creates more channels than expected for one
conversation. This change should protect these tests from mentioned race
condition.
=> test(plugin-board): create new conversation for channel listing test

packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
Add feature toggle when registering spark device during plugin-calendar integration test.
Hopefully this fixes issue mentioned in Build Squad
@ianwremmel
=> fix(plugin-calendar): Add feature toggle for plugin-calendar

packages/node_modules/@ciscospark/plugin-avatar/src/avatar-url-batcher.js, packages/node_modules/@ciscospark/plugin-avatar/src/avatar-url-store.js, packages/node_modules/@ciscospark/plugin-avatar/src/avatar.js, packages/node_modules/@ciscospark/plugin-avatar/src/config.js, packages/node_modules/@ciscospark/plugin-avatar/test/integration/spec/avatar.js, packages/node_modules/@ciscospark/plugin-avatar/test/unit/spec/avatar-url-store.js, packages/node_modules/@ciscospark/plugin-avatar/test/unit/spec/avatar.js, packages/node_modules/@ciscospark/spark-core/src/lib/batcher.js
fix(@ciscospark/plugin-avatar): Avatars are not retrieved and stored correctly when attempting to batch large numbers of requests
Fixes #564 
Web client requests many avatars on load and when entering spaces with large numbers of people. These requests are often duplicated many times as well. Usually a duplicate request through spark-core.batcher.request returns a deferred promise that resolves with the original, non-duplicate request's promise. However, these conditions introduce a race condition that can cause a duplicate to be resolved on an original's promise *after* cleanup code defined in batcher.request has been executed. The cleanup causes the promise to resolve to "true" instead of the request response and introduces issue #564. This problem is addressed in commit …
=> Sdkv7 avatar

packages/node_modules/@ciscospark/helper-html/src/html.js, packages/node_modules/@ciscospark/helper-html/src/html.shim.js, packages/node_modules/@ciscospark/helper-html/src/index.js, packages/node_modules/@ciscospark/helper-html/test/unit/spec/html.js, packages/node_modules/@ciscospark/plugin-conversation/src/index.js, packages/node_modules/@ciscospark/plugin-conversation/test/integration/spec/verbs.js
I'm not really convinced this is the right behavior for convo, but it's what the web client does now. After updating the convo tests and a conversation with @pcl, I'm reasonably convinced the right behavior is to reject messaged with disallowed html. That, however, is a PM/UX decision that'll need to be made product wide. Until then, this seems to be the "most correct" of the available options.
=> Reimplement filterEscape and restore pre 0.7 convo behavior

packages/node_modules/@ciscospark/internal-plugin-support/src/support.js, packages/node_modules/@ciscospark/internal-plugin-support/test/integration/spec/support.js, packages/node_modules/@ciscospark/internal-plugin-support/test/unit/spec/support.js
Fixes failure to upload logs from web-client
=> refactor(@ciscospark/i-plugin-support): call getUserToken on submitLogs

package.json, tooling/lint-package-names.sh
We inadvertently published two bad releases because of a package name collision. This linter ensures that package names match their directory name
=> fix(tooling): add package name linter

packages/node_modules/@ciscospark/internal-plugin-conversation/src/conversation.js, packages/node_modules/@ciscospark/internal-plugin-conversation/src/convo-error.js, packages/node_modules/@ciscospark/internal-plugin-conversation/src/index.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/integration/spec/create.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@ciscospark/internal-plugin-user/src/user-uuid-batcher.js, packages/node_modules/@ciscospark/internal-plugin-user/test/unit/spec/user-uuid-batcher.js
Previously, when creating a user, it did not handle the scenario when a user cannot be created. Also, it would fail creating a conversation if there were any invalid users. This PR adds an additional option, which allows the conversation to be created without the invalid users.
=> fix(internal-plugin-conversation): handle user and convo creation errors

packages/node_modules/@ciscospark/internal-plugin-board/src/board.js, packages/node_modules/@ciscospark/internal-plugin-board/src/index.js, packages/node_modules/@ciscospark/internal-plugin-board/src/realtime.js, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/unit/spec/board.js
- image files now have no payload (to be consistent with other clients)
- if metadata is specified when `addImage` then payload will contain metadata
- `getChannels` now allows option `type` which can have values: whiteboard or annotated (by default if type is empty then server takes it as type `whiteboard`).
=> refactor(@ciscospark/internal-plugin-board): allow image files to have no payload

packages/node_modules/@ciscospark/internal-plugin-metrics/src/call-diagnostic-events-batcher.js, packages/node_modules/@ciscospark/internal-plugin-metrics/src/metrics.js, packages/node_modules/@ciscospark/internal-plugin-metrics/test/unit/spec/call-diagnostic-events-batcher.js, packages/node_modules/@ciscospark/internal-plugin-metrics/test/unit/spec/metrics.js
Add a new function `submitCallDiagnosticEvents` in metrics plugin with callDiagnosticEventsBather to support of sending call diagnostic event to `/clientmetrics`.
=> feat(@ciscospark/internal-pulgin-metrics): support call diagnostic event

packages/node_modules/@ciscospark/internal-plugin-avatar/src/avatar-url-batcher.js, packages/node_modules/@ciscospark/internal-plugin-avatar/src/avatar-url-store.js, packages/node_modules/@ciscospark/internal-plugin-avatar/src/avatar.js, packages/node_modules/@ciscospark/internal-plugin-avatar/src/config.js, packages/node_modules/@ciscospark/internal-plugin-avatar/test/unit/spec/avatar.js
This PR exposes whether an avatar is a default avatar or not. Also, when an avatar is requested, it fetches all sizes of the avatar and stores them into the cache so that they will all match when different sizes are fetched and expire the same time
=> fix(avatar): add defaultAvatar param and fetch all sizes of avatars

packages/node_modules/@ciscospark/plugin-people/src/people.js, packages/node_modules/ciscospark/src/ciscospark.js, packages/node_modules/ciscospark/src/index.js, packages/node_modules/ciscospark/src/plugins/memberships.js, packages/node_modules/ciscospark/src/plugins/messages.js, packages/node_modules/ciscospark/src/plugins/rooms.js, packages/node_modules/ciscospark/src/plugins/team-memberships.js, packages/node_modules/ciscospark/src/plugins/teams.js, packages/node_modules/ciscospark/src/plugins/webhooks.js
- Standardize wording across objects
- Add `text`/`markdown` properties to `MessageObject` (closes #680)
- Change several property types from `uuid` to `string`
- Correct several `@link` links
=> API Documentation Updates

package.json
A security vulnerability was reported for the existing version of package qs. Upgraded it to fix the issue.
High severity vulnerability found on qs@5.2.1
desc: Prototype Override Protection Bypass
https://snyk.io/vuln/npm:qs:20170213
=> fix(@ciscospark/http-core): upgrade package "qs"

packages/node_modules/@ciscospark/internal-plugin-conversation/src/conversation.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/integration/spec/verbs.js
Add ability to set/unset ANNOUNCEMENT tag to conversations.
https://sqbu-github.cisco.com/WebExSquared/cloud-apps/wiki/Announcement-Only-Spaces-Design
=> feat(@ciscospark/internal-plugin-conversation): set/unset space property

packages/node_modules/@ciscospark/internal-plugin-board/src/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/unit/spec/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/unit/spec/encryption.js
- add lockChannelForDeletion to lock channel before deleting or to tell
whether a channel cannot be locked since it is in use
- move encryption related unit tests to unit/spec/encryption
=> feat(@ciscospark/i-p-board): prevent deletion of active whiteboard

packages/node_modules/@ciscospark/internal-plugin-mercury/src/mercury.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/integration/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/unit/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/service-collection.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/service-model.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/index.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/lib/device-fixture.json, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/service-collection.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/service-model.js, packages/node_modules/@ciscospark/test-helper-mock-spark/src/index.js
- feature toggle `web-ha-messaging`
- when we get a new catalog, we parse service and serviceHostMap and
encapsulate into serviceCatalog collection
- getWebSocketUrl should now replace webSocketUrl due to its ability
to take datacenter availability into account
- add new method to mark current service url as fail and get a new one,
it cycles through all the host and when all hosts fail, it requests
new service registration info from wdm
=> feat(@ciscospark/i-p-wdm): support Spark High Availability Design

packages/node_modules/@ciscospark/test-helper-test-users/src/index.js
on line 86, token is being pushed in as
```javascript
users.push({
token: {
access_token: process.env['CISCOSPARK_ACCESS_TOKEN_' + i]
}
})
```
so the assert should be `assert(users[j].token.access_token`
=> fix(@ciscospark/test-helper-test-users): assert the correct access_token

packages/node_modules/@ciscospark/spark-core/src/interceptors/auth.js, packages/node_modules/@ciscospark/spark-core/src/lib/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js
if token.revoke fails, credentials.refresh() should still succeed. failure happens when there is an old token that was not cleaned up when logging out
I think this PR also addresses the error when logging out: https://github.com/ciscospark/spark-js-sdk/pull/796, but might be good to have both changes in. Even if token.revoke fails for a different reason, we still want credentials.refresh() to succeed
=> fix(@ciscospark/spark-core): catch token revocation failure

packages/node_modules/@ciscospark/helper-image/src/index.js
Previously we use `new Buffer(byteLength)` to instantiate a new buffer,
then copy from our file arrayBuffer to this new buffer. 
https://github.com/ciscospark/spark-js-sdk/blob/d16dadc8a80f6760eaa28270c13a299b179e4f26/packages/node_modules/%40ciscospark/helper-image/src/index.js#L50-L56
Since `new Buffer` is deprecated, using `Buffer.from` should produce the desired behavior
=> fix(@ciscospark/helper-image): copy from buffer using Buffer.from

packages/node_modules/@ciscospark/internal-plugin-board/src/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/unit/spec/board.js
If the board is opened by the user and there is no further user activity on it, we can use this event to mark it as still being used and prevent other users from deleting it
=> feat(@ciscospark/i-p-board): channel keep alive

packages/node_modules/@ciscospark/internal-plugin-conversation/src/conversation.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/integration/spec/create.js
Fixes posting markdown when creating a 1:1 space. Previously, it only took `displayName`. However, it needs to handle `content` for markdown.
* SDK Version
* Node/Browser Version: 8.9.4
* NPM Version: 5.6.0
=> fix(@ciscospark/i-p-conversation): allow markdown when creating 1:1

packages/node_modules/@ciscospark/internal-plugin-team/src/index.js, packages/node_modules/@ciscospark/internal-plugin-team/test/integration/spec/mercury.js, packages/node_modules/@ciscospark/test-helper-mocha/src/index.js
There is a new activity event with teamRoomStatus object type. https://sqbu-github.cisco.com/gist/brialam/6702e04c04f59fd97526b0fb3caaee36 This PR handles the decryption of this new objectType
* SDK Version
* NPM Version
=> feat(@ciscospark/i-p-team): handle teamRoomStatus decryption

packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/ping.js, packages/node_modules/@ciscospark/plugin-authorization-browser/test/integration/spec/authorization.js, packages/node_modules/@ciscospark/plugin-authorization-node/test/integration/spec/authorization.js, packages/node_modules/@ciscospark/test-helper-appid/README.md, packages/node_modules/@ciscospark/test-helper-appid/src/create-user.js, packages/node_modules/@ciscospark/test-helper-appid/src/router.js, tooling/lib/test/index.js, wdio.conf.js, webpack.config.js
JWT generation was not using the parameters as documented on the [developer portal](https://developer.ciscospark.com/guest-issuer.html). These changes will allow us to match the style as well as gives some new options.
There was also an issue with `dotenv` importing order that has been resolved.
=> Add ability to provide more options to appid user

docs/_posts/guides/9999-01-04-servers.md
requestAuthorizationCodeGrant namespace was incorrect in last example even though it was corrected in a previous example.
=> Fixes namespace of requestAuthorizationCodeGrant in node documentation

packages/node_modules/@ciscospark/plugin-phone/src/index.js, packages/node_modules/@ciscospark/plugin-phone/src/phone.js, packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/lib/event-expectations.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/call.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/phone.js
A few things on this PR:
* A new phone event `call:created` was added
* Whenever a locus event happens to a call we aren't aware of via `emittedCalls`, the event will trigger
* Event names have been exported as an object `phoneEvents` to reduce the amount of "magic strings"
* Refactored the register locus listing to use the `listActiveCalls` method
* Expanded integration tests
=> feat(@ciscospark/plugin-phone): add call:created event

packages/node_modules/@ciscospark/helper-image/package.json, packages/node_modules/@ciscospark/helper-image/src/detect-filetype.js, packages/node_modules/@ciscospark/helper-image/src/index.js, packages/node_modules/@ciscospark/helper-image/src/process-image.browser.js, packages/node_modules/@ciscospark/helper-image/src/process-image.js, packages/node_modules/@ciscospark/internal-plugin-avatar/src/avatar.js, packages/node_modules/@ciscospark/internal-plugin-avatar/src/config.js, packages/node_modules/@ciscospark/internal-plugin-avatar/test/unit/spec/avatar.js, packages/node_modules/@ciscospark/internal-plugin-conversation/package.json, packages/node_modules/@ciscospark/internal-plugin-conversation/src/share-activity.js
Fixes issue with the image orientation on profile avatars. The code for the same was earlier available as part of internal-plugin-conversation, but that is moved to helper-image so that the same code with minimal changes could be utilized for internal-plugin-avatar.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-2864
- Test images to reproduce and verify the existing bug could be referred from: https://github.com/recurser/exif-orientation-examples
* SDK Version
* NPM Version
=> fix(internal-plugin-avatar): profile image orientation

packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/ping.js
The services are stripped of the `url` in their listing. It started failing recently because they changed the allowed CORS to the service.
=> test(i-p-wdm): fix incorrect speechServicesManager name

packages/node_modules/@ciscospark/bin-sauce-connect/src/start.js
The current version of sauce connect no longer works and needs to be updated.
=> chore(bin-sauce-connect): update sc version to 4.4.8

docker/builder/cmd.sh, packages/node_modules/@webex/sparkd/README.md, packages/node_modules/@webex/sparkd/bin/sparkd, packages/node_modules/@webex/sparkd/package.json, packages/node_modules/@webex/sparkd/src/config.js, packages/node_modules/@webex/sparkd/src/index.js, packages/node_modules/@webex/sparkd/src/memory-store.js, packages/node_modules/@webex/sparkd/src/session.js, packages/node_modules/@webex/sparkd/src/spark.js, packages/node_modules/@webex/sparkd/test/integration/spec/session.js, tooling/commands/test.js, tooling/lint-package-names.sh
Adds the first @webex org package to publish. `sparkd` is not a dependency of any other package and is in low, specialized use, making it a good candidate to test rebranding. 
Introduces a change to the test script so that specific packages are ignored by browser tests. Some packages are meant to run only in Node, so we now have the ability to configure that and avoid confusion when running tests via command line. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SSDK-1910
```
npm test -- --package @webex/sparkd 
npm test -- --package @ciscospark/sparkd 
npm test -- --package @webex/sparkd --node
npm test -- --package @webex/sparkd --browser
npm test -- --package @webex/plugin-rooms
```
* SDK Version: 1.31
* …
=> Add @webex/sparkd package

SCRIPTS.md, browsers-ng.js
Since firefox is a source of pain currently, this change will allow us to provide a command line variable to limit which browser the tests are run on. 
* SDK Version
* NPM Version
=> chore(testing): add ability to limit browsers

packages/node_modules/@ciscospark/internal-plugin-mercury/src/mercury.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/service-collection.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/service-model.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/ping.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/device.js
On a network reconnect the web-client currently fails to sync to fetch the new messages and always displays a 'Reload' banner to load the client manually. On further analysis it is observed that due to HA changes, web-client tends to try different URLs to connect to mercury on failure. After exhausting the mercury URL list, it marks them as failed and tries to do a device re-registration. Since the client is offline, the device registration never succeeds and brings the client in a limbo state. Having exhausted all the mercury URLs, it does not try to reconnect on getting back online again and ends up showing the 'Reload' banner.
The fix is to recycle the mercury URLs, when the list is exhausted, whenever this scenario happens and then attempt connecting them again trying one URL at a …
=> fix(i-p-mercury): kick off syncing process on network reconnect

packages/node_modules/@ciscospark/spark-core/src/lib/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js
If the `state` param was an empty object, it would be encoded and added to the URL.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SSDK-1931
This is unrelated, but a Chrome test is failing:
```
FAILED TESTS:
#initialize()
✖ schedules a refreshTimer
Chrome 66.0.3359 (Mac OS X 10.13.4)
AssertError: expected refresh to have been called at least once but was never called
```
=> fix(credentials): exclude state from URL when it is empty

packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/events-model.js
Integration environment removes notifications for spaces bigger than 15.
From Locus Team:
> on the test failing in integration on alertType - how easy is it to run the test with <15 test users? I see that we have a config that turns off alerts when number of participants > 15.
> On prod this value is set to 25
=> test(plugin-phone): reduce the # of test users

packages/node_modules/@ciscospark/internal-plugin-mercury/src/mercury.js
Adds a check to make sure HA is enabled before fetching the new websocket URL list as part of HA work.
Fixes # (issue) https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-20161
* SDK Version
* NPM Version
=> fix(i-p-mercury): fetch new websocket URL when HA enabled

.snyk, package.json
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/npm:braces:20180219
- https://snyk.io/vuln/npm:lodash:20180130
- https://snyk.io/vuln/npm:validator:20180218
The following vulnerabilities are fixed with a Snyk patch:
- https://snyk.io/vuln/npm:qs:20140806-1
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-20576
These patches fix tooling (reports, etc.) so there is no direct way to test them. However, I ran the tests once and noted any unique failures. All of those pass locally or produce no new errors. 
*Pass*
- Chrome_67_0_3396_(Mac_OS_X_10_12_6).@ciscospark/plugin-memberships.plugin-memberships.plugin-memberships #memberships #get() "before all" hook
- …
=> Patch & upgrade packages to reduce vulnerabilities

browsers-ng.js
Safari tests on previous versions of macOS have started failing. In order to get them passing, using a newer test image resolves the issue.
Ran the full suite of tests with the new version and safari tests passed where they were previously failing.
- [] I have commented my code, particularly in hard-to-understand areas
- [] Any dependent changes have been merged and published in downstream modules
=> chore(testing): update to latest macOS version

packages/node_modules/@ciscospark/recipe-private-web-client/README.md, packages/node_modules/@webex/recipe-private-web-client/README.md, packages/node_modules/@webex/recipe-private-web-client/package.json, packages/node_modules/@webex/recipe-private-web-client/src/config.js, packages/node_modules/@webex/recipe-private-web-client/src/index.js, tooling/lint-package-names.sh
There was a note on the `@ciscospark/recipe-private-web-client` package to remove it. However, the web client is still using this package. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-26483
=> Reinstate recipe-private-web-client

packages/node_modules/@ciscospark/spark-core/src/lib/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js
The change fixes the issue where the refresh_token is expired for a user, as a result when a request for refreshing the access_token is made, it fails too with an error "The refresh token provided is expired, revoked, malformed, or invalid". This results in hanging of the web-client. We would want the user to be logged out when this condition is met.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-5100
* SDK Version
* NPM Version
=> fix(spark-core): emit InvalidRequestError, if refresh token expires

packages/node_modules/@ciscospark/plugin-phone/src/phone.js, packages/node_modules/@ciscospark/plugin-phone/test/lib/locus.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/phone.js
Call objects will still emit locus events, but the main phone pluginshould not create calls for inactive locus events.
Fixes # SPARK-18814
=> feat(plugin-phone): remove call:created event for inactive loci

packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/policy.js
The logout timer currently runs only once to determine if the client is inside or outside the corporate boundary and hence does not handle the case where in the client goes outside the boundary after the first check. We need to reset the logout timer after every successful check so that it keeps checking after some interval.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-25130
All tests on internal-plugin-wdm passes locally.
=> fix(i-p-wdm): resets logout timer after receiving pong

packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/screenshare.js
The way the sdk is currently working, when setting the share media to inactive, firefox 61 now removes our content field from the media object. I've setup the tests to handle either situation, both of which are allowed and function properly.
`npm test -- --package @ciscospark/plugin-phone --browser`
=> test(plugin-phone): add check for if screen exists

packages/node_modules/@ciscospark/spark-core/src/config.js, packages/node_modules/@ciscospark/spark-core/src/interceptors/auth.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/interceptors/auth.js
The following changes allow passing auth token to a list of whitelisted domains.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-31712
Added tests to ensure that the auth tokens are added in the request header only for whitelisted domains.
=> feat(spark-core): allow auth token on whitelisted domains

packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/lib/event-expectations.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/group-calling.js
Adds a `host` field to the `Call` object for group enabled calling. This field will be the replacement for `call.from` which only works with 1:1 calls.
It also starts the tests for configs with the `enableExperimentalGroupCallingSupport` enabled.
Fixes #930 
* SDK Version
* NPM Version
=> Group call "host" field added

packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/group-calling.js
Adds a `roomId` field to the call object when group calling is enabled.
Fixes #930 
=> feat(plugin-phone): add roomId to call object

packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/lib/device-fixture.json
The wdm response returns back support props such as partner/customer logos, help links, support links, etc. However this was not getting saved onto the device object and not getting passed to the web client. This PR adds those props to the device object
* SDK Version
* NPM Version
=> fix(internal-plugin-wdm): add missing support props on device object

packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/state-parsers.js
If a device is not associated to a user, it should be considered its own membership and treated as one.
This is to fix the issue of a 1:1 call to a device not registering the device as a member and the call never ends if the device hangs up first.
Fixes # SPARK-29430
* SDK Version v1.41.0
* Node/Browser Version 8.11.3
* NPM Version 5.6.0
=> fix(plugin-phone): add devices to memberships

packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js, packages/node_modules/@ciscospark/plugin-phone/test/lib/locus.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/replacement.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/state-parsers.js
Usage of `locus.self.deviceUrl` did not work properly in all scenarios.
Fixes # SPARK-37709
=> feat(plugin-phone): use device status from devices to determine joined

README.md
The node sample was using `ciscospark` instead of `ciscospark/env`,
`ciscospark/env` is the recommended way to use the SDK in a non-browser environment.
However, I suggest that we start to move away (and possible deprecation) from `ciscospark/env` and have people move to just `ciscospark` and have users explicitly `init()` the library.
`/env`'s grabbing of the access token and initializing the SDK "automagically" isn't the best and having two different ways to initiate the SDK is just confusing at the end of the day.
I've included a section that still tells users how to use `ciscospark/env`
I'm also suggesting moving away from the Browserify sample and move to a Parcel sample.
Fixes [38320](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-38320)
=> Remove /env from the README 

test.py
CI/KMS was getting confused between the two equivalent, but differently named, Hydra URLs, https://hydra-intb.ciscospark.com/v1 and https://apialpha.ciscospark.com/v1/. 
Update to https://apialpha.ciscospark.com/v1/.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-44902
python test.py
=> Update Hydra URL in test script

packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/lib/device-fixture.json
Adds the field to Device so that org level permissions can be set to block or allow Giphys.
* SDK Version
* NPM Version
=> feat(internal-plugin-wdm): add clientMessagingGiphy field to Device

packages/node_modules/@ciscospark/internal-plugin-search/src/search.js, packages/node_modules/@ciscospark/internal-plugin-search/test/integration/spec/search.js
Remove query check from search request.
This allows us to search for all items in a convo rather than having to match with a string. For example, I needed a search that returns all files in a conversation. 
* SDK Version
* NPM Version
=> fix(search): remove query check

Jenkinsfile, package-lock.json
Samples are not working on prod because they are now built with integration URLs. This exports the proper environment variables in the "build docs" stage of the pipeline so samples are built with prod URLs. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-51238
=> Fix samples in production

Jenkinsfile, package.json, tooling/lib/build.js, webpack.config.js
Update samples' webpack config to use production urls instead of BTS when building in the pipeline/for production
Fixes #[51238](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-51238)
=> fix(samples): use production urls when building samples through webpack

packages/node_modules/@ciscospark/internal-plugin-presence/src/config.js, packages/node_modules/@ciscospark/internal-plugin-presence/src/presence-batcher.js, packages/node_modules/@ciscospark/internal-plugin-presence/src/presence.js, packages/node_modules/@ciscospark/internal-plugin-presence/test/integration/spec/presence.js, packages/node_modules/@webex/recipe-private-web-client/src/index.js
Enabled presence module for web-client use.
Added batching handling to presence list function.
Previously, web-client was making the apheleia requests itself. We're now going to rely on the sdk instead.
Apheleia's list and subsribe requests have a cap of 50 ids per request. Subscribe() already handles more than 50 ids with batches. Copied that logic over to list().
* SDK Version
* NPM Version
=> feat(presence): enable presence for web-client

packages/node_modules/@ciscospark/common/test/unit/spec/exception.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/space.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/integration/spec/ping.js, packages/node_modules/@ciscospark/spark-core/package.json, packages/node_modules/@ciscospark/test-helper-mocha/src/index.js
- Update contributors on `spark-core` package. I believe this will trigger the necessary updates for `ciscospark`. 
- Remove `skipInIE` in favor of using *bowser* directly in the test files. `skipInIE` was not working; I suspect that child processes did not have the right context, similar to the `flaky` method failing earlier. 
- Mark *ping* tests as flaky. Services in the Integration environment have been flaky and are blocking builds. I believe these tests may have value as TAP tests, but within the context of updating packages, they merely frustrate. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-50339
=> Update contributors & skip flaky tests

README.md, packages/node_modules/ciscospark/README.md
The gitcdn script is broken and after investigating, the way it was built was looking in `/dist` after webpack built packages (which is redundant).
So just remove references to gitcdn, but still allow rollup to build the script just don't advertise it (because at this point it is more work to remove the build process for it and _"eventually"_ will be fixed)
=> remove references to gitcdn script since it's broken

.babelrc, karma-ng.conf.js, package-lock.json, package.json, packages/node_modules/@ciscospark/common/test/unit/spec/exception.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/space.js, packages/node_modules/@ciscospark/media-engine-webrtc/src/engine.js, packages/node_modules/@ciscospark/media-engine-webrtc/test/unit/spec/engine.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/media-state-controls.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/screenshare.js, packages/node_modules/@ciscospark/test-helper-mocha/src/index.js, tooling/lib/test/karma.js
Upgrades `bowser` to appropriately skip IE 11 Lyra tests. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-62550
> New and existing unit tests pass locally with my changes
Existing failing tests have not been fixed. They are [documented](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-42359?filter=18897).
=> Fix skipping IE 11 Lyra tests

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/report-generator.js
2 unnamed imports in the plugin were assuming default exports which did not match expectations. In one case (InvalidEmaillAddressError) this caused an exception, the other potentially a strange dependency issue when the js-sdk is consumed by the atlas client.
Fixes issues integrating with Atlas Client UI.
A separate change is included which is a straightforward refactor of a request into it's own method. 
All existing tests run and still pass
* SDK Version
* NPM Version
=> Fixing issues with unnamed imports

packages/node_modules/@ciscospark/internal-plugin-metrics/src/metrics.js, packages/node_modules/@ciscospark/internal-plugin-metrics/test/unit/spec/metrics.js
We currently whitelist which properties we send to metrics-a. This allow us to send "context" which is a required field when piping metrics through segment A to segment. 
* SDK Version
* NPM Version
=> fix(metrics): allow context through the whitelist

packages/node_modules/ciscospark/src/ciscospark.js
Remove `plugin-meetings` until it replaces `plugin-phone`, e.g., samples, tests. 
Fixes NA
=> Do not include plugin-meetings by default

browsers-ng.js, browsers.js, packages/node_modules/@ciscospark/media-engine-webrtc/browsers.js, packages/node_modules/@ciscospark/plugin-phone/browsers.js
Move to headless browsers for local testing to stop unnecessary karma window from opening
* SDK Version
* NPM Version
=> Move to headless browsers for local testing

packages/node_modules/@ciscospark/internal-plugin-conversation/src/conversation.js, packages/node_modules/@ciscospark/internal-plugin-mercury/src/mercury.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/integration/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/unit/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-team/src/team.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/interceptors/server-error.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/interceptors/server-error.js, packages/node_modules/@ciscospark/plugin-phone/src/call.js
change web-ha-messaging to web-high-availability-messaging.
1. Older version of SDK code is still using the web-ha-messaging toggle.
2. We turn it on, and if they are not using your latest code, then the recent widget or SDK calls will break
Fix
* SDK Version
* NPM Version
=> fix: change web-ha-messaging to web-high-availability-messaging

packages/node_modules/@ciscospark/common/src/constants.js, packages/node_modules/@ciscospark/common/src/index.js, packages/node_modules/@ciscospark/plugin-memberships/src/memberships.js, packages/node_modules/@ciscospark/plugin-messages/src/messages.js, packages/node_modules/samples/browser-socket/app.js
Add membership events -- new PR with cherry picked commits thanks to help from @adamweeks   Should address all comments from https://github.com/webex/spark-js-sdk/pull/1135
New events:
- membership:created
- membership:deleted
- membership:updated  -- change in moderator status or isRoomHidden status
- membership:seen -- read receipt
Event DTO is as similar as possible to the membership webhooks
No tests yet. Since the goal here is to have these events match the webhooks, an ideal test would be to create a space, add some members, modify some (ie: make moderators), send and receive some read receites etc. The framework should register for both the SDK events and the webhooks and then it can compare them. Need to learn more about how to create …
=> Feat membership events

packages/node_modules/samples/browser-auth-implicit/test/wdio/spec/implicit-grant-authentication.js, packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call/app.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/normal-dialing.js
Custom asserts were causing sample tests to fail because the asserts were undefined. Instead of fixing them to work again, just use the builtins and chai's expect
Fixes [#67117](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-67117)
* SDK Version
* NPM Version
=> Refactor away from custom asserts and use builtins

packages/node_modules/@webex/internal-plugin-wdm/src/device/device.js, packages/node_modules/@webex/internal-plugin-wdm/test/integration/spec/device.js, packages/node_modules/@webex/internal-plugin-wdm/test/unit/lib/device-fixture.json
There will be a new peopleInsightsEnabled toggle from control hub and we want to be able to read the value
* SDK Version
* NPM Version
=> feat(wdm): add people insights admin toggle to device

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js
Previously, when we needed to convert an email address to a user id we called an API in the People plugin for each email we required. For large amounts of emails (the client currently allows up to 500 emails as parameters in each report), this resulted in many requests and some of those requests were rate-limited and received 429 responses. This fix switches over to a SCIM api in hydra which allows batching of emails in a single request. It can process 50 emails in a single request, so we may still have to make multiple requests, but not on a scale which we expect to cause issues.
Also making changes to the way some errors are logged/reported during some flows in the plugin.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-72848
This scenario is currently only covered by test scripts …
=> fix(ediscovery): adding bulk support for emails to uuid conversion

browsers-ng.js
The `--karma-debug` helper flag is useless in headless mode.
=> chore: open head(full?) browsers in debug mode

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/encryption.js
Conversation service for cardAction Activity has been updated to require parent activity. List of changes are:
- Added default activity object
- Added additional parameter(parentActivity)
- Assigned parentActivity Id and type to the cardAction Activity
* SDK Version
* NPM Version
@mattnorris
=> refactor(internal-plugin-conversation): send parentActivity

packages/node_modules/@webex/plugin-meetings/src/locus-info/mediaSharesUtils.js, packages/node_modules/@webex/plugin-meetings/src/members/index.js
previously, when attempt to grab the "content" mediaShare, we assumed it was at the `[0]` index. the order of these mediaShares however is not guaranteed to have content at `[0]`, so instead of `[0]`
use `find`. this meant that when emitting a `MEMBERS_CONTENT_UPDATE` event, we were not correctly reporting who ended/started sharing.
bug fix
Take over someone else's share. Check the payload from the `MEMBERS_CONTENT_UPDATE` event. instead of `null` values, it will have member ids as expected.
=> fix(media): find content mediaShare

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
`leave` method in `packages/node_modules/@webex/plugin-meetings/src/meeting/index.js` now accepts an options argument and passes further down to util/request. the user can now specifiy what resourceId, correlationId, locusUrl, etc they wish to leave on.
=> fix(meetings): accept and pass options from meeting.leave

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
`parent` is a reserved props in Ampersand.
Replacing `parent` props of share activity objects in client side causes issues.
Thus if it is a thread reply, then construct `parent` property just before posting it to the server.
Bug fix (non-breaking change which fixes an issue)
=> fix(internal-conversation-plugin): parent reserved word issue

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/retry.js, packages/node_modules/samples/browser-read-status/app.js
Adding retry handling for rate limiting and timeouts to ediscovery plugin. The retry behaviour can be configured, but by default it will attempt 3 retries, with exponentially increasing delays of 4, 9 and 16 seconds.
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-71491
New feature (non-breaking change which adds functionality)
Manual testing required simulation of errors that trigger retry mechanism
=> Adding retry handling for rate limiting and timeouts to ediscovery plugin

packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js
Converting file display name decryption errors over to warnings.
Noticed that Whiteboard snapshots created by the Web Client are setting the uploaded file's display name to the activity's id in plaintext. This causes the decryption to fail. Whilst the unencrypted display name seems like a bug we think a display name failure should not omitted the entire activity.
Local test of the change in the eDiscovery downloader.
* SDK Version
* NPM Version
=> fix(ediscovery): file name decrypt errors should be warnings not errors

packages/node_modules/@webex/internal-plugin-metrics/src/metrics.js, packages/node_modules/@webex/internal-plugin-metrics/test/unit/spec/metrics.js
/clientmetrics api requires a new property 'eventPayload' to submit [business](https://wiki.cisco.com/display/WX2/Splunk+-+Business+Metrics) metrics to splunk. This pull request adds support for this property in method 'submitClientMetrics'. This will be an optional property like tags, fields e.t.c. This makes sdk able to send business metrics to splunk. 
- [ x] New feature (non-breaking change which adds functionality)
ran test for package internal-plugin-metric
* SDK Version - 0.5.349
* Node/Browser Version - node 8.16.0
* NPM Version …
=> feat(internal-plugin-metrics): add support to business metric payload

packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-messages/test/integration/spec/messages.js
Update how message:created events are shaped so that they properly
populate the text, markdown, and files fields. Clean up testing
so that it handles this properly, and adjust testing statements
to utilize the proper 'files' field instead of 'file'. Update
documentation for messages.listen() to identify how to retrieve
the html field data to satisfy the related internal case.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-78472
=> fix(plugin-messages): update message created event handling

packages/node_modules/@webex/media-engine-webrtc/test/unit/spec/engine.js, packages/node_modules/@webex/plugin-device-manager/sample/index.html, packages/node_modules/@webex/plugin-phone/test/integration/spec/screenshare.js, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
- Skip inconsistent tests with Media Engine. They no longer provide confidence and will be deprecated for `plugin-meetings` shortly. 
- Fix kitchen sink sample tests.
=> Skip flaky tests

packages/node_modules/@webex/internal-plugin-search/src/search.js, packages/node_modules/@webex/internal-plugin-search/test/integration/spec/search.js
Updated `search.js` to return a response object with breadcrumbs instead of just returning list of activities.
Refactor: adding breadcrumbs to search requests
Currently not tested by automated testing, tests are failing before changes currently.
* SDK Version
* NPM Version
=> feat(plugin-search): added breadcrumbs

Jenkinsfile
Currently, some packages are getting version bumped which is causing issues when it comes to unit testing to `webex` package that does a version check. That version is dependent on `webex-core`, and since `webex-core` isn't forced to bump on all PR/merges a version mismatch failure is most likely to happen.
Instead of just adding `webex-core` to bump, bump everything.
Also, bump test concurrency to 5 to speed up testing on Jenkins
* SDK Version
* NPM Version
=> Force all packages to version bump

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-call-with-screenshare/index.html, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-multi-party-call/index.html, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/index.html, packages/node_modules/samples/browser-single-party-call-with-mute/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call/app.js, packages/node_modules/samples/browser-single-party-call/index.html, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/normal-dialing.js
Adds a call status table to the samples and uses those tables for testing. This makes the tests more specific and less flaky due to timing issues being removed.
This also includes a fix to the screen sharing code to allow for local screen share to be displayed.
=> Samples test features and styling

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
This is an expected failure and is handled by the SDK.
Having the console error print out was causing user confusion.
When a meeting is created with a 1:1 email, we are unable to fetch the meeting info since it doesn't exist. The error is handled appropriately and the meeting gets created properly. No need to spam the console with an error.
Fixes # (issue) SPARK-85535
=> fix(meetings): remove error log for meeting info failure

packages/node_modules/@webex/http-core/src/request/index.js, packages/node_modules/@webex/webex-core/src/index.js, packages/node_modules/@webex/webex-core/src/interceptors/user-agent.js, packages/node_modules/@webex/webex-core/src/webex-core.js, packages/node_modules/@webex/webex-core/test/unit/spec/interceptors/user-agent.js
Adding support for an app to set a custom `user-agent` header on all requests. The app can control this by setting the **appName** and **appVersion** configuration during init. e.g.
webex = WebexSdk.init({
credentials: {
supertoken: superToken
},
config: {
credentials: {
client_id,
client_secret
},
appName: 'custom-user-agent',
appVersion: '1.0.0',
}
});
By allowing for custom `user-agents` it'll be easier to identify where metrics are coming from.
- [?] This change requires a documentation update
If an existing app already sets the **appName** / **appVersion** and expects a `user-agent` of `@webex/http-core` this could  break it. I'm not sure how likely that is and would defer to the reviewers expertise.
I'm not sure if this needs …
=> feat(webex-core): adding support for a custom user-agent

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/create.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@webex/internal-plugin-encryption/src/config.js, packages/node_modules/@webex/internal-plugin-encryption/src/kms.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/kms.js, packages/node_modules/@webex/plugin-memberships/src/memberships.js, packages/node_modules/@webex/plugin-memberships/test/integration/spec/memberships.js
Add a max timeout for renegotiating ECDH keys so we don't end up in a loop getting new keys. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-84651
`npm run test -- --package @webex/internal-plugin-encryption --node`
=> Add max timeout for renegotiating ECDH keys

packages/node_modules/@webex/webex-core/src/webex-core.js
When uploading logs to the new client logs service `defaults()` didn't recurse and so the uploadProtocol was being omitted unintentionally. 
* SDK Version
* NPM Version
=> fix: recursively default upload options

packages/node_modules/@webex/internal-plugin-ediscovery/src/transforms.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/transforms.js
Fix for an out of memory issue. In a real world test the ediscovery downloader process was dying. Through profiling we were able to identify the root cause. The download in question was arriving at a set of activities for a large space. i.e. With ~3,300 participants. As the downloader was retrieving 3,500 activities at a time this translated to 
3,300 participants * 3,500 activities * 50 bytes (e.g. Leia Vitali <teamcloudniners+leia@gmail.com>) = 577500000 bytes or 577.5 MBs of RAM. Eventually that caused RAM to run out.
[SPARK-87426 - Downloader Hang at offset 743800 for report c4d5cc0f-e5d8-4e1c-aa63-59bf3d51920f](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-87426)
Original reporter will validate with a friendly build. …
=> fix(ediscovery): remove display names to avoid out of memory errors

packages/node_modules/@webex/internal-plugin-wdm/src/device/device.js, packages/node_modules/@webex/internal-plugin-wdm/test/integration/spec/device.js, packages/node_modules/@webex/internal-plugin-wdm/test/unit/lib/device-fixture.json
Add the `navigationBarColor` parameter, which is used the customize the colour of the Navigation Bar
=> feat(internal-plugin-wdm): add support for navigationBarColor

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/UPGRADING.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/webex-test-users.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call/app.js
Adds `meetings.register` method to do the device registration, websocket connect, and locus event listening. 
BREAKING CHANGE: No longer automatically listens to locus events upon initialization.
Fixes # SPARK-86902
* SDK Version
* NPM Version
=> feat(plugin-meetings): add #register method

packages/node_modules/@webex/internal-plugin-team/src/team.js, packages/node_modules/@webex/internal-plugin-team/test/integration/spec/get.js
Teams plugin was using `webex.request` improperly. Removed the extraneous params.
Fixes # SPARK-94009
=> fix(i-p-teams): remove bad request param

packages/node_modules/@webex/plugin-authorization-browser/src/authorization.js, packages/node_modules/@webex/plugin-authorization-node/src/authorization.js
WebClient team has identified that when the serviceUrl is pulled from the service catalog for hydra, it doesn't match the specification provided by the env variables. Since this is a one-off case that will be corrected by a future PR, this hotfix should solve the issue.
=> Hotfix jwt service url issue

packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
Add user activation validation to the services plugin. Additionally,
append a param key that allows for bypassing the Atlas request to
send user activation emails.
=> Spark 93941 add user activation status

packages/node_modules/@webex/internal-plugin-team/test/integration/spec/get.js
Remove the unnecessary 'skip' clause from the testing suite
now that all tests for the specified clause are passing.
=> test(internal-plugin-team): remove skip clause from testing suite

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/UPGRADING.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/index.html
The above is being added because currently, convoId will not work at all. We have to do some testing and documentation changes, as with federation/fedramp convoId is no longer present (and no longer uniquely identified a conversation)
=> Breaking Change: meetings | federation convoId -> convoUrl

packages/node_modules/@webex/webex-core/src/lib/services/interceptors/service.js, packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js
Fix error handling within the services plugin to allow
the service interceptor to return an error message on failure
to get catalog.
Fixes # SPARK-99013
=> fix(webex-core): fix error handling in services

.circleci/config.yml
Add multi-line error handing to test runners within the CircleCi config files in order to address an issue occurring in which when an error is thrown in a test, it doesn't report errors in CircleCI
* SDK Version
=> chore(circle-ci): fix unit test failure not reporting in circle

packages/node_modules/@webex/test-users/src/index.js
Looks like a recent move away from the test-legacy-user module for creating test users broke these tests as the new approach lacked support for **roles** and **orgId**.
https://github.com/webex/webex-js-sdk/commit/58dd59738fcbf4f46ff50e45ca55f5b457b98c62
Since the above commit these tests would have failed. I'm not familiar enough with the system to know why they did not block commits, etc.
5 failing
1) Encryption
#onBehalfOf
getKey:
KmsError: Request id eb75e621-5467-4b0b-be7d-ed32de4d9e29 user 917e4c88-38a1-4688-9881-517bcc6ccd74 doesn't have permission to do operation on behalf of another user bc5c370b-071d-421b-8490-b791b1f3dd63
KMS_RESPONSE_STATUS: 403
KMS_REQUEST_ID: 8a834c47-473c-48e9-9b7e-c36310d360ee
Fixing some tests …
=> fix(encryption): re-supporting roles when creating test users

packages/node_modules/@webex/test-users/src/index.js, packages/node_modules/@webex/test-users/test/integration/spec/index.js
Adds the ability to pass "type" and "machineType" to the test user library. These configs are used in the `internal-plugin-lyra` integration suite. 
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-101003
=> feat(test-users): add support for machine configs

packages/node_modules/@webex/internal-plugin-wdm/src/device/device.js, packages/node_modules/@webex/internal-plugin-wdm/test/unit/spec/device.js
This change allows us to pass additional default headers for the device registration and refresh. This is required by WDM for EU users as they will not return the correct serviceHostMap via WDM as they expect everyone to be using u2c going forward. 
I ran `npm test -- --packages @webex/internal-plugin-wdm` and the unit tests passed. 
* SDK Version
* NPM Version
=> feat: pass through default device headers

packages/node_modules/@webex/internal-plugin-mercury/README.md, packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js, packages/node_modules/@webex/internal-plugin-mercury/src/socket/socket-base.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury-events.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/socket.js, packages/node_modules/@webex/test-helper-mock-web-socket/src/index.js
When testing our ediscovery downloader client on a dedicated proxy test environment we found that we could not establish a connection to mercury to open a web socket. In order to fix this we had to add a https proxy agent, configure it with the proxy url (which we have set as HTTPS_PROXY to enable proxy support in the http request module) and pass it as an option to the WS websocket constructor.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-96966
All mercury tests were run (npm test — —packages @webex/internal-plugin-Mercury) and 4 new tests were added to …
=> Add proxy support for mercury web socket connections

packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js, packages/node_modules/@webex/webex-core/src/lib/services/service-url.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/service-catalog.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/service-url.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/services.js
A recent change has appended new clusters to the U2C service host map that aren't being mapped to any specific service. The current methods used to map the services only map hosts with the same root host address as the key. In order to map the additional hosts, the hostIds from the host catalog must be analyzed against the service names in the serviceLinks section.
Fixes # SPARK-102783
=> Spark 102791/append additional cluster info

packages/node_modules/@webex/internal-plugin-encryption/src/encryption.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/encryption.js
For POST /download/endpoints the parameter with allow=unchecked should be put into the request body as an array. This will allow unscanned files to be downloaded without a warning, but files currently being scanned or already determined to be infected will evoke 423 or 410 responses.
If the client is using the Files APIs to download thumbnails or preview pages, then need to add "allow=unchecked, evaluating" in the new field in the POST body accordingly.
Fixes #SPARK-99531
Wrote two new test cases to test download for a file. One test case is written for download function where as another for the _fetchDownloadUrl() function.
* SDK Version: 1.80.29
* Node/Browser Version: 1.80.29
* NPM Version: 6.4.1
=> feat(encryption): add blocking qualifiers in client on file download

packages/node_modules/@webex/plugin-webhooks/src/webhooks.js
Documentation at https://webex.github.io/webex-js-sdk/api/#webhooks is wrong, in particular, the return types for get webhook and list webhooks, they seem to have been mixed up. From that link clicked through to the source code and found the mistake. I assume docs are auto generated so this change should hopefully propogate through to the docs.
No tests ran as it is a simple documentation change
=> fix(plugin-webhooks): fix get and list webhooks return types

packages/node_modules/@webex/plugin-phone/src/call.js
Converting the phone plugin to use services plugin methods instead of the deprecated device plugin methods.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106018
=> feat(plugin-phone): use services catalog for conversation url

packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/content.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/report.js
Removes the `getServiceUrl` stubs from the unit tests which were unused.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106011
=> test(ediscovery): remove getServiceUrl stubs

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/conversation.js
Remove all references for the service catalog nested under the devices plugin and replace them with appropriate methods from the services plugin.
=> Spark 106010/remove device service references

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
Remove an unnecessary catch block from the conversation
plugin to prevent the bypassing of a consuming promise
chains.
=> fix(internal-plugin-conversation): remove unnecessary catch block

packages/node_modules/@webex/internal-plugin-mercury/src/socket/socket.shim.js
Fixes `WebSocket is not defined` issue popping up when testing on SauceLabs
Fixes [SPARK-102783](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-102783)
* SDK Version
* NPM Version
=> Better browser support for socket shim

packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js
Uses the space url instead of id since locus no longer supports id it seems.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-107156
=> test(meetings): use space url instead of id

.circleci/config.yml, karma-ng.conf.js, tooling/lib/test/karma.js
With the move to a bash script for testing packages, testing was improperly exiting with a code of `0`, even if a test reported a failure. This fixes that and removes the need for the other script to look through xml files to see if something had failed or not.
Fixes [SPARK-106753](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106753)
* SDK Version
* NPM Version
=> Refactor CircleCI test reporting

packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/roap/request.js
Switches the meetings plugin to use non-deprecated service catalog methods.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106016
=> feat(meetings): use service plugin methods

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/encryption.js
This PR is a continuation of this PR: #1401 
From conversation package, we are making a call to encryption package for scanning and downloading a file. I and Meesha, had added a new options argument for allowing unchecked files to get downloaded upon end-user request.
Fixes #SPARK-99531
This PR doesn't need a new test cases.
* SDK Version: 1.80.29
* Node/Browser Version: 1.80.29
* NPM Version: 6.4.1
=> fix(plugin-conversation): Add option argument to download encrypted file

package-lock.json, package.json, packages/node_modules/@webex/internal-plugin-conversation/src/share-activity.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/share-activity.js
These changes are a part of the new feature that is ANTI-MALWARE SCANNING. In share-activity.js in _upload function where we were making /finish API call, we are sending fileHash of the file that is uploaded in the body of the API call.
Note: Added a new package [crypto-js](http://npmjs.com/package/crypto-js) to generate file hash
Fixes # [SPARK-92936](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-92936)
Added a new test to cover fileHash sent in the body of /finish API call.
Test command: 
> npm test — —packages @webex/internal-plugin-conversation --node
Test Configuration:
SDK Version 1.80.29
Node/Browser Version 8.16.2
NPM Version 6.4.1
=> feat(internal-plugin-conversation): calculate fileHash on file upload

packages/node_modules/@webex/plugin-meetings/webex.js, packages/node_modules/@webex/webex-core/README.md, packages/node_modules/@webex/webex-core/src/config.js, packages/node_modules/@webex/webex-core/src/interceptors/auth.js, packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/service-catalog.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js, packages/node_modules/@webex/webex-core/test/unit/spec/interceptors/auth.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/service-catalog.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/services.js
This pull request encompasses all changes needed to fully decouple the `wdm` services catalog from `webex-core`. This includes adding new helper methods, adding new tests, as well as updating documentation.
Fixes # SPARK-106008
=> Spark 106008/convert webex core

packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js
To support setting a `user-agent` on the mercury websocket I'm expanding which options can be passed down to mercury via the `init`. This'll allow us to support corporate proxies which can direct traffic based on `user-agent`.
=> feat(mercury): expand which options can be passed down

packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js
Added functions to decrypt-transform to decrypt reaction activity objects.
see https://confluence-eng-gpk2.cisco.com/conf/display/CUERVOS/Reactions+-+Crawl for reference of what these objects look like.
Feature/added functionality
I used this code to develop the feature in the Webex Teams web client. this [PR](https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/362) allows consuming reactions in the Webex Teams web client.
I also added tests to `packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js`
* SDK Version: v1.80.63
* Node/Browser Version: Node v10.16.2/Chrome: 79.0.3945.74
* NPM Version: 6.9.0
=> feat(reactions): add decrypt-transforms for reaction objects

packages/node_modules/@webex/internal-plugin-devices/src/devices.js, packages/node_modules/@webex/internal-plugin-devices/test/unit/spec/devices.js, packages/node_modules/@webex/internal-plugin-devices/test/unit/spec/wdm-dto.json
Generate the shape of the devices plugin's properties as well as the derived values and session data. This should reflect the data in the original wdm plugin.
This is a rework of the [draft pull request](https://github.com/webex/webex-js-sdk/pull/1413) to rework `internal-plugin-wdm`.
This pull request contains all of the changes needed to implement the received DTO from the **WDM** endpoint as device properties. This should reflect the device properties available via the `internal-plugin-wdm`.
Note: This pull request does not include any new tests, but is instead a step towards fully implementing the devices plugin. Reviewers should be looking for typos, bad grammar, missed properties, and other improvements.
Please describe the tests that you ran to verify your changes. Provide …
=> feat(internal-plugin-devices): generate devices properties

packages/node_modules/@webex/internal-plugin-encryption/src/encryption.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/encryption.js, packages/node_modules/@webex/internal-plugin-encryption/test/unit/spec/encryption.js
This PR adds support for multi-cluster file download. Before this PR, files are downloaded from the files-service tied to the `internal.device._values -> serviceHostMap`.  
In some use cases (i.e. federation) the file location may be stored on different file services. The PR points the file service to the one received in the endpoint URL.
* SDK Version
* NPM Version
=> WIP : feat(internal-plugin-encryption): add support for multi-cluster file download

packages/node_modules/@webex/plugin-meetings/browsers.js, packages/node_modules/@webex/plugin-meetings/src/index.js
Ok team, I have confirmed that the screen share issue is due to Firefox 72. According to their [changelog](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72):
> The MediaDevices.getDisplayMedia() method can now only be called in response to a user gesture such as a click event 
This means we can’t do the tests without some sort of webdriver. 
I have placed a workaround in to stick the sauce labs version of FF to 71.
=> test(meetings): fix to FF 71

packages/node_modules/@webex/common/src/constants.js, packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-messages/test/integration/spec/messages.js
Add the attachments element the message:created event when the message included an adaptive card.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-116380
* SDK Version
* NPM Version
=> Add attachments to message event when sending adpative card

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/src/index.js, packages/node_modules/@webex/internal-plugin-flag/src/index.js, packages/node_modules/@webex/internal-plugin-search/src/index.js, packages/node_modules/@webex/internal-plugin-search/src/search.js, packages/node_modules/@webex/internal-plugin-search/test/integration/spec/search.js, packages/node_modules/@webex/test-helper-retry/src/index.js
Moved federation search into sdk. search can now return results from remote clusters
fixes incorrect call to bulk_activities_fetch endpoint
* SDK Version
* NPM Version
=> fix(i-p-search): return message search results from remote clusters

packages/node_modules/@webex/internal-plugin-devices/test/integration/spec/devices.js
Remove unnecessary assertions in the devices plugin
integration tests that assert details during the
setup stages.
The changes within this pull requests are scoped to unnecessary assertions within setup blocks, such as `before` and `beforeEach` methods within the integration tests for the `internal-plugin-devices` plugin. These methods have been updated to no longer include redundant assertions within the setup stages, as well as other miscellaneous changes to blocks that were unnecessary.
Fixes # [SPARK-119621](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-119621)
**Test …
=> test(internal-plugin-devices): remove unnecessary assertions

packages/node_modules/@webex/internal-plugin-user/src/user.js
Fix the failing test associated with this plugin by
adding catalog collection prior to a specific method call.
The changes within this pull request are scoped to fixing the tests within `internal-plugin-user`. It seems as though the method call was attempting to validate a user without having an appropriate `atlas` service available in the catalog.
Fixes # [SPARK-120864](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-120864)
* Node/Browser Version v10.18.0
=> test(internal-plugin-user): fix failing test

packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/kms.js
The changes in this pull request are scoped to fixing the failing test within `internal-plugin-encryption`. It seems as though the timeout was too short, and a number of retries value was no longer correct. These have been addressed.
Fixes # [SPARK-120861](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-120861)
* Node/Browser Version v10.18.0
=> test(internal-plugin-encryption): extend ping timeout

packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury-events.js
allows client to reconnect to next available priority host instead of trying same web socket url
* SDK Version
* NPM Version
=> fix(i-p-mercury): reconnect with next available priority host

CONTRIBUTING.md, packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-messages/test/integration/spec/messages.js
Update message:created websocket event to include a parentId field if the messages is a threaded reply.
Also add tests to validate that the plugin-messages.create and plugin-messages.list functions handle threaded replies as expected
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-119677
Added #threadedMessageTests() to the plugin-messages test suite.   Test sends two messages, one that is a "regular" message, and one that is a threaded reply.  Validate that the event for the reply includes a parentId.  Query the messages and ensure that the parentId exists when it should.  Validate that the parentId query parameter works as expected.
* SDK Version
* NPM Version
=> Threading api v3

packages/node_modules/@webex/plugin-meetings/src/roap/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/roap/util.js
`RoapUtil.compareLastRemoteOffer` was incorrectly checking for a blank SDP remote offer. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-120894
* SDK Version
* NPM Version
=> fix(meetings): check for empty for previous SDP offer

packages/node_modules/samples/browser-call-with-screenshare/app.js
The screenshare samples tests have become quite flaky.
Upon investigation, it appears the ROAP is not ready in time when we update media.
Add a new function `waitForMediaReady` that waits for the meeting's media to be ready before progressing.
=> test(samples): add wait for media ready

packages/node_modules/@webex/internal-plugin-calendar/src/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/src/index.js, packages/node_modules/@webex/internal-plugin-calendar/test/integration/spec/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/test/unit/spec/calendar.js
Calendar will soon stop sending encrypted notes and participant lists that exceed 20k length from the currently used /calendar API. They'll instead be `null`, and 2 new APIs have been provided to fetch notes and participants with meeting id, which will have to be used in those cases.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-100549
* SDK Version
* NPM Version
=> feat(calendar): handle /calendar API not returning meeting notes and participants

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
We’ve had customer reports that the meetings plugin wasn’t working with angular applications, and we were able to recreate the issue around the usage of finally. There might be a better babel config that works with angular, but consider this async conversion a “workaround” to get customers up and running.
I didn’t have full context on the workflow, but I tried to recreate it as best as possible without changing any of the tests. Let me know if I missed something.
=> fix(meetings): use async instead of finally

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/integration/spec/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/content.js
As part of federation work we need ediscovery.js to support reaching out to remote (i.e. None home cluster) eDiscovery servers. There is code to support this already. But we discovered that it has problems with the decryption of space activities. Namely the code
* assumed all requests would have a `resource` property and failed when they did not
* tried to retrieve a remote space id from the home cluster eDiscovery (which cannot find it)
* wiped the space summary cache when the remote report summaries were also cached
I'm removing APIs which could breaking existing clients. But as we control the only client of eDiscovery this is not a concern.
Introduced appropriate tests and updated existing tests. I also integration this …
=> fix(ediscovery): handle reportids that can be either uuids or urls

packages/node_modules/@webex/plugin-attachment-actions/src/attachmentActions.js
Missing closing parenthesis in documentation
=> docs(attachment-actions): fix typo in attachmentActions.js [skip npm] 

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-128909
When creating a 1:1 meeting with the meetings plugin, an error is logged to the console about not getting info from /meetingInfo. This error is expected and should not use the "error" wording causing unneeded customer requests to developer support.
=> feat(meetings): change error log for 1:1 creation

package.json
The scope of this pull request is to fix a CI bug that occurs during the static analysis job in which we lint the bundled SDK.
=> fix(eslint): add umd bundle to lint ignore [skip npm]

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/encryption.js
After a recent change in conversation service, unencrypted conversations no longer contain the kmsResourceObjectURL property.
This removes all such assertions in the tests for conversation plugin.
=> test(internal-conversation): remove assertions for kmsResourceObjectURL

packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js, packages/node_modules/@webex/internal-plugin-mercury/src/socket/socket-base.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury.js
We've a E2E test app to validate the eDiscovery Download Manager. But we found the app was not shutting down without a `process.exit(..)` call. Using [wtfnode](https://www.npmjs.com/package/wtfnode) I identified the mercury socket as being the cause. It was not closed and this meant the app remained running. I "fixed" this with
await spark.internal.mercury.disconnect()
in the test's `after` section. But, intermittently, the app would still hang and at the same time I'd see a `unhandledRejection` with an `undefined` error.
I tracked the rejection down to [mercury's abort handling](https://github.com/webex/webex-js-sdk/blob/master/packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js#L318) which gets called by the [abort event in the backoff …
=> fix(mercury): timing condition where disconnect did not close websockets

.circleci/config.yml
The scope of the changes in this pull request are focused on adding naming to the tap test CI jobs to make their scope determinable before opening the job directly. The changes to the circle CI config require circle ci v2.1+.
See [this Circle CI documentation reference](https://circleci.com/docs/2.0/configuration-reference/#job_name-1).
=> chore(circle): improve tap test naming

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js
Adds a meeting event which states that media has started receiving bytes
Fixes [SPARK-128912](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-128912)
=> add meeting:media:{local,remote}:start event

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
screensharing currently doesn't handle a takeover that well, and the `isSharing` variable doesn't get updated
The current solution is to check if a takeover happened and then stop the local share using `stopShare`
NOTE: This is still slightly buggy because once a takeover happens, locus gets conflicted and doesn't properly allow the plugin user to takeover
Fixes [SPARK-116558](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-116558)
=> better handling of screensharing takeover

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
This adds the `meeting.setRemoteQualityLevel` function. This will set the quality level in the meeting's mediaProperties object, then calls `updateMedia` to set the max framesize of the offer.
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-133788
=> Meetings set remote quality

packages/node_modules/@webex/webex-core/src/credentials-config.js, packages/node_modules/@webex/webex-core/test/integration/spec/credentials/credentials.js
The scope of the changes in this pull request are to address the issue in which an authorization URL is provided with the credentials config.
Fixes # [SPARK-133890](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-133890)
=> fix(webex-core): derived auth url error

packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/kms.js
Fixing for TAP test failures. We have a JIRA to re-enable.
=> test(encryption): skip broken test

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Check if camera and mic exists/have permissions and then check against given getUserMedia constraints
Fixes [SPARK-132100](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-132100)
=> Use enumerateDevices to check if Device Permissions match media constraints

packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
The scope of the changes in this pull request are to fix the issue associated with using hydra person id values when utilizing `Meetings#create()`.
Fixes # [SPARK-134739](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-134739)
* Node/Browser Version **v10.18.0**
* NPM Version **v6.13.4**
=> fix(plugin-meetings): fix hydra person id support

packages/node_modules/webex/src/webex.js
Fixing the docs for `Webex.init` usage with an access token.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-136745
=> docs(webex): fix init docs [skip ci]

packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/services.js
The scope of the changes in this pull request are focused around generating the credentials config value `authorizeUrl`. An earlier bug fix seemed to have impacted the federation status of this `authorizeUrl` value.
Fixes # [SPARK-137781](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-137781)
* Node/Browser Version v10.18.0
=> fix(webex-core): service to credentials auth url

.circleci/config.yml, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
This re-arranges the conversation plugin's integration tests because tests don't seem to idempotent.
By arranging them this way, tests that affected later test don't have an effect anymore. Tests seem to consistently pass at this  point.
=> test(internal-conversation): rearrange post() tests to avoid failures

packages/node_modules/@webex/plugin-logger/src/logger.js, packages/node_modules/@webex/plugin-logger/test/unit/spec/logger.js
Follow up to https://github.com/webex/webex-js-sdk/pull/1652. Noticed that while that PR fixed the recursive loop it also had an unintended side effect. Namely it caused issues like
> failed to execute Logger#warn RangeError [ERR_OUT_OF_RANGE]: The value of "defaultMaxListeners" is out of range. It must be a non-negative number. Received [Circular]
and
> uncaughtException TypeError: Function.prototype.apply was called on [Circular], which is a string and not a function
Realised that the original PR did not take into account primitives and functions were also being walked.
Added an enhanced unit test to cover this case.
* SDK Version
* NPM Version
=> fix(plugin-logger): circular ref should not filter funcs or primatives

packages/node_modules/samples/browser-plugin-meetings/index.html
The changes in this request is scoped to allowing all characters into the input field for DTMF in the meetings sample.
Fixes # [SPARK-143416](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-143416)
=> fix(samples): add all chars to dtmf input

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Users were not able to override the default configuration and
the media utilities were taking the hard coded config from config.js
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-145738
=> feat(meetings): pass sdk config to media functions

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
We missed adding the call start time to logs and it is helpful when correlating meetings.
=> feat(meetings): add call start to logs

browsers-ng.js, packages/node_modules/@webex/plugin-meetings/browsers.js, packages/node_modules/@webex/plugin-phone/browsers.js
karma doesn't respect webdriver w3c `goog:chromeOptions` and `ms:edgeOptions` when passing in args
It will however respect `flags`, so revert back to the old style with `flags: []`
* SDK Version
* NPM Version
=> remove chrome/edgeOptions since karma doesn't respect it [ci skip]

browsers-ng.js, packages/node_modules/@webex/plugin-meetings/browsers.js
Removing `goog:chromeOptions` broke saucelabs for some reason, so adding back the code that will fix it.
Reporting the issue to saucelabs so hopefully they will fix it.
Issue is that `flags: []` is being reported as a `oversized non-string` and not respecting the the flags given, so that means mic permissions notification pops up again
=> chore(browsers): tweak chrome flags for saucelabs [skip-ci]

packages/node_modules/@webex/http-core/src/index.js
The scope of this pull request is to update the request options to include `json: false` in the case of uploading client logs.
Notes on this, we actually send three requests when uploading logs:
POST => this contains the file name and upload protocol
PUT => this contains the buffer as well as the content type of the buffer
POST => this contains the metadata of the uploaded file
Based on the scope of the task provided, we were sending the logs as `content-type: application/json` when the content type should have been handled via the `json: false` options parameter.
In my tests, in every case, the content-type of the put buffer was `content-type: application/octet-stream`
Based on the conditions that were provided as a hotfix from the requester, the changes in this PR should resolve this …
=> fix(http-core): json options param

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
The scope of this pull request is to remove every instance of `console.log` and `this.logger` from `plugin-meetings` and replace these calls with `LoggerProxy.logger`. Note that this does not include `this.loggerRequest`.
Fixes # [SPARK-148852](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-148852)
=> fix(plugin-meetings): calling invalid loggers

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js
The scope of this pull request is to add the `subClientType` metrics value to the requests to the metrics endpoint with the value of `WEB_APP`.
Fixes # [SPARK-149810](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-149810)
=> feat(plugin-meetings): add sub client types

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js
In order to stabilize the reconnection logic, we need to disable the auto reconnect based on mercury connection. This is the first step in getting peer connection reconnects working properly.
Additional changes are adding logs for all the peer connection events as well as auto uploading logs after calls at the request of @jpjpjp
=> Ice peer connection events

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
In order to get screen sharing on safari to work, we needed to have less of a promise chain above the actual navigator call. This was causing issues on safari because it lost track that it was called via a user action (security). 
I've added a `meeting.shareScreen` function that reduces the steps to actually sharing a screen.
Samples and documentation have also been updated.
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-141969
=> Add `meeting.shareScreen` function

packages/node_modules/samples/browser-plugin-meetings/app.js
The mediaSettings global variable in the kitchen sink app was set to an empty array when it should be set to an empty has object - Arrays in JS are objects and can have properties but in browsers like Safari you will not see the array's properties being logged out also in the future if code changes and they decide to pull keys or do some looping things could break
=> fix(samples): update mediaSettings global to object

packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js
Starting the collection of logs doesn't need to be "info" level.
=> feat(meetings): change stats analyzer log level

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
The scope of the changes in this pull request is to add timeout logic to the ice disconnect event tree and remove all current logic from the `meeting.reconnect` method except for general logging.
Fixes # [SPARK-151805](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-151805)
=> feat(plugin-meetings): add ice disconnect timeout

packages/node_modules/@webex/plugin-meetings/src/media/index.js
Javascript just... _sigh_ why?
Setting quality to LOW in Firefox (along with Safari iOS & Chrome Android) and providing a deviceID causes mediaConfig to break since `video.width` is not provided along with deviceID.
Extra work maybe needed to handle iOS and Android, since updating meetingQuality on those clients causes the same over-constraint issue seen on firefox
Fixes # (issue) (PENDING CREATION)
* SDK Version
* NPM Version
=> Also check if video.width exists first

packages/node_modules/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
The scope of this pull request is to fix failing unit tests based around a downstream class. These tests cannot run appropriately due to the coupling of the upstream classes as a unit test.
=> fix(plugin-meetings): remove test failure

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
This is, instead of using the metrics plugin
For some reason the metrics plugin cannot find its own members.
=> fix(meetings): sendOperational metrics directly with request

packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
The scope of the changes in this pull request are to update client metrics to be sent via the metrics plugin instead of utilizing `request` directly.
Fixes # [SPARK-153055](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153055)
=> fix(plugin-meetings): utilize metrics submission method

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Send `getDisplayMedia()` failures as operational metrics to metrics service for aggregation.
=> feat(meetings): send getDisplayMedia() failures as ops metric

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixing triggers and unit tests around `meeting.reconnect()`.
=> feat(meetings): emit triggers on reconnect completion

packages/node_modules/@webex/plugin-meetings/src/common/errors/reconnection-in-progress.js, packages/node_modules/@webex/plugin-meetings/src/common/events/util.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
It's finally here! After a few weeks of feature work, the meetings reconnect triggers and logic are ready to be merged into master. 
These live behind a configuration that has it defaulted to false, so users will need to opt-in to this feature at first.
=> feat(meetings): add reconnect logic

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
The scope of the changes in this pull request are to improve the current logging within the meetings plugin to allow the participant to determine when they successfully/unsuccessfully mute either their video or audio streams.
Fixes # [SPARK-152340](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-152340)
=> feat(plugin-meetings): improve mute logging

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Minor doc update to reflect method's actual return value.
Addresses confusion in issue https://github.com/webex/webex-js-sdk/issues/1788
=> docs(meetings): reflect getAllMeetings() actual return value

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR updates the pull request template to make it more concise. The idea is to avoid contributors leaving the default 
template untouched, and encourage them to give context on the changes.
This also moves the checklist from the PR template to the contributing guide
=> chore: update pull request template [skip ci]

packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Fixes: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-147674
SDK Meetings Stats Analyzer Packet Loss Unit Tests
In order to test only the unit tests for plugin-meetings run this command from your terminal: `npm test -- --packages @webex/plugin-meetings --unit`
---
=> test(meeting): add unit tests for meetings stats analyzer packet loss

packages/node_modules/@webex/common/src/constants.js, packages/node_modules/@webex/common/src/index.js, packages/node_modules/@webex/common/src/uuid-utils.js, packages/node_modules/@webex/plugin-attachment-actions/src/attachmentActions.js, packages/node_modules/@webex/plugin-memberships/src/memberships.js, packages/node_modules/@webex/plugin-memberships/test/integration/spec/memberships.js, packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-rooms/src/rooms.js
Fixes and Tests for the issue where IDs were not being properly encoded in the websocket events for the attachmentAction, membership, message and rooms resources.
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-159014
Note, two plugin-membership tests were failing.  I believe this was unrelated to this change, it looks like someone modified the tests so that the roomType element of some membership objects were not being tested.  Restored this to include this check.
Relevant plugin tests all pass
The new webhook/websocket comparison test is in the samples directory.  To run cd to /packages/node_modules/samples/node-compare-sockets-webhooks.  Run `npm install` to load dependencies.   Set environment variables:
* …
=> Spark 159014

.circleci/config.yml, .versionrc.js, CONTRIBUTING.md
Just some tweaks I've observed over the past two days.
`standard-version` isn't as maintained as it seems
---
=> Standard version tweaks

package-lock.json, package.json
The current commitlint packages are outdated and rely on an older version of conventional-changelog-angular (1.*.*) which itself has a insecure dependency - updating commitint will bring the conventional-changelog-angular dependency up to it's most current version which is 5.0.10 - there is a fix for release 5.0.11 that fixes the insecure dependency
https://github.com/conventional-changelog/conventional-changelog/issues/658
Once this patch is released - our packages should automatically be updated as we have the patch-package tool that runs after post install
Fixes #[162649](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-162649)
=> chore(package): update commitlint

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js
The scope of the changes in this pull request are to add the ability to determine which participants have changed their state between locus events.
Fixes #[SPARK-161919](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-161919)
=> feat(meetings): locus info participant deltas

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Updated shareScreen to pull in SDK configuration defaults.
Currently shareScreen was not using any resolution preferences set via SDK configuration.
Updated the logic to use these settings if present.
Fixes #SPARK-162954
**Notes:**
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgU1RFUDEoKHNoYXJlU2NyZWVuKSkgLS0-fEdlbmVyYXRlcyBzaGFyZSBzdHJlYW1zIGJ5IGNhbGxpbmd8IFNURVAyKFwiTWVkaWEuZ2V0RGlzcGxheU1lZGlhIChzaGFyZUNvbnN0cmFpbnRzT3B0aW9ucywgc2RrQ29uZmlnKVwiKVxuICBcbiAgU1RFUDIgLS0-IHxMb2dpYyBmb3IgZ2VuZXJhdGluZyBjb25zdHJhaW50c3wgU1RFUDN7XCJEb2VzIHNoYXJlQ29uc3RyYWludHMgZXhpc3Q8YnI-d2l0aGluIHNoYXJlUHJlZmVyZW5jZXMgb3B0aW9uczxicj5wYXNzZWQgaW4gdG8gdGhlIGZ1bmN0aW9uP1wifVxuICBcbiAgU1RFUDMgLS0-fFlFUyAtIEV4aXN0c3wgU1RFUDNfMVtVc2Ugc2FtZSBzaGFyZSBwcmVmZXJlbmNlcyBwYXNzZWQgaW5dXG4gIFNURVAzIC0tPnxOT3wgU1R …
=> fix(plugin-meetings): shareScreen pulls in sdk configuration

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js
Fixes test case where before was being used instead of beforeEach, causing leaky test cases.
=> test(convo int): prefer beforeEach to before

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/conversation.js
Create helper method to recurse through the "next" links of convo's */parent/* endpoint.
Part 2 of 3 from suggested PR flow agreed upon [here](https://github.com/webex/webex-js-sdk/pull/1809#issuecomment-666576235)
=> feat(conversation): add helper for fetching all child activities

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Allow screenShare to override the frameRate by using screenFrameRate.
When calling shareScreen() it will look to SDK config settings to see if screenFrameRate is defined and use it under certain conditions.
Fixes #SPARK-162954
---
=> fix(meeting-plugin): allow share frame rate override

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js
Fixes bug where listActivitiesThreadOredered (wrapper function for _listActivitiesThreadOrdered) determines the "done" value of its iteratator response incorrectly.
=> fix(conversation): threads iterator 'done' is true when no more activities can be fetched

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
- Convo server no longer broadcasts the 'stop_typing' event over mercury
Because the server is no longer sending the 'stop_typing' event over mercury, I decided to check if we successfully sent the 'stop_typing' event from the return value.
[SPARK-141543](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-141543) #done
---
=> test(internal-plugin-conversation): update test

packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When first reported updating meeting quality level changed the video device if you had two video devices and was using your non-default camera. When recently tested using the samples, the local video stream of the caller did not change but the video displayed to the remote party did change to the other camera. Therefore the caller was unaware of that the remote party sees a different video stream.
If the caller leaves a meeting without closing the browser window and attempts to rejoin then the last camera used will be remembered. To rejoin the caller must getting media streams, click the join button and then click on the add media button.
Caller A - JS SDK (calls into space, must have two cameras)
Remote Party B - Native Desktop client (joins space)
**Steps to reproduce:**
Caller A should …
=> fix(meeting-plugin): getMediaStreams uses last used video device

documentation/webex.md
Accessing the code grant method is inside the authorization plugin and not at the top-level.
This was brought up in one of the developer help spaces.
---
=> docs(nodejs): fix sample NodeJS usage

packages/node_modules/@webex/internal-plugin-device/src/device.js, packages/node_modules/@webex/internal-plugin-device/test/integration/spec/device.js
This adds TTL when to the device registration request whenever registrations are configured as ephemeral.
Fixes [SPARK-171365](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-171365)
---
=> fix(device): set TTL when registering device as ephemeral

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
The JSDoc does not match the implementation.
Fixes #[SPARK-158533](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-158533)
---
=> docs(meeting): remove MediaStream param from updateShare [skip ci]

.circleci/config.yml
- NPM and github are out of sync. Forcing the next version number.
=> feat(release): v1.92.2 [skip ci]

packages/node_modules/@webex/plugin-meetings/src/locus-info/controlsUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js
Fixes issue where if recording is not found it does not delete the meeting object from the store 
---
=> fix(plugin-meeting): meeting object not deleted on end

packages/node_modules/@webex/internal-plugin-conversation/src/activities.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js
This commit fixes an issue where the activities returned by the threading wrapper functions use the parent ID as the main ID when an activity has been edited. This change is necessary because when determining read receipts, convo service lists the edit's activity as the lastSeenActivityUUID, which made edits not appear as read.
=> fix(conversation): set returned edit activity IDs to original ID

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Hey there! 
On the interstitial page before actually creating and joining a meeting, we want to get the users local media streams to show their camera/mic is working. The current implementation requires you to have a meeting instance in order to call `.getMediaStream()`. 
There are 2 flows
1. We could create a meeting but not join it. The problem here is that if a sync is calling in between create/join the meeting gets destroyed
2. We could expose the media streams outside of the meeting instance (it's a util file as is) and then the user can grab those streams and pass them when creating and joining the meeting
---
=> feat: expose getUserMedia on meetings object

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Currently getDisplayMedia failure metrics is only being used to track the getDisplayMedia failure
We dont have any for screen share failures and the promise does not reject if share fails
---
=> fix(meeting-plugin): send share error metrics

packages/node_modules/@webex/internal-plugin-ediscovery/src/transforms.js
This change supports an upcoming enhancement to edit message. Currently users cannot edit a message if it contains an attached file. In the future this will be possible. However it does mean that a file's `encryptionKeyUrl` may differ from the activity's `encryptionKeyUrl`. e.g. When editing an old activity in a space where key rotation has occurred. To support these scenarios in ediscovery the code will also check this new property. If it is not defined it'll default back to the activity's `encryptionKeyUrl`.
=> feat(ediscovery): support scr decryption on files that use their own key url

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js
The scope of the changes in this pull request are to adjust the joining logic to prevent multiple events from being sent if the client [JS SDK] is already attempting to join the meeting. Additional deferring logic has been implemented to further improve the joining experience.
Fixes [SPARK-153106](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153106)
---
=> fix(plugin-meetings): defer joining and duplicate metrics

.circleci/config.yml
Disable documentation temporarily until we can get an updated version that handles es6 syntax
[SPARK-178735](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-178735) #done
---
=> chore: disable documentation

packages/node_modules/@webex/internal-plugin-calendar/src/index.js
calendar service payloads include a `encryptedOrganizer` property, which has `encryptedEmailAddress` and `encryptedName` fields. currently, these properties are not decrypted. this PR fixes that.
if you'd like me to add tests for this change, please let me know where. i was thinking [here](https://github.com/webex/webex-js-sdk/blob/0bd7155d9a614b12cec844596d833580e94db427/packages/node_modules/%40webex/internal-plugin-calendar/test/integration/spec/calendar.js#L183) but i see this test is skipped...
=> fix(calendar): decrypt organizer email and name

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
No need to track participant left event as that does not represent the media inactive event ,
Currently causing too many API calls 
---
=> fix(plugin-meetings): remove media inactive metrics

packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/request.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/testUtils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
This PR adds an optional parameter to the join meeting flows to allow transcoding (Edonus) for 1:1 calls. This fixes a bug in Chrome 86 that breaks remote video. 
The tests were also failing locally so made some resiliency updates to those and suppressed/mocked some errors.
=> feat: add preferTransocoding option

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/handler.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
fix(plugin-meeting): add periodic key frame request to edonus
fix(plugin-meetings): neglects duplicate roap event with same seq
fix(meeting-plugin): send metrics for framesDropped and framesRendred
fix(plugin-meetings): cannot share second time when stopping using stop share overlay
---
=> Metric for MQA and share fix

packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js
Remove the failing test for 1:1 calls and enable it once its fixed 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-185546
---
=> test(plugin-meetings): skip flaky test

packages/node_modules/@webex/plugin-meetings/src/media/index.js
Enable missing RTX on reconnect
---
=> Enable rtx 1

packages/node_modules/@webex/plugin-meetings/src/constants.js
Currently no jira, but an ad hoc fix to the missing constant that was causing the meetings plugin to crash after leave failure.
=> fix(plugin-meetings): add MEETING_LEAVE_FAILURE constant

packages/node_modules/@webex/webex-core/src/lib/services/services.js
I could be way out of left field here... but i was trying to add emailhash autosignin functionality to the web client, and this was standing in my way. since the .catch always .resolve anyway, this just makes sure the function doesn't call it on silly params
=> fix(authorization): optional chain

packages/node_modules/@webex/webex-core/src/lib/services/services.js
Updating to not log entire response since it's not needed
---
=> fix(webex-core): remove logging entire client region info response

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Fixes issues with replace locus , Always last active locus url will get replaced
---
=> fix(plugin-meeting):  locus replace always with the last active

packages/node_modules/@webex/plugin-meetings/src/reachability/index.js
Fixes a bug in GDM Reachability where we call .close() on a connection
that has already been closed. This check prevents that.
Fixes #SPARK-165138
---
=> fix(plugin-meetings): check peerConnection state before closing

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/reachability/index.js, packages/node_modules/@webex/plugin-meetings/src/reachability/request.js
Move the GDM discovery to the meetings registration flow.
Also refactored the unnecessary usage of webex stateless plugin and made the webex object a class instance variable instead.
Fixes #https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-192941
---
=> Gdm discovery during register

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
When using a conversation id from hydra, we were ignoring the work the meeting info utility was doing to decode and detect the destination type. 
---
=> fix(plugin-meetings): use fetch info for destination

packages/node_modules/@webex/webex-core/src/lib/services/interceptors/server-error.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/interceptors/server-error.js
Adds 502 and 503 support to failover checks
---
=> fix(server-interceptor): add additional error codes for failover

package-lock.json
#SPARK-201387 security fix
chai has a dependency on this package, but bumping it still matches the dependency requirement `"pathval": "^1.1.0",`
=> fix(package): bump pathval to 1.1.1

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes [SPARK-194866](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-194866)
Replaces #1983 
I manually tested by setting a breakpoint and closing the peer connection before the stabilty check and it errored properly. Still need to figure out how to automate the testing for these features.
=> feat(meetings): fail meeting join if peer connection isn't stable

packages/node_modules/@webex/plugin-meetings/src/common/logs/request.js
Currently `meeting:logUpload:success` fires even when logs fail to upload. This ensures the failure is handled correctly.
Fixes #SPARK-210681
---
=> fix(plugin-meetings): prevent success message when log upload fails

packages/node_modules/samples/browser-single-party-call-with-mute/app.js
We were using the `.muted` property which isn't supported by safari
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#browser_compatibility
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-196047
=> fix(samples): use play and pause for muting

packages/node_modules/@webex/plugin-meetings/src/config.js
Enable RTX media resiliency for video 
---
=> feat(plugin-meetings): enable rtx media resiliency by default

packages/node_modules/@webex/webex-core/src/webex-core.js
Fixes [SPARK](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-203178)
On WebEx, when user uploads a file we should check for file limit and restrict the user to upload files within specified limit or 2048 MB by default
---
=> fix(upload): add abort function on file upload for webex

docs/api/index.html, documentation/config.yml
Removes phone plugin references in the SDK docs "calling" section and renames section to "meetings".
Fixes #SPARK-117145
---
=> docs(api): remove phone plugin reference

tooling/lib/build.js, webpack.config.js
Fixes incident where UMD bundle was not being produced.
---
=> fix(umd): update script to accomodate Weback CLI v4

packages/node_modules/@webex/internal-plugin-support/src/support.js, packages/node_modules/@webex/internal-plugin-support/test/unit/spec/support.js
Client logs service does not handle empty key value pairs.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-214511
=> fix(support): only upload keys that exist

packages/node_modules/@webex/plugin-meetings/src/constants.js
Change the default timer for connection failure 
---
=> fix(plugin-meetings): decrease the timer for meeting connect failure

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/audio.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/video.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
=> fix(plugin-meetings): reset audio and video state machines when leaving a meeting

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180894
In scenario where the host joins first then leaves the meeting without assigning a new host , The locus does not send any host info so we make sure to not parse host info it its not present
---
=> fix(plugin-meetings): fix hostId error when host is not present

packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-errors.js, packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-meetings-error.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Currently metrics gets flooded with errors when user is trying to do a action due to meeting inactivity 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-215716
---
=> fix(plugin-meetings):  throw error when meeting is inactive on a action

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js
when declining a meeting the current SDK defaults to a `reason: 'BUSY'`. the reason part of the request payload is optional, so we should allow people to decline a call with no reason. currently in the web client, declining with a reason of "busy" causes different behavior when rejecting an incoming call compared to the desktop clients. when rejecting the 1:1 on desktop, they don't send a reason.
=> fix(meetings): make reason for decline optional

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fix broken code to check the IDLE state for guest user
---
=> fix(plugin-meetings): throw error when guest is in IDLE state

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
The intention of this PR is to add the ability to "hide" and "unhide" conversations via the js sdk as can be done in the thick clients, so that this can be added to the web client. This appears to be done via the "IGNORED" tag. I'm not certain if this is the best way of doing it, but I tried to follow the pattern used for muting./ unmuting messages and mentions.
=> Add ignore and unignore functionality

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Improved handling of stopping share stream natively, and checks/fixes if screen share is out of sync.
Fixes #SPARK-190274
---
=> fix(plugin-meetings): prevents screen share from getting out of sync

packages/node_modules/@webex/plugin-meetings/src/roap/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/utils/testUtils.js
This PR is to remove the unique ID sent for `mediaId` property when sending a ROAP request on reconnect. When a unique ID is sent, it prevents the media from streaming properly. We don't fully understand why yet, but we're reverting back how the request was previously sent.
Fixes #[214541](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-214541). See also [WEBEX-180532](https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-180532)
=> fix(meetings): don’t set media ID on reconnect to avoid black screen

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js
Use new conversation endpoint that only returns a list of conversations without activities or participants.
Fixes #[SPARK-232873](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-232873)
---
=> Add ability to use new conversationsSummary resource

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js
fixes #SPARK-209898
The problem was that updateVideo was updating also the audio track
reference in the meeting object, while the rtc connection was still
using the old audio track, so then muting would stop working, because
we would be muting the wrong track.
Same applies to updateAudio.
=> fix: prevent updateVideo from updating the audio track

packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
…ough to sendUserActivation
Allow for extra options to be passed through to sendUserActivation when sending the activation and to use license service.
This will be useful for webex web app in user activation flow to validate user.
---
=> feat(core): allow for options in sendUserActivation

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes #SPARK-238731
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-238731
---
=> fix(plugin-meetings): camera still on when sendVideo is false

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Fixes #[SPARK-231755]
Currently the moveTo and moveFrom methods (which instantiate a new device) invoke methods on the Metrics object that currently do not exist and were previously removed.  This PR makes sure the metrics calls are using the appropriate methods and passing the appropriate options
---
=> fix(meetings): use proper metrics methods in move media calls

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js
fixes: SPARK-227135
Extending the changeVideoLayout API so that the app
can send renderInfo to the backend. The actual sending
of the request is debounced, because /control endpoint
has a rate limit of 24 per second and it's very likely
that developers will call this API very frequently in
some scenarios (for example on window size change).
=> feat(meetings): Custom size remote video (coming soon)

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js
If you use the SDK to join a meeting via a SIP url and that meeting has nothing to do with webex (so it's not a url of a PMR or of any webex space) - for example if you call a meeting hosted by Cisco Meeting Server (CMS): example: `alpha_test2@alphauk.cisco.com` then the meeting object doesn't get destroyed after you leave the meeting and it remains there forever.
This kind of meeting is reported by locus as type = "SIP_BRIDGE". I've checked with Locus team and they confirmed that it's better to treat SIB_BRIDGE types of meetings like CALL ones (and not like MEETING ones)
Fixes [SPARK-248251](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-248251)
=> fix(meetings): remove non-Webex calls after user leaves

packages/node_modules/@webex/plugin-meetings/src/meeting/muteState.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js
If video and audio are not set together, the server will set the missing stream to false (unmuted) by default.
Fixes [SPARK-242346](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-242346).
Replaces https://github.com/webex/webex-js-sdk/pull/2116 due to CI issues
=> fix(meetings): set both, audio and video, when muting

packages/node_modules/@webex/plugin-meetings/src/networkQualityMonitor/index.js
When screen sharing, the log is filled with errors:
"TypeError: Cannot set property 'packetLoss' of undefined
This PR fixes it.
=> fix: stop flooding logs with errors while screen sharing

packages/node_modules/@webex/internal-plugin-ediscovery/README.md, packages/node_modules/@webex/internal-plugin-encryption/src/kms.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/kms.js
This PR will fix [SPARK-257081 - Update webex-js-sdk to support `onBehalfOf` as well as `userId` for scenarios where the CO does an onBehalfOf himself](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-257081). Basically it's an edge case where a Compliance Officer is decrypting content **onBehalfOf** himself. KMS had a bug where, in this scenario, the code flow assumed this is not an **onBehalfOf** request, and as a result fails with a 403.
This issue is being covered by 
* BEMS01309085 [New] C3 TO BE ASSIGNED CPR COMPANY   691741276  Failed to download Summary Report via ediscovery Download Manager. Hangs at downloading... Indicates 'disconnected-waiting to try' and can't download the data finaly
* Cisco TAC Case : 691741276
The customer is also complaining about how long it's taken for …
=> fix(encryption): setting onbehalfof to support an edge case

packages/node_modules/@webex/internal-plugin-user/src/user.js, packages/node_modules/@webex/internal-plugin-user/test/integration/spec/user.js, packages/node_modules/@webex/internal-plugin-user/test/unit/spec/user.js, packages/node_modules/@webex/webex-core/src/credentials-config.js
If there is any authorization error, Client can leverage CI User One Time Login APIs to provide user with an option to do One Time login using a 6 digit PIN.
For social sign in flow webapp requires new functions for generating and validating one time passwords. 
Wiki links for both apis are:
https://wiki.cisco.com/display/IDENTITY/API+-+Generate+UserOTP
https://wiki.cisco.com/display/IDENTITY/API+-+Validate+UserOTP
Added generateOTP and validateOTP for the above and also added relevant integration and unittests.
SPARK-260835
---
=> feat(internal-plugin-user): generate and validate otp

packages/node_modules/@webex/internal-plugin-ediscovery/src/transforms.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/transforms.js
eDiscovery will be handling new activities which contain space information (name, description etc.) that must be decrypted so that the end user will be able to read it.
Fixes #[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-238602]
---
=> SPARK-238602 Decrypt space information for eDiscovery

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/src/share-activity.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/share-activity.js
When uploading a space avatar, the client begins by uploading the proposed image file to the Files Service, using a POST request. This story is to add the property "role":"spaceAvatar" to that request body. Doing so will allow Files to bypass its normal file share blocking rules.
Fixes #SPARK-239726
=> fix(internal-plugin-conversation): uploading space avatars 

packages/node_modules/@webex/common/src/constants.js, packages/node_modules/@webex/common/src/index.js, packages/node_modules/@webex/internal-plugin-device/src/config.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/roap/collection.js, packages/node_modules/@webex/plugin-meetings/src/roap/handler.js, packages/node_modules/@webex/plugin-meetings/src/roap/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js
These changes are required for adding the dial-in feature to Cantina. Tharin has detailed what the sdk changes are here:
https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=189965849 and had originally opened a PR here https://github.com/webex/webex-js-sdk/pull/2144
Unfortunately, he has had to hand it over to me and I do not have permissions to push to his fork or modify his PRs, so I have had to create this new PR incorporating all of the comments from #2144. Once squashed, it should be ready to go.
Part of https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224642
=> feat(dial-in): add ability to provision and remove dial in devices

documentation/README.md
Noticed the docs hyperlink was broken
=> docs(readme): correcting the docs hyperlink

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280998
---
=> fix(meetings): move meetingInfo instantiation to onReady callback

packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js
Added test case for checking sipUrl in response.
=> test(plugin-meetings): check sipUrl in meetingInfo response

packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/utils/webex-test-users.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260888
at the time of this writing: the test works when using v2, but other existing tests (16) fail when using v2
=> test(plugin-meetings): added test for hydra roomId on new meetingInfo Api

packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js
Added spec for:
- Fetch meeting information with a conversation URL for a 1:1 space
- Invalid conversation URL and asserting that fetchMeetingInfo returns an error.
The following is the test results when `config.enableUnifiedMeetings = true`
=> test(plugin-meetings): add spec for conversation

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/utilv2.js
Fixes [SPARK-263135](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263135)
This happened in the [Webex Server](https://webex.github.io/webex-js-sdk/example/servers) usage and not in [browsers](https://webex.github.io//webex-js-sdk/guides/browsers/) because the plugin-meetings tries to create an object for [RTCPeerConnection](https://github.com/webex/webex-js-sdk/blob/master/packages/node_modules/%40webex/plugin-meetings/src/meetings/util.js#L78) which wouldn't be available in node.js (while checking if H264 codec is available). Basically browser creates this object whereas server wouldn't and the error gets caught.
---
=> fix(plugin-meetings): logger init before meeting's onready call

packages/node_modules/@webex/plugin-meetings/src/common/errors/captcha-error.js, packages/node_modules/@webex/plugin-meetings/src/common/errors/password-error.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/utilv2.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Initial draft of changes required to support password and captcha when talking with WbxAppApi
It's still got lots of todo comments, console logs, etc.
Tests need to be added/updated.
Some of the new code may be also be gated on the config setting for using wbxappapi.
=> feat(plugin-meetings): password and captcha support for unified space meetings

packages/node_modules/samples/browser-plugin-meetings/app.js
This pull request is to disable unified meetings in sample application as discussed in PR linked above.
- Disable unified meetings on `webex.init` call
- Display the correct meeting version on webex ready 
- Unified Meeting Version on load is manually checked in sample app
- Toggled meeting info back and forth and created meetings to verify correct working
---
=> docs(browser-plugin-meetings): disable unified meetings by default

packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/peerconnection-manager/utils.js
](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-299232)
Server rejects request from a ipv6 browser having ipv6 address in c line 
Parse the SDP and convert the Ipv6 candidates to 0.0.0.0 in c line
Performed manual testing on t mobile network i iphone
---
=> fix(plugin-meetings): media not connecting on ipv6 network

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/handler.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
We are changing the current operational metrics to behaviors metrics so that we can track the user activity flow 
which help identifying the user flow and issues 
We are changing the metrics values from "Operational" to "behavioral" and adding some user properties like userID , os information etc 
https://analytics.amplitude.com/cisco-cross-project/dashboard/48b3zev
Did manual test where the data is been shown in the dashboard 
---
=> feat(plugin-meetings): start sending behavioral metrics to amplitude

packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/peerconnection-manager/index.js
Currently the sdk offers transport cc using the config value enableExtmap which will make sure we send 
`a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01`
as an offer to the server and server responds back with an answer 
In cases remote screen share the server offers the same 
`a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01`
in the remote SDP but the client initially has disabled transport cc 
So we need to make sure we remove the extmap line not only in the offer from client but also offer from the server
remove extmap based on toggle in peerconnection manager
Manual test was performed
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#subm …
=> fix(plugin-meetings): fix extmap config boolean

packages/node_modules/@webex/webex-core/src/interceptors/webex-user-agent.js, packages/node_modules/@webex/webex-core/test/unit/spec/interceptors/webex-user-agent.js
Fixes a singleton issue discovered from the react-widgets, where the proper metadata wasn't be set correctly for identification purposes.
Check if a `appLabel` property exists in the given config and append that information for metrics
Unit
---
=> feat(core): check for appPlatform for spark-user-agent

packages/node_modules/@webex/plugin-meetings/src/meetings/util.js
Avoiding showing an error message when H.264 is not detected in a Node environment.
Changing the error log to a warning log
Manual test to see warning instead of an error.
---
=> fix(plugins-meetings): warn if H.264 codec is not detected

packages/node_modules/@webex/internal-plugin-conversation/src/share-activity.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/share-activity.js
Working on restricting file upload/download based on file type requires the client to send file extension "claimedFileType" for every upload request.
I have added additional property "claimedFileType" inside file upload request. That property will be used to restrict file to be upload/download by file type extensions. 
Unit Test
---
=> feat(internal-plugin-conversation) send file extensions on file upload

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Attach an error payload when `meeting.join()` throws an error.
Catch and parse the Locus error and send a diagnostic-event.
Manual test to see if error payload is attached when attempting to join an invalid meeting.
Automated test:
`npm test -- --packages @webex/package-meetings --node`
---
=> feat(plugin-meetings): send diagnostic error when join fails

docs/index.html
This is a quick tweak to add a link to the samples/index.html in the navbar of the homepage
- [ x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ x] I discussed changes with code owners prior to submitting this pull request
- [ x] I have not skipped any automated checks
- [ x] All existing and new tests passed
- [ x] I have updated the documentation accordingly
---
=> docs(): add a link to all the samples in the nav bar

docs/samples/browser-plugin-meetings/app.js, packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/request.js, packages/node_modules/@webex/plugin-meetings/src/meetings/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/utils.js, packages/node_modules/@webex/webex-core/src/interceptors/payload-transformer.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/services.js
All the new adhoc webex meetings will use the new instantspace api for there webex meetings 
As part of the api we need to fetch the conversation then make a api call to instant-space with the invite 
use the Following api for instant meetings 
https://confluence-eng-gpk2.cisco.com/conf/display/WMT/WebexAppAPI+API+Document
Did manual testing to join a adhoc meeting and also checked if the obtp is being received 
---
=> feat(plugin-meetins: add adhoc meetings support

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
We were seeing issue where the Eu org an some specific domains are not able to get userPreferences information 
Silently fail the function 
https://pr-2332.d3m3l2kee0btzx.amplifyapp.com/samples/browser-plugin-meetings/
---
=> fix(plugin-meetings): fail silently if webex site information not found

SCRIPTS.md, package.json
I want to be able to build a single package e.g. `npm run build:package @webex/plugin-meetings` but the suggested method of `simply run some other script` is 1. unhelpful and 2. incorrect. If I run that, the prebuild step is called which clears the rest of the packages making it impossible to make changes to just one package.
Undeprecate the `build:package` command. When this command is run, it no longer triggers the prebuild step for build and so only builds the intended package.
---
=> build(package): fix building a single package

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
Users with config.experimental.enableUnifiedMeetings disabled see incorrect meeting information when they are in spaces with other users that have config.experimental.enableUnifiedMeetings enabled and start instant meetings that overlap with scheduled meetings.
SDK will now use conversation url to match incoming Locus event with existing meetings only for non-USM meetings irrespective of the configuration config.experimental.enableUnifiedMeetings
manual tests of steps described in spark-325176
---
=> fix: spark-325176 non-USM users see meetings with wrong participants

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
When a meeting is about to start in 5 minutes, we receive information about it from Locus and SDK creates a meeting object. At this time SDK fetches the meeting info for that object. This will cause a spike of traffic to the wbxappapi service - they have seen this problem with UCF and it has caused an outage of wbxappapi service on multiple occasions.
WbxAppAPI team have asked us to put a random delay for the call to meetinginfo api for OBTPs to avoid the spike in traffic. They've already agreed this solution with UCF team and UCF have already done this implementation - they add a random delay (up to 2-3 minutes) or fetch the meeting info immediately if the user presses the OBTP before the random delay is finished.
1. Change createMeeting() so that it doesn't call …
=> feat(webex): add random delay to fetchmeetinginfo

packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/request.js, packages/node_modules/@webex/plugin-meetings/src/meetings/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/utils.js, packages/node_modules/@webex/webex-core/src/lib/services/constants.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/unit/spec/services/services.js
JIRA Ticket - [SPARK-325626](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-325626) - Start Using the /meetings api for preferred webex site 
Started using the meetings API for the preferred Webex site
Changed the function name to getMeetingPreferences
Used the https://webexapis.com/v1/meetingPreferences and mention it in the constant file
Updated the util function to parse the site info and get the default Webex site from it
Unit Testing covered
I started using the meetings API for the preferred Webex site
Moved From using identity to fetch Preferred Webex site to https://developer.webex.com/docs/api/v1/meeting-preferences/get-meeting-preference-details
For fetch preferred Webex site information
Use the above api to fetch the preferred meeting site rather then using the identity
< …
=> fix: use the meetings preferences api for webex site

webpack.config.js
[SPARK-303051](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303051) Thinkrite - JS SDK - sample slow on PORT 8080 
Using the .env for PORT in the web pack config
Screnshot added below -
---
=> fix(plugin-meetings): using the env for port in the web pack config

packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
The ipv6 address was not being masked with CIDR /96 for localNetworkPrefix. As a result, it was showing the ip address suffixed with `...0`.
The localNetworkPrefix is now being masked with CIDR /96 and same is getting sent to the `clientmetrics` API for `diagnostic-event` type event
---
=> fix: mask localNetworkPrefix in ipv6 format to CIDR/96

.eslintrc.json
There are yellow linter lines all over due to the 80 character line limit that is only a warning. It is clear that nobody wants this, otherwise all the lines would be smaller.
As it is right now it interferes with the ability to read the code and to spot other warnings.
Changing eslint to ignore the line length
---
=> chore(eslint): ignore max line length

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/src/encryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/encryption-transforms.js
1. added support for incoming meeting chat activity events
2. do not encrypt payload sent to meeting-container service to create convo (check `created: 'True'`)
=> Imc chat events

packages/node_modules/@webex/internal-plugin-device/src/device.js, packages/node_modules/@webex/internal-plugin-device/test/unit/spec/device.js
WDM (device service) has implemented a new caching mechanism to prevent the unnecessary sending of the large feature toggle json.
This PR implements that caching mechanism.
1. Collect the etag header upon successful registration
2. Send the etag in `If-None-Match` header
3. If the etag matches, only update the user and entitlement sections of the feature toggles (developer feature toggles are empty in this case)
---
=> Wdm optimization

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/constants.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Behavioural metrics for enable and disable BNR functionality.
Added behavioural metrics for enable and disable BNR functionality to track the usage and any corresponding errors.
---
=> feat(plugin-meetings): added metrics for bnr functionality

packages/node_modules/@webex/plugin-meetings/src/members/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/members/index.js
A small error in the name of the members request used when raising / lowering hand
Correcting the name and updating some tests
All paths through the method
=> fix: use the correct members request in raiseOrLowerHand

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/members/index.js, packages/node_modules/@webex/plugin-meetings/src/members/request.js, packages/node_modules/@webex/plugin-meetings/src/members/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/members/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/members/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/members/utils.js
- Adding the lower all hands method to the plugin-meetings
- Add lower all hands to members
- Added utils
- Added tests
---
=> feat: added lower all hands to plugin-meetings

packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
Fixes [SPARK-352626](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-352626)
In #2392 a change was made to the `fetchMeetingInfo` function which resulted in it not returning the meeting info... This should rectify that issue by actually returning the response from the request. This also improves upon existing tests which now ensure something is returned from the promise (currently it is `undefined`).
Note that there is one test that is still broken, but is unrelated to this change so I have opened [SPARK-353036](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-353036) to track it (since I think some logic in the actual implementation will want to be fixed also).
- Unit tests added to ensure the request response is returned in the promise
- Checked meeting info on web client when using …
=> fix: return the response from the meetingInfo API

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Missing validation for device registration before user joins a meeting
- Fixes the missing validation for device registration before user joins a meeting
- Adds unit test for the same
Screenshot
---
=> fix(plugin-meetings): add validation for device registration

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/infoUtils.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/infoUtils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/selfUtils.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-354097
This pull request addresses
meeting display hints are set to true even when one has joined the meeting.
by making the following changes
Added a check to see if participant is in the meeting.
---
=> fix: check joined display hints

package.json
docs build was failing due to recent inclusion of typescript files
added the necessary flag to the documentation build script
---
=> fix(docs): fix docs build for ts files

karma-ng.conf.js
no jira
When running tests like this:
```
npm test -- --packages @webex/plugin-meetings --unit --browser --karma-debug --browsers chrome
```
I get the following errors:
```
15 09 2022 09:07:47.714:ERROR [framework.browserify]: bundle error
15 09 2022 09:07:47.714:ERROR [framework.browserify]: SyntaxError: /home/mawojtcz/my-build/webex-js-sdk2/packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/lib/BasicSeqCmp.json: Missing semicolon. (2:15)
1 | {
> 2 |   "comparisons": {
|                ^
3 |     "test_equals01_rev": {
4 |       "current": "test_equals01_b",
5 |       "new": "test_equals01_a",
15 09 2022 09:07:47.715:WARN [karma]: No captured browser, open http://localhost:8001/
```
Fixed karma config.
unit tests
--- …
=> fix: karma tests fail to start in a real browser

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, docs/samples/browser-plugin-meetings/style.css
Worked on Samples -
Added the height and width parameter to the remote screenShare layout - Removed
Some UI adjustment
Updating video element code for UI
show the current resolution and fps using the getSettings on the video track every 3 seconds
Changes in samples code - 
docs/samples/browser-plugin-meetings/app.js
docs/samples/browser-plugin-meetings/index.html
---
=> feat(samples): sample app provide option to select the resolution & UI adjustments

docs/samples/browser-plugin-meetings/app.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This change is for sending FULL HD i.e. 1080p video(local video).
1. Updated samples app.js to accomodate new FULL HD track when user selects local resolution as 1080p.
2. Updated `setLocalVideoQuality` of meeting to check if browser is chrome then stop the current track(open [bug link](https://bugs.chromium.org/p/chromium/issues/detail?id=943469)) and sets local resolution to 1080p.
3. Checked the behaviour on all 3 browsers i.e. Chrome, Safari and firefox.
---
=> send full hd

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
When in the meeting lobby, we aren't sending or receiving media, which causes the call to timeout. We should be sending locus keepAlives to keep the call alive.
I have added a repeating timer to send locus keepAlives, based on the thick client code https://sqbu-github.cisco.com/WebExSquared/spark-client-framework/blob/71d7176dd4591e92859c06c4ee6e3198ee162455/spark-client-framework/Services/TelephonyService/LocusManager.cpp#L2629
---
=> fix(guest join): send keepalives when in lobby

packages/node_modules/@webex/plugin-meetings/src/reachability/index.js, packages/node_modules/@webex/plugin-meetings/src/reachability/request.ts, packages/node_modules/@webex/plugin-meetings/test/unit/spec/reachability/request.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-364898
With the current design of reachability in JS-SDK, it will always fail if the cluster is on the same network as the client, which means that it will always fail for video mesh nodes if client is on the corporate network and it also always fails for the cisco cloud clusters if you are on cisco network (or cisco vpn). Cisco users always get some video mesh nodes in their cluster list, so that means that reachability always takes 5s for cisco users, because:
- if they're on Cisco VPN, the reachability checks for all clusters will fail, so they wait for the 5s timeout 
- if they're not on VPN, the reachability checks for cisco video mesh nodes fail, because they're only available on cisco network, so again the clients will have to wait …
=> fix(plugin-meetings): Using new reachability timeout values (1s for video mesh, 3s for the rest)

.circleci/config.yml, package.json, tooling/dep2.js
Fixes the issues with the release broken with yarn workspace, converts all the workspace reference to actual version number
=> fix: release to publish correct version number

docs/samples/browser-plugin-meetings/app.js
If you had more than one meeting going on, the sample app was applying settings to the first one instead of the one it was in. Noticed during multistream testing.
changed getCurrentMeeting to select the meeting with selectedMeetingId (which is already done in some places in the code), instead of picking the first meeting off the list. Discussed with @marcin-bazyl 
---
=> fix(sample app): apply settings to correct meeting

package.json, packages/@webex/internal-plugin-llm/LICENSE, packages/@webex/internal-plugin-llm/package.json, packages/@webex/internal-plugin-voicea/LICENSE, packages/@webex/internal-plugin-voicea/package.json, packages/@webex/plugin-meetings/LICENSE, packages/@webex/plugin-meetings/package.json, packages/webex/LICENSE, packages/webex/package.json
This PR is Ad-hoc and does not have a ticket associated with it.
Webex JS SDK was still showing MIT in package.json
Changed package.json license property to point to Cisco EULA
---
=> fix: sdk licence update to cisco eula

packages/@webex/plugin-meetings/src/common/errors/webex-errors.js, packages/@webex/plugin-meetings/src/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This is a PR for sdk_v3 branch. It makes sure we send the same kind of metrics related to SDP handling on the sdk_v3 branch as we have been sending on master.
This PR depends on webrtc-media lib changes from here: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/145 that have been released as "@webex/internal-media-core@0.0.14-beta"
=> spark-367050: SDP related metrics

packages/@webex/plugin-meetings/src/media/properties.js, packages/@webex/plugin-meetings/src/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/media/properties.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Added connectionType to BEHAVIORAL_METRICS.ADD_MEDIA_SUCCESS metric (this is part of the TURN TLS feature, so that we know how many clients connect using TURN).
jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-370008
There seems to be a bug in Firefox and Safari where they don't set the relayProtocol correctly for the local candidate when connecting using TURN. It works fine in Chrome/Edge.
There is an indentation change in addMedia() in meeting/index.js, because there were some `then()` calls that were unnecessarily nested, so it's best to view the diff with "hide whitespace" checkbox ticked. I've fixed it here, because this is also already fixed on sdk_v3 branch and is causing conflicts every time I merge latest master into sdk_v3, so fixed it now on master to make my life …
=> feat(plugin-meetings): added connection type to "js_sdk_add_media_success" metric

packages/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
There was a recent change on master to the output of `doTurnDiscovery()` function, so after merge from latest master the TURN server information was not properly passed to `createMediaConnection()` resulting in browser failing to create the RTCPeerConnection.
Similar fix will be required on master, although the code is slightly different there.
=> fix: use correct TURN TLS information when reconnecting

packages/@webex/plugin-meetings/src/media/index.js, packages/@webex/plugin-meetings/src/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Changed Media.createMediaConnection() to take a value for debugId that's passed to the roap media connection, so that we can set it to be unique per meeting - this is especially useful when looking at logs from integration test runs where we have multiple test users and meetings happening at the same time in same browser tab.
While I was there, I've reorganised the arguments of Media.createMediaConnection() and put things that are optional in options and things that are not optional as separate args.
=> fix: set unique debugId for media connections

packages/@webex/plugin-meetings/src/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-392487
Client app had no explicit API to know when a RemoteMedia instance was no longer useable. It had to assume that when a layout changes, the old RemoteMedia instance are stopped or that when we leave the meeting they are all stopped.
Added a "stopped" event to RemoteMediaEvents, which is emitted from RemoteMedia.stop()
unit tests
---
=> fix: added stopped event to RemoteMedia

packages/@webex/plugin-meetings/package.json, yarn.lock
ts-sdp lib has introduced an API breaking change in version 1.3.1 so we don't want to use ^ in the version designation in package.json, because we can accidentally bring in the new version that breaks SDK
Removed ^ from the @webex/ts-sdp version. Also removed it for @webex/internal-media-core, because this lib is often changing rapidly and may have API breakages in minor versions too.
automatic tests
---
=> fix: version of @webex dependencies

packages/@webex/plugin-meetings/src/meetings/index.ts
As per docs `meetings.uploadLogs()` is supposed to return a `feedbackId` but it was not being returned.
Returns the feedbackId from `meetings.uploadLogs()`
---
=> fix(plugin-meetings): return feedbackId from uploadLogs

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/reactions/reactions.ts, packages/@webex/plugin-meetings/src/reactions/reactions.type.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js
Add new public method `sendReaction` on meetings plugin on the meeting object.
- add new request under plugin-meetings/meeting/request
- add new public method on the meeting object
Unit tests, manual testing.
---
=> feat(reactions): add sendReaction on meeting plugin

packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Added support to pass `facingMode` and `frameRate` while setting custom video resolution in `getMediaStreams` method of meetings.
---
=> fix(plugin-meetings): facing mode in get media streams

packages/@webex/internal-plugin-conversation/src/encryption-transforms.js, packages/@webex/internal-plugin-team/src/team.js, packages/@webex/internal-plugin-team/test/integration/spec/actions.js, packages/@webex/internal-plugin-team/test/unit/spec/team.js
when users join a space we need to send a new kmsMessage
`packages/@webex/internal-plugin-team/src/team.js` `.joinConversation` now takes an additional argument `userId`. this argument *must* be provided. this function also creates a new body with a kmsMessage sent with the POST to convo to join the space
---
=> fix(plugin-conversation): Send kms on join

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/media/internal-media-core-wrapper.ts, packages/@webex/plugin-meetings/src/media/properties.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/src/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/properties.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js, yarn.lock
TS errors related to MediaConnection types.
Fix is done in @webex/internal-media-core lib in this [PR](https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/157) and this SDK PR is just updating the SDK accordingly so that it builds: basically we now import all the MediaConnection types directly from @webex/internal-media-core, they are not wrapped with `MediaConnection` anymore.
unit tests
---
=> fix(plugin-meetings): imports of MediaConnection from internal-media-core

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-391543
This is the only place in the SDK where localStorage is used instead of using the boundedStorage interface. localStorage should
not be used directly as it ignores the preferences of the SDK user to use their chosen storage adapater.
Roap and RoapRequest were using localStorage directly. I've updated them to use boundedStorage instead. This necessitated some slight refactoring to allow these classes to use the async boundedStorage interface.
---
=> Spark 391543 use bounded adapter

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This is a workaround for https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-308749
Edonus sometimes doesn't handle Roap glare correctly. This happens especially when we are stealing screen share from someone. In that case we send an SDP offer to Edonus and also request floor from Locus. Locus giving us floor triggers an offer from Edonus. Edonus should not send us that offer if it already has an outstanding offer from us, but it does it and it sends it with an increased seq, which is a breach of the Roap protocol and as a result Linus doesn't correctly detect the glare condition and even though we reply with Error-Conflict to Edonus' offer, Linus keeps resending us that offer until eventually Edonus times out and call is destroyed.
Changing the code so that we only send the floor request …
=> fix: workaround for edonus bug when handling Roap glare

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/multistream/remoteMedia.ts, yarn.lock
Update version of webrtc-adapter to match what WCME is using (it's also required for Firefox to work in multistream, although it's not the only fix required)
Also adding types in a couple of places as typescript complains about them missing when using local linked internal-media-core lib.
---
=> fix: update webrtc-adapter

packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
When the user joins remotely muted (meeting demands users to join muted), then the user unmutes themselves, the locus wasn't unmuting the user. This is because, on join locus thinks we are locally muted as well as remotely muted as we send localSdp based on both local mute state and remote mute state.
We have introduced a new audio method to know if we are locally muted which is sent on the /media request on join. This way, locus is aware we are remotely muted but locally un mute. This way the ROAP OFFER / ANSWER / OK cycle is corrected.
---
=> fix(plugin-meetings): set correct local audio state in localsdp 

.gitignore
- remove types folder from `.gitignore` so that they get published to npm
- change gitignore
---
=> feat(gitignore): remove types folder from gitignore

packages/@webex/plugin-meetings/src/meeting/index.ts
@marcin-bazyl 
the roap bug from the "Participants being kicked out of real world converged meeting" space is a regression on SDK master that was introduced in the [prettier PR](https://github.com/webex/webex-js-sdk/pull/2548) - every time anyone calls Meeting.updateMedia() SDK sends the new Offer twice (increasing the seq each time), so as a result you will be dropped from the call.
This is because updateMedia() calls sendRoapMediaRequest() twice: the block between lines 4888 and 4913 should be removed - it's a duplication of the block in the next lines - looks like some merge that has gone wrong
removed the merged code
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/C …
=> fix: call disconnecting after calling updateMedia

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, yarn.lock
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-393485
Enables receiving and sending of screen share in multistream meetings
using latest internal-media-core version that:
- contains WCME version that has a workaround for missing bundling support in the backend (required for screen share to work)
- enables floorControlledPresentation in WCME config 
---
=> fix: enabled screen share for multistream

packages/@webex/plugin-meetings/src/meeting/index.ts
Metric for failure to add media is sent twice.
Removed the call to send metric, because there is another catch later down in that function that sends the same metric again.
---
=> fix: 'js_sdk_add_media_failures' metric is sent twice

packages/@webex/plugin-meetings/src/members/index.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlotManager.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-405017
When a remote participant joins a meeting, we get a source update event on a receive slot and a Locus update on the member (with the new csi value for the video stream for that member). If the receive slot event comes before the Locus update, the SDK ReceiveSlot (and consequently also the RemoteMedia object) will have memberId set to undefined.
Updating memberId on all receive slots that have it undefined whenever any Locus update to members happens
---
=> fix: update memberId on ReceiveSlots when members are updated

packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-405017
When we find memberId after a Locus update, the app doesn't know about the change.
We now emit SourceUpdate event so that the existing app code for that event handles the memberId update too.
---
=> fix: emitting SourceUpdate event when memberId is found for ReceiveSlot

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, yarn.lock
This PR adds multistream logs to the log buffer to be sent after a call ends or fails.
The webrtc-media-core lib was altered to allow for a log handler for multistream logs.  This PR adds a log handler callback that maps the log types (`warn`, `info`, `debug`, etc) to the internal webex logger.
Note: relies on this PR: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/164
---
=> fix(plugin-meetings): add multistream logs to log buffer

packages/@webex/plugin-meetings/src/config.ts
Video freeze for most people all the time in multistream meetings
Reducing the limit of total resolution of all received streams from 4K to 1080p.
---
=> fix: reduced maxMacroblocksLimit for multistream

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts
An error where stats for a previous transceiver are missing causing a TypeError.
Adding optional chaining around the lookup of the stats results.
---
=> fix(plugin-meetings): add optional chaining around stats lookup

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, yarn.lock
Videos sometimes not appear at all after switching layout.
Bringing in a new version of WCME that has the fix for https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-320266 and removing the SDK code that resets the sourceState for receive slots that are not used any more - this can be removed, because now this is taken care of by WCME.
---
=> fix: remove code for resetting of source state

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/src/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMedia.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-385727
Adds size hint API to multistream
The width and height of a video element can be given to the remote media object which causes a request to be sent respecting the frame size calculated from the width and height.
---
=> feat: provide size hint remote media

packages/@webex/internal-plugin-support/src/support.js, packages/@webex/internal-plugin-support/test/unit/spec/support.js
Sending of product area and issue in the log metadata.
adding the keys: `productAreaTag` and `issueTypeTag` in  method : `_constructFileMetadata`
Tested the sdk code locally with the client code.
---
=> feat(internal-plugin-support): allow productAreaTag and issueTypeTag to be in log metadata

jest.config.js, packages/@webex/internal-plugin-conversation/src/share-activity.js, packages/@webex/internal-plugin-device/src/device.js, packages/@webex/internal-plugin-encryption/package.json, yarn.lock
The scope of the changes in this pull request are to update the version of the dependency `node-jose` within the `encryption` plugin to prevent a potential bug introduced with platform iterations [infinite looping].
This also includes fixes for failing integration tests in:
* internal-plugin-device
* internal-plugin-conversation
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-407814
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-411322
=> fix(encryption): node-jose version

README.md, packages/@webex/internal-plugin-metrics/src/metrics.js, packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js, packages/webex/README.md
removed org_id, client_id and user_id tags from operational metrics,
added client_id as part of fields instead of tags
added/updated unit test for the same
files - 
packages/@webex/internal-plugin-metrics/src/metrics.js
packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js
removed org_id, client_id and user_id tags from operational metrics,
added client_id as part of fields instead of tags
added/updated unit test for the same
`client_id` has been added to the field, PFA for the same as proof value has been passed in payload.
---
=> fix(metrics): remove org_id, client_id and user_id tags from operational metrics

packages/@webex/internal-plugin-flag/jest.config.js, packages/@webex/internal-plugin-flag/package.json, packages/legacy/eslint/static/ignore-patterns.js, packages/legacy/jest/README.md, packages/legacy/jest/package.json, packages/legacy/jest/static/index.js, yarn.lock
The scope of the changes in this pull request are to generate the core jest config as an elevated package. This package is being consumed in the *test* package: `internal-plugin-flag`.
=> feat(legacy): generate test config

packages/@webex/plugin-meetings/src/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMedia.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-414720
Allows the set size hint functionality choose maxFs correlating to a 1080 video stream.
Added an extra threshold at 900px height, above which 1080 will be chosen
---
=> feat: provided size hint chooses 1080 above 720px height

packages/@webex/plugin-meetings/src/controls-options-manager/index.ts
The scope of the changes in this pull request are to update the getControls() method to be scalable using a switch statement.
This unblocks work with in meeting options.
=> fix(meetings): set controls to switch

packages/@webex/plugin-meetings/package.json, yarn.lock
updates @webex/internal-media-core to latest version that contains latest WCME, which contains a fix for changing RTX SSRC (WEBEX-325356)
=> fix: updated @webex/internal-media-core

packages/@webex/plugin-meetings/src/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts
SPARK-417486
Lack of logging when changing layout
Logs the slots in remoteMediaManager
---
=> feat(multistream): improve logging for setLayout

packages/@webex/internal-plugin-conversation/src/conversation.js, packages/@webex/internal-plugin-conversation/test/unit/spec/conversation.js
The scope of the changes in this pull request are to add recipients to reactions within conversations for Direct IMC.
[SPARK-419331](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-419331)
=> feat(conversation): add recipients to reactions

packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-400286
add edit lock info for the dotoggle/create/end api
---
=> feat (plugin-meetings): refactor for the call api add edit lock info  

packages/@webex/plugin-meetings/src/meetings/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/utils.js
This is affecting test users. They are being created with no site set to default. Since the user has at least one site available to use, it makes sense in this case to return that from parseDefaultSiteFromMeetingPreferences 
---
=> feat(plugin-meetings): use the first site if none are default

packages/@webex/plugin-meetings/src/config.ts, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Add the installedOrgID parameter when fetching meeting info. This represents the org ID of the machine, rather than the user which is why I've made it a config parameter i.e. it is not expected to change over the lifetime of the sdk instance
---
=> feat(plugin-meetings): installed org ID

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/members/index.ts, packages/@webex/plugin-meetings/src/members/request.ts, packages/@webex/plugin-meetings/src/members/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/members/index.js, packages/@webex/plugin-meetings/test/unit/spec/members/request.js, packages/@webex/plugin-meetings/test/unit/spec/members/utils.js
Added new feature edit display name for the participants in a meeting
* If a Host/Cohost/Attendee renames self, Clients can use [locus.info](http://locus.info/).displayHints.joined[].CAN_RENAME_SELF_AND_OBSERVED to render the UI.
* If a Host/Cohost renames another participant, Clients can use 
locus.info.displayHints.moderator[].CAN_RENAME_OTHERS or locus.info.displayHints.coHost[].CAN_RENAME_OTHERS to render the UI.
---
=> Meeting Roster Control - Edit Display Name Feature

packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
Media requests are not resent after reconnecting to the meeting. This issue is caused by the SDK workaround for removing duplicate requests.
Clear the previous requests array after reconnecting to the meeting but prior to resending the media requests.
1. Manually tested disconnecting from the network for 15 seconds and reconnecting, then checking the logs to see if the media request has been sent, and checking to see if media can be seen and heard.
---
=> fix(plugin-meetings): clear previous requests after reconnection

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
A log message not having a receive slot or csi to which it corresponds.
Adding a receive slot lookup callback to the `StatsAnalyzer` to find a Receive Slot from an ssrc.
---
=>  fix: add receive slot id and csi to log message

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When using the usePhoneAudio() function to do a dial-out/dial-in the audio stays active in the SDK even though audio is also connected via PSTN and this causes echo. Muting audio in the SDK is an option and that stops the echo but that doesn't seem right. Issue is not present in Webex Meeting desktop and web clients.
Stopped the audio in sdk on desktop when dial-out or dial-in is successful.
---
=> fix: echo problem solve when usePhoneAudio is used

packages/@webex/plugin-meetings/src/locus-info/selfUtils.ts
The ExtCare customer is trying to join the meeting without having a gap for the media to be attached to the locus and that caused both of the users to be stuck in the waiting room.
This PR fixes the above issue by waiting for the locus event to be complete and then proceed with syncMeetings. 
---
=> fix(plugin-meetings): check if joinedWith exists in changedSelf

packages/@webex/plugin-meetings/src/locus-info/selfUtils.ts
The ExtCare customer is trying to join the meeting without having a gap for the media to be attached to the locus and that caused both of the users to be stuck in the waiting room.
This PR fixes the above issue by waiting for the locus event to be complete and then proceed with syncMeetings. 
---
=> fix: syncmeeting made to wait for handleLocusEvent

packages/@webex/internal-plugin-llm/src/llm.ts, packages/@webex/internal-plugin-llm/test/unit/spec/llm.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-424343
Based on board team unless we pass the deviceurl we won't reuse the connection
---
=> fix(plugin-meetings): pass devcie url for llm POST call

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
- add isMultistream property to metrics
---
=> feat(metrics): include is multistream

packages/@webex/plugin-meetings/src/metrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/metrics/index.js
The errorData in the error payload for a call analyzer event must be json
---
=> fix(plugin-meetings): send json in the error payload

packages/@webex/internal-plugin-calendar/src/calendar.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.js
Originally, the list(...) API will return a list of calendar events, for each calendar event, if it does not return notes data, it will send out a new API call to get notes for that calendar event.
The api call to get notes separately in above list(...) API is meaningless because if a calendar event has notes, the notes will be returned in list API. This implementation will cause performance issue.
Remove meaningless API calls of fetching notes separately.
Test it manually on web page, and run unit test to cover it automatically.
---
=> perf(internal-plugin-calendar): remove meaningless remote calls to improve performance

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
This is to bring in a fix in webrtc-core for:
* https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-425825
* https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-425826
Upgrading the version of internal-media-core to version 1.36.1 which contains the fix (via web-client-media-engine).
- [] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
---
=> fix: upgrade internal-media-core to version 1.36.1

packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/utilv2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
In order to fix https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-421937 there is a need to be able to pass in extra parameters when fetching meeting info, specifically when creating a new meeting. 
This PR adds the ability to provide arbitrary additional params when creating and when fetching meeting info in general, filtered to ensure both key and value are truthy (this can be changed later of course).
---
=> feat: allow for extra params to be provided when fetching meeting info

packages/@webex/http-core/package.json, yarn.lock
Fixes a vulnerability issue in the qs npm dependency. [CVE-2022-24999](https://nvd.nist.gov/vuln/detail/CVE-2022-24999)
Upgrading the qs value in http-core package to the latest value
- [] I have updated the documentation accordingly
---
Ran test locally for http-core:
```
$ yarn test:unit --packages @webex/http-core
(node:50084) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
==============================================
===== Testing with Jest @webex/http-core =====
==============================================
PASS   @webex/http-core  packages/@webex/http-core/test/unit/spec/interceptors/http-status.js
http-core
Interceptors
HttpStatusInterceptor
#onResponse
✓ …
```
=> fix(http-core): update qs version to fix vulnerability

packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts
add unlockEdit parameter for update breakouts
For case that host close manager dialog, need to update breakout and release edit lock at the same time
---
=> feat(breakout): add unlockEdit parameter when update breakouts

packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
3 main issues:
1. When tracks are published, there are 2 separate state machines for audio and video and they trigger local mute updates in Locus independently. If these happen quickly one after another Locus may handle them out of order resulting in incorrect mute state.
2. Roap messages can happen at any time and they also end up calling /media API in Locus (same as local mute state updates), so they can happen while we are sending a local mute state update - this can cause problems and incorrect mute state in Locus.
3. If client mutes/unmutes very quickly at the beginning when joining a meeting and we try to send local mute update on /media API to Locus before we've sent an SDP offer, Locus fails, because there is no confluence in the server
Created a new class LocusMediaRequest that …
=> fix: refactor code for sending /media requests to Locus

packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/metrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/metrics/index.js
- fix critical issue in CA, errors cannot contain empty array or [null] if the error mapping fails
- add default error mapping for meeting info response err
- refactor
manual, unit tests
---
=> feat(ca): fix error for meeting info

packages/@webex/plugin-logger/src/config.js, packages/@webex/plugin-logger/src/logger.js, packages/@webex/plugin-logger/test/unit/spec/logger.js
- reduce log truncations
- increasing the config.historyLength default value to 10000
- handle runtime config.historyLength changes
---
=> chore(logger): handle runtime config.historyLength changes

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
For multistream, we need to set/delete sdp parameters for music mode on audio lines that is performed by the `setCodecParameters` and `deleteCodecParameters` of WCME. We are writing a method to interface the same with the client.
We are writing a method `enableMusicMode` to interface the with the web-client to apply/remove the codecParameters on the audio lines for music mode.
---
=> feat(plugin-meetings): add method to enable music mode

packages/@webex/internal-plugin-calendar/src/calendar.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-413846
spark-413846 replace id with uri when call calendar api getPartipants and getNotesByUrl
1. add new function: getNotesByUri
2. getParticipants replace id with uri  
---
=> feat(calendar): spark-413846 replace id with uri when call calendar api getPartipants and getNotes

packages/@webex/plugin-meetings/src/annotation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/annotation/index.ts
fix processStrokeMessage format bug. The format needs to follow the protocol
https://confluence-eng-gpk2.cisco.com/conf/display/WMT/Annotation+Protocol+Detail+Definition
---
=> fix(Live-Annotation): processStrokeMessage format bug

packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
Sometimes the request to fetch the preferred site information from hydra fails. In that case fall back to getting it from the user info.
---
=> feat(plugin-meetings): fallback to getting preferred site from user

packages/@webex/plugin-meetings/src/locus-info/controlsUtils.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/controlsUtils.js
The scope of the changes in this pull request are to improve conditionals within the **controls have changed** scopes for meetings. As well as address the missing `video` parser.
=> fix(meetings): video control meeting events

packages/@webex/plugin-meetings/src/constants.ts
We've seen cases where SDP answer arrives just after the addMedia() timeout. Not sure who decided the 8s timeout, but I think it's worth increasing it to 15s
Increased timeout from 8s to 15s
---
=> fix: Increase addmedia timeout

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts
One of the customers reported an error thrown up at the time of leaving the meeting. The error is thrown because peerConnection is null at the time of getting and parsing stats one last time before cleaning up the peerConnection.
The change is simply to remove the peerConnection only after sending one last MQA data which already happens in [this line](https://github.com/webex/webex-js-sdk/pull/2867/files#diff-bfae05440410022d826a0f6d3ee83997e3471a619c6d7925db6da86a83597990R394). Just that we had to not remove peerConnection before the request for sending one last MQA data is complete.
The **MeetingUtil.cleanUp** method is being called thrice when meeting leave happens. 
- **First time -** From the **locusInfo.on(EVENTS.DESTROY_MEETING)** event where the **autoUploadLogs** isn't true.  …
=> fix(plugin-meetings): peerconnection detached after sending last mqa

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
current issue: the locus url changes when user join or leave a breakout session, and the connection to the LLM is reconnected, and it will stop listening to the `event:relay.event` event and will not listen to it again.
listen to `event:relay.event` of LLM when connection updates
---
=> fix(plugin-meetings): listen to relay event from llm when update llm

packages/@webex/plugin-meetings/src/controls-options-manager/util.ts, packages/@webex/plugin-meetings/test/unit/spec/controls-options-manager/util.js
The scope of the changes in this pull request are to hot-fix the service issue not accepting partial controls payloads for reactions. This is explicitly for controls requests within meetings, and within the reactions scope only.
=> fix(meetings): reaction controls service workaround

packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts
Listener for maxFsUpdate was not removed on cancelRequest which was causing warning for memory leak detected in canitna on pagination
This PR fixes that issue by removing the listeners
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-436891
Listener for maxFsUpdate was not removed on cancelRequest which was causing warning for memory leak detected in canitna on pagination
This PR fixes that issue by removing the listeners
- [ x] Bug fix (non-breaking change which fixes an issue)
---
=> fix(plugin-meetings): remove listeners

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, yarn.lock
internal-media-core PR with the API changes: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/183
This PR has a minimum set of changes in JS-SDK for it to work with internal-media-core from above PR. There should be no change in behavior here. 
It's a step towards having webrtc-core local tracks in transcoded meetings APIs
=> fix: changes required to work with new internal media core api

packages/@webex/plugin-meetings/src/annotation/annotation.types.ts, packages/@webex/plugin-meetings/src/annotation/constants.ts, packages/@webex/plugin-meetings/src/annotation/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/test/unit/spec/annotation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js
Feat(Live-Annotation): start share with annotation info
The presenter with live-annotation info can change annotation privilege
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-438213?filter=-1
---
=> Feat(Live-Annotation): start share with annotation info

packages/@webex/plugin-meetings/src/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-436886
Added fixCsis to be called with an array so that we avoid sending too many requests to pin/unpin
---
=> feat(plugin-meetings): added setActiveSpeakerCsis() API

package.json, packages/webex/package.json, yarn.lock
When we include the 2.29.4 SDK or any version after that and try to bundle it using a bundler like the webpack, we see the following error,
Module not found: Error: Can't resolve '@babel/runtime-corejs2/...'
runtime-corejs2 was moved from "dependencies" -> "devDependencies" in https://github.com/webex/webex-js-sdk/commit/6bd256768b4f1c0bab7f09ec4bf50778125308b5 , since its a production dependency we are getting this error.
Moving babel/runtime-corejs2 to dependencies in webex package
---
=> fix: move runtime-corejs2 to dependency in package webex

packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts
The current problem is that the breakoutStatus does not change when the breakoutType changes from BREAKOUT to MAIN, but the breakoutStatus change event is still triggered.
The reason is that breakoutStatus is a derived state that uses the value of status in groups if it is currently in the main session, or the value of status if it is currently in the breakout session. but the cache property in derived's configuration is set to true.
set cache to false in derived's config.
---
=> fix(plugin-meetings): set breakoutStatus cache false avoid duplicate changes

packages/@webex/internal-plugin-conversation/src/encryption-transforms.js, packages/@webex/internal-plugin-conversation/test/unit/spec/encryption-transforms.js
The scope of the changes in this pull request are to narrow the scope of the conversation encryption transforms to not include meeting container policy updates. This allows for these requests to be sent as intended by the service.
[SPARK-438073](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-438073)
=> feat(conversation): do not encrypte meeting container policies

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-442003
When joining a meeting without microphone and camera permissions, addMedia() calls getDevices() from webrtc-core which throws a WcmeError of type `ErrorTypes.DEVICE_PERMISSION_DENIED`
Catching and ignoring the error thrown by getDevices() in addMedia(), because we don't need the device list for anything anyway, that call is only made for logging purposes.
tested manually with the web app, also added unit test
---
=> fix: cannot join meetings if we have no microphone or camera permissions

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, yarn.lock
[SPARK-430526](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-430526)
SDK is sometimes requesting more streams that are actually available and this messes up Homer's calculations for bandwidth estimation and as a result we sometimes get "bandwidth limited" source state for some receive slots instead of the video.
Changed MediaRequestManager so that it trims the active-speaker media requests to not ask in total across all requests for more than the num of total or live sources (depending on the preferLiveVideo option). This is done only for main video, no need for it for slides or audio.
manual testing with sample app and web app, unit tests
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-req …
=> fix: SDK requesting too many streams from Homer

packages/@webex/media-helpers/README.md, packages/@webex/plugin-meetings/src/meetings/meetings.types.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
For noise reduction effect in meetings, we don't want to expose `workletProcessorUrl` and `legacyProcessorUrl` to users while creating noise reduction effect.
Omitted `workletProcessorUrl` and `legacyProcessorUrl` from `INoiseReductionEffect` in meetings.types.ts file.
Also updated readme.md file and test case file.
---
=> fix: effects contraints update

packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-442495
to fix issue that sometimes can't get the right roster list when join into breakout session. The root cause is that sometimes will receive the moved main locus (the sequence is bigger one) first, then receive the breakout locus (the sequence is smaller) later, will drop the breakout locus by sequence comparing. Should skip the main locus that resource is moved on this device (follow native client's new logic on it)
add resource is moved on this device in `isNeedHandleMainLocus`, if resource is moved which mean already join into bo, drop this main locus 
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING. …
=> fix(breakout): skip moved state main locus

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
should trigger ASK_RETURN_TO_MAIN event after meeting joined.
check if meeting isJoined before trigger ASK_RETURN_TO_MAIN event.
---
=> fix(plugin-meetings): trigger ask return to main event after meeting joined

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
- add behavioural event to failing to send CA metric if meeting is not found
- have only seen this happening in SDK, this is to check how often it happens in production
- add event
---
=> feat(ca-metrics): add behaviorual event for ca fails

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/index.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
- add support to send client events without meetingId (for pre join)
- export public function types
- refactor latency formulas (instead of using client.meeting.* -- which we are not supposed to use, I created some internal events that have the same naming but prefixed with internal. (because they do match with what I need) instead and use those as internal events to save the latencies).
- refactor submitClientEvent
- split into 2 private functions to create client event
---
=> feat(ca-metrics): refactor submitClient, support correlationId

packages/@webex/internal-plugin-calendar/src/calendar.encrypt.helper.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.encrypt.helper.js
[WEBEX-343541](https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-343541)
I have a use case that invokes invokes 'getFreeBusy' by room id list to get room free busy. In this case, don't need to encrypt the id list of the request parameter, and also need to send a request without encrypt url. Only when free busy request payload only includes the sensitive data, like email, need to encrypt these request parameters, and payload includes encrypt url.
Otherwise, don't encrypt the payload and encrypt url, Due to the calendar service will valid both encrypt url and the sensitivity that are both present. if not, will return 400 bad request to the caller.
---
Make sure to have …
=> fix(plugin-calendar): enhance getFreeBusy function

packages/@webex/internal-plugin-metrics/src/new-metrics.ts
- add optional type for `options` in submitInternalEvent
- fix type
---
=> feat(ca-metrics): add optional type

packages/@webex/media-helpers/src/constants.ts, packages/@webex/media-helpers/src/index.ts, packages/@webex/plugin-meetings/src/index.ts
We need pre-defined constant values for camera and screen share track which can be used by users to create these tracks.
Added 3 constant enum values from webrtc-core repo which are: `FacingMode`, `DisplaySurface`, `PresetCameraConstraints`
---
=> fix: add enum constants for video and display track

.circleci/config.yml, packages/@webex/plugin-meetings/src/breakouts/breakout.ts, packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/breakout.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/events.ts
- fix issue with breakouts CA events, forgot to bind `this`
-add .bind(this)
- manual test
---
=> feat(ca-metrics): add bind to passed in func

packages/@webex/internal-plugin-conversation/src/conversation.js, packages/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/@webex/internal-plugin-encryption/src/encryption.js, packages/@webex/internal-plugin-encryption/test/unit/spec/encryption.js
clients should not use file.scr.loc for downloading files. instead should use file.url. this change *needs* to happen with Federation Phase 4 incoming. as files are migrated across clusters, the url will change (from source to target cluster url). services *can not* and *will not* change the `file.scr.loc` (they would have to decrypt the scr and re-encrypt with new values)
for downloading files simply replace all uses of `file.scr.loc` with `file.url`
---
=> fix(conversation): use file.url instead of file.scr.loc for download

packages/@webex/plugin-meetings/src/member/index.ts, packages/@webex/plugin-meetings/src/member/member.types.ts, packages/@webex/plugin-meetings/src/member/util.ts, packages/@webex/plugin-meetings/test/unit/spec/member/index.js, packages/@webex/plugin-meetings/test/unit/spec/member/util.js
A user wanted to know the status of remote participant's audio/video status mean whether it's being sent or not. Currently we have status object on nested participant object which can be accessed like,
`meeting.members.membersCollection.members['memberId'].participant.status`
To have an easy access, we extracted it on members object and user can access it like,
`meeting.members.membersCollection.members['memberId'].mediaStatus`
Extracted media status in member class.
---
=> feat: extract media status on members from nested participant

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This fix is required to complete following jira. Once this gets merged Cantina side fix will follow.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-437454
Event MEETING_SELF_PHONE_AUDIO_UPDATE is updated to return reason, this helps Cantina to distinguish between successful disconnect and disconnect due to failure.
Since there was no unit test related to pstnUpdate, I have added test related to my change.
- [x ] Bug fix (non-breaking change which fixes an issue)
---
=> fix(plugin-meetings): dialout left reason

packages/tools/package/src/commands/increment/increment.ts, packages/tools/package/src/models/package/package.constants.ts, packages/tools/package/src/models/package/package.ts, packages/tools/package/src/models/package/package.types.ts, packages/tools/package/src/utils/yarn/yarn.ts, packages/tools/package/test/integration/increment/increment.test.js, packages/tools/package/test/integration/package/package.test.js, packages/tools/package/test/integration/yarn/yarn.test.js
The scope of the changes in this pull request are to update the package increment workflow to allow for synchronizing the branched package versions with the latest package version on publish.
* `latest` branch is coupled to `{package}` NPMJS tag with version `3.2.1`
* `next` branch is coupled to `{package}@next` NPMJS tag with version `3.2.1-next.25`
**Pull Request is made against `latest` branch, and merged**
* `latest` NPMJS version is now `3.2.2`
* `next` NPMJS version remains at `3.2.1-next.25`
**Pull Request is made against `next` branch, and merged**
* `latest` NPMJS version remains `3.2.2`
* `next` NPMJS version is now `3.2.2-next.1`
=> feat(package-tools): improve version control

docs/samples/browser-plugin-meetings/app.js
Sample app is not using max-bundle for multistream meetings
Changed it to use max-bundle. I've hardcoded it, because we've GA-ed this some weeks ago so there is no need for another checkbox in an already crowded sample app UI.
manually checked sample app
---
=> fix(plugin-meetings): changed sample app to use max-bundle

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
[SPARK-449067](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-449067)
- since we're creating the media connection in lobby now, it doesn't make sense to subtract it from totalMediaJMT
- refactor
-unit test
---
=> feat(ca-metrics): do not subtract stay in lobby for mediaJMT

packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/locus-info/parser.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-447189
Integration test "users "bob" and "chris" join the meeting" from the converged-space-meeting.js sometimes fails, because we receive Locus DTO events out of order over the websocket.
Fixed JS-SDK to ignore full locus DTOs that are older than current working copy. I've confirmed with Locus team that this is what we should do.
Added new unit tests
---
=> fix: ignore old full Locus DTOs

packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/plugin-meetings/test/unit/spec/members/index.js
The parseInterpretationInfo was throwing an error when the when attempting to trigger an event. The first argument for the `Trigger.trigger` must be an object with a trigger method. This is usually a webex plugin or similar. In this case it needed to be the meeting, as the util has no trigger method.
This was masked by the unit tests because other tests would assign Trigger.trigger to be a sinon stub, thus stubbing for all subsequent tests.
---
=> feat(plugin-meetings): fix si trigger

packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-450417
According to https://sqbu-github.cisco.com/WebExSquared/locus/wiki/Locus-Delta-Events, in the DESYNC case the client should use syncUrl from the workingCopy to obtain the most up-to-date delta from Locus. However, existing SDK implementation is always fetching full Locus instead of the delta. This can have bad consequences for 1k meetings where the Locus DTO is very large.
Changed the code to ask for delta if we have syncUrl and fallback to full DTO otherwise.
Also fixed the code that handles delta response from http requests triggered from sendLocalMuteRequestToServer() and updateLocusWithDelta() - the existing code was calling onDeltaLocus() which means it was bypassing the queue for delta processing and it could cause problems if …
=> fix: ask for delta instead of full locus DTO when handling DESYNC

.eslintrc.js, eslintrules/rules/es6.js, eslintrules/rules/imports.js, eslintrules/rules/style.js, package.json, packages/legacy/eslint/static/rules/es6.js, packages/legacy/eslint/static/rules/imports.js, packages/legacy/eslint/static/rules/style.js, yarn.lock
Add a linter plugin for inclusive language and fixes all the errors generated post configuration 
Fixes the inclusive language issue and doesn't allow to add any new
---
=> fix: validated - add linter for inclusive language and fix all the errors

packages/@webex/plugin-meetings/src/common/queue.ts, packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/test/unit/spec/common/queue.js, packages/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/locus-info/parser.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-447996
Existing design was to do a sync if client gets an out-of-order Locus delta event. However, it turns out that this is not a great solution, because in 1k meetings, delta events often come in the wrong order and if clients then start sending sync requests, Locus becomes overloaded and even more events may come out-of-order, triggering more syncs and it just gets worse and worse.
UCF team has done a change to cache out-of-order events and wait for some time to see if the missing events eventually come. If the missing events don't arrive within a certain random timeout between 10s and 15s, a sync is done. Also if the cache grows too much (more than 5 events), sync is also done immediately.
UCF design is described …
=> fix: handle out-of-order Locus delta DTOs

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-439656
User should not be able to broadcast message in a breakout session if there is a policy restriction
---
=> feat(plugin-meetings): consider policy for broadcast message

packages/@webex/plugin-meetings/src/meeting/index.ts
Raising this PR to merge the changes in beta branch for PR: https://github.com/webex/webex-js-sdk/pull/2993 
Added error message when a guest starts the transcription and it doesn't work until host enables it. Using isClosedCaptionsActive property inside meeting object. This is set to false until any licensed user enables transcription. Once they enable it, transcription starts working for guest user.
---
=> fix(plugin-meetings): added error for transcription not working when guest joins first

packages/@webex/internal-plugin-board/test/integration/spec/board.js
recently merged https://github.com/webex/webex-js-sdk/pull/2925/files which changes how files are downloaded. the board integration tests download files and were not updated (somehow the previous PR got green build, anyways...)
updated the packages/@webex/internal-plugin-board/test/integration/spec/board.js tests
---
=> fix(board): fix integration board tests for download files

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts
- fix return type for submitClientEvent
- manual test
---
=> feat(metrics): fix return type client event CA

packages/@webex/plugin-meetings/src/statsAnalyzer/global.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The logs were filled with 'No video frames sent/received/decoded' and 'No audio samples sent/received/decoded' logs. 
Root cause:
RTCStatsReport used to send statistics for type = 'track' which had the details about the track like frames sent, frames height etc. Now this information is being sent in the type inbound-rtp and outbound-rtp statistics
Fixed the StatsAnalyzer to correctly populate the track results.
Calling the processTrackResult function from the  processInboundRTPResult and processOutboundRTPResult functions.
---
=> fix(plugin-meetings): no-frames-received-sent-stats-error

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/sendSlotManager.ts
- Setting up of SendSlotManager and it's relevant UT
- Updating the usage of codecParameter APIs for music mode to SendSlots
=> feat(SendSlotsManager): initial setup and related meeting changes (#1)

.circleci/config.yml, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
- at the moment, correlationId is passed to the join method on the meeting object in SDK. This is too late in the flow. Updating correlationID in SDK should be done as part of the createMeeting method.
- needed for pre-join CA metrics 
- remove correlationId options from public join method to public create method.
---
=> feat(pre-join): add new correlationId logic

packages/@webex/http-core/src/index.js, packages/@webex/http-core/src/request/utils.ts, packages/@webex/http-core/test/unit/spec/index.js, packages/@webex/http-core/test/unit/spec/request/utils.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-456521
After more testing via a modified Cantina, the options returned from 
sdk.buildClientEventFetchRequestOptions() needed a few tweaks.
- added 'keepalive: true' instead of expecting it to be added in cantina
- convert body to JSON string when json=true
- default header content-type to 'application/json'
- default header accepts to 'application/json'
Updated unit tests and manually tested.
=> Spark 456521 adjust built metric fetch options

.github/workflows/deploy.yml, CONTRIBUTING.md, package.json, packages/calling/package.json, yarn.lock
the issue of not building the bundles for deployment. 
1. Fixed the command to build UMD in the deploy.yml
2. Added a script in the root `package.json` to make it easier for developers to build locally and test samples
3. Changed the commands in the CONTRIBUTING.md accordingly.
4. Removed unnecessary `webex` dependency in `packages/calling/package.json`
Tested building the code - UMD folder created successfully
No errors observed for commands running in deploy.yml
Was able to build and host samples page locally.
---
=> fix(build): add umd build for deploy step, provide local build command

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/global.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Currently, we don't send any metric when frames are not being sent for various reasons on mobile devices. If device is not sending videoFrames or video is not encoded, we are not triggering any event for that.
As part of this PR:
1) added an EVENT when video is encoded but frames are not sent in statsAnalyzer
2) added an EVENT when video is not being encoded in statsAnalyzer
3) Emitted two new EVENTS for the above scenarios
4) sending behavioral metric to Amplitude for above scenarios
Test the following scenarios:
- when frames sent is 0
- when frames sent value is not changing
- when frames sent is 0 but video is encoded
- when video is not being encoded 
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitti …
=> fix(meeting): added noFramesSent noVideoEncoded events

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
- method was recently refactored out in a util file but the return string was changed too
- fix buildType from production to prod
-fix renaming, add type
---
=> feat(ca): fix prod meta

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-458352
SDK is not sending geohint information to Locus when joining meetings, because the code in joinMeeting() is reading a field `this.webex.meetings.clientRegion`, but that information is stored inside `this.webex.meetings.geoHintInfo`.
The code has been incorrect like this since the beginning when geohint request was added 3 years ago - it never worked.
Using correct field to read geohint info.
Also added geohint to /media requests.
Existing tests + manual e2e run with web app (confirmed with Orpheus that they received the geohint)
---
=> fix: geohint info missing in Locus join requests

packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-382443
JS-SDK has always been sending UDP and TCP reachability results, but in fact the checks are done only over udp. TCP results were set to the same what was for UDP. With the current way how we do reachability, it's impossible to do it over TCP (it would require changes to Linus).
Indicating to the backend that we don't do reachability over TCP and xTLS by setting `untested:"true"` field
unit tests + manually joined a meeting with the web app to check that nothing is broken end-2-end and confirmed with Orpheus team that it's all fine on their side
---
=> fix: don't send fake TCP reachability results

packages/@webex/internal-plugin-metrics/src/index.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-458903
Currently we are using one of `MEETING_REMOVED_REASON` as the CA event leaveReason.  These are not valid values for the CA event, which needs to be one of 'paired-leave' | 'one-to-one' | 'ended-by-locus'.
We should not conflate locus leave reason with CA event leave reason.
I added a new prop/arg to meeting.leave() (`clientEventLeaveReason`) that can be used to pass in one of the valid CA reasons. By default this property will be undefined (it is optional).
Updated unit tests and tested manually.
=> fix(call-analyzer): fix client.call.leave reason

packages/@webex/internal-plugin-encryption/src/constants.js, packages/@webex/internal-plugin-encryption/src/kms-batcher.js, packages/@webex/internal-plugin-encryption/src/kms-errors.js, packages/@webex/internal-plugin-encryption/test/unit/spec/kms-errors.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-459735
Error handling when an encryption key is revoked and kms throws 405 error codes
Added an event listener that gets triggered as soon as the specific error codes start coming in from revoking the key.
---
=> feat(): byok revoked error handling

packages/@webex/plugin-meetings/README.md, packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reachability/request.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/request.js, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-460221
The backed requires us to tell them what ip network we're on when doing API calls to /discovery and when sending clientMediaPreferences to Locus.
For now, in this PR we just send "unknown" - this should be enough to make meetings work in both ipv4 and ipv6 networks. There are more jiras in the epic to detect the ip network and send correct information - this will be done in other PRs.
More details here: https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/SPARK-448167+-+IPv6+support
Added `getIpVersion()` to Reachability class. It's called from all the places that need to know the IP network version.
Manual e2e test with the web app to confirm that we send the ipver parameter and that the backend is happy with it.
---
Make sure …
=> feat: sending ipver parameter to Locus and Orpheus

docs/samples/calling/app.js, docs/samples/calling/index.html, docs/samples/calling/style.css
- Updated the samples page with improved UI
**Before**
**After**
---
=> docs(calling): improve samples UI. add back getDevice

packages/calling/src/Voicemail/BroadworksBackendConnector.test.ts, packages/calling/src/Voicemail/BroadworksBackendConnector.ts, packages/calling/src/Voicemail/UcmBackendConnector.test.ts, packages/calling/src/Voicemail/UcmBackendConnector.ts, packages/calling/src/Voicemail/Voicemail.test.ts, packages/calling/src/Voicemail/WxCallBackendConnector.test.ts, packages/calling/src/Voicemail/WxCallBackendConnector.ts, packages/calling/src/Voicemail/voicemailFixture.ts, packages/calling/src/common/Utils.ts, packages/calling/src/common/constants.ts
Code coverage for voicemail module files were less.  Need to write UT to cover the uncovered code.
Added UTs for following files:
1. BroadworksBackendConnector.test.ts
2. UcmBackendConnector.test.ts
3. Voicemail.test.ts
Some code refactor in below files:
1. BroadworksBackendConnector.ts
2. UcmBackendConnector.ts
3. Utils.ts
CODE COVERAGE REPORT:
PREVIOUSLY
CURRENT:
---
=> test(calling): voicemail module test cases added

packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/rtcMetrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts
Using the correct correlation id in RtcMetrics requests.
Pulls in the `correlationId` from the meeting object
---
=> fix: add correct correlation id to rtcmetrics

packages/@webex/http-core/src/lib/xhr.js, packages/@webex/http-core/src/request/request.shim.js
N/A
SDK logs often have lines like this:
`,2023-09-21T06:55:39.397Z,wx-js-sdk,Error: [object ProgressEvent]`
which are not very useful - we know nothing about the error and is very difficult to find the code from where the error originated.
Improved the log so it will look like this now:
`,2023-09-26T11:30:28.352Z,wx-js-sdk,XHR error for GET to https://myspark.cisco.com/spark_session_check.json :,Error: XMLHttpRequest Error: ProgressEvent: loaded=0, total=0, lengthComputable=false, target.readyState=4`
manual run with web app
---
=> fix: improve error logging for xhr

docs/samples/calling/app.js, packages/calling/src/CallHistory/CallHistory.test.ts, packages/calling/src/CallHistory/CallHistory.ts, packages/calling/src/CallingClient/CallingClient.test.ts, packages/calling/src/CallingClient/CallingClient.ts, packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts, packages/calling/src/CallingClient/calling/callManager.test.ts, packages/calling/src/CallingClient/calling/callManager.ts, packages/calling/src/CallingClient/calling/types.ts, packages/calling/src/CallingClient/line/index.ts, packages/calling/src/CallingClient/line/line.test.ts, packages/calling/src/CallingClient/line/types.ts, packages/calling/src/CallingClient/types.ts, packages/calling/src/Events/types.ts, packages/calling/src/common/Utils.test.ts
Required changes for line class.
1. Move below from callingClient to line: 
- makeCall()
- incomingCallListener()
- getCallManager()
2. Add below new APIs in calling client and line:
CallingClient:
- getActiveCalls()
- getConnectedCall()
Line: 
- getCall()
3. Change call event from callingClient:incomingCall to line:incomingCall.
4. To store lineData in the callManager. Added lineDict in call manager that holds the {deviceId: lineId} information. Also added addLine and getLine api to populate and fetch the lineDict
5. Changes in the samples page 
- event handler for line:incoming_call event
- changes from callingClient.makeCall to line.makeCall
--- …
=> feat(calling): move apis, listeners from calling client to line

packages/@webex/media-helpers/package.json, packages/@webex/media-helpers/src/index.ts, packages/@webex/media-helpers/src/webrtc-core.ts, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/index.ts, packages/@webex/plugin-meetings/src/media/index.ts, yarn.lock
- [SPARK-458871](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-458871)
- [SPARK-463101](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-463101)
- Exports VideoContentHint on the `plugin-meetings`
- Does the right import for `MultiStreamConnectionConfig`
=> fix(plugin-meetings): export VideoContentHint and import MultiStreamConnectionConfig

docs/samples/calling/app.js, docs/samples/calling/index.html, packages/@webex/media-helpers/package.json, packages/calling/src/CallingClient/calling/call.ts, packages/calling/src/index.ts, packages/webex/src/calling.js, yarn.lock
Adding changes to use the BNR feature in CallingSDK for WebRTC Calling.
Added static function to create and return NoiseReductionEffect object in calling.js
Added the effect to the localMicrophoneStream being used for calls in app.js and enabled it.
Listening for 'output_track_change' event to update the tracks once BNR is enabled/disabled.
---
=> feat(callingsdk): initial changes to add bnr

packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-458624
Remove showToUser option from submitClientEvent.
---
=> feat(ca): remove show to user

packages/@webex/internal-plugin-device/src/device.js, packages/@webex/internal-plugin-device/src/ipNetworkDetector.ts, packages/@webex/internal-plugin-device/test/unit/spec/ipNetworkDetector.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-460571
We need to detect if we're on IPv4 or IPv6 network (or both)
Added IpNetworkDetector to webex.internal.device as described in the tech breakdown page:
https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/SPARK-448167+-+IPv6+support
unit tests + tested manually with sample app and modified meetings plugin that calls webex.internal.device.ipNetworkDetector.detect() to see if it works correctly in real browser
---
=> feat: added IpNetworkDetector to webex.internal.device

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, docs/samples/browser-plugin-meetings/style.css, packages/@webex/plugin-meetings/src/common/errors/webex-errors.ts, packages/@webex/plugin-meetings/src/config.ts, packages/@webex/plugin-meetings/src/meeting-info/util.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts, packages/@webex/plugin-meetings/src/meetings/index.ts
JavaScript SDK: SDK Room/SPACE ID Depreciation code changes
Updated the code in the Util for handling room IDs, and now an error is thrown with the migration guide link when a Space ID is used. Also, an error code has been added. 
The sample code has also been updated to reflect these changes.
---
=> feat(meetings): space id depreciation code change

packages/@webex/plugin-meetings/src/config.ts
As part of the harmony change we need to turn on the v2 space meeting by default, this is the first step for the USM meeting, the toggles for the USM are on the client side, so before the sever changes the client to USM we need to migrate the code to USM 
---
=> fix(plugin-meetings): enable adhoc and unified space meeting by default 

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/sendSlotManager.ts
- The SendSlotsManager throws an error as the SendSlots in the SDK was never cleared on meeting leave
- The SendSlotsManager is introduced with a new method `deleteSlot`
- The `meeting.clearMeetingData()` method clears all the send slots by using the `deleteSlot` method above
---
=> fix(plugin-meetings): reset sendSlotsManager on meeting leave

docs/samples/calling/app.js, docs/samples/calling/index.html
In the calling samples page, if we don't receive the CALL_ESTABLISHED event the samples page gets stuck. The 'end-call' button remains disabled.
We have removed the dependency of any event on the button state. As soon as we make the call 'end-call' button is enabled and we can cut the call.
Also
The advanced settings or region and country take effect when the calling.init() button is pressed. But the button is located above the Advanced section. So a user will miss the chance to change the settings before initializing calling. So moved the 'Initialize Calling' button bellow Advanced settings
https://github.com/webex/webex-js-sdk/assets/72344404/9178cf56-5428-406d-af12-752c7de8d35d
https://github.com/webex/webex-js-sdk/assets/72344404/806f29e2-063b-4d32-ba63-a9a6346e2f1b
< ENUMERATE TESTS …
=> fix(calling): removed-events-dependency-on-call-buttons

packages/@webex/media-helpers/package.json, packages/@webex/media-helpers/src/webrtc-core.ts, packages/@webex/media-helpers/test/unit/spec/webrtc-core.js, packages/@webex/plugin-meetings/package.json, yarn.lock
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466805
1. Browser hangs when SDK tries to log the options passed into addMedia() when camera track has blur effect applied
2. Cannot join multistream meetings
1. Added toJSON method to camera and mic stream classes so that we only log useful fields
2. Updated internal-media-core to bring a fix for handling multiple negotiation needed events that can come before first offer is created
tested manually with the web app
---
=> Stream classes add media fix

docs/samples/browser-plugin-meetings/app.js
When we change the microphone device, if audio is muted, then with the next device, it starts with audio unmuted. Same for camera device.
We're setting previous mute state to new stream created before publishing the streams in the deviceChange api in samples app.
---
=> fix(samples): correct mute state on device change

packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
Avoid the need for a redirect by using the locusClusterUrl from meetingInfo
The locusClusterUrl is passed to the request from the joinMeeting util.
I've only made the change for the `/call` route since when we join a meeting using `/participant` we already know the cluster
---
=> feat(plugin-meetings): use locus cluster url to avoid the redirect

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/src/index.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
- add temporary flag to mark buildType as test for pre join events
- avoids noise data while testing this in prod
- fix event property in prepare util function
- refactor, add new flag
---
=> feat(ca): add temporary flag for buildType

packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
Guest users failed to reconnect because reconnect attempted to syncMeetings
Only syncMeetings during reconnect if user is not an unverified guest
---
=> fix(plugin-meetings): do not sync meetings if unverified guest

packages/@webex/plugin-meetings/src/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466192
It's been confirmed with the backend team that ipver parameter only needs to be sent with roap offer and turn_discovery_request when calling the /media API
Removed the ipver parameter from other calls to /media API (like other roap messages and local mute/unmute)
updated unit tests, also checked manually with sample app
---
=> fix: only sending ipver when it's really needed

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reachability/request.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts, packages/@webex/test-helper-mock-webex/src/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-461655
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466194
getIpVersion() was in Reachability class and always returned "unknown"
As agreed in tech breakdown, moved the function to meeting util and implemented it to call webex.internal.device.ipNetworkDetector or return undefined for Firefox
unit tests, manual run of sample app
---
=> feat: moved getIpVersion() to meeting util and implemented it

packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
We often see logs missing in mats.webex.com, we have a metric for log upload failure, but not for success.
Also, noticed the metric for failure was always sending meetingId=undefined
=> fix: added metric for succesful log upload

packages/@webex/internal-plugin-metrics/package.json
error in package, as it can't import event-dictionary-ts to export types, and then we can't import types properly in cantina
move event-dictionary-ts from devDependencies to dependencies
---
=> Include event dictionary in package

package.json
The scope of the changes in this pull request are to fix the existing `build`, `prebuild` and `clean` scripts to properly trigger. as of the current yarn version, `pre` and `post` script lifecycle hooks [are not supported](https://yarnpkg.com/advanced/lifecycle-scripts) by yarn (with a few small exceptions). `build` now explicitly calls `clean`. Additionally, the glob patterns in `clean` were not wrapped in `"`, which caused the `clean` command to fail when no files were found. This has also been fixed as a part of this PR.
=> fix(scripts): build clean skip prebuild

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-472237
when addMedia() times out, SDK was sending "client.ice.end" event without any errors, because wrong parameters were passed to getErrorPayloadForClientErrorCode()
Fixed the parameters.
unit tests, manual run with sample app
---
=> fix: error is missing in client.ice.end event

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-472336
When we get out of order delta events we start a timer and we do a Locus delta sync when that timer expires. We are seeing a large number of cases where that Locus delta sync request fails - it's not clear why, but when this happens SDK is stuck in a state where it will keep re-trying the delta sync every 10-15s until it succeeds or until we get the missing delta events from Locus, which seems to never happen.
If delta sync fails, do a full sync - this should get us out of the state where we keep retrying the delta sync.
Also added some metrics to help us investigate further what is causing the problem of failing delta syncs in the first place.
unit tests
--- …
=> fix: do a full Locus sync if a delta sync fails

packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
While in a meeting if the internet is disconnected for some amount of time the remote video and audio stops. In samples page remote video shows "undefined 0fps". While the internet is disconnected if the connection status fails the newly created connection never reaches the 'connected' state it gets stuck in connecting. 
This is caused because while reconnection locus doesn't expect the media ID to be passed. We only take into account the config value for enableTurnDiscovery and doesn't take into account that TURN discovery is skipped if reachability succeeds. 
Made sure that when Roap checks if TURN discovery is being done or not it checks all the conditions and not just the config.
After all the following scenarios, the meeting is successfully joined with two-way audio and video.
- …
=> fix(plugin-meetings): cherry-picked-PR-2782-from-beta

.circleci/config.yml, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
Experiencing a failure when attempting to start an instant space meeting URL: https://co.webex.com/wbxappapi/v2/meetings/spaceInstant.
The error message received is '416 Range Not Satisfiable' with the response '416020' and message 'e2ee decrypt error.'
should pass encrypted title based on APPI API ("/wbxappapi/v2/meetings/spaceInstant) Team.
Updated the code and tests for this.
https://github.com/webex/webex-js-sdk/assets/3918217/cd095b24-d8a0-45b2-a6a9-8ee79420c5c8
Tested some basic manual flow and also attached the screen recording -
- Register
- Create ad-hoc meeting with conv URL
- Join with media
- Checked participants
- checked if meeting is started in space or not
- leave
--- …
=> fix(meetings): pass encrypted title based on APPI API for conversation

docs/samples/browser-plugin-meetings/app.js, packages/@webex/plugin-meetings/src/meeting/index.ts
Media settings toggle for audioEnabled is not working as expected while we toggle it and calls updateMedia().
1. Changed samples app logic to call updateMedia() only with the toggles which are changed by user and not all settings.
2. Added error logic in updateMedia() when shareAudioEnabled is toggled for a transcoded meeting.
---
=> fix(plugin-meetings): media settings toggles fixed

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Transcriptions do not work if user get placed in lobby and then is admitted into the meeting
Issue was happening because transcription method requires a `datachannelUrl` to generate a `webSocketUrl` which is then used to create transcription object. Until guest user is not admitted into the meeting, `datachannelUrl` is not generated and so the method fails to start the transcription.
As a part of this issue fix, we have an event triggered when guest is admitted into the meeting which is "SELF_ADMITTED_GUEST" so added the logic there to retry for transcription if not started earlier.
After this fix, following 2 scenarios will start working which were not working previously. Below scenarios are tested on web SDK samples app.
1. When guest user wants to join meeting with transcription:
1.1 …
=> fix(plugin-meetings): start transcription when guest user is admitted

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-471367
Locus error 2409062 was not mapped in the error catalog, so defaults were being used.
Add locus error 2409062 mapped to 12002 along with error payloads.
Unit test added.
---
=> feat(ca-metrics): use correct error payload for 2409062

packages/@webex/webex-core/src/lib/services/services.js, packages/@webex/webex-core/test/unit/spec/services/services.js
Adding hostCatalog object inside webex
Created new field: _hostCatalog in services.js file as part of services object
Under _formatReceivedHostMap, updating the _hostCatalog with what is present in serviceHostmap(response from get request to u2c service)
Initialized Webex and checked if hostCatalog object was populated
---
=> fix(services): added hostCatalog inside webex

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts
sdk has a generic locus error code: 4008 w category: signaling for when an uninvited user tries to join a locked meeting. 
made it better by adding another error code: `12003` w category: expected and mapped it to specific locus error code: `2423025` - Only invited users can attend this meeting. If you received the invitation at a different email address, switch to your account with that email address before joining the meeting. This way we have a 1:1 mapping for this specific locus error code for future. 
---
=> feat(plugin-meetings): adding a new error code for users not invited to join locked meeting

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-475304
There is no API to refresh permission token
Added API to refresh permission token.
NOTE: currently this doesn't work correctly for cases when we start an instant space meeting - the new meeting info we get after refresh is not the same as we got from /spaceInstant API call - this is being discussed with WbxAppAPI team
---
=> feat: add API for renewal of the permission token

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
- refactors join to no longer wait for llm connection and receive transcribing
- there is a relatively big side effect caused by this refactor
- - before we did not allow users to join the meeting if either of these 2 failed
- - with the new refactor, now the users will always be able to join the meeting regardless if llm or transcribing succeeds. When this happens, the user will experience a smaller set of features in the meeting. 
- - future improvements will include to retry this operations in case they fail, but for now we agreed to not do it
- refactor public join method
- add unit tests
- unit test, manual test
---
=> feat(meetings): refactor public join method

packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reachability/request.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-477129
We call isAnyClusterReachable() to decide if TURN-TLS should be attempted or not. That function checks if we reached any media cluster during reachability checks and that includes also video mesh nodes (VMNs). VMNs will most likely be reachable even when customer has a firewall blocking all udp and tcp to public nodes and when we join a call we might be placed on a public media node, so we should not take VMNs into account.
- renamed isAnyClusterReachable() to isAnyPublicClusterReachable() and changed the implementation so that it only checks the public nodes.
- we were sending the whole contents of stored reachability results to Locus when joining meetings, but now these results also include a `isVideoMesh` property that we don't …
=> fix: ignore VMN reachability when deciding if we should use TURN-TLS or not

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
updating internal-media-core to bring a fix from WCME for TURN-TLS connections
relevant WCME PR: https://sqbu-github.cisco.com/CPaaS/web-client-media-engine/pull/296
=> fix: update internal-media-core to 2.0.4

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
refresh permission token when meetingJoin happens
- combine `getPermissionTokenTimeLeft` and `refreshPermissionToken` to refresh the token on join if the token is about to expire in the next 10 seconds
- added unit tests
- checkAndRefreshPermissionToken method unit tests
- additional join unit tests (catching errors, etc.)
=> fix: refresh permission token on meetingjoin

package.json, packages/@webex/media-helpers/package.json, packages/@webex/media-helpers/tsconfig.json
The issue where, typescript doesn't detect types for the imports from `@webex/media-heleprs` package
- Adding a typescript config
- Adding the typescript build script for `@webex/media-helpers` package
- Executing this command along with other `tsc` commands in `<rootFolder>/package.json`
- Checked in multiple places of `packages/@webex/plugin-meetings/src/meeting/index.ts` by providing an invalid key for the imported enums and we got to see the error that the provided key isn't available. For instance,
---
=> fix(media-helpers): tsconfig for creating types setup

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
Currently Unauthorized errors raised by the SDK appear as an unknown error.
Reclassify these errors to be AuthenticationFailed
---
=> feat(plugin-metrics): classify unauthorized errors

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
Make use of the new network CA category
Changing the category to network for the following errors:
- 1010 (AuthenticationFailed)
- 1026 (NetworkError)
- 4009 (NetworkUnavailable)
See [SPARK-478597](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-478597) for details.
---
=> feat(plugin-metrics): use network category for relevant errors

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
bumping webrtc-media-core library version after I merged a bug fix in webrtc-media-core lib. 
fixed ROAP OK message to be retransmitted when same seq answer is received again. PR link: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/201
---
=> chore(internal-media-core): version bump

tooling/babel-plugin-inject-package-version.js
the issue of the sdk_version being set to "undefined" while sending metrics using the webex.min.js or the other min.js files.
The babel plugin that injects a version was using the wrong file to inject the version. The root package.json no longer has a `version` parameter in `next` branch. The package.json inside `packages/webex/` is the place where `version` will be populated during deploy. Changed the path in the plugin file so it picks the right version.
Built the CDN files after making the change to the plugin. Hosted these locally and ran webex initialization and meetings.register. The clientmetrics sent to the metrics service has the right version.
---
[metrics-version-fixed.har.txt](https://github.com/webex/webex-js-sdk/files/13645203/metrics-version-fixed.har.txt)
Make sure to have …
=> fix(tooling): fix the version injection plugin to pull version from right location

packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts, packages/calling/package.json, packages/webex/package.json
While in a meeting if the internet is disconnected for some amount of time the remote video and audio stops. In the samples page, remote video shows "undefined 0fps". 
This is caused because while reconnection locus doesn't expect the media ID to be passed. We only take into account the config value for enableTurnDiscovery and don't take into account that TURN discovery is skipped if reachability succeeds.
Made sure that when Roap checks if TURN discovery is being done or not it checks all the conditions and not just the config
Joined the scheduled meeting as guest, switched off wifi for 10 seconds and resumed wifi before the guest is out of the meeting. Once the reconnect to the meeting is successful, audio and video is working now.
Logs: …
=> fix(plugin-meetings): adding fix done in PR 2782 in next branch

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The missing "TLS" transport type when calling while using a TLS connection.
Using only local candidates to determine the transport type and using the `relayProtocol` stats item when it exists.
=> fix(plugin-meetings): add tls transport type

packages/@webex/plugin-meetings/test/integration/spec/journey.js
https://github.com/webex/webex-js-sdk/pull/3185#discussion_r1397110588 
Passing stream in the parameter list of waitForPublished() and comparing the stream received inside the triggered event with the the stream present in the parameter list
---
=> fix(integration): fix waitForPublished() in SDK integration tests

docs/samples/calling/app.js, docs/samples/calling/index.html
The issue of initialization failure while using WxCC access tokens. These tokens do not have additional features enabled such as voicemail. Moreover, XSI API requests such as Call Settings (Forwarding, DND, Call Waiting) will also fail.
1. Move initialization of all additional features under a new function
2. Provide a new button for fetching all settings so we don't do this automatically
3. Voicemail.init() is now triggered when clicking the Voicemail button and not automatically during initialization
With regular Webex suite access token:
1. Register with Webex Calling
2. Place call and check for media
3. Check voicemail
4. Check settings and test whether DND setting works
With WxCC token:
1. Register with Webex Calling
2. Ensure calls work. 
3. Ensure no errors encountered during …
=> fix(samples): avoid init failure for tokens without additional features

package.json
Cannot build JS-SDK when doing local linking with @webex/internal-media-core
It's because the dist folder of internal-media-core was getting deleted during the build
checked that it builds with local link
---
=> fix: local linking with internal-media-core

packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts, packages/calling/src/CallingClient/calling/callManager.test.ts
Developers could pass empty localAudioStream to dial and answer API which led to roapMessageReceived failing. For an incoming call, the patch is first sent to Mobius then roapMessageReceived is called, in the scenario where roapMessageReceived failed since the patch is already sent the call state changes to connected even though we do not have a localAudioTrack.
- While answering, if localAudioTrack is empty call is not connected and disconnect is sent to mobius. A warning message is also given.
- While dialing, If localAudioTrack is empty, call is cleared immediately and warning message is given
- First call roapMessageReceived and then send patch to Mobius.
[dial-flow.log](https://github.com/webex/webex-js-sdk/files/13736845/dial-flow.log) …
=> fix(call): error-handling-for-empty-track-while-answer-dial

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The missing "TLS" transport type when calling while using a TLS connection. Adds on to this PR: https://github.com/webex/webex-js-sdk/pull/3243 by using the successful `candidate-pair` to get the correct `local-candidate`.
Using only local candidates to determine the transport type and using the `relayProtocol` stats item when it exists.
=> fix: use candidate pairs to identify correct local candidate

packages/calling/src/CallingClient/calling/CallerId/index.ts, packages/calling/src/common/Utils.ts
the issue of names and numbers being logged by @webex/calling during resolution of the caller ID.
Removed the logging of this information from the statements where they are printed.
* Tested an outgoing call and ensured that the Caller ID is working fine.
* Checked the logs in the outgoing call and ensured that the name and number isn't being logged by the calling package anywhere
[remove-PII.log](https://github.com/webex/webex-js-sdk/files/13742594/remove-PII.log)
---
=> fix(calling): remove logging of personal info

docs/samples/calling/app.js, docs/samples/calling/index.html, packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts, packages/calling/src/CallingClient/calling/types.ts
The ability to change the microphone while a call is in progress.
1. Creating a new function on the Call object called `updateMedia` which takes the new device's stream as an input.
2. Added a "Change Device" button to change the microphone and speaker during a call
Tested the following on Chrome 120.0.6099.109 and Edge 120.0.2210.91
1. Place a call from the kitchen sink. Call is connected on laptop microphone and speakers
2. Connect headphones with mic. Click "Get Devices" to list this new device in the kitchen sink
3. Select new microphone and speaker and click "Change Device"
4. Check on the remote party if the audio is now getting transmitted from the headphone microphone and the remote party's audio is being redirected to the headphones
---
Make sure to have followed the …
=> feat(calling): add updateMedia in call

packages/@webex/internal-plugin-llm/src/constants.ts, packages/@webex/internal-plugin-mercury/src/mercury.js, packages/@webex/internal-plugin-mercury/src/socket/socket-base.js, packages/@webex/internal-plugin-mercury/test/integration/spec/webex.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js
Cantina use 2 mercury connection via the mercury plugin, but it is not shown in the logs
Adding the domain of the mercury connection to the log helps to identify the connection.
---
=> Fix mercury log

packages/calling/src/CallingClient/line/index.ts, packages/calling/src/CallingClient/line/types.ts, packages/calling/src/Errors/index.ts, packages/calling/src/Events/types.ts, packages/calling/src/index.ts
There were compilation errors on the ILine interface due to which we weren't able to receive events on line object.
Addition of extending eventing class on ILine interface and small corrections.
I ran the build and unit tests locally to check everything was passing after the changes.
---
=> fix(calling): extend eventing class on ILine interface 

packages/calling/src/index.ts
Need to pass the local audio stream while invoking dial/answer API. It is giving type error in web client so need to import LocalMicrophoneStream for typecasting the stream.
Exporting LocalMicrophoneStream from media-helpers package so that it is available in web client under @webex/calling.
---
=> fix(calling): export LocalMicrophoneStream

packages/@webex/plugin-meetings/test/unit/spec/members/index.js
Fixing a .only in plugin-meetings unit test
---
=> feat(plugin-meetings): fix .only test

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
we currently send a latency metric for turn discovery even if it fails
check that both entries in the object returned from doTurnDiscovery are well defined before sending the metric
---
=> fix(plugin-meetings): don't send turn latency if it fails

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
This PR updates internal-media-core to 2.2.1, which includes wcme 3.11.0 and ts-sdp 1.6.0.
with the new wcme version, client can chooes to enable/disable audio twcc by configurations (see below config when create MultistreamConnection), and it's disabled by default.
type MultistreamConnectionOptions =
{ 
disableSimulcast:boolean;
bundlePolicy:BundlePolicy;
iceServers:RTCIceServer[] |undefined;
disableContentSimulcast:boolean;
disableAudioTwcc:boolean;
};
Tested with WCME test app.
---
=> fix: update internal-media-core to 2.2.1

packages/@webex/http-core/src/request/request.shim.js, packages/@webex/http-core/test/unit/spec/request/request.shim.js
This is a speculative fix, capitalizing the Authorization header, just in case this is a reason that some web proxies might get confused.
---
=> feat(http-core): capitalize Authorization header

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The MQE `peripherals` values are sometimes missing the `information` property.
ensuring that the `information` property is not undefined.
---
=> fix(meetings): ensure non-undefined value for peripheral information property

packages/@webex/plugin-meetings/src/meetings/collection.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/collection.js
Added a helper method so that everyday debugging is a bit easier....
when using js console and trying to read something from the active meeting we normally have to do this:
`webex.meetings.meetingCollection.meetings[<some_uid>]`
and we have to know which uid to use if there are multiple meetings in the SDK
now we can do this instead:
`webex.meetings.getActiveWebrtcMeeting()`
=> fix: added method for getting the meeting with active webrtc connection

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts
- reduce ca metrics logging, they are too verbose
- simply removed logging and their equivalent unit tests 
- manual test
---
=> feat(ca-metrics): reduce logging

docs/samples/browser-plugin-meetings/app.js, packages/@webex/plugin-meetings/src/common/errors/reclaim-host-role-error.ts, packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/member/index.ts, packages/@webex/plugin-meetings/src/member/util.ts, packages/@webex/plugin-meetings/src/members/index.ts, packages/@webex/plugin-meetings/src/members/request.ts, packages/@webex/plugin-meetings/src/members/types.ts, packages/@webex/plugin-meetings/src/members/util.ts, packages/@webex/plugin-meetings/test/unit/spec/member/index.js, packages/@webex/plugin-meetings/test/unit/spec/member/util.js, packages/@webex/plugin-meetings/test/unit/spec/members/index.js, packages/@webex/plugin-meetings/test/unit/spec/members/utils.js
The need to be able to reclaim the host role by any other participant in the meeting. This is especially useful in meetings where hosts of the meeting don't join and one of the guests has to take up the role of a host.
Refer #3272 and #3289 for the same functionality being added in the `beta` branch. This needed to be done in the `master` branch due to the release of USM.
[Confluence document](https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?spaceKey=LOCUS&title=Reclaim+Host+Role) for reclaiming host.
1. Added the types required in members for the ServerRoleShape
2. Added utility functions to create the required role object in the body from a member's parameters
3. Added the assignRoles function to the members object which eventually triggers the request to assign caller …
=> feat(meetings): add ability to reclaim host role with hostKey

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Sometimes we are kicked out of the meeting after failing to establish a media connection the first time
attempt to rejoin meeting if state is LEFT after first connection attempt
---
=> fix(plugin-meetings): rejoin when retrying media connection if needed

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts
Negative join times in ca-events result in them being dropped. It happens because sometimes (and we aren't sure why), there happens to be more than one `internal.client.meetinginfo.request` and more than one `internal.client.meetinginfo.response`. When calculating the timestamp difference between the response and request, sometimes the newest request time causes the timestamp to evaluate to a negative number.
We no longer let the `internal.client.meetinginfo.request` or `internal.client.meetinginfo.response` be put into the map twice. We only need the first timestamp values of each.
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-reques …
=> feat(ca-metrics): fix negative timestamps

packages/@webex/internal-plugin-metrics/src/config.js, packages/@webex/internal-plugin-metrics/test/unit/spec/batcher.js, packages/@webex/internal-plugin-metrics/test/unit/spec/client-metrics-batcher.js, packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js
Currently, there is a 15 second timer that is triggered when waiting for the metrics service to populate in our catalog. We want to extend this to cover the additional users with slower internet connections. Because we are not waiting long enough, we are getting pre join meeting failures, this should hopefully fix that.
---
=> fix(metrics): catalog delay

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-490019
We still see Locus error "User is not authorized to operate on Participant" in some cases when we retry. We have code that does rejoin, but it's not happening, because of the meeting state at that point. This metric will help us understand better what meeting state we're in.
Added metric for retry, kept it generic with a specific reason field so that it can be expanded in the future if we do other retries (like for example to try other media nodes)
unit tests
---
=> fix(plugin-meetings): add metric for addMedia() retries 

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
getPermissionTokenExpiryInfo returns undefined as well, this PR makes sure there is protection in code for that.
We epect typescript to complain but in sdk repo a function returning undefined is considered as having return type of 'any' hence typing getPermissionTokenExpiryInfo didn't help. Will raise a jira so that we can identify the cause of that, could be some misconfiguration
---
=> fix(plugin-meetings): consider undefined return type

packages/@webex/media-helpers/package.json, packages/@webex/media-helpers/test/unit/spec/webrtc-core.js, packages/@webex/plugin-meetings/package.json, yarn.lock
Updating the internal-media-core version. This includes updates from json-multistream (https://sqbu-github.cisco.com/CPaaS/json-multistream/pull/45) and webrtc-core (https://github.com/webex/webrtc-core/pull/69).
No changes on the SDK level other than updating package.json and unit tests.
Main goal here is to make sure https://github.com/webex/webrtc-core/pull/69 doesn't break mute/unmute functionality in the web client. Manually tested on a locally run web client with the following cases related to mute/unmute:
1. Web client mutes/unmutes their own microphone/camera.
2. Host mutes web client's microphone/camera.
3. Host unmutes web client user's microphone with "moderated unmute mode" enabled.
- However, this sometimes does not work if "allow attendees to unmute themselves in the …
=> fix(media-helper): update internal-media-core with webrtc-core mute changes

packages/@webex/media-helpers/package.json
Reverts a change to the typescript building of media-helpers
Removing `/types` from build command
---
=> fix(media-helpers): revert changes to type generation

packages/@webex/internal-plugin-metrics/package.json, packages/@webex/plugin-meetings/package.json
types declaration files were not being created for plugin-meetings and internal-plugin-metrics
---
=> fix: types-in-plugin-metrics-meetings

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-484765
Issue is that if client's clock is wrong then we calculate the timeLeft for permission token to expire incorrectly hence refreshing the token when not required.
To work around this we now get the current time when we receive the token, we also extract iat (issued time) from permission token payload and workout the shift in time. We then use this to work out the adjusted current time before calculating the timeLeft for permission token to expire. This fix stops us from  refreshing the token when it' not required.
--- …
=> fix(plugin-meetings): Fix timestamp

packages/@webex/plugin-meetings/src/index.ts, packages/@webex/plugin-meetings/src/interceptors/index.ts, packages/@webex/plugin-meetings/src/interceptors/locusRetry.ts, packages/@webex/plugin-meetings/test/unit/spec/interceptors/locusRetry.ts
If the client receives a 503 error message and if the Retry-After header is present, then client will retry with the same request based on the estimated time, if there is no Retry-After header, then client will immediately retry the exact same request one more time before it notifies the user of the error.
Added an interceptor to catch locus 503 errors and added a retry logic using setTimer to retry same request after Retry-After time (if given) or 2000ms (default)
---
=> fix(): adding retry timer for locus service unavailable

packages/@webex/internal-plugin-mercury/src/mercury.js
Removing needless web-ha-mercury metric.
As far as I know. Nobody uses this for anything.
- [] Tooling change
---
=> fix(mercury): remove needless metric

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When pressing the "join with media" button in the sample app, the app is not calling Meeting.joinWithMedia(), instead it's calling Meeting.join() followed by Meeting.addMedia()
- changed it to call Meeting.joinWithMedia()
- moved the code that was in sample app's addMedia() before calling Meeting.addMedia() to doPreMediaSetup() so that it can also be called before calling Meeting.joinWithMedia() in joinMeeting()
- moved the code that was in sample app's addMedia() after calling Meeting.addMedia() to doPostMediaSetup() so that it can be called after calling Meeting.joinWithMedia() in joinMeeting()
- added a check for media in lobby to Meeting.joinWithMedia()
manual testing with the sample app
--- …
=> fix: update sample app to call Meeting.joinWithMedia()

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/meeting/index.ts, yarn.lock
- `jwtDecode@4.x` requires node 18 and the SDK doesn't need node 18.
- Downgrading the jwtDecode's version to an older one where the node version isn't a requirement
---
=> fix(plugin-meetings): downgrade jwtDecode for node 16 usage

packages/@webex/plugin-meetings/src/meeting/muteState.ts
ExtCare has reported that participants lose mute control after X mins in a session.  A user will join and is muted, after a while they cannot unmute or mute themselves.  
Snippet of the error on the JS SDK logs
```
,2024-02-12T16:05:03.779Z,wx-js-sdk,Meeting:index#unmuteAudio --> unmuting audio
,2024-02-12T16:05:03.783Z,wx-js-sdk,Meeting:index#unmuteAudio --> unmuting audio failed, ,Error
at new r (https://assets.extcareop.com/mirror/cisco/webex/teams/sdk/2.57.1/webex.min.js:2:872506)
at e.value (https://assets.extcareop.com/mirror/cisco/webex/teams/sdk/2.57.1/webex.min.js:2:1079021)
at a.value (https://assets.extcareop.com/mirror/cisco/webex/teams/sdk/2.57.1/webex.min.js:2:1232249)
at VCRWebexMeeting.unmuteAudio (webpack://encounterui/./src/components/VideoCollaboration/Webex/WebexMeeting …
```
=> fix(meeting): allow unmute request from user when unmuteAllowed becomes null

packages/@webex/plugin-meetings/README.md, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
When Mercury reconnection occurs, we want to sync all meetings from Meetings Collection. In syncMeetings, the default of keepOnlyLocusMeetings is true to not cause breaking changes as the old behaviour of syncMeetings was to keeping only Locus Meetings and destroying any other.
Set keepOnlyLocusMeetings to false on reconnection cases. This means that, on reconnection, meetings without an active locus url would NOT be destroyed, and thus, will be kept on the sync.
- [] Bug fix (non-breaking change which fixes an issue)
---
=> feat(pluging-meetings): sync all meetings from Meeting Collection when reconnecting

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
Avoid duplicate request of meeting info
Adding extra parameter to `meeting.create` method to pass down pre-fetched meeting info, also adding utility methods to process the new parameter.
---
=> fix: avoid duplicate request of meeting info by passing it from cantina

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts
When we reconnect, we send some roap messages and 2 of them (TURN_DISCOVERY_REQUEST and OFFER) are being sent with empty media Id. Only the first one of them should be sent with empty media id. Empty media id indicates to Locus that this is a new connection and that they should create a new confluence in the server
As we are now hardcoded to always send TURN_DISCOVERY_REQUEST as the first Roap message when reconnecting, we can now also hardcode the code for sending offer to never use empty media id.
unit tests
---
=> fix: when reconnecting, JS-SDK calls Locus /media API with empty mediaId twice

packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Less than optimal tests in the `statsAnalyzer` module
Adding unit tests.
Each `process__` method for the different types of stats.
Log messages for different packets' sending and receiving scenarios.
---
=> fix(meetings): add stats analyzer tests

packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
most tests not running from a bug in tests from this PR: https://github.com/webex/webex-js-sdk/pull/3387
removing a `.only` tag left in on a new test
All tests
---
=> fix(test): remove only tag for test

packages/tools/cli/package.json, packages/tools/package/README.md, packages/tools/package/index.js, packages/tools/package/package.json, packages/tools/package/src/commands/index.ts, packages/tools/package/src/commands/sync/sync.ts, packages/tools/package/src/commands/update/index.ts, packages/tools/package/src/commands/update/update.constants.ts, packages/tools/package/src/commands/update/update.ts, packages/tools/package/src/commands/update/update.types.ts, packages/tools/package/src/index.ts, packages/tools/package/test/module/update/update.test.js
When this pull request is merged, this will publish the `@webex/cli-tools` and `@webex/package-tools` packages to **NPM** for consumption within down-stream clients.
The scope of the changes in this pull request are to add the `update` command to the `@webex/package-tools` package. This new command allows for consumers of the JS SDK to update their dependencies based on the latest available from `NPMJS`.
```jsonc
/* ./package.json */
{
/* ... */
"dependencies": {
/* ... */
"querystring-es3": "^0.2.1"
},
"devDependencies": {
/* ... */
"@babel/cli": "^7.17.10",
"@babel/core": "^7.17.10"
}
}
```
```bash
yarn webex-package-tools update --packages @babel/cli querystring-es3 --tag next
querystring-es3: ^0.2.1 => 1.0.0-0
@babel/cli: ^7.17.10 => 8.0.0-alpha.6
```
```jsonc
/* ./package.json */
{ …
```
=> feat(tools/packages): update command

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/http-core/src/request/request.shim.js, packages/@webex/http-core/test/unit/spec/request/request.shim.js, packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/index.ts
- Right now, the SDK does not listen to events until we do `startTranscription` and Guest users do not need to startTranscription to receive transcription. This event listening doesn't happen at the Voicea level too. 
- The SDK doesn't wait for the LLM connection to be established
- The `Invalid right-hand for instanceOf Blob` error
- Listening to events in Voicea from meetings by default
- Listening to LLM events from voicea by default
- Making Voicea toggle call only if the current user's role is 'host'
- Wait for LLM connection to be established and then resolve Meeting Join
- Making a toggle in the Sample app to enable transcription on login
- In http-core, for the invalid error, the Blob is mocked instead of importing it from Buffer since we imported it only for jest tests
- Enabling …
=> fix(plugin-meetings): listen to transcript for guests

packages/@webex/test-users/src/index.js
- Setting the preferred WebexSite of a created Test User
- Adding a new `setPreferredSite` function in test-users package, to allow for setting the preferred webexsite after a test user has been created
- Didn't add integration tests, since they are not testable / there is an issue currently that test-users package doesn't allow running the integration tests (saying "Found 0 tests" when running).
- Tested the function locally
---
=> test: test-user set preferred webexsite

packages/@webex/plugin-meetings/src/rtcMetrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts
Reconnections ruining telemetry dumps. This PR in conjunction with work on the job will show multiple connections in calls where a reconnect happens.
Adding a connection id to metrics payloads and resetting the connection id on RTCPeerConnection `connectionstatechange` events.
Sending queued metrics and creating a new `connectionId` on a `connectionstatechange` failure event.
---
=> fix(plugin-meetings): add connection id to rtcmetrics

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts
`getInterstitialToMediaOKJMT` returned with `undefined` 99.9% of the cases because the media flow did not started because at the time when media engine ready event emitted.
used `client.ice.end` latency instead of the media started values. This is what UCF use as well.
---
=> fix(metrics): getInterstitialToMediaOKJMT calculation

packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
users who had had reachability done while on VPN would not be able to reconnect properly if their VPN disconnected during a meeting
perform reachability before reconnection to give users the best chance at reconnecting
---
=> fix(plugin-meetings): do reachability before every reconnect attempt

packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The mis-formatting of browser MQEs.
changing the event shape from this:
```
audioReceive: [
{
streams: [{...}], // main audio
common: {...},
},
{
streams: [{...}], // main audio
common: {...},
},
{
streams: [{...}], // main audio
common: {...},
},
{
streams: [{...}], // slides audio
common: {...},
},
]
```
to this:
```
audioReceive: [
{
streams: [
{...}, // main audio
{...}, // main audio
{...}, // main audio
],
common: {...}
},
{
streams: [{...}], // slides audio
common: {...}
}
]
```
for all audio and video; senders and receivers.
Testing the new MQE shape is accurate
---
=> fix(plugin-meetings): mqe streams format

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When a user leaves a breakout session, locus is initialized again for the main session and the sdk meeting object is updated accordingly with locus-info line 1165
```
this.updateMeeting(parsedInfo.current);
```
However, the client does not receive a trigger for this update, so it stays with outdated meeting info. 
Triggering MEETING INFO AVAILABLE on MEETING_INFO_UPDATE, which is only triggered by locus' updateMeetingInfo method.
---
=> fix(plugin-meetings): trigger meeting info available on meeting info update

packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
In scenarios where LLM is not enabled before Webex initialization, we are sending a POST request to update the LLM connection during meeting cleanup.
Added a check in the cleanup function to check if meeting.config.enableAutomaticLLM  is set to true. If not, we do not invoke updateLLMConnection().
Unchecked EnableLLM in Kitchen Sink App before webex initialization and joined the meeting. Triggered meeting.endMeetingForAll() from the console and verified that the registration request to the data channel url is not sent out post the end API call.
[Network_logs_with_fix.txt](https://github.com/webex/webex-js-sdk/files/14741974/Network_logs_with_fix.txt)
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-p …
=> fix(meetings): fix to avoid llm connection update when its not enabled

packages/@webex/plugin-meetings/src/roap/request.ts
A small change in plugin-meetings/src/roap. This change is not required. No change in logic
options in passed as an argument to sendRoap. options has roapMessage in it. So it doesnt matter if we take options.roapMessage.seq or roapMessage.seq, roapMessage is not modified.
---
=> fix(plugin-meetings): reverted-redundant-change

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
In current state, when a user is admitted from the lobby, LLM connection is not established, as a result they may not be able to receive any reactions. This PR addresses the issue as a result LLM connection is established in the receivers end.
https://github.com/webex/webex-js-sdk/assets/11624479/8298eb44-8491-4b60-82c2-d8fc7f3e21c6
---
=> Fix: Added updateLLMConnection when guest is admitted from the lobby

packages/@webex/internal-plugin-mercury/package.json, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury-events.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/internal-plugin-mercury/test/unit/spec/socket.js
Uts were failling in next. Reverted internal-plugin-mercury to use Mocha.
Tests run using mocha.
---
=> fix(internal-plugin-mercury): use-mocha-for-uts

packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-presence/test/unit/spec/presence-worker.js
Revert skipped test in plugin-metrics and plugin-mercury because those tests were failling when we run in jest. Since we have moved them back to mocha those tests are passing.
internal-plugin-presence, changes the test so that it can run in both jest and mocha. Easier to migrate to beta. We dont run these tests in next this is solely for the migration process. 
Made the same changes in beta branch and all tests are passing there. Plugin-metric and plugin-mercury tests are passing in next as well as beta
---
=> test(metrics): revert jest changes for metrics and mercury plugins

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
adding browserLaunchMethod metric to send to CA.
see relevant cantina PR: https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/5650/files
reading browserLaunchMethod from options if sent via cantina.
---
=> fix(metrics): adding browserLaunchMethod metric in CA

packages/@webex/internal-plugin-metrics/package.json, yarn.lock
remove authIntelligenceGenerationReqResp latency from metrics
update event dictionary dependency which contains the required change
---
=> feat: remove authIntelligenceGenerationReqResp latency

packages/@webex/internal-plugin-dss/test/unit/spec/dss.ts
The PR is to revert this test back to it's original state and just add an one-line fix
The changes made are reverting the promise.then to old async/await methodology so that it doesn't diverge much with beta and add a one-line fix suggested by Marcin
Please refer to this discussion for better explanation: https://github.com/webex/webex-js-sdk/pull/3499#discussion_r1571133053
---
=> test(internal-plugin-dss): revert test and fix with an empty catch

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
WCME munged the SDP answer and created copies of m-sections before passing the SDP to the browser via setRemoteDescription(). As a result, if there was a global b=TIAS line and b=TIAS lines at some media sections, the totals don't add up correctly in the munged SDP answer. This causes issues with audio in Chrome.
This request is about removing the logic of setting b=TIAS lines in the WCME and removing some logic fixes in the internal media core. 
tested manually with the web app and js-sdk app
=> fix: remove the logic of setting b=TIAS lines in the internal media core

package.json
After https://github.com/webex/webex-js-sdk/pull/3575, to build samples we need `/packages/webex/dist/meetings.js`
Changed 'yarn run samples:build` command to first build the packages and then build the samples.
---
=> fix(tooling): fix-samples-build-cmd

packages/@webex/media-helpers/src/webrtc-core.ts
`LocalCameraStreamEvents` uses `LocalMicrophoneStreamEventNames` instead of `LocalCameraStreamEventNames`
`LocalCameraStreamEventNames` is used for `LocalCameraStreamEvents` instead of `LocalMicrophoneStreamEventNames`
---
=> fix(media-helpers): change type for local camera stream events

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
MQA team has announced that they are removing the peripherals property in MQE and will only use cameraInfo/microphoneInfo/speakerInfo instead. Currently, on the web client, we are only populating the peripherals property and are not populating cameraInfo/microphoneInfo/speakerInfo. This PR addresses this issue
See pinned message in the Ask MQA space for more details.
[webexteams://im?space=e291a140-f2a2-11ea-a094-5519499aaa4d&message=e1895b50-0133-11ef-9b2a-b19ef59b66fb](webexteams://im?space=e291a140-f2a2-11ea-a094-5519499aaa4d&message=e1895b50-0133-11ef-9b2a-b19ef59b66fb)
Changes filling peripherals field in MQE to cameraInfo/ microphoneInfo/ speakerInfo
- Meeting with 2 people using `samples:serve` [correctly emitted](https://gist.github.com/SomeBody16/140f62495c0e6ea21f43d02546feff6b) …
=> feat(plugin-meetings): use [peripheralName]Info instead of peripherals in MQE

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/plugin-meetings/src/config.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/reachability/clusterReachability.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reachability/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/clusterReachability.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/util.ts
Currently, we are doing only reachability checks for UDP and TCP.
This PR introduces a reachability check also for TurnTLS. It will allow checking before the call if client is capable of reaching to our turn servers. TurnTLS will be marked as experimental.
Tested with the JS SDK Sample app.
---
=> fix: add reachability checks for TLS

packages/calling/package.json, yarn.lock
Calling is using an older version of internal-media-core, due to this migrating WWC to use public calling-sdk is causing type errors. To avoid these type errors upgrading internal-media-core in calling package.
Full discussion - https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/5749/files#r2085329
Got a green build locally with this dependency.
---
=> feat(calling): update-internal-media-core-version

packages/@webex/internal-plugin-voicea/src/voicea.ts, packages/@webex/internal-plugin-voicea/test/unit/spec/voicea.js, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
- PII Information is being logged from Voicea
- There are Circular Dependency between Voicea and Meetings because of using TriggerProxy in Voicea
- Removed Circular Dependency by getting rid of TriggerProxy usage in Voicea
- In plugin-meetings, again got rid of TriggerProxy and started logging in place
- Tested all the Voicea-based events for Closed Captions
- Ensured sample app is working fine for the newest changes and that the user-facing events are emitted appropriately
- Checked logs through Sample applications for any of the Voicea events not logging any Payload/PII information
---
=> fix(plugin-meetings): remove logs and circular dependency with voicea

packages/webex/src/calling.js
calling plugin missing dss plugin import due to which we can't utilize dss functions in the calling code.
requiring the `@webex/internal-plugin-dss` in `calling.js`
1. Check the presence of the `webex.internal.dss` object. 
2. Run a test to lookup a user by doing `contacts.webex.internal.dss.lookup({id: userId});`
3. Test other calling functionality like making calls.
---
=> feat(contacts): import dss plugin for search and cloud contact resolution

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/media/MediaConnectionAwaiter.ts, packages/@webex/plugin-meetings/src/media/properties.ts, packages/@webex/plugin-meetings/test/unit/spec/media/MediaConnectionAwaiter.ts, packages/@webex/plugin-meetings/test/unit/spec/media/properties.ts, yarn.lock
Currently, MultistreamMediaConnection doesn't wait for the ICE Gathering to complete. What results in sometimes not waiting for relay candidates to be gathered. Not waiting for relay candidates to be gathered, may result in not intended media connection failure even though media could be establish through the TurnTLS.
This PR introduces functionality which on media connection will wait for ICE Gathering to be completed. What's more retry have been added in case ICE Gathering completes in requested time duration, but no DTLS connection have been established yet.
JS SDK Multistream Connection Establishment
JS SDK Transcoded Connection Establishment
Web App
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting …
=> fix: wait for ice gathering state to complete or timeout

docs/samples/calling/app.js, packages/webex/src/calling.js
2 device registrations occur in the Calling SDK.
- `calling.register` which calls the `internal.device.register` from `webex/calling.js`
- `line.register` which does the Mobius line registration
While we have the above two methods for deregistering, we do not have a deregister method only for `line` and not for `calling` which does the WDM device deletion operation
- This PR introduces that method in `webex/calling.js` - The Calling class such that, users can do this deregister upon successful deregistering of line
- Or, they can call `calling.deregister()` method alone which will deregister all the active lines, disconnect mercury and delete WDM device as well
In the below recordings, you can see that the WDM device and Mercury registration doesn't happen before this change and they …
=> fix(calling): wdm deregister method

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Revert "feat(plugin-meetings): use [peripheralName]Info instead of peripherals in MQE (#3565)"
This reversion is necessary because the new MQE format was causing validation errors, since the MQA team has not actually adopted the new format yet (we've discussed with the MQA team to make sure such an issue won't happen again).
This reverts commit bd29ca809ca04e244e163fe81d99db10ee91e941.
Manually checked MQEs sent from the SDK sample app and verified that they are correct on OpenSearch.
---
=> fix(plugin-meetings): revert peripherals MQE back to array

packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts
Issue 1: After disabling BNR on the same call, if we try to enable BNR in a muted state, then stream goes missing completely, and after unmuting, the stream is still missing.
Steps to reproduce: Enable BNR and disable BNR while the call is unmuted. Now mute the call and enable BNR. Unmute the call now and the stream should go missing without the fix.
Issue 2: In subsequent calls after disabling BNR, enabling BNR in an unmuted state messes up the mute-unmute behaviour again and the stream remains present always.
Steps to reproduce: Enable BNR and disable BNR while the call is unmuted and disconnect the call. Now establish second call and enable BNR in unmuted state. Now try to mute the call and the stream will always be present and can be heard on the other side. Muting the stream stops …
=> fix(calling): mute/unmute fix with bnr

packages/@webex/plugin-meetings/src/locus-info/selfUtils.ts, packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/selfUtils.js
The issue arises from `mutedByOthersChanged` in `selfUtils`. This function should not trigger a user mute update when the user receives a notification from the server that the server has been updated remotely to a muted state but not from another person. 
I have added the fix to `mutedByOthersChanged` that will avoid updating the mute state when the server state doesn't change by others and added testcases for `selfUtils.mutedByOthersChanged`
---
=> fix(plugin-meetings): Mute issue with host and "mute all" action

packages/@webex/internal-plugin-voicea/package.json, packages/@webex/internal-plugin-voicea/tsconfig.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/index.ts, packages/@webex/plugin-meetings/src/meeting-info/util.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts
Export important classes, objects, and constants in plugin-meetings. This will make sure we dont have to import them from from '/dist' folder in WWC.
In internal-plugin-voicea, we were not creating declaration files.
- Exporting all required objects in plugin-meetings.
- Changed commands in plugin-voicea, and added tsconfig to create proper declaration files.
---
=> fix(meetings): fix types

packages/@webex/plugin-meetings/src/index.ts
1. After [PR-3602](https://github.com/webex/webex-js-sdk/pull/3602) all imports were working fine except MeetingInfoUtil. Methods inside  MeetingInfoUtil were not accessible directly in web-client 
What went wrong? Using `export * as MeetingInfoUtil from './meeting-info/utilv2';` exported everything under `MeetingInfoUtil` namespace. To utilize methods in MeetingInfoUtils we would have to do `MeetingInfoUtil.default` in web-client
Fix - import the default export from 'meetingsInfoUtils.ts' and then export the class.
2. JoinMeetingError was not exported.
MeetingInfoUtil is accessible as before. JoinMeetingError is exported.
-Locally linked these changes and ran tests in web-client.
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master …
=> fix(plugin-meetings): export-meetinginfoutil-as-class

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Missing MQE stats (`requestedBitrate`, `requestedFrameSize`) from web client
It's a follow to PR #3526 (previously to beta branch)
Filled missing stats in `statsAnalyzer` (`plugin-meetings`)
- meeting with 2 people using `samples:serve` correctly reads stats from WCME (logs)
- meeting with 2 people using `samples:serve` correctly sends MQE requested with filled requestedBitrate and requestedFrameSize ([curl](https://gist.github.com/SomeBody16/d0597ae2a5b11c920d1b73b57633302a))
---
=> fix(plugin-meetings): requestedBitrate and requestedFrameSize stats

packages/@webex/plugin-meetings/src/media/properties.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/properties.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
We have a suspicion that DTLS handshake failures are caused by Linus not handling correctly the switching of the selected ICE candidate pair.
Sending `selectedCandidatePairChanges` with the add media success and failure metrics so that we can prove that it's always greater than 1 when DTLS handshake fails and equal to 1 when we connect without issues.
Unfortunately, selectedCandidatePairChanges is not supported by Firefox and Safari, so we'll get these metrics only on Chrome and Edge.
Implementation details:
- I've renamed `getCurrentConnectionType()` to `getCurrentConnectionInfo()`, because now it returns more properties
- `getCurrentConnectionType()` used to wait for the connection to be established, I've removed that, because we need to call it now in failure cases when connection is …
=> fix: sending selectedCandidatePairChanges metric

packages/@webex/plugin-meetings/src/common/errors/reconnection-in-progress.ts, packages/@webex/plugin-meetings/src/common/errors/reconnection-not-started.ts, packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
When a reconnection is started, we first do reachability checks and if during that time we get a FAILED connection state notification, we end up starting another reconnection. We should only do 1 reconnection at a time.
Setting ReconnectionManager.status to IN_PROGRESS sooner and also refactored the code a bit so that the status is private and only ReconnectionManager changes it. Also moved sending of some metrics and emitting events from Meeting into ReconnectionManager so that now ReconnectionManager really is the one managing the reconnection.
unit tests
---
=> fix: 2 reconnections started in parallel

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
When host move a web client to lobby in a breakout, the web client UI state should be right.
Need handle main session locus info in the case.
---
=> fix(moveToLobby): need handle main locus info when move to lobby from breakout

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts
We were sending CA event "client.locus.media.request" and "client.locus.media.response" every time we do Locus /media API call. These calls are made when we want to send Roap messages, but also when we mute/unmute. CA is not interested in the mute/unmute ones and in some meetings users generate a lot of them.
It's been agreed with CA team that we will only send the "client.locus.media.request" and "client.locus.media.response" events for Roap messages, not for mute/unmute operations.
Also I've noticed that for Roap messages we were sending the "client.locus.media.request" event too early, when it still might be queued inside LocusMediaRequest, so in some extreme edge cases when the LocusMediaRequest is stuck, we might send the CA event and never actually do the Locus reuqest, so I've …
=> fix: don't send CA events when we do Locus /media API calls for mute/unmute and improve when we send them for Roap messages

packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts
While updating the local track, a DOM exception error was encountered complaining for the peer connection to be closed. Hence enabling BNR fails after the first call. This happens because the old listener is used for the OutputTrackChange event on the localAudioStream, which uses the previous media connection, which is closed while updating the local track.
index.js:6603 Uncaught (in promise) DOMException: The peer connection is closed.
at https://localhost:8000/samples/calling.min.js:2:3712596
at Array.forEach (<anonymous>)
at r.value (https://localhost:8000/samples/calling.min.js:2:3712231)
at r.value (https://localhost:8000/samples/calling.min.js:2:3713170)
at r.value (https://localhost:8000/samples/calling.min.js:2:3847575)
at Je.<anonymous> …
=> fix(calling): switching off stream listeners to avoid having multiple listeners

packages/@webex/internal-plugin-voicea/src/index.ts, packages/@webex/internal-plugin-voicea/src/voicea.ts, packages/@webex/internal-plugin-voicea/src/voicea.types.ts, packages/@webex/internal-plugin-voicea/test/unit/spec/voicea.js, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/voicea-meeting.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/voicea-meeting.ts
As part of this PR: #3620 breaking changes were made to how captions are emitted in the events. This broke the Transcriptions in the plugin-meetings
- Change everything to new payload structure
- Add timestamp in new payload for Voicea final captions
- Update voicea and SDK tests in `plugin-meetings`
- We also have refactored a util method,
- Earlier, we were processing NEW_CAPTIONS in two data formats, `isFinal:true` came with "transcript" object while `isFinal:false` came with "transcripts" array
- Now, the breaking change has aligned such that we always get only "transcripts" array
- Therefore, this method now performs all the caption processing on "transcripts" array and only does the needed changes based on "isFinal" boolean. This means that we process `isFinal:false` as an interim …
=> fix(plugin-meetings): update transcription for new voicea payload

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Instant connected reported that, the `moveTo` API doesn't unpublish the localStreams. This is because the method `closeRemoteStreams` that was there before `cleanupLocalStreams` handled it appropriately and `cleanupLocalStreams` doesn't
- Added the cleanup logic in `moveTo` method that closes the existing media connection, cleans up remote and local streams and also stops statsAnalyzer from sending any data
- Removed reconnect logic as that is not required anymore
- Instead we do `addMedia` with a forced retry to do turn discovery (`isMoveToInProgress` flag ensures of that in the `establishMediaConnection` method)
- Join a Meeting with Audio and Video > Pair to a device > `moveTo` - This ensured the Video and Audio gets cut off
- Join a Meeting with Audio and Video > Share Screen > Pair …
=> fix(plugin-meetings): unpublish streams on moveTo

packages/legacy/tools/src/utils/server.ts, packages/webex/src/webex.js
As part of this PR: #3645, we removed `@webex/plugin-presence` from the package thereby avoiding conflict while doing `yarn install`
This however is still not removed from the source and is causing issues when trying to import the `webex` package
- Removing @webex/plugin-presence from the src/webex.js main file also 
**When trying to bundle the webex package using parcel bundler:**
---
**When trying to use the SDK on a node-js app:**
---
=> fix(webex): remove plugin-presence from src

packages/@webex/plugin-meetings/src/reachability/index.ts
This PR adds missing functionality of logging unreachable xTLS clusters.
After this change all unreachable xTLS clusters will be logged at the end of reachability check.
Tested with JS-SDK sample app.
---
=> fix: during adding xtls reachability logging unreachable xtls clusters were missed

packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/webex-core/src/config.js, packages/@webex/webex-core/src/lib/services/constants.js, packages/@webex/webex-core/src/lib/services/service-catalog.js, packages/@webex/webex-core/src/lib/services/services.js, packages/@webex/webex-core/test/integration/spec/services/services.js, packages/@webex/webex-core/test/unit/spec/interceptors/auth.js, packages/@webex/webex-core/test/unit/spec/services/service-catalog.js
in fedramp, it's important that clients do not send auth token to resources outside of the "fedramp" boundary. therefore, we should only send auth headers in the following cases
1. the resource is in the u2c catalog
2. the resource is in the list of allowed domains
i changed the allowedDomains to be empty in FedRAMP by default. if the user wants more domains in fedramp, they can pass them through config or by `setAllowedDomains()`. in commercial, we keep the existing list of allowedDomains.
the reason webex.com cannot be a default allowedDomain in fedramp is because there are commercial sites, like cisco.webex.com and we don't want fedramp users sending their auth tokens to arbitrary commercial *.webex sites
1. manually tested with config value `fedramp: false`
2. manually tested with …
=> feat(fedramp):  only add domains if commercial

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts
Currently, there were a couple of MARI-related metrics with incorrect values. The purpose of this PR is to update metrics for the Web client.
Add `mariRtxEnabled`, `mariLiteEnabled`, remove `remoteReceiveRate`
---
=> fix(plugin-meetings): update MQE for MARI related metrics

packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Web app wants to know when we are blocked at the network level so that we can show a UI warning to the user.
Added API that web app can call to find out if webex media clusters are completely unreachable. 
unit tests
---
=> feat: added isWebexMediaBackendUnreachable() API

packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Incorrect reporting of `rtxPackets` and `rtxBitrate` for video MQEs in `MQEIntervalSessionTransmitVideo` and `MQEIntervalSessionReceiveVideo`.
- Updated the reporting of `rtxPackets` to use the WebRTC stat `retransmittedPacketsReceived` for received video and `retransmittedPacketsSent` for transmitted video.
- Updated the reporting of `rtxBitrate` to use the WebRTC stat `retransmittedBytesReceived` for received video and `retransmittedBytesSent` for transmitted video.
=> fix(plugin-meetings): streamline rtxPackets and rtxBitrate

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
So, while joining a meeting using the Web SDK, we check if the `enableAutomaticLLM` is set to true and connect the LLM  websocket and once we do this, we notify the customer through an event `meeting:transcription:connected`
We do this once the `updateLLMConnection` method is resolved. However, this is inaccurate sometimes leading to early emission of the event
To avoid such inaccuracy, this change will here-on listen to the 'online' event emitted by the LLM plugin and then trigger the `meeting:transcription:connected` event
Here's [link to the sharepoint upload](https://cisco-my.sharepoint.com/:v:/p/kmadavan/EUEyyMAsfDJNhsFgdQwS-nEB1Dheba4JmIeONRGf7MHnRw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZp …
=> fix(plugin-meetings): trigger transcript connected after llm online

packages/@webex/internal-plugin-feature/package.json, packages/@webex/internal-plugin-feature/src/feature.js, packages/@webex/internal-plugin-feature/src/index.js, packages/@webex/internal-plugin-feature/test/unit/spec/feature.js, packages/@webex/internal-plugin-mercury/src/mercury.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/test-helper-mock-webex/src/index.js, webpack.config.js, yarn.lock
The final circular dependency that is left out. This PR cuts off the circular dependency between `internal-plugin-mercury` and `internal-plugin-feature` 
- Remove the `internal-plugin-mercury` dependency from `internal-plugin-feature`
- On successful connect of `webex.mercury.connect` event, the mercury object listens to the `event_featureToggle`
- Whenever this event is called, the handler checks if it has a legitimate envelope and identifies the feature and sends it to feature plugin by calling `webex.internal.feature.updateFeature`
- This `webex.internal.feature.updateFeature` is the method that is modified from earlier `handleFeatureUpdate` call back listener
--- …
=> fix: circular dependency b/w feature and mercury

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
Removal of the non-blocking `exports.getBuildType` error that appears in the logs which was annoying
As per [this ticket](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-470747), the `exports` was added to the `getBuildType` call so that it can be stubbed and tested in the unit tests. To address this, I've changed the getBuildType code to show a log that this method was called and then test `webex.logger.log` instead of `getBuildType`
The aim was to know if this method was called with the right attributes and that is accomplished
**Logs before and after**
| Before | After |
| --- | --- |
| [webex.github.io-1719717587011.log](https://github.com/user-attachments/files/16043036/webex.github.io-1719717587011.log) | [pr-3671.d3m3l2kee0btzx.amplifyapp.com-1719717796375.log](https://github.com/ …
=> fix(internal-plugin-metrics): remove exports.getBuildType error

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
the problem where `rtcstats` is causing join failures on Firefox versions around 107/108 due to the following error: TypeError: _this.sctp.addEventListener is not a function.
`rtcstats` fix: https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-390724 
WCME version update: https://sqbu-github.cisco.com/CPaaS/web-client-media-engine/pull/389
Media Core version update: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/232
=> fix: update internal media core version

packages/@webex/webex-core/src/lib/services/services.js, packages/@webex/webex-core/test/integration/spec/services/services.js, packages/@webex/webex-core/test/unit/spec/services/services.js
There was a fundamental misunderstanding in the previous parsing algorithm. It assumed that the `id` of each service in the host catalog was the same as the service name as referenced by the serviceLinks. This is not the case. The result was that for certain services, no alternative hosts would be identified. The previous version also created a mock version of the primary with a higher priority. I have also removed this.
The code does the following:
* Iterates over the serviceLinks. Each key of the service links is the service name.
* Finds the corresponding URL key in the host catalog 
* Extract the ID from the first host under this entry
* Generate the first entries in the hosts for this service. homeCluster is set to true for hosts entered here, as indicated by the serviceLink pointing …
=> fix(webex-core): fix parsing of u2c hostmap

packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Currently, `multistreamEnabled` has the wrong value for MQE. It should be `true` for **multistream** and `false` for **transcoded** meetings
Fix value for MQE `multistreamEnabled`, add tests
---
=> fix(plugin-meetings): update multistreamEnabled

packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The deprecation of the `remoteLossRate` property in MQE and its replacement with `maxRemoteLossRate`.
- Removed the `remoteLossRate` property from relevant MQE data structures and interfaces.
- Added the `maxRemoteLossRate` property where applicable.
- Updated all references and calculations to use `maxRemoteLossRate` instead of `remoteLossRate`.
- Unit tests were updated and run to ensure that the new property is being used and the old property is no longer referenced.
- Manual testing was conducted in a development environment to ensure that the changes did not negatively impact the user experience or data reporting.
---
=> fix(plugin-meetings): deprecate remoteLossRate for maxRemoteLossRate

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Being able to determine whether a hardware or a software encoder is being used when share video gets muted.
Including the share video encoder implementation in the SDK event that is emitted whenever the share video mute state changes.
---
=> feat: add share video encoder implementation to share video mute event

packages/@webex/internal-plugin-llm/src/llm.ts, packages/@webex/internal-plugin-llm/test/unit/spec/llm.js, packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-541046
There were two issues in previous implementation:
1. SDK subscribe breakout message right after join meeting but before client register and connect to LLM successfully, so subscription will fail.
2. When dataChannelUrl changed will trigger updateLLMConnection, but updateLLMConnection doesn't check whether dataChannelUrl changed, and do nothing if locus Url is same. But in fact we need reconnect LLM if dataChannelUrl changed.
1. SDK subscribe breakout message only when join a breakout when LLM should be connected successfully.
2. updateLLMConnection do reconnect if dataChannelUrl changed.
--- …
=> fix(bo): can't receive broadcast in some cases

packages/calling/package.json, yarn.lock
This Pull Request upgraded the minimatch which is an internal dependency of mocha. Updating the mocha to the latest version can upgrade the minimatch dependencies.
I have changed the version of  mocha from 9.1.2 to 10.6.0, leading to the latest version of the minimatch version.
After running, I had run the Kitchen Sink App and test the all process and features and it was working fine.
---
=> chore(deps): bump minimimatch with mocha internally 3.0.4 to 5.1.6

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js, yarn.lock
Missing MQE stats `cpuInfo.numberOfCores` 
Adds `cpuInfo.numberOfCores` to MQE to expose the number of logical processors
---
=> fix(plugin-meetings): numberOfCores stats

packages/@webex/plugin-meetings/src/metrics/index.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/metrics/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Recently added reachability metrics are sending an object with nested objects inside it as metricsFields, Amplitude doesn't like that, we need to flatten the object.
Added a helper method for flattening the objects for Amplitude metrics and using it in reachability.
Original PR where the reachability metric was introduced:
https://github.com/webex/webex-js-sdk/pull/3696
unit tests
---
=> fix: reachability metrics sending nested metricFields

docs/samples/calling/index.html
In the Kitchen sink app, initialize was failing due to the new input box added for the JWT token as it had both properties: hidden and required. Hence it failed for scenarios where we select service.indicator as calling.
Removed the required property from the <input> HTML element 
Tried to initialize with calling as well as guest calling.
---
=> fix(sample): fixed jwt token input box error

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When we're missing H264 codec, we will fail to add media, but joinWithMedia() will still do a 2nd attempt - this is unnecessary. Also, for any other case where we fail to create the offer, there is no point retrying.
Don't do retries when we fail to create the SDP offer (that's what happens when the codec is missing).
unit tests, manual test with webapp
---
=> fix: don't retry if we're missing h264 codec

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting-info/index.ts, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting-info/util.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/collection.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/meetings/meetings.types.ts, packages/@webex/plugin-meetings/src/meetings/util.ts, packages/@webex/plugin-meetings/src/personal-meeting-room/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/request.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/utilv2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/plugin-meetings/test/unit/spec/personal-meeting-room/personal-meeting-room.js
1-1 calls cause fetchmeeting request to be sent to wbxappapi that always fails
create meeting API
Added new type to create meeting api to state its a one2one meeting so by using that type to skip fetchmeeting api
MANUAL Testing done by passing ONE_ON_ONE_CALL in WWC and added below network logs
[withFix.txt](https://github.com/user-attachments/files/16487469/withFix.txt)
[withoutFix.txt](https://github.com/user-attachments/files/16487470/withoutFix.txt)
---
=> fix(plugin-meetings): prevent fetchMeetingInfo service call for one2one meeting. 

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When we fail to send SDP offer or never receive the answer the calls were incorrectly classified as success in CA
It's been agreed with CA team that we should send 'client.media-engine.remote-sdp-received' with an error if we don't receive the answer (that includes also cases where we fail to send the offer as the answer comes in http resposnse to that request).
unit tests, manually tested with web app
---
=> fix: send 'client.media-engine.remote-sdp-received' with error when not receiving SDP answer

packages/@webex/plugin-authorization-browser-first-party/src/authorization.js, packages/@webex/plugin-authorization-browser-first-party/test/unit/spec/authorization.js
plugin-authorization-browser-first-party currently requires an emailhash, but the auth flow itself does not require one. It is possible to go directly to the authorize URL without first knowing the email.
No longer require emailhash when returning from idbroker. If emailhash is not provided, the preauth catalog will be collected without it (i.e. limited based on proximity). The normal flow with emailhash will be unaffected by this change.
---
=> feat(plugin-authorization): allow auth with no emailhash

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
Last changes to firefox with full-ice supported encountered issues on older versions of firefox <=114.
Those versions expect `ice-ufrag to be present in all m-line sections. Previously it was working correctly, because we were injecting dummy candidates to all lines, and homer was responding with those lines.
With full-ice candidates are injected only to first m-section, which result in having ice-ufrag only in first section in response.
Updates internal-media-core to version which ensure that all media sections does have ice candidates.
Tested on firefox 110, 113, 129. Have not found any new issues.
---
=> fix(plugin-meetings): firefox <=114 encounters issues with missing ice-ufrag

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When a meeting host has joined and started transcription already and a non-host participant joins the meeting, the `meeting:receiveTranscription:started` event is not triggered. We had the condition because:
1. A non-host participant cannot `toggleTranscribing` and now, a participant can `turnOnCaptions` even if they're not host. 
2. A non-host participant would receive captions even without having to request Voicea to `turnOnCaptions`
Now, we are removing the host condition because:
1. `turnOnCaptions` is allowed by locus for non-host participants also
2. The original issue of `meeting:receiveTranscription:started` event not triggered is because Voicea doesn't think it has to trigger that event unless we `turnOnCaptions`
Additionally, in this PR we also restrict `setSpokenLanguage` to be …
=> fix(plugin-meetings): transcription:started event for every participant

packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
The frame rate of metrics that is from CLP automateddiagnostics for WEB APP is not unified with Webex APP. The frame rate of the Webex APP is multiple 100, but the WEB APP is not. 
Multiply frame related stats by 100
- samples app correctly sends stats multiplied by 100
- unit tests
---
=> fix(plugin-meetings): framerate multiplied by 100

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
When joinWithMedia() fails to establish media connection, but succeeds on the retry, Call Analyzer still marks the join with mediaOutcome=failed
Introduced a callback for determining the value of icePhase sent on failure. The callback has different logic when addMedia() is called from joinWithMedia(), because joinWithMedia() knows that it will do a retry as opposed to the public addMedia() method, which also has its own retry logic, but it's different - it only does a retry if TURN server is not used on 1st attempt.
There was also another property called `retriedWithTurnServer` that was purely used by addMedia() internally so I've created a `addMediaData` object inside `Meeting` to store all "addMedia" related things in it.
I've also split the public addMedia() method into a protected …
=> fix: incorrect icePhase when joinWithMedia() fails on 1st attempt

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/calling/package.json, yarn.lock
We are rolling out Full-ICE support for Firefox. Currently we have low limitation on number of ICE Candidates. We will gather metrics to understand how many ICE Candidates we need, to adjust correctly new maximum number of ICE Candidates. To ensure none of them will be skipped.
This PR introduce changes which will result on submitting metrics on ICE Candidates.
Tested with JS-SDK Sample app Chrome 127, Firefox 113, 129
---
=> fix(plugin-meetings): send metrics on gathered ice candidates count

packages/@webex/internal-plugin-metrics/src/metrics.types.ts
=> feat(internal-plugin-metrics): add more verbs to taxonomy for behavioral metrics

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
Missing `clientSignallingProtocol` stat in media quality event
Fill `clientSignallingProtocol` at `meetingJoinInfo.clientSignallingProtocol` with value `WebRTC`
---
=> fix(plugin-meetings): clientSignallingProtocol stat

packages/@webex/plugin-meetings/src/locus-info/selfUtils.ts, packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/selfUtils.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-555818
Fixes a BEMS case defect where remote audio mute can get out of sync with local audio mute.
BEMS space: webexteams://im?space=c4706ce0-56e0-11ef-81df-a39e6dd40a42
Steps to recreate bug:
1. start a meeting as host, unmuted
2. uncheck "allow participants to unmute"
3. mute 
4. unmute
5. mute (problem: sdk's representation of server remote audio is still unmuted)
6. unmute (because sdk thinks remote is already unmuted, we do not try to change it)
The server remote audio is still muted (notice the muted icon in the participant list)
With the fix, the server remote audio is unmuted as expected.
First, I needed to revert a [fix from months ago](https://github.com/webex/webex-js-sdk/pull/3621). This fix was causing the locus diff update …
=> fix(audio-mute): fix sometimes out-of-sync remote audio mute

packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Sometimes TURN-TCP reachability completes succesfully, but then media fails to connect over TCP. Adding TURN-TCP to peer connection configuration, to verify if it will help in this scenario.
Modifying discovered TURN-TLS to work as bare TURN-TCP server.
Tested with sample app(Chrome,Edge,Firefox) and blocked UDP to force connections over TCP.
---
=> fix(plugin-meetings): add to peer connection bare turn tcp server

packages/calling/src/CallSettings/UcmBackendConnector.test.ts, packages/calling/src/CallSettings/UcmBackendConnector.ts, packages/calling/src/CallSettings/constants.ts, packages/calling/src/Contacts/ContactsClient.test.ts, packages/calling/src/common/Utils.test.ts, packages/calling/src/common/Utils.ts, packages/calling/src/common/constants.ts
CORS issues faced by the SCIM requests because we are directly contacting identity.webex.com instead of the API GW.
SCIM query will now use https://webexapis.com and https://integration.webexapis.com for resolution of users as this has been indicated as the correct manner by the SCIM team. 
1. Created a cloud contact on BTS and PROD environments
2. Deleted contact group in BTS
3. Checked Call Settings for user in PROD and BTS environments.
4. Tested incoming and outgoing call. Contact resolutions worked fine.
ZIP file attached with console logs and HAR from tests.
[SDK_CORS_SCIM_tests.zip](https://github.com/user-attachments/files/17002462/SDK_CORS_SCIM_tests.zip)
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md# …
=> fix(contacts): use webexapis.com url to avoid cors

packages/@webex/plugin-meetings/src/rtcMetrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts
When investigating join meeting failure cases where ICE connection was successful, but RTP packets seemed to be not getting through I saw a lot of webrtc dumps that were missing the stats, they only contained the log. It's because SDK uploads the dumps 5s after connection creation and WCME also calls getStats() 5s after connection creation, but it's just after the SDK timer, so the metrics that get uploaded don't have the result of the 1st getStats() call.
Changed SDK to do the first upload as soon as we get a first stats-report.
unit tests and manual run with the web app
---
=> fix(meetings): empty webrtc dumps when user closes the browser early

packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Orpheus team wants us to tell them if we are on an ipv4 or ipv6 network (or both) when we call the discovery/v1/clusters API. To know this we would need to gather local ICE candidates before making that call - that can take some time (few hundred milliseconds), so for now we will do this in parallel to making the API call just so that we can measure how long it takes and send the timings with reachability metrics.
- starting ip network detection when we do reachability, but not waiting for it to complete
- sending the information about how long it took in reachability metric
This means that now we'll be sending the `ipver` parameter to Locus when we're joining a meeting based on the results of ip network detection done during last reachability check. Previously we've just been always …
=> feat(meetings): do ip version detection in parallel with reachability

packages/@webex/internal-plugin-presence/src/presence.js, packages/@webex/internal-plugin-presence/test/integration/spec/presence.js, packages/@webex/internal-plugin-presence/test/unit/spec/presence.js, packages/@webex/plugin-presence/src/presence.ts, packages/@webex/plugin-presence/test/integration/spec/presence.ts, packages/@webex/plugin-presence/test/unit/spec/presence.ts
Webex user's status is not always being cleared correctly from Agent Desktop after a call ends, as a result of the `label` parameter not being filled in the request to the [Aphelia V1 API](https://backstage.corp.webex.com/catalog/default/api/apheleia-endpoint#/default/post_apheleia_api_v1_events). When the request is made without a `label`, the Aphelia backend is  unable to associate 2 events (the setting and clearing of "on a call" status) that can result in an agent's status getting "stuck" until the TTL expires
Filling the `label` parameter in the API request
* Checked request works as intended with Postman
* Added to integration test
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) …
=> feat(presence-plugin): pass label to aphelia API whilst setting status

packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
We've recently added information about timings for IP network version checks to "js_sdk_reachability_completed" metric, but reachability is triggered from various places, one of them being reconnection. We want to know the timings just from reachability that's called during webex.meetings.register() and not from reconnection.
added reachability trigger information to the "js_sdk_reachability_completed" metric
unit tests
---
=> fix(meetings): added reachability trigger to metrics

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/test-helper-mock-webex/src/index.js
Raised from a customer BEMS case:
When users have configured inactivity timeout in control hub for example for 30 mins, when they join a meeting, after 30 min they get logged out by the SDK and web app doesn't update the UI, so they remain in the meeting but cannot do any operations like mute/unmute/start recording (they just fail) and also Mercury connection is dropped, so they won't get any updates about the meeting.
Internal device plugin has the inactivity timer and it relies on meetingStarted/meetingEnded methods to be called when a user joins or leaves (or gets dropped from) a meeting to avoid being logged out while in a meeting. These methods were not being called from anywhere, so I've added calls to them in plugin-meetings.
This solution is not ideal as it won't work correctly if …
=> fix(meetings): webex.internal.device doesn't know when user is in a meeting

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Adding a private readonly variable (once set) meeting join time marker
Adding a private readonly variable (once set) meeting join time marker
Both manual and automated. future web client PR to come
---
=> feat(meetings): add meeting join time marker

packages/@webex/internal-plugin-mercury/src/config.js, packages/@webex/internal-plugin-mercury/src/index.js, packages/@webex/internal-plugin-mercury/src/mercury.js, packages/@webex/internal-plugin-mercury/src/socket/socket-base.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/internal-plugin-mercury/test/unit/spec/socket.js
webexteams://im?space=0f339300-7b90-11ef-a299-e5869c69951d
BEMS01793489
On logout, we are not properly deleting the registered device. This PR addresses this issue, whilst keeping backwards compatibility.
A new config option, `beforeLogoutOptionsCloseReason` is provided which defaults to the existing reason -> `done (forced)`.
A new logout function, used on logout which proxies into disconnect, using the provided reason code by consumer. if it is undefined, or already one of the existing reasons, it skips this flow, and uses the same disconnect as before (via proxy). If it is a new reason, i.e., `done (permanent)` this will get passed through all the way to the socket.close function. The socket close function, even with done (forced) was previously calling a reconnect, which caused the …
=> fix(mercury): fix logout mercury delete

docs/samples/browser-plugin-meetings/app.js, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
This PR is used to address the 403 Forbidden issues that the user had seen in the meetings widgets sample app. When a user clicks on the register button in the logs it shows a 403 forbidden error but the user can join the meeting which means these are unnecessary logs that should be avoided. So, we are fixing this issue first in the kitchen sink app so that the meetings widgets get fixed where the following changes are made to work fine so that users don't get the unnecessary logs again.
Whenever a user joins a meeting as a user/guest then we will ignore the 403 forbidden error (unnecessary logs) but this does not happen with the verified user. so for that, I used the people API to fetch the user details in this I found that the user is a type of **_"appuser"_** so based on this I …
=> fix(plugin-meetings): resolved guest issue forbidden error

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/prelogin-metrics-batcher.ts
... the update to the diagnostic event, ensuring that the `upgradeChannel` field is populated with the value `"gold"` for `buildType` set to `"prod"` (already populated in SDK). For other options, the string value remains the same as in `buildType.`
- Populate the `upgradeChannel` field with the value `"gold"` for buildType set to `"prod"`.
- Ensure that for other `buildType` options, the `upgradeChannel` string value remains the same as in `buildType`.
- Updated the unit test to reflect the changes.
- Manual testing with the sample app:
- MQR are generated with the new property:
=> feat: add `upgradeChannel` metric

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
This PR includes fix for the case with the ROAP issue described in [SPARK-559619](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-559619)
PR in media core: https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/279
Roap now contains `sendRetryStateError` handler for `settingRemoteAnswer` state interruption for `Offer/Offer Request` cases when `isOkInTransaction` header is passed for the answer 
- SDK manual testing case with the example from PR [SPARK-559619](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-559619)
- bug bush session with WCME team
---
=> fix: update media-core version with roap fix

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
When a user is accessing webex from a restricted region WDM is sending an error which gets marked as a client.login.failure result in CA.
These are expected failures and we should be marking them as expected.
I've added the WDM errors with codes 4404002 and 4404003 as an expected error when generating the error object for CA events.
The errors from WDM were taken from [here](https://sqbu-github.cisco.com/WebExSquared/wdm/blob/2405875ef0201358322f8fc31cd3f5ba04459284/server/src/main/java/com/cisco/wx2/wdm/server/WDMUtils.java)
Dashboard to see the current CA failures due to this error: https://wapgrafana-staging.webex.com/d/bacea9f0-52cc-42b3-b4f5-82e9985d4e0a/operation-denied-due-to-region-restriction?orgId=1&from=now-30d&to=now
Unit tests have been added
---
Make sure to have followed …
=> fix(internal-plugin-metrics): restricted region wdm error marked as expected

packages/calling/src/common/Utils.test.ts, packages/calling/src/common/Utils.ts, packages/calling/src/common/constants.ts
The BroadWorks API was failing due to an issue where the v2.0 version string was appearing twice in the endpoint URL. This was happening because some customers were configuring the XSI endpoint in the Partner Hub with /v2.0/ instead of the expected /v2.0. As a result, this duplication was causing the API calls to fail.
We have added an additional check inside the getXsiActionEndpoint function to handle this scenario:
If the xsiEndpoint contains /v2.0/, we slice it to remove the trailing / and avoid duplicating the version string in the URL.
This ensures that the URL is correctly formatted and prevents further issues with BroadWorks API calls.
This fix now accounts for both /v2.0 and /v2.0/, providing more flexibility in the endpoint configuration while resolving the API issue.
< DESCRIBE …
=> fix(voicemail): added /v2.0/ check for BWRKS xsiendipoint

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
We get various client login failures with UNKNOWN error, just passing serviceErrorCode, serviceErrorName in hope to get more debug in metrics
---
=> fix(internal-plugin-metrics): passing service errors for debugging

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
CA event validation failures, because of missing fields like correlationId, etc.
When meetings are deleted and removed from webex.meetings.meetingCollection, copy the bare minimum information about them like correlationId, locusUrl, etc to another collection `deletedMeetings` so that the information can be retrieved later by metrics plugin or anyone else that needs it.
unit tests
---
=> fix(meetings): ca event validation failures

packages/@webex/webex-core/src/index.js, packages/@webex/webex-core/src/interceptors/webex-tracking-id.js, packages/@webex/webex-core/src/webex-core.js
Currently the tracking id is fixed at the point of initialization of the sdk. In order to use the same trackingid for the same web session, it is necessary to make a few small changes to expose both the id itself and the sequence number.
---
=> feat(webex-core): expose tracking id

packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts
Passing through the table from the consuming app
param drilling
Manual link with web client
unit tests (originally missing)
---
=> fix(metrics): pass through table from new-metrics

.circleci/config.yml
Publishing of the latest v2.x versions to a separate tag on NPM. This tag is called `legacy`. This is to ensure that the `latest` tag which is on v3.x doesn't get affected by merges in the `master` branch
Change the config.yml command for npm publish.
Not applicable.
---
=> fix(publish): change publish to legacy tag instead of latest

packages/calling/src/CallingClient/registration/register.test.ts, packages/calling/src/CallingClient/registration/register.ts
Failover to secondary mobius server immediately after 4 keep alive failure for contact center flow.
Here we have introduced a new variable/flag to check we need to failover immediately or not. That flag gets set only when the flow is contact centre and keepalive is failing. It gets reset back when the immediate failover logic runs.
Able to failover to backup mobius server immediately after 4 keepalive failure.
**Note**: Please check the [HAR](https://jira-eng-gpk2.cisco.com/jira/secure/attachment/1324962/failover-after-keepalive-public-repo.har) file attached on the JIRA.
Tested on the samples page by blocking the primary server domain and after 4 keepalive failure registration switched to secondary server.
--- …
=> fix(calling): failover immediately after 4 keepalive failures for cc flow

packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/src/rtcMetrics/index.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/rtcMetrics/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/CallingClient/calling/call.ts
Adds RtcMetrics to the Calling package.
Calling SDK is now able to send the RTC Metrics.
**Screenshot**
**Note**: Please check the JIRA for [HAR](https://jira-eng-gpk2.cisco.com/jira/secure/attachment/1324588/calling-rtc-metrics.har) file.
Tested both Calling and Meeting stats being sent and attached the HAR files on the JIRA.
---
=> feat(calling): add rtcMetrics in the call
