Gruntfile.circle.js, Gruntfile.package.js, packages/example-phone/Gruntfile.js, packages/plugin-phone/Gruntfile.js, tasks/istanbul.js, tooling/circle-scripts/validate.sh
=> chore(tooling): limit PR builds to static analysis and unit tests

run.sh, tooling/test.sh
=> refactor(tooling): decrease default concurrency limit and make concurrency limit overridable

packages/spark-core/package.json, packages/spark-core/src/index.js, packages/spark-core/src/lib/batcher.js, packages/spark-core/src/plugins/credentials/index.js, packages/spark-core/test/unit/spec/lib/batcher.js
=> Implement Batcher base class

packages/common/src/events.js, packages/common/src/index.js, packages/plugin-encryption/.eslintrc.yml, packages/plugin-encryption/README.md, packages/plugin-encryption/package.json, packages/plugin-encryption/src/config.js, packages/plugin-encryption/src/encryption.js, packages/plugin-encryption/src/ensure-buffer.browser.js, packages/plugin-encryption/src/ensure-buffer.js, packages/plugin-encryption/src/index.js, packages/plugin-encryption/src/interceptor.js, packages/plugin-encryption/src/kms-batcher.js, packages/plugin-encryption/src/kms-error.js, packages/plugin-encryption/src/kms.js, packages/plugin-encryption/test/.eslintrc.yml, packages/plugin-encryption/test/index.js, packages/plugin-encryption/test/integration/spec/encryption.js, packages/plugin-encryption/test/integration/spec/kms.js, packages/test-helper-make-local-url/package.json, packages/test-helper-make-local-url/src/index.js
=> feat(plugin-encryption): implement plugin-encryption

packages/plugin-conversation/package.json, packages/plugin-conversation/src/conversation.js, packages/plugin-conversation/src/encrypter.js, packages/plugin-conversation/test/integration/spec/encryption.js, packages/plugin-conversation/test/integration/spec/verbs.js
=> convo 3: add/leave/update/updateKey

packages/plugin-conversation/package.json, packages/plugin-conversation/src/conversation.js, packages/plugin-conversation/src/encrypter.js, packages/plugin-conversation/test/integration/spec/encryption.js, packages/plugin-conversation/test/integration/spec/get.js, packages/plugin-conversation/test/integration/spec/verbs.js
=> convo 4: simple verbs

packages/plugin-logger/.eslintrc.yml, packages/plugin-logger/README.md, packages/plugin-logger/package.json, packages/plugin-logger/src/config.js, packages/plugin-logger/src/index.js, packages/plugin-logger/src/logger.js, packages/plugin-logger/test/.eslintrc.yml, packages/plugin-logger/test/index.js, packages/plugin-logger/test/unit/spec/logger.js
=> feat(plugin-logger): implement advanced logger

packages/plugin-feature/.eslintrc.yml, packages/plugin-feature/README.md, packages/plugin-feature/package.json, packages/plugin-feature/src/config.js, packages/plugin-feature/src/feature.js, packages/plugin-feature/src/index.js, packages/plugin-feature/test/.eslintrc.yml, packages/plugin-feature/test/index.js, packages/plugin-feature/test/integration/spec/feature.js, packages/plugin-feature/test/unit/spec/feature.js, test/unit/lib/mock-spark.js
fixes https://github.com/ciscospark/spark-js-sdk/issues/65
=> migrate legacy feature service to plugin-feature

packages/common/src/index.js, packages/common/src/one-flight.js, packages/common/src/while-in-flight.js, packages/common/test/unit/spec/while-in-flight.js, packages/plugin-conversation/src/conversation.js, packages/plugin-encryption/src/encryption.js, packages/plugin-user/src/user.js, packages/plugin-wdm/src/device/device.js, packages/spark-core/src/lib/storage/make-spark-store.js, packages/spark-core/test/unit/spec/lib/batcher.js
=> Credentials 1: Add whileInFlight and some minor fixes

packages/widget-chat/src/actions/conversation.js, packages/widget-chat/src/actions/user.js, packages/widget-chat/src/components/activity-list/index.js, packages/widget-chat/src/containers/chat-widget/index.js, packages/widget-chat/src/reducers/conversation.js, packages/widget-chat/src/reducers/user.js
Isolate each reducer's states into separate objects. Update references
to spark state. Remove unused method calls.
=> refactor(widget-chat): Remove unused references, change store to props

packages/plugin-conversation/src/conversation.js
Same PR #206 but for widget-dev branch
=> fix(plugin-conversation): Add support for options in one on one convo

packages/widget-chat/src/actions/conversation.js, packages/widget-chat/src/actions/user.js, packages/widget-chat/src/containers/chat-widget/index.js, packages/widget-chat/src/reducers/conversation.js, packages/widget-chat/src/reducers/user.js
- Fix bug where we're pulling current user multiple times
- Add mercury hook so that new messages are appended to conversation
- Change conversation pull to get latest 30 activities
=> feat(widget-chat): Add mercury hooks and fix multiple user pulls

packages/plugin-feature/src/feature.js, packages/plugin-feature/test/integration/spec/feature.js
Cisco requirement page: https://sqbu-github.cisco.com/WebExSquared/cloud-apps/wiki/Custom-Notifications---Feature-Toggle-Batch-API
=> Introduces feature batch API

packages/plugin-conversation/src/conversation.js, packages/plugin-mashups/.eslintrc.yml, packages/plugin-mashups/README.md, packages/plugin-mashups/package.json, packages/plugin-mashups/src/config.js, packages/plugin-mashups/src/index.js, packages/plugin-mashups/src/mashups.js, packages/plugin-mashups/test/.eslintrc.yml, packages/plugin-mashups/test/index.js, packages/plugin-mashups/test/integration/spec/mashups.js, packages/plugin-mashups/test/unit/spec/mashups.js
initial pull request for mashup plugin and a minor conversion plugin fix
=> initial commit for mashups

packages/widget-chat/src/actions/conversation.js, packages/widget-chat/src/components/activity-item-post/__snapshots__/index.test.js.snap, packages/widget-chat/src/components/activity-item-post/index.test.js, packages/widget-chat/src/components/activity-item-system-message/__snapshots__/index.test.js.snap, packages/widget-chat/src/components/activity-item-system-message/index.js, packages/widget-chat/src/components/activity-item-system-message/index.test.js, packages/widget-chat/src/components/activity-item-system-message/styles.css, packages/widget-chat/src/components/activity-item/__snapshots__/index.test.js.snap, packages/widget-chat/src/components/activity-item/index.js, packages/widget-chat/src/components/activity-item/index.test.js, packages/widget-chat/src/components/activity-list/index.js, packages/widget-chat/src/reducers/conversation.js
This will display a system message for activities that have been deleted upon initial load. It also will convert existing messages to a deleted message when an activity arrives via mercury.
=> feat(widget-chat): deleted message support in activity list

packages/test-helper-appid/.eslintrc.yml, packages/test-helper-appid/README.md, packages/test-helper-appid/package.json, packages/test-helper-appid/src/create-user.browser.js, packages/test-helper-appid/src/create-user.js, packages/test-helper-appid/src/index.js, packages/test-helper-appid/src/router.js, packages/test-helper-server/package.json, packages/test-helper-server/src/index.js
=> feat(test-helper-appid): add test helper for creating app id test users

packages/plugin-conversation/package.json, packages/plugin-conversation/src/share-activity.js
=> fix(plugin-conversation): switch to 'mime-types' module

packages/plugin-conversation/src/conversation.js, packages/plugin-wdm/src/device/device.js, packages/plugin-wdm/test/integration/spec/device.js, packages/plugin-wdm/test/unit/spec/policy.js
=> feat(plugin-wdm): add autologout policy support

packages/plugin-conversation/src/conversation.js, packages/plugin-conversation/src/decryption-transforms.js, packages/plugin-conversation/src/encryption-transforms.js, packages/plugin-conversation/src/process-image.browser.js, packages/plugin-conversation/src/process-image.js, packages/plugin-conversation/src/share-activity.js, packages/plugin-conversation/test/integration/spec/verbs.js
=> feat(plugin-conversation): add room avatar support

packages/plugin-conversation/test/integration/spec/verbs.js
For @ianwremmel to checkout. Test fails when deleting a share.
=> test(plugin-conversation): Add test for deleting share from conversation

packages/widget-message-meet/Gruntfile.js, packages/widget-message-meet/README-USAGE.md, packages/widget-message-meet/package.json, packages/widget-message-meet/src/app.js, packages/widget-message-meet/src/components/list-separator/index.js, packages/widget-message-meet/src/containers/message-meet-widget/__snapshots__/index.test.js.snap, packages/widget-message-meet/src/containers/message-meet-widget/index.js, packages/widget-message-meet/src/root.js
To use the new code, you'll need to change the `USERID` environment var in `.env` to `TO_USER_EMAIL`.
=> feat(widget-message-meet): Update widget data api

packages/plugin-credentials/src/credentials/common.js, packages/plugin-credentials/src/token.js, packages/plugin-credentials/test/unit/spec/credentials.js, packages/plugin-encryption/package.json, packages/plugin-encryption/src/index.js, packages/plugin-encryption/src/kms.js, packages/plugin-encryption/test/integration/spec/encryption.js, packages/plugin-encryption/test/integration/spec/kms.js, packages/plugin-user/test/integration/spec/user.js, packages/recipe-private-web-client/.eslintrc.yml, packages/recipe-private-web-client/Gruntfile.js, packages/recipe-private-web-client/README.md, packages/recipe-private-web-client/package.json, packages/recipe-private-web-client/src/config.js, packages/recipe-private-web-client/src/index.js, packages/recipe-private-web-client/test/.eslintrc.yml, packages/recipe-private-web-client/test/index.js, packages/spark-core/src/config.js, packages/spark-core/src/spark-core.js
=> Add npm linkable packages

packages/plugin-conversation/src/index.js, packages/plugin-conversation/test/integration/spec/verbs.js
=> fix(plugin-conversation): decrypt inbound payloads before normalizing

packages/plugin-credentials/src/credentials/common.js, packages/spark-core/src/plugins/credentials/credentials/common.js, src/client/credentials/credentials.shim.js
this updates the CI login screen with the spark theme
=> feature(CI-page): use cisService instead of service

packages/plugin-credentials/src/credentials/browser.js, packages/plugin-wdm/src/device/device.js, packages/spark-core/src/lib/storage/make-spark-store.js, packages/spark-core/src/lib/storage/memory-store-adapter.js, packages/spark-core/src/spark-core.js, packages/spark-core/test/integration/spec/spark-core.js, packages/storage-adapter-spec/src/index.js, src/client/credentials/credentials.shim.js, src/client/device/device.js, src/spark-core.js
fixes https://github.com/ciscospark/spark-js-sdk/issues/220
=> fix(logout): fix spark.logout() to fail gracefully

Jenkinsfile
Uncommented stage to kick CDN job spark-js-sdk--publish-chat-widget-s3
=> Jenkins update - Uncomment CDN Stage

packages/plugin-board/test/unit/spec/realtime.js, test/unit/spec/services/board/realtime.js
=> fix(plugin-board): add return statement to realtime buffer event test

docs/_includes/header.html, docs/_layouts/example.html, docs/_layouts/page.html, docs/index.html
* Change navigation bar and items
* Update main page with clarification for what content is available and link to GitHub repository
=> Docs: Layout Update

Jenkinsfile, packages/plugin-wdm/src/device/device.js, packages/plugin-wdm/test/integration/spec/device.js
=> fix(plugin-wdm): ensure missing `deviceType` does not cause an iOS URL

packages/plugin-board/src/board.js, packages/plugin-board/test/integration/spec/board.js, packages/plugin-board/test/unit/spec/board.js, src/client/services/board/persistence/persistence.js, test/integration/spec/services/board/actions.js, test/unit/spec/services/board/persistence.js
Server does not support delete single content by id anymore
=> refactor(board): remove deleteContent as its API is deprecating

.babelrc, package.json, packages/common/src/exception.js, packages/common/src/index.js, packages/common/test/unit/spec/exception.js, packages/http-core/package.json, packages/http-core/src/http-error-subtypes.js, packages/http-core/src/http-error.js, packages/plugin-encryption/package.json, packages/plugin-encryption/src/kms-error.js, packages/plugin-mercury/package.json, packages/plugin-mercury/src/errors.js, packages/spark-core/package.json, packages/spark-core/src/lib/spark-http-error.js, packages/spark-core/src/lib/storage/errors.js, packages/spark-core/src/plugins/credentials/grant-errors.js
=> Remove extend-error in favor of subclasses

packages/plugin-phone/src/call.js
This fixes issues where you cannot operate on the call once it's been answered.
=> fix(plugin-phone): Fix video/audio state issue on join

packages/plugin-user/src/user.js, packages/plugin-user/test/integration/spec/user.js
To fix failing atlas integration tests
@ianwremmel please review!
=> Added the user agent to user plugin tests against the atlas activations endpoint

Jenkinsfile, docker/builder/Dockerfile, docs/_posts/guides/9999-02-01-plugin-development.md, package.json, packages/http-core/src/request/index.js, packages/plugin-user/src/user.js, packages/test-helper-test-users/package.json, packages/test-helper-test-users/src/index.js, run.sh, src/client/client/client-base.js, test/integration/lib/landingparty.js, test/integration/spec/client/credentials.js, test/integration/spec/services/encryption/multi-org.js, tooling/publish.sh
=> fix(http-core): add default user agent in node environments

deps.js
The point of this PR was to add envify to all packages, but I ended up cleaning up deps.js so it's easier to see how everything fits together.
=> chore(tooling): make deps.js readble; add browserify transform handling

packages/node_modules/@ciscospark/plugin-board/test/integration/spec/board.js, test/integration/spec/services/board/actions.js
=> test(plugin-board): only check for successful ping

packages/node_modules/@ciscospark/plugin-board/src/board.js, packages/node_modules/@ciscospark/plugin-board/test/unit/spec/board.js
Since kms server adds the fix to no longer add the board creator author to board KRO, this code to remove board creator auth should be removed :)
=> refactor(plugin-board): remove check for board creator auth in create

packages/node_modules/@ciscospark/plugin-phone/.eslintrc.yml, packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/media-state-controls.js, tooling/build.js
This removes a race condition in toggleSendingAudio/toggleSendingVideo. A future PR will make this more efficient
=> fix(@ciscospark/plugin-phone): address race in toggleSending

packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/src/web-rtc-media.js
Smaller than it looks, the first commit just alphabetizes call.js.
=> Fix async media

packages/node_modules/@ciscospark/plugin-people/src/people.js, packages/node_modules/@ciscospark/plugin-people/test/integration/spec/people.js, packages/node_modules/@ciscospark/plugin-phone/browsers.js, packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/src/index.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/call.js
For a future PR:
- sip address
- phone number
- better event model
sipUrl and phone number are missing for the moment because I can't create test users that produce those properties (nor do I know where in the DTO they would appear)
=> Call Memberships v0

CONTRIBUTING.md, package.json
- add 'People' to the API Reference
- add new Pull Request instructions
=> Documentation Updates

packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/space.js
Add retry to create machine account
=> test(@ciscospark/internal-plugin-lyra): retry create machine account

packages/node_modules/@ciscospark/common/src/one-flight.js, packages/node_modules/@ciscospark/common/test/unit/spec/one-flight.js
Fixes plugin support and oneFlight
=> Fixes plugin support and oneFlight

package.json
Revert the changes made in 4ffc2954f539e0cb2dd8579fc7763bde8ae0571a. Fixes #642.
=> Revert API Docs Change

packages/node_modules/@ciscospark/spark-core/src/index.js, packages/node_modules/@ciscospark/spark-core/src/interceptors/spark-user-agent.js, packages/node_modules/@ciscospark/spark-core/src/spark-core.js, packages/node_modules/@ciscospark/spark-core/test/integration/spec/spark-core.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/interceptors/spark-user-agent.js, packages/node_modules/ciscospark/src/ciscospark.js, packages/node_modules/ciscospark/test/integration/spec/request.js
=> feat(@ciscospark/spark-core): add spark-user-agent header

packages/node_modules/@ciscospark/common/src/capped-debounce.js, packages/node_modules/@ciscospark/common/test/unit/spec/capped-debounce.js, packages/node_modules/@ciscospark/spark-core/src/lib/batcher.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/lib/batcher.js
Two main features in the two different commits. I've tested all of the plugins that are using batcher and there were no changes needed in their tests.
=> Debounce batcher maxCalls

packages/node_modules/@ciscospark/plugin-people/src/config.js, packages/node_modules/@ciscospark/plugin-people/src/people-batcher.js, packages/node_modules/@ciscospark/plugin-people/src/people.js, packages/node_modules/@ciscospark/plugin-people/test/integration/spec/people.js
Includes changes from #653 
Limit is set at 10 people per request due to hydra limitation
=> Add bulk support to people.list()

packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/call.js
=> fix(@cisospark/plugin-phone): allow call#answer on self initiated calls

packages/node_modules/@ciscospark/plugin-people/src/people.js, packages/node_modules/@ciscospark/plugin-people/test/integration/spec/people.js
=> feat(@ciscospark/plugin-people): add support for people.get('me')

packages/node_modules/@ciscospark/helper-html/src/html.shim.js, packages/node_modules/@ciscospark/helper-html/test/unit/spec/html.js
=> fix(helper-html): make the javascript protocol filter case insensitive

packages/node_modules/ciscospark/src/ciscospark.js
This should reduce bundle size by 500KB
=> fix(ciscospark): do not load the full lodash library

packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js
Solves *part* of the bug that will result from delta events, but not all of it.
=> fix(@ciscospark/plugin-phone): rely on server info to detect calls

documentation/config.yml, package.json, packages/node_modules/@ciscospark/plugin-people/src/people-batcher.js, packages/node_modules/@ciscospark/plugin-phone/src/call-membership.js, packages/node_modules/@ciscospark/plugin-phone/src/call-memberships.js, packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/src/calls.js, packages/node_modules/@ciscospark/plugin-phone/src/config.js, packages/node_modules/@ciscospark/plugin-phone/src/index.js, packages/node_modules/@ciscospark/plugin-phone/src/phone.js, packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/media-state-controls.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/multi-party.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/phone.js, packages/node_modules/@ciscospark/plugin-phone/test/lib/locus.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/phone.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/replacement.js
=> Group Calling

documentation/config.yml, package.json, packages/node_modules/@ciscospark/internal-plugin-calendar/test/integration/spec/calendar.js, packages/node_modules/@ciscospark/internal-plugin-locus/src/index.js, packages/node_modules/@ciscospark/internal-plugin-locus/src/locus.js, packages/node_modules/@ciscospark/internal-plugin-locus/test/unit/lib/BasicSeqCmp.json, packages/node_modules/@ciscospark/internal-plugin-locus/test/unit/lib/SeqCmp.json, packages/node_modules/@ciscospark/internal-plugin-locus/test/unit/spec/locus.js, packages/node_modules/@ciscospark/plugin-people/src/people-batcher.js, packages/node_modules/@ciscospark/plugin-phone/package.json, packages/node_modules/@ciscospark/plugin-phone/src/call-membership.js, packages/node_modules/@ciscospark/plugin-phone/src/call-memberships.js, packages/node_modules/@ciscospark/plugin-phone/src/call.js, packages/node_modules/@ciscospark/plugin-phone/src/calls.js, packages/node_modules/@ciscospark/plugin-phone/src/config.js, packages/node_modules/@ciscospark/plugin-phone/src/index.js, packages/node_modules/@ciscospark/plugin-phone/src/phone.js, packages/node_modules/@ciscospark/plugin-phone/src/state-parsers.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/lib/cmr.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/delta.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/dtmf.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/media-state-controls.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/multi-party.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/spec/phone.js, packages/node_modules/@ciscospark/plugin-phone/test/lib/locus.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/call.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/phone.js, packages/node_modules/@ciscospark/plugin-phone/test/unit/spec/replacement.js, packages/node_modules/@ciscospark/test-helper-mocha/src/index.js, packages/node_modules/ciscospark/package.json
Some of the currently approved call changes do not seem to play nicely together. This PR is where I plan to do the work to coordinate changes (with potential rebases) so that I do not need to keep all those PRs in sync.
Closes #696
Closes #698
Closes #699
Closes #692
Closes #700
Closes #701
=> Consolidated Calling Changes

packages/node_modules/@ciscospark/internal-plugin-encryption/src/kms.js
change unset to delete in weakmap to fix fatal error in node
=> fix(@ciscospark/i-p-encryption): change unset to delete

packages/node_modules/@ciscospark/internal-plugin-board/src/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/board.js, packages/node_modules/@ciscospark/internal-plugin-board/test/unit/spec/board.js
Mainly remove the link between a whiteboard and a spark space.
=> feat(@ciscospark/i-p-board): allow delete channel from a spark space

documentation/ciscospark.md, tooling/lib/updated.js
- correct typos
- change acronym capitalization
- update URLs
=> Correct Typos in API Reference

packages/node_modules/@ciscospark/internal-plugin-encryption/src/kms.js, packages/node_modules/@ciscospark/internal-plugin-encryption/test/integration/spec/kms.js
need to get authorization list of the resource, so we can authorize user to the resource if the user is not authorized, also only de-authorize the user that is authorized.
=> feat(@ciscospark/i-p-encryption): get auth list of the resource

.npmrc, packages/node_modules/@ciscospark/internal-plugin-search/test/integration/spec/search.js
- includes the removal of package-lock.json
- stops generating the html coverage report because it's kinda flaky
- change search bot test to use /applications
=> pipeline stability fixes

packages/node_modules/@ciscospark/internal-plugin-lyra/src/lyra.js, packages/node_modules/@ciscospark/internal-plugin-lyra/src/space.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/unit/spec/lyra.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/unit/spec/space.js, packages/node_modules/@ciscospark/recipe-private-web-client/src/index.js
=> feat(@ciscospark/i-p-lyra): allow sending proximity token

packages/node_modules/@ciscospark/internal-plugin-calendar/src/index.js, packages/node_modules/@ciscospark/internal-plugin-calendar/test/integration/spec/calendar.js
decrypt more fields for calendar meeting
=> fix(internal-plugin-calendar): Decrypt webexUrl

packages/node_modules/@ciscospark/internal-plugin-mercury/test/integration/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/device.js
=> Rebase Hostmap Refresh

packages/node_modules/@ciscospark/internal-plugin-mercury/src/index.js, packages/node_modules/@ciscospark/internal-plugin-mercury/src/mercury.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/unit/spec/mercury-events.js, packages/node_modules/@ciscospark/internal-plugin-mercury/test/unit/spec/mercury.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/service-model.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/service-collection.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/spec/service-model.js
Add metrics to track when a url has failed
=> High availability metrics

packages/node_modules/@ciscospark/spark-core/src/lib/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js
the forEach here won't remove all tokens due to this.userTokens.models
being modified during forEach, replacing with the while loop to remove
all the tokens
=> fix(@ciscospark/spark-core): use while loop to remove token instead

netlify.toml
Fixes [SSDK-1682](https://voxeolabs.atlassian.net/browse/SSDK-1682)
=> fix(samples): build samples with correct NODE_ENV

packages/node_modules/@ciscospark/internal-plugin-conversation/src/process-image.browser.js
This will fix the logic in computing the dimensions of an image thumbnail. This is in response to a BEMS case that got opened again our client.
I tested it manually.
* SDK Version
* NPM Version
=> fix(@ciscospark/plugin-conversation): correct process image aspect ratio

packages/node_modules/@ciscospark/recipe-private-web-client/src/config.js, packages/node_modules/@ciscospark/storage-adapter-session-storage/README.md, packages/node_modules/@ciscospark/storage-adapter-session-storage/package.json, packages/node_modules/@ciscospark/storage-adapter-session-storage/src/index.js, packages/node_modules/@ciscospark/storage-adapter-session-storage/test/unit/spec/storage-adapter-session-storage.js
This adds a session storage adapter which is _very_ similar to the existing local storage adapter.
npm test -- --package @ciscospark/storage-adapter-session-storage
=> feat(storage): add sessionStorage adapter

Jenkinsfile
Update the jenkinsfile to use the machine account for github when doing merges.
=> chore(tooling): update github sshagent

.snyk, package.json
The following vulnerabilities are fixed with a Snyk patch:
- https://snyk.io/vuln/npm:qs:20140806-1
Trying this security patching tool. In this case, it patched the qs files locally.
**Let me know how you feel about this approach.**
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-18907
=> Fix qs vulnerability

package.json
Upgrade webpack to fix samples. 
Fixes #834 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-21619
=> Fix samples

packages/node_modules/@ciscospark/jsdoctrinetest/README.md, packages/node_modules/@webex/jsdoctrinetest/package.json
Update README with keywords and "deprecate" old README.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-21321
=> docs(jsdoctrinetest): update README with keywords

BUILD-ISSUES.md, CONTRIBUTING.md, SCRIPTS.md
Updated installation and testing instructions for contributors. Added a `BUILD-ISSUES.md` file to reference and more information on setting up SauceLabs to run the SDK tests. 
- This change requires a documentation update
Tests are not required because these are only documentation changes.
=> Update Install & Test Instructions

tooling/commands/check-testable.js, tooling/lib/updated.js
A slight bug in our tooling stack improperly ran our full test suite when a documentation only change happens. This fixes the bug.
=> Update check testable

packages/node_modules/@ciscospark/internal-plugin-support/src/support.js
Adds correlationId to whitelist of values passed in logs metadata.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-5404
`npm test -- --package @ciscospark/internal-plugin-support`
=> fix(internal-plugin-support): add correlationId to logs metadata

packages/node_modules/@ciscospark/http-core/src/interceptors/http-status.js, packages/node_modules/@ciscospark/spark-core/src/config.js, packages/node_modules/@ciscospark/spark-core/src/interceptors/redirect.js
Support Web Client Sharding (307 redirect)
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-18307
Verified all tests passed for spark-core and http-core packages locally.
=> feat(spark-core): handle locus URL redirects

wdio.conf.js
Using some of the changes we've made to stabilize the wdio tests on the widgets tests. 
* Manually set selenium version to one compatible with sauce
* The `browser.logTypes();` command was failing on recent versions of firefox and not displaying errors properly, so I added a try/catch for when the command is not available.
- [] I have added tests that prove my fix is effective or that my feature works
=> feat(tooling): attempt to stabilize wdio sample tests

packages/node_modules/samples/browser-auth-implicit/test/wdio/spec/implicit-grant-authentication.js, packages/node_modules/samples/browser-auth-jwt/test/wdio/spec/jwt-authentication.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call-with-mute/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/normal-dialing.js, wdio.conf.js
Instead of using webdriver's [reload](http://webdriver.io/api/utility/reload.html) command between tests, simply use [refresh](http://webdriver.io/api/protocol/refresh.html) instead. This reduces the amount of time and number of sessions used by testing the sample applications.
=> test(samples): replace reload() with refresh()

README.md
Updates the sample brew install script for dependencies to the correct package names.
=> docs(readme): add correct brew install command

packages/node_modules/@ciscospark/internal-plugin-conversation/src/decryption-transforms.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js
This adds support for decrypting recording activities from conversation.
I added some initial unit tests for the decryption transforms @mattnorris. @adamweeks, and @bzang. I only added tests for the two new ones I added. Let me know what you think.
=> feat(i-p-c): add decryption transforms for recordings

packages/node_modules/@ciscospark/internal-plugin-lyra/src/space.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/space.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/unit/spec/space.js
Fixes issues with using Lyra service for manually pairing and then leaving the aux devices.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-7498
* SDK Version
* NPM Version
=> fix(i-p-lyra): manually pair and leave device

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/package.json, packages/node_modules/@webex/plugin-meetings/sample/app.js, packages/node_modules/@webex/plugin-meetings/sample/index.html, packages/node_modules/@webex/plugin-meetings/src/ciscospark.js, packages/node_modules/@webex/plugin-meetings/src/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings.js, webpack/webpack.config.base.js, webpack/webpack.config.dev.js, webpack/webpack.config.js
Rebased and addressed comments on Bernie's PR, #939
=> Create initial meetings plugin scaffolding

package-lock.json
Patch security vulnerability.  
Fixes https://nodesecurity.io/advisories/118
=> chore(security): fix vulnerability

packages/node_modules/@webex/plugin-meetings/api.md
=> Add plugin-meetings docs

packages/node_modules/samples/browser-single-party-call/app.js, packages/node_modules/samples/browser-single-party-call/index.html
Added a sample of how to set browser constraints to the single party calling sample app.,
=> feat(samples): add constraints example to single party

packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/index.html
Adds the remote mute state to the state table.
=> feat(samples): add remote mute state display

packages/node_modules/@ciscospark/http-core/test/unit/spec/interceptors/http-status.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/interceptors/redirect.js
Added tests to ensure functioning of locus redirects
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-31776
* SDK Version
* NPM Version
=> test(http-core): ensures functioning of locus redirects

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Create initial meeting module
Fixes [#3428](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-34284)
=> WIP - Create initial meeting module

packages/node_modules/@ciscospark/internal-plugin-lyra/src/space.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/device.js, packages/node_modules/@ciscospark/internal-plugin-lyra/test/integration/spec/space.js
bind/unbind a Space on a board
Fixes#: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-39513
* SDK Version
* NPM Version
=> fix(i-p-lyra): bind/unbind a webex board after pairing

.gitignore, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/sharing-mercury.js, packages/node_modules/@ciscospark/plugin-authorization-browser-first-party/test/automation/spec/authorization-code-grant.js, packages/node_modules/@ciscospark/plugin-authorization-browser/test/automation/spec/authorization-code-grant.js, packages/node_modules/@ciscospark/plugin-authorization-browser/test/automation/spec/implicit-grant.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/interceptors/rate-limit.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/spark-core.js, test.py
- Some tests fail inconsistently. Skip these tests to create a stable baseline to [investigate](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-42359). 
- `npm test` is not as helpful as it could be. The test suite fails when it encounters one error. This script tests each SDK package in production and integration and writes those results to CSV for comparison. 
Fixes N/A
```bash
python test.py
```
=> Update tests to create baseline

package-lock.json, packages/node_modules/@ciscospark/internal-plugin-board/test/integration/spec/sharing-mercury.js, packages/node_modules/@ciscospark/plugin-phone/test/integration/lib/cmr.js, packages/node_modules/@webex/bin-sauce-connect/src/start.js
Add "whistler" CMR support for integration. 
**Note:** This does not yet work in integration, but is prepping the client for when it does work.
Fixes N/A
```
npm test -- --package @ciscospark/plugin-phone
```
=> Add CMR integration support

.vscode/launch.json, packages/node_modules/@webex/plugin-meetings/sample/app.js, packages/node_modules/@webex/plugin-meetings/sample/index.html, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-adapter.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-interface.js
=> rename a few methods

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-adapter.js
=> fix(media): minor code cleanup

packages/node_modules/@webex/plugin-meetings/src/roap/roap-adapter.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-handler.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-interface.js
=> minor ROAP module clean up

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
=> fix(media): make calls work after merge for andrews change

package.json, webpack/webpack.config.samples.js
=> serve samples from root

package-lock.json, packages/node_modules/@ciscospark/plugin-phone/test/integration/lib/cmr.js
Fix CMR ("Whistler") service for BTS integration tests. 🎉
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-43568
`.env` should be updated with the following URLs: 
```
ACL_SERVICE_URL="https://acl-intb.ciscospark.com/acl/api/v1"
ATLAS_SERVICE_URL="https://atlas-intb.ciscospark.com/admin/api/v1"
CONVERSATION_SERVICE="https://conversation-intb.ciscospark.com/conversation/api/v1"
ENCRYPTION_SERVICE_URL="https://encryption-intb.ciscospark.com/encryption/api/v1"
IDBROKER_BASE_URL="https://idbrokerbts.webex.com"
IDENTITY_BASE_URL="https://identitybts.webex.com"
WDM_SERVICE_URL="https://wdm-intb.ciscospark.com/wdm/api/v1"
WHISTLER_API_SERVICE_URL="https://whistler.onint.ciscospark.com/api/v1"
```
Then run: 
```sh
npm test -- --package …
```
=> Fix Whistler for BTS

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-handler.js, packages/node_modules/@webex/plugin-meetings/src/roap/roap-interface.js
=> fix(meeting): update constants and dependency

packages/node_modules/@webex/plugin-meetings/src/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/samples/browser-meetings/app.js
=> emit events for media establishment

README.md, packages/node_modules/ciscospark/README.md
The readme on the ciscospark package still shows the outdated readme.
This PR also updates it and fixes an issue that was reported to us about one of the examples being incorrect 
Fixes #1013
=> Update the readme for the ciscospark package on npm

packages/node_modules/@ciscospark/internal-plugin-wdm/src/device/device.js, packages/node_modules/@ciscospark/internal-plugin-wdm/test/unit/lib/device-fixture.json
Adds a couple of missing props from the device registration
* SDK Version
* NPM Version
=> fix(wdm): update device with new props

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/request.js
=> fix(deps): remove bluebird dep

packages/node_modules/@webex/plugin-meetings/src/meeting-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/personal-meeting-room/index.js, packages/node_modules/@webex/plugin-meetings/src/stats/aggregator.js, packages/node_modules/@webex/plugin-meetings/src/stats/history.js, packages/node_modules/@webex/plugin-meetings/src/stats/interval.js, packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
=> Pmr phase i

Jenkinsfile, package.json, rollup.config.js
Provide the correct version number when generating the iife script and have been ignored when CI runs the linter through it, as it was causing Jenkins jobs to fail during static analysis.
Fixes # (not reported)
=> Add correct version number to script and correctly ignore when linting

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/ciscospark.js, packages/node_modules/@webex/plugin-meetings/sample/app.js, packages/node_modules/@webex/plugin-meetings/sample/device.js, packages/node_modules/@webex/plugin-meetings/sample/index.html, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/state.js, packages/node_modules/@webex/plugin-meetings/src/roap/util.js
Meeting plugin can share and receive share.  
Join method currently only joins the meeting . addMedia function adds the actual media to the meeting 
* SDK Version
* NPM Version
=> Wireless screen share

packages/node_modules/@webex/plugin-meetings/internal-README.md
Update sample documentation for developers and testers to clarify when/how to run the `plugin-meetings` sample. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-53904
=> Update sample documentation for developers and testers

packages/node_modules/@ciscospark/media-engine-webrtc/src/engine.js
Explicitly set "Plan B" for SDP. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-58995
=> Fix mute/unmute bug in Chrome 72

packages/node_modules/@webex/plugin-meetings/sample/app.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/members/collection.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/util.js
=> fix(plugin-meetings): revert back to a promise

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, sauce.py, test.py
Fixed issue while cleanup
* SDK Version
* NPM Version
=> fix:  clean up and test fixes

package.json, packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery-error.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/report-generator.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/report-request.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/activities.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/content.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/report-generator.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/report.js
Merging latest changes for the discovery plugin, including:
- Multiple report file download and size restrictions
- Whiteboard content download and decryption
- Custom error for multiple email validation
- Content Summary retrieval by space (with caching)
- Fixes for missing EML fields
- Removal of unused code/properties
Existing unit tests have been updated or added to, and are all passing
=> Merging latest changes for the discovery plugin

browsers-ng.js, browsers.js
Remove IE11 tests and old, unused browser tests. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-64534
=> Remove incompatible & unused browser tests

documentation/config.yml, package.json, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Add Meetings documentation to the GitHub API docs. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-62552
* SDK Version
* NPM Version
=> Add Meetings documentation

packages/node_modules/@ciscospark/common/src/constants.js, packages/node_modules/@ciscospark/common/src/index.js, packages/node_modules/@ciscospark/common/src/uuid-utils.js, packages/node_modules/@ciscospark/plugin-messages/src/messages.js, packages/node_modules/@ciscospark/plugin-messages/test/integration/spec/messages.js
Add file attachments to Mercury messages. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-66906
=> Add file attachments to Mercury messages

packages/node_modules/@ciscospark/internal-plugin-conversation/src/conversation.js, packages/node_modules/@ciscospark/internal-plugin-conversation/test/integration/spec/share.js, packages/node_modules/@ciscospark/plugin-messages/src/messages.js
support `activityType` and `parentActivityId` when posting activities.
Fixes #1133 
* SDK Version
* NPM Version
=> feat(internal-conversation): support posting threading activities

BUILD-ISSUES.md, CONTRIBUTING.md, packages/node_modules/@ciscospark/plugin-memberships/src/notes-on-moderator-status.txt
Added details about install dependencies node-gyp and python 2.7 in CONTRIBUTING.md.  Updated BUILD-ISSUES.md to just point to the build section in CONTRIBUTING.md to avoid having (inconsistent) data in two places
Readme files only
None
=> docs(readme): added more build dependency info

packages/node_modules/@ciscospark/spark-core/test/unit/spec/credentials/credentials.js, packages/node_modules/@ciscospark/spark-core/test/unit/spec/interceptors/auth.js
Move lingering downscope error messages to `trace` to clean up the console. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-71525
=> Remove downscope error messages

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js
Paging the getReports API. Fixing transform bug/edge case.
=> Latest ediscovery changes

packages/node_modules/@webex/internal-plugin-presence/src/presence.js, packages/node_modules/@webex/internal-plugin-presence/test/integration/spec/presence.js
Add ability to enable & disable presence and a convenience method to see its state. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-53219
=> Add ability to enable & disable presence

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
Reflect server changes.
When posting an activity, we will add `parent` object in the `activity` object.
* SDK Version
* NPM Version
=> feat(internal-plugin-conversation): reflect thread server change

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/encryption.js
- Added cardAction Activity in spark-internal-conversation
- Edited existing test to use verb cardAction Activity 
* SDK Version
* NPM Version
@mattnorris
=> feat(internal-plugin-conversation): support cardAction Activity

README.md
- Provides access to the code and main page of samples so that they don't get out of sync. 
- Provides a link to the hosted samples for reference. 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-74170
=> docs(readme): simplify samples links

packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js
Provide additional logs during an error
- [] I have added tests that prove my fix is effective or that my feature works
=> fix(ediscovery): enhance logs for errors

packages/node_modules/@webex/internal-plugin-ediscovery/src/index.js
Adding error handling for case where space has no participants (covered for full report but not report summary)
No point decrypting space name if participants is empty, and logging will help us identify when this case occurs
No new tests for this specific case
=> Improve report summary logging

packages/node_modules/@webex/internal-plugin-support/src/support.js, packages/node_modules/@webex/webex-core/src/webex-core.js
=> fix(uploads): ensure toggles are respected

packages/node_modules/@webex/plugin-meetings/UPGRADING.md
Added phone to meetings upgrade guide.
Documentation
=> docs(meetings): add upgrade guide

packages/node_modules/@webex/plugin-memberships/README.md, packages/node_modules/@webex/plugin-memberships/src/memberships.js, packages/node_modules/@webex/plugin-messages/README.md, packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-rooms/README.md, packages/node_modules/@webex/plugin-rooms/src/rooms.js
Update the JSDOC comments to include the scope requirements
for plugin-memberships, plugin-meetings, and plugin-rooms listen() methods.
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-81065
=> docs: update scope requirement for listen methods

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Make sure the resolution is 720p for video all the time 
* SDK Version
* NPM Version
=> set default resolution for camera

packages/node_modules/@webex/internal-plugin-avatar/src/avatar.js
=> feat(internal-plugin-avatar): update deprecated apis

packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Removed extra logs from the meeting plugin.
=> fix(meeting): removed console logs

packages/node_modules/@webex/plugin-meetings/src/media/index.js
Fix to change the media device 
* SDK Version
* NPM Version
=> fix: change media device

packages/node_modules/@webex/internal-plugin-feature/src/feature.js, packages/node_modules/@webex/internal-plugin-feature/test/integration/spec/feature.js
=> fix(i-p-feature): remove connecting to mercury in listen

packages/node_modules/@webex/plugin-meetings/UPGRADING.md, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/webex/test/integration/spec/commonjs.js
Some issues came up during samples conversion with the meetings plugin that should be resolved by this PR. 
Fixes # SPARK-84344
=> Meetings plugin various fixes

tooling/commands/ci.js
reenable cobertura and lcov for unit testing on circleci
* SDK Version
* NPM Version
=> reenable cobertura and lcov for unit testing on circleci

package-lock.json, package.json, packages/node_modules/@webex/internal-plugin-board/test/unit/spec/encryption.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury-events.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/socket.js, packages/node_modules/@webex/internal-plugin-metrics/test/unit/spec/metrics.js, packages/node_modules/@webex/internal-plugin-wdm/test/unit/spec/policy.js, packages/node_modules/@webex/plugin-logger/test/unit/spec/logger.js
Update sinon to v7 and fix any breaking changes.
sinon v4 (what we're on now) -> v5 deprecated .reset() for .resetHistory()
Also `sinon.match` was not used properly and caused an error, so replace with `assert.match`
* SDK Version
* NPM Version
=> refactor(sinon): update sinon to v7 and fix breaking changes

packages/node_modules/@webex/webex-core/src/interceptors/user-agent.js, packages/node_modules/@webex/webex-core/test/unit/spec/interceptors/user-agent.js
Bugfix for user-agent setting in browser.
=> fix(webex-core): do not set custom user-agent in browser

packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-call-with-screenshare/index.html, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js
Remote users were unable to screen share. Also adds a bit better screen share event handling and styling.
Fixes # (issue) Spark-86608
Added video stream grid:
Samples tests for screenshare have been updated and are passing.
=> Screenshare Sample Fixes

package.json
Currently, npm run clean does nothing. Fix this by updating the syntax
used by rimraf.
Fixes # SPARK-87905
=> fix(npm): fix clean script

packages/node_modules/@webex/common/src/uuid-utils.js, packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@webex/internal-plugin-team/src/team.js, packages/node_modules/@webex/internal-plugin-team/test/unit/spec/team.js, packages/node_modules/@webex/plugin-memberships/src/memberships.js, packages/node_modules/@webex/plugin-rooms/src/rooms.js
- Instead of going to the generic convo server for convo specific
actions, use the convo specific API.
* SDK Version
* NPM Version
=> feat(convo): update convo specific APIs

packages/node_modules/@webex/plugin-meetings/src/common/logs/logger-proxy.js
=> fix(meetings): add info to the logger

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-flag/src/flag.js, packages/node_modules/@webex/internal-plugin-team/src/team.js
- Follow `additionalUrls` for bulk fetches that provide it
- Split `flags` by cluster before fetching them
* SDK Version
* NPM Version
=> feat(federation): bulk fetches for federation

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
=> fix(conversation): cache url on create

packages/node_modules/samples/browser-auth-jwt/test/wdio/spec/jwt-authentication.js
JWT integration environment is supposedly fixed.
=> test(samples): reenable jwt sample test

.circleci/config.yml
=> chore(circleci): move to executors and add integration test job

.circleci/config.yml
Reverts webex/webex-js-sdk#1316
=> Revert "chore(circleci): move to executors and add integration test job"

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/UPGRADING.md, packages/node_modules/samples/browser-call-with-screenshare/index.html, packages/node_modules/samples/browser-multi-party-call/index.html, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-single-party-call-with-mute/index.html, packages/node_modules/samples/browser-single-party-call/index.html
I'll update this later...probably
* SDK Version
* NPM Version
=> refactor(samples): implement playsinline attribute for webrtc

.circleci/config.yml, CONTRIBUTING.md, package.json, tooling/commands/version/current.js, tooling/lib/version.js
=> Pipeline v3 - Update Contributing Guide + Fix NPM Publishing

.circleci/config.yml
=> Pipeline v3 - fix commitlint issue

package.json
Add Tim Scheuering to the contributors' list for package.json
=> docs(package): add tim s to contributors

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js
=> fix(meetings): res & fps config - firefox gdm

packages/node_modules/@webex/plugin-attachment-actions/src/attachmentActions.js, packages/node_modules/@webex/plugin-messages/src/messages.js
Enhance the current initializer JS Doc for the messages and attachment actions plugin.
=> Spark 93557 js doc init update

packages/node_modules/@webex/webex-core/src/interceptors/redirect.js, packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/service-catalog.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
Create validation methods to identify that a url is a part
of the current service catalog. Additionally, append methods
that can be utilized to retrieve other service data, such as
`clusterId`.
SPARK-94197
SPARK-86858
=> Create service validation methods

package-lock.json
=> Update critical eslint-utils security fix

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js, wdio.conf.js
=> fix(webex): 409 Conflict fix

packages/node_modules/@webex/plugin-meetings/src/stats/events.js
=> fix(meetings): fix SPARK-95339

packages/node_modules/@webex/common/src/uuid-utils.js, packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
- construct a hydra ID using a cluster
- get URL based on ID and cluster
* SDK Version
* NPM Version
=> feat(global-id): support clusters

package-lock.json, package.json
Test users package requires it and it wasn't added in previous PR to package.json.
=> fix(package): add node-random-name

packages/node_modules/@webex/http-core/README.md, packages/node_modules/@webex/http-core/src/lib/interceptor.js, packages/node_modules/@webex/http-core/src/request/index.js, packages/node_modules/@webex/http-core/test/integration/spec/interceptor.js
Append an additional method to help enable more verbose
network logging when the env flag is enabled.
=> feat(http-core): enhance verbose network logging

.circleci/config.yml, package-lock.json, package.json
=> Fix docs malformed url + Documentationjs upgrade

packages/node_modules/@webex/test-helper-test-users/src/index.js
Migrates the test-helper-test-users package to use the built in test-user library. 
Ran tests for multiple plugins and samples. All run successfully.
=> feat(test-helper-test-users): convert to test-users

.circleci/config.yml
Move integration job parallel with unit and sample jobs [skip npm]
* SDK Version
* NPM Version
=> Move sample job parallel with integration job

.circleci/config.yml, packages/node_modules/@webex/http-core/src/lib/interceptor.js, packages/node_modules/@webex/http-core/test/integration/spec/interceptor.js
Update the interceptor log test to validate if verbose networking logging is either enabled or disabled before running the test.
=> test(http-core): fix interceptor log test

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
fixes: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-98172
fixes: https://github.com/webex/webex-js-sdk/issues/1366
=> fix(media): prevent unstable media stream updates

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/media/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
Share resolution fix for firefox
* SDK Version
* NPM Version
=> fix(meeting): screen share resolution

.env.default, packages/node_modules/@webex/internal-plugin-conversation/README.md, packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js
=> fix(i-p-conversation): correct default cluster

.babelrc
=> Reconfigure babel for better mobile and browser support

packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/conversation.js, packages/node_modules/@webex/internal-plugin-team/src/team.js
Archiving/Unarchiving teams is broken on the latest version of master and on teams.webex.com. This fixes it, but there are test failures unrelated to my PR. I will also add tests that should have caught this breaking change
* SDK Version
* NPM Version
=> fix: archive team should return a promise

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/samples/browser-plugin-meetings/index.html
=> feat(meetings): add hydra people id support

packages/node_modules/@webex/plugin-meetings/src/meeting/audio.js, packages/node_modules/@webex/plugin-meetings/src/meeting/video.js
fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-100796
=> fix(meetings): mute if stream undefined fix

packages/node_modules/webex/src/webex.js
=> Add `internal presence plugin` to webex package

packages/node_modules/@webex/webex-core/src/lib/storage/memory-store-adapter.js
Stop uncaught exception with make-storage-adapter
Fixes [SPARK-94823](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-94823)
* SDK Version
* NPM Version
=> Stop uncaught exception with make-storage-adapter

.circleci/config.yml
Remove approval check from integration job
* SDK Version
* NPM Version
=> Remove approval check from integration job

packages/node_modules/@webex/internal-plugin-team/test/unit/spec/team.js
Remove device references from files within the internal-plugin-team plugin and redirect them to internal-plugin-services as necessary.
Fixes # SPARK-106014
=> fix(internal-plugin-team): remove device references

packages/node_modules/@webex/internal-plugin-search/src/index.js
=> feat(search): use services plugin

packages/node_modules/@webex/plugin-device-manager/sample/app.js, packages/node_modules/@webex/plugin-device-manager/src/device-manager.js
Deprecate any references to the wdm plugin's service methods and replace them with references to the services plugin's service.
methods.
Fixes # (issue) spark-106015
=> fix(plugin-device-manager): deprecate wdm with services methods

packages/node_modules/@webex/internal-plugin-board/src/index.js, packages/node_modules/@webex/internal-plugin-board/test/integration/spec/realtime.js
=> feat(board): use services plugin

packages/node_modules/@webex/internal-plugin-presence/test/integration/spec/presence.js
Test was missing async ability and not actually running.
=> test(presence): enable async subscribe test

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/util.js
=> fix(meetings): webrtc chrome createOffer  issue

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/webex-core/src/interceptors/request-logger.js
This PR comprises of code changes to remove PII from logs
**Tracking JIRA**
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-102761
* SDK Version
* NPM Version
=> chore(logs): initial commit remove PII from logs

.circleci/config.yml
Sometimes the output of the modified packages script gets lost in a long output of the tests. This is simply a helper for PRs.
=> Circle changed packages outputter

packages/node_modules/@webex/internal-plugin-mercury/src/mercury.js, packages/node_modules/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
=> fix(i-p-mercury): update mercury to use u2c

packages/node_modules/@webex/internal-plugin-ediscovery/src/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/integration/spec/ediscovery.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/content.js
* SDK Version
* NPM Version
Replaces PR-1440
=> feat(ediscovery): add new ediscovery API

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-team/src/team.js, packages/node_modules/@webex/internal-plugin-team/test/integration/spec/create.js, packages/node_modules/@webex/internal-plugin-team/test/unit/spec/team.js
=> fix(i-p-team): handle recordUUIDs failure gracefully

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
Bugfix for https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-106833 around updating audio to different devices. The issue arises when there was no previous media direction.
Added unit tests to verify the failing case. There were no unit tests for the function, so no other cases were added, but should be considered tech debt to add better coverage.
=> Meetings Plugin - updateAudio fix

packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js
NOTE: Need to add tests
Allowing previous field to be decrypted to change the system message in web client.
for this PR: https://sqbu-github.cisco.com/WebExSquared/webex-web-client/pull/392
NEED TO ADD TESTS
* SDK Version
* NPM Version
=> decrypt previous convo

package.json, tooling/commands/version/next.js, tooling/lib/version.js
=> Fix get-next-version script for node v10

packages/node_modules/@webex/webex-core/src/lib/services/services.js
Improve the user validation method to increase the readability and reliability of the user validation requests.
Fixes # SPARK-95999
* Node/Browser Version V8.16.0
* NPM Version V6.4.1
=> feat(webex-core): improve user validation method

packages/node_modules/@webex/plugin-meetings/src/roap/request.js
Bugfix for ROAP handling of the videoMuted property when sharing.
Fixes # (issue) https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-110363
=> fix(meetings): use correct videoMuted property

packages/node_modules/@webex/webex-core/src/lib/services/services.js
This was previously refactored a month or so ago [here](https://github.com/webex/webex-js-sdk/commit/9ffaddaa83a4ca013e8d465317a0be6416bee46c) but it looks like there was a typo in the change
Fixes an issue with activating users in the latest sdk versions
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix: read canAuthorize from credentials

packages/node_modules/@webex/internal-plugin-devices/src/index.js, packages/node_modules/@webex/internal-plugin-devices/src/interceptors/device-url.js, packages/node_modules/@webex/internal-plugin-devices/test/unit/spec/interceptors/device-url.js
=> Device url interceptor

packages/node_modules/@webex/webex-core/src/interceptors/auth.js, packages/node_modules/@webex/webex-core/test/unit/spec/interceptors/auth.js
check catalog promise was not getting resolved if the service was not found but not handling uri
* SDK Version
* NPM Version
=> fix: [webex-core] whitelisting domain

packages/node_modules/@webex/webex-core/src/webex-core.js
=> fix(webex-core): change interceptor url to service

packages/node_modules/@webex/webex-core/src/interceptors/auth.js
Previously we automatically return false from the the auth interceptor for web-authentication because it wasn't listed in the service catalog. It's listed there now. 
* SDK Version
* NPM Version
=> fix: remove web-auth hack

packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
=> Use SHA256 to encode email

packages/node_modules/@webex/internal-plugin-team/src/team.js, packages/node_modules/@webex/internal-plugin-team/test/unit/spec/team.js
=> fix(i-p-team): return rejected promise instead of throw

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/src/encryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/encryption.js
- If the default key is set to null, replace it with a new one.
* SDK Version
* NPM Version
=> fix(i-p-conversation): fix kms cert rotation

packages/node_modules/@webex/webex-core/src/interceptors/auth.js
Reverts webex/webex-js-sdk#1483
=> Revert "fix: remove web-auth hack"

packages/node_modules/@webex/internal-plugin-device/src/device.js
The scope of the changes in this pull request are wrapped around adding persistent device plugin handlers. Tests against the wrapped methods are already included, as they are decorators.
* Node/Browser Version v10.16.0
=> fix(internal-plugin-device): add persistence with device

packages/node_modules/@webex/plugin-meetings/browsers.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, wdio.conf.js
=> Firefox 72

packages/node_modules/@webex/internal-plugin-metrics/src/call-diagnostic-events-batcher.js, packages/node_modules/@webex/plugin-meetings/src/analyzer/analyzer.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/mqa-processor.js, packages/node_modules/@webex/plugin-meetings/src/stats/data.js, packages/node_modules/@webex/plugin-meetings/src/stats/events.js, packages/node_modules/@webex/plugin-meetings/src/stats/metrics.js, packages/node_modules/@webex/plugin-meetings/src/stats/stats.js, packages/node_modules/@webex/plugin-meetings/src/stats/transformer.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/webex-config.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/test-helper-mock-webex/src/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-122138
added MQA metrics for share
Will be easy to add audio and video MQA, maybe 1-2 day effort.
works for FF and chromium
data verified in MQA backend
works for wireless share and non-wireless-share
does not break existing call flows
=> feat(metrics): add automatic media metrics and format

packages/node_modules/@webex/internal-plugin-calendar/src/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/src/collection.js, packages/node_modules/@webex/internal-plugin-calendar/src/config.js, packages/node_modules/@webex/internal-plugin-calendar/src/constants.js, packages/node_modules/@webex/internal-plugin-calendar/src/util.js, packages/node_modules/@webex/internal-plugin-calendar/test/integration/spec/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/test/unit/spec/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/test/unit/spec/utils.js
PR for creating calendar collection in the calendar plugin and syncCalendar logic
* SDK Version
* NPM Version
=> feat(calendar): Calendar sync api

packages/node_modules/@webex/internal-plugin-calendar/src/calendar.js, packages/node_modules/@webex/internal-plugin-calendar/test/unit/spec/calendar.js
=> fix(i-p-calendar): fix undefined encryptedNotes

packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
This PR comprises of code changes to refactor validation / activation of a user, 
Currently if `Atlas` sends an error with `403` still `SDK` returns and empty `user` object. 
Hence client didn't receive any error that gives a wrong impression to client.
So  now if **Atlas** rejects `Activation` i am sending and `rejection/ error` to the client so that can be handled
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-124923
* SDK Version
* NPM Version
=> feat(webex-core): refactor/ improve user validation and activation SPARK-124923

packages/node_modules/@webex/internal-plugin-device/src/device.js, packages/node_modules/@webex/internal-plugin-device/src/features/feature-model.js
=> fix(features): fix duplicated items in feature lists

docs/_posts/guides/9999-01-01-getting-started.md
The scope of the changes in this pull request are focused on fixing a single line in a javascript example within the guides/getting-started page.
Fixes # [SPARK-126611](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-126611)
* Node/Browser Version v10.18.0
=> docs(guides): fix invalid javascript example

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
Added a `meeting.sendDtmf` feature to the meetings plugin and kitchen sink samples.
Fixes # [https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-117172](SPARK-117172)
* SDK Version
* NPM Version
=> feat(meetings): add sendDtmf feature

CONTRIBUTING.md, packages/node_modules/samples/browser-auth-implicit/test/wdio/spec/implicit-grant-authentication.js, packages/node_modules/samples/browser-auth-jwt/test/wdio/spec/jwt-authentication.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-multi-party-call/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js, packages/node_modules/samples/browser-single-party-call-with-mute/test/wdio/spec/normal-dialing.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/normal-dialing.js, wdio.conf.js, wdio.helpers.d/lib/add-command.js
=> Rename browserSpock & browserMccoy to browserChrome & browserFirefox

CONTRIBUTING.md, README.md, tooling/lib/build.js
=> Readme parcel fix

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js
=> [Samples] Better muting remote audio toggle + correct MediaError for getUserMedia

.circleci/config.yml, .gitignore, README.md, documentation/webex.md, package-lock.json, package.json, packages/node_modules/@webex/plugin-attachment-actions/README.md, packages/node_modules/@webex/plugin-device-manager/sample/index.html, packages/node_modules/samples/browser-auth-implicit/index.html, packages/node_modules/samples/browser-auth-jwt/index.html, packages/node_modules/samples/browser-call-with-screenshare/index.html, packages/node_modules/samples/browser-multi-party-call/index.html, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-read-status/index.html, packages/node_modules/samples/browser-single-party-call-with-mute/index.html, packages/node_modules/samples/browser-single-party-call/index.html, packages/node_modules/samples/browser-socket/index.html, packages/node_modules/webex/README.md, tooling/commands/build.js, tooling/lib/build.js, tooling/lib/test/index.js, webpack.config.js
=> Generate UMD Build using sample's Webpack config

.circleci/config.yml
=> Add tap test jobs on CircleCI

packages/node_modules/@webex/internal-plugin-device/src/interceptors/device-url.js, packages/node_modules/@webex/internal-plugin-device/test/unit/spec/interceptors/device-url.js, packages/node_modules/@webex/webex-core/src/lib/services/service-catalog.js, packages/node_modules/@webex/webex-core/src/lib/services/services.js, packages/node_modules/@webex/webex-core/test/integration/spec/services/services.js
=> Check if catalog isReady 

.circleci/config.yml
The scope of this pull request is to address the tap tests not reporting failures when failures are present.
Fixes # [SPARK-133294](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-133294)
=> fix(ci): fix tap test failure reporting

packages/node_modules/@webex/plugin-meetings/src/common/errors/parameter.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/index.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
Adds the ability to set the local video quality during a meeting.
=> Meetings set local video quality

packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/testUtils.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/webex-test-users.js
By its use of test-helper-test-users, the removal of the test user will automatically be added to the after suite.
Also fixed some misspellings in testUtils.
=> Meeting Integration Test Fixes

.circleci/config.yml
The build command as well as the tests were using the integration environment.
This adjusts the TAP tests to build for production servers, as well as points the test runners to the proper test user convo service and EU org id.
No JIRA, came up during incident investigation.
Tested manually with webex-core using the provided env vars and was getting 100% pass rate.
Verified config changes via:
> `circleci config validate`
> Config file at .circleci/config.yml is valid.
=> Updating Circle TAP config to use production environment

packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
Adds the `setMeetingQuality` functionality to the meeting object.
Fixes # https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-133791
=> Add setMeetingQuality functionality

.circleci/config.yml
Hotfix for TaP test failure for webex-core
https://wiki.cisco.com/display/WX2/Orgs+for+Federation+Testing
=> chore(circle): add updated eu org [skip ci]

package-lock.json, package.json, packages/node_modules/@webex/common/src/base64.js, packages/node_modules/@webex/common/src/index.js, packages/node_modules/@webex/common/src/isBuffer.js, packages/node_modules/@webex/common/test/unit/spec/common.js, packages/node_modules/@webex/helper-image/src/index.js, packages/node_modules/@webex/http-core/src/request/request.js, packages/node_modules/@webex/internal-plugin-encryption/src/ensure-buffer.js, packages/node_modules/@webex/internal-plugin-encryption/src/kms-certificate-validation.js, packages/node_modules/@webex/internal-plugin-encryption/test/integration/spec/encryption.js, packages/node_modules/@webex/test-helper-appid/src/create-user.js, packages/node_modules/@webex/test-helper-file/src/file.js, packages/node_modules/@webex/webex-core/src/interceptors/response-logger.js
Update internal use of Buffer to a "version" that will work in both node or in the browser
Fixes [SPARK-123728](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-134728)
=> Buffer polyfill

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/src/stats/filter.js, packages/node_modules/@webex/plugin-meetings/src/stats/stream.js, packages/node_modules/@webex/plugin-phone/src/stats/filter.js, packages/node_modules/@webex/plugin-phone/src/stats/stream.js
Update internal use of Streams to a "version" that will work in both node or in the browser
Fixes [SPARK-123729](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-134729)
=> readable-stream polyfill

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
Determined that the code to select a specific audio device via `updateAudio` in the samples was incorrect.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-119710
=> Meetings Samples - Fix update audio device selector

.circleci/config.yml
=> chore(circle): skip convo tap [skip ci]

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
The changes in this pull request are scoped around implementing the `Authentication` section of the new Meetings Sample.
Fixes # [SPARK-143728](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-143728)
=> refactor(samples): add meetings sample authentication

packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call/app.js
Removes deviceType property from meetings config object in samples - if you think it's pertinent I can remove config object as well as it's now an empty object that sets no properties
No tests removing property that was just being set twice
=> fix(samples): remove deviceType from meetings config object

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
The changes within this pull request are scoped to the `manage meetings` section of the new meetings samples.
Fixes # [SPARK-143729](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-143729)
=> feat(samples): add meetings management

packages/node_modules/@webex/plugin-meetings/browsers.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/test-helper-mocha/src/index.js, patches/README.md, patches/karma-safari-launcher+1.0.0.patch
Safari went on a Safari and finally found the mythical `webkit:WebRTC` flag in the wild.
Fixes [SPARK-105397](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-105397)
=> Test plugin-meetings against Safari

packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
Today I (somewhat) learned how to use //webrtc-internals
Fixes [#SPARK-133817](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-133817)
=> Add ability to override quality on join

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/common/events/events-scope.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/global.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Builds on #1620 
How to test:
Use the [network link conditioner](http://www.thomashanning.com/network-link-conditioner/) tool and simulate high packet loss. Notice the quality of the meeting be set to lower and lower settings.
=> feat(meetings): setting the resolution to lower on packet loss

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
Add General Controls and Select Meeting subsections.
This pull request includes the new Meeting Controls subsection of the new Meetings Sample. 
Fixes # SPARK-146168
=> feat(samples): add meeting control/general section

packages/node_modules/@webex/plugin-meetings/src/media/index.js
Firefox gods why are you displeased with us using tiny constraints
* SDK Version
* NPM Version
=> Implement workaround for LOW contraint on Firefox

packages/node_modules/@webex/plugin-meetings/src/common/logs/request.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/webex.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/node_modules/@webex/plugin-meetings/webex.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/webex/src/webex.js
Ability to upload SDK logs via the meetings plugin.
=> Meetings Upload Log Capabilities

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/mediaQualityMetrics/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/global.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Same as https://github.com/webex/webex-js-sdk/pull/1697
Sends mqa Data to dashboard 
Link for the MQA dashboard 
Dashboard to validate if mqa result is generated https://meetings-sre-dashboard.cisco.com/es_reports_query
https://mats.webex.com/diagnostic/#/common/mqe-view-clp?m=false&startTime=1591388141703&endTime=1591388856180&wcId=163231480046203520&crId=7014c094-3bec-4f90-bcc6-e2b3003395d1&caller=Arun%20Ganeshan
This is how it looks like on control hub 
https://sqbu-github.cisco.com/WebExSquared/event-dictionary
Place where all the processing of event and validation happens 
Please delete options …
=> feat(plugin-meetings): send media quality metrics to control hub

packages/node_modules/@webex/webex-core/src/config.js
Add 'webexapis.com' to the default config
SPARK-148905
* SDK Version
* NPM Version
=> fix(config): add `webexapis.com` to config

packages/node_modules/@webex/test-users/src/index.js
There is a new test user service
https://sqbu-github.cisco.com/WebExSquared/cig-service/wiki
This is the first step in migrating to use that endpoint as it requires a specific scope
* SDK Version
* NPM Version
=> fix: add new test users scope

packages/node_modules/@webex/test-users/src/index.js
The new CI gateway service doesn't default the user type like the convo service did. The convo service defaulted this user value if none was provided. We're just moving the default to the client library. 
* SDK Version
* NPM Version
=> Remove test user

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
=> test(i-p-conversation): fix tests

packages/node_modules/@webex/plugin-meetings/src/common/events/util.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/request.js, packages/node_modules/@webex/plugin-meetings/src/roap/util.js
This scope of this PR is add the appropriate logging to any errors in meetings plugin so adding 
`LoggerProxy.logger.error(message)`
to any try catch statements and .catch promise methods
Fixes # [SPARK-148851](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-148851)
* SDK Version
* NPM Version
=> Add missing logs to errors

packages/node_modules/@webex/plugin-meetings/src/mediaQualityMetrics/config.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js
Add share mqa and bug fixes for it 
added share
=> fix(meeting-plugin): fps and resolution values

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
In addition to meeting streams, get media devices, and basic steps
This pull request includes new subsections Source Devices and Media Streams of the new Meetings Sample. 
Fixes # 
SPARK-143732
SPARK-146169
=> feat(samples): add meeting control/source devices

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
A couple refactors removing unnecessary promise-layers.
=> Send getUserMedia Failures as Metric

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
The scope of the changes in this pull request are focused around adding the meetings devices section from the original `plugin-meetings-sample` to `meetings-sample`.
Fixes # [SPARK-143731](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-143731)
=> feat(meetings-sample): add devices section

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html
This pull request includes the participants subsection of the new Meeting Controls as part of the new Meetings Sample.
Fixes # [SPARK-143730](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-143730)
=> Add Participant controls to new meetings sample

packages/node_modules/@webex/plugin-meetings/src/meeting/util.js
Remove un authorized event for call analyzer
* SDK Version
* NPM Version
=> fix(plugin-meetings): remove disconnect events

packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
Hotfix for the timeout issue in [this pull request](https://github.com/webex/webex-js-sdk/pull/1727).
=> fix(plugin-meetings): timeout clear issue

karma-ng.conf.js, wdio.conf.js
=> refactor(webdriver): fix local selenium issue with browserName

packages/node_modules/@webex/plugin-logger/src/logger.js, packages/node_modules/@webex/plugin-logger/test/unit/spec/logger.js
This adds the ability to group messages together in the console and logs.
* SDK Version
* NPM Version
=> feat(p-logger): add group logging

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153080
=> feat(meetings): reconnect mercury on network issue

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js
PR consists of this section of the reconnect flow chart.
=> feat(meetings): add rejoin meeting capability

packages/node_modules/samples/browser-meetings/app.js, packages/node_modules/samples/browser-meetings/index.html, packages/node_modules/samples/browser-meetings/test/wdio/spec/mediatest.js
This PR is to migrate the existing tests in the kitchen sink app to the new refactored branch - it also adds the capability to answer and reject calls in the new refactored kitchen sink app
Fixes # ([SPARK-151808](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-151808))
Tests were migrated from current browser-plugin-meetings to browser-meetings directory (new kitchen sink app)
* SDK Version
* NPM Version
=> feat(samples): migrate tests and ability to answer/reject calls

packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
[SPARK-115468](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-115468) #code-complete
* SDK Version
* NPM Version
=> fix(p-meetings): close remote stream when leaving

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/samples/browser-call-with-screenshare/app.js
SPARK-152947 #code-complete
* SDK Version
* NPM Version
=> feat(p-meetings): log 'join' and 'leave'

packages/node_modules/@webex/plugin-meetings/src/common/events/util.js
[SPARK-154227](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-154227) #code-complete
* SDK Version
* NPM Version
=> fix(p-meetings): log circular objects

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
[SPARK-152742](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153026) #code-complete
* SDK Version
* NPM Version
=> feat(p-meetings): log 'addMedia' and 'updateMedia'

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
Added ice disconnect and small fixes 
* SDK Version
* NPM Version
=> Media inactivity event

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
[SPARK-153801](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153801) #code-complete
* SDK Version
* NPM Version
=> feat(p-meetings): log mute/unmute

packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js
Small PR to send reconnect ca metrics
https://webex.splunkcloud.com/en-US/app/squared/call_analyzer__reconnect_success?form.ca_device_type=webex-js-sdk&form.ca_time.earliest=-60m%40m&form.ca_time.latest=now&form.ca_interval=1h&form.ca_device_version=*&form.ca_session_type=*&form.ca_is_test=*&form.ca_site_type=*&form.ca_org_id=*&form.ca_locus_dc=*&form.ca_dedup_user=where%201%20%3D%3D%201&form.myusetime=where%201%20%3D%3D%201&form.ca_failure_type=*
https://call-analyzer-dev.cisco.com/?correlationId=96dfc2e5-0681-4182-bd6c-0d6fb34c4269
Please describe the …
=> fix(plugin-meeting): send reconnect metrics

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/util.js, webpack.config.js
The scope of the changes in this pull request are to address the invalid conversation serviceUrl lookup process used within the meetings plugin when creating a meeting and joining it.
[SPARK-157390](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-157390)
=> fix(plugin-meetings): convo service lookup

packages/node_modules/@webex/plugin-phone/src/call.js
The scope of the changes in this pull request is to update the `plugin-phone` plugin to utilize federated cluster information.
Fixes # [SPARK-159300](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-159300)
=> fix(plugin-phone): call cluster federation

packages/node_modules/@webex/internal-plugin-calendar/src/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-160974
parent link -https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-160297
`to fix following error`
---
=> fix(calender): handle meetingJoinInfo DTO correctly

packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call/app.js
Enable reconnect for meeting-samples
=> feat(samples): enable reconnection to meeting sample

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/selfConstant.js
added feature to emit server media inactivity for reconnect
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-161433
=> feat(plugin-meeting): add event for server media inactivity

.circleci/config.yml
Disabling of TAP tests until proper engineering coverage.
---
=> ci: disable TAP tests

tooling/modified-packages.js
Testing modified packages script on circle
---
=> Testing modified packages

package-lock.json
Fixes #[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-167132](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-167132)
---
=> fix(package): update faye-websocket package version

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes #[SPARK-167060](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-167060)
---
=> fix(meetings): send mute control with audio mute

packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/create.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/verbs.js
There is an issue with Atlas/CI where side boarding consecutively turns into 409s.
Skipping testes until it's fixed.
---
=> test(conversation): skip user side boarding tests

packages/node_modules/@webex/plugin-device-manager/src/device-manager.js
Requested by @InteractiveTimmy 
---
=> fix(device-manager): throw error on search failure

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/UPGRADING.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js, packages/node_modules/@webex/plugin-meetings/webex.js
Fixes issue with safari media ready event and multiple obtp issue when using a conversion to dial in 
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-170709
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-171580
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-171578
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-168059
---
=> Meeting plugin fixes

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/controlsUtils.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-165740
---
=> Meeting Plugin - Added Recording Events 'started', 'stopped', 'paused', 'resumed' 

packages/node_modules/@webex/plugin-meetings/README.md
No issue, just discovered improper documentation.
---
=> docs(meetings): update members doc

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes #https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-170709
---
=> fix(plugin-meeting): media ready event not triggring

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/mqa-processor.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js
MQA analyzer was reporting negative values for audio rtpPackets and some of them values were -1 
---
=> fix(plugin-meetings):  fix audio RTPpackets and -1 values

package-lock.json, package.json
=> chore: revert 'documentation'

packages/node_modules/@webex/internal-plugin-ediscovery/src/transforms.js, packages/node_modules/@webex/internal-plugin-ediscovery/test/unit/spec/transforms.js
Adding support for the decryption of meeting activities. Specifically 
Meeting Titles
{
"activityId": "65d2c570-fe42-11ea-a10e-81bb18766f0a",
"timestamp": "2020-09-24T08:46:08.000Z",
"verb": "add",
"actorId": "926423f2-4b7f-4654-94e0-f05faa311be4",
"actorDisplayName": "compliance@yopmail.com",
"targetId": "894a4458af354ebfbf3fa1c025fb88b8_I_172954877251558750",
"meeting": {
"id": "894a4458af354ebfbf3fa1c025fb88b8_I_172954877251558750",
"objectType": "meeting",
"title": "XXXXXXXXX",
"start": "2020-09-24T08:39:49.000Z",
"end": "2020-09-24T08:46:08.000Z",
"webLink": "https://publictest.dmz.webex.com/webappng/sites/publictest/meeting/postinfo/894a4458af354ebfbf3fa1c025fb88b8_I_172954877251558750"
},
"spaceName": "compliance test's Personal Room",
"containerName": "compliance test's Personal …
=> feat(ediscovery): support decryption of meeting activities

package-lock.json, package.json
I am now a contributor to open-source projects
---
=> stop npm-force-resolution to run on ci && update package-lock

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Look who's back, back again... and without a ticket 👍 
---
=> Send failure metrics on more functions in meeting/index

.circleci/config.yml
- Enable TAP testing without paging
[SPARK-182161](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-182161) #done
---
=> chore: enable TAP testing

packages/node_modules/@webex/webex-core/test/unit/spec/credentials/token.js
=> fix(webex-core): fix unit tests

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js
Enable RTX media re transmission by removing the RTX value
---
=> fix(plugin-meetings): add support for rtx re transmission

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/create.js
This PR comprises of code changes to allow user to create a classified space
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-176840
---
=> feat(space-classification): allow user to create a classified space

packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js
Added code to add geoHint as part of join request 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-192958
Fixes #SPARK-192958
---
=> feat(plugin-meetings): add geo hint for join request

.github/SUPPORT.md, CONTRIBUTING.md, README.md, packages/node_modules/@webex/common/src/constants.js, packages/node_modules/@webex/common/src/event-envelope.js, packages/node_modules/@webex/plugin-attachment-actions/src/attachmentActions.js, packages/node_modules/@webex/plugin-authorization-browser/src/authorization.js, packages/node_modules/@webex/plugin-authorization-node/src/authorization.js, packages/node_modules/@webex/plugin-memberships/src/memberships.js, packages/node_modules/@webex/plugin-memberships/test/integration/spec/memberships.js, packages/node_modules/@webex/plugin-messages/src/messages.js, packages/node_modules/@webex/plugin-messages/test/integration/spec/messages.js, packages/node_modules/@webex/plugin-rooms/src/rooms.js, packages/node_modules/@webex/plugin-rooms/test/integration/spec/rooms.js, packages/node_modules/@webex/plugin-team-memberships/test/integration/spec/team-memberships.js, packages/node_modules/@webex/plugin-webhooks/test/integration/spec/webhooks.js, packages/node_modules/@webex/webex-core/README.md, packages/node_modules/samples/browser-read-status/app.js, packages/node_modules/samples/browser-read-status/explanation.html, packages/node_modules/samples/browser-read-status/index.html, packages/node_modules/samples/browser-socket/app.js, packages/node_modules/samples/browser-socket/index.html, packages/node_modules/webex/README.md
Fixes [SPARK-186353](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-186353)
---
=> Webex rebranding

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/mediaQualityMetrics/config.js, packages/node_modules/@webex/plugin-meetings/src/meeting/audio.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/video.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/global.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js, packages/node_modules/@webex/plugin-meetings/test/utils/testUtils.js
TBD screen shots for logs and MQE
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-186042
---
=> fix(meeting-plugin):  send missing media quality metrics

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/reconnection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/handler.js, packages/node_modules/@webex/plugin-meetings/src/roap/index.js
Fixes [SPARK-186101](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-186101)
---
=> feat(plugin-meetings): use new correlation on rejoin

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js
Fixes #https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-191901
---
=> fix(plugin-meetings): throw error if no valid ice candidates are found

packages/node_modules/@webex/plugin-logger/README.md, packages/node_modules/@webex/plugin-logger/test/unit/spec/logger.js
Updating docs on log levels
---
=> docs(logger): add docs on logger levels

packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js
Hotfix, due to issue WEBEX-149785
SPARK-203445
=> fix(plugin-meetings): encode destination on request

.env.default
=> Update test users eu orgid for prod/bts

.circleci/config.yml, package.json, tooling/commands/exec.js
Fixes [SPARK-207457](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-207457)
---
=> Update `exec` command for newer version of Yargs

.env.default, packages/node_modules/@webex/test-helper-mocha/src/index.js, packages/node_modules/@webex/test-helper-test-users/src/index.js, packages/node_modules/@webex/test-users/src/index.js, packages/node_modules/@webex/test-users/src/whistler.js, packages/node_modules/@webex/test-users/test/integration/spec/whistler.js
Fixes [SPARK-193921](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-194931)
---
=> Add ability to generate test users using Whistler API

packages/node_modules/@webex/plugin-meetings/src/mediaQualityMetrics/config.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/global.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/node_modules/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Fixes #https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-194861
Makes sure the packet loss info is correct compared to the server side and the jitter and other information are present 
---
=> fix(plugin-meetings): add missing mqe and fix packet loss values

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-210353
---
=> fix(plugin-meetings): add default IP address for MQE

packages/node_modules/@webex/internal-plugin-support/src/support.js, packages/node_modules/@webex/internal-plugin-support/test/unit/spec/support.js, packages/node_modules/@webex/plugin-meetings/src/common/logs/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
=> fix(plugin-meetings): added userId, orgId and meetingId for upload logs

packages/node_modules/samples/browser-auth-implicit/app.js, packages/node_modules/samples/browser-auth-jwt/app.js, packages/node_modules/samples/browser-call-with-screenshare/app.js, packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-read-status/app.js, packages/node_modules/samples/browser-single-party-call-with-mute/app.js, packages/node_modules/samples/browser-single-party-call/app.js, packages/node_modules/samples/browser-socket/app.js
In this PR, I have replaced innerHTML with innerText to establish and present better security practice for potential developers, who are looking to use the WebEX Javascript SDK.  
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-186855
=> Replaced innerHTML with innerText

netlify.toml
Hotfix for failed netlify deploy
---
=> chore(netlify): remove production env var

packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js
Fixes [SPARK-219578](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219578)
---
=> docs(meetings): remove references to join meeting via meeting link

package-lock.json, package.json
Fixes [SPARK-217140](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-217140)
---
=> Update lodash to latest (v4.17.21)

package-lock.json
npm audit is yelling about elliptic and y18n
---
=> npm audit -- elliptic + y18n

packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js
=> add console.warn deprecation message about using meeting-link on create

packages/node_modules/samples/browser-single-party-call/app.js, packages/node_modules/samples/browser-single-party-call/index.html, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-and-reject.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/dial-before-connect.js, packages/node_modules/samples/browser-single-party-call/test/wdio/spec/normal-dialing.js
Jira - https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-218461
Replaces #2048
=> docs(samples): added oauth flow into single-party-call

package.json, packages/node_modules/@webex/test-helper-test-users/src/index.js, tooling/lib/test/karma.js
=> fix safari not closing correctly + fix karma deprecation notice

packages/node_modules/@webex/plugin-meetings/src/locus-info/parser.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/parser.js
Fixes the "invalid locus" error of the locus parser.
Fixes #SPARK-226855
---
=> fix(plugin-meetings): fix locus parser error

package-lock.json, package.json
Fixes [SPARK-219510](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219510)
---
=> chore(deps): force terser-webpack-plugin to v4 for all deps

package-lock.json, package.json, packages/node_modules/@webex/media-engine-webrtc/src/engine.js, packages/node_modules/@webex/plugin-meetings/src/common/browser-detection.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/media/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/mqa-processor.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/stats/transformer.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/common/browser-detection.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js, packages/node_modules/@webex/test-helper-mocha/src/index.js
[SPARK-224282](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224282) #done
=> fix: update bowser

packages/node_modules/@webex/plugin-meetings/src/common/browser-detection.js, packages/node_modules/@webex/plugin-meetings/src/media/index.js, packages/node_modules/@webex/plugin-meetings/src/media/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/mqa-processor.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/src/stats/transformer.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
=> fix(meetings): handle useragent lookup when running on node

packages/node_modules/@webex/plugin-meetings/test/unit/spec/common/browser-detection.js
=> test(meetings): test no useragent scenario

packages/node_modules/@webex/internal-plugin-conversation/src/conversation.js, packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/src/index.js, packages/node_modules/@webex/internal-plugin-conversation/test/integration/spec/get.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-216755
---
=> SPARK-216755-getThreads

packages/node_modules/@webex/plugin-meetings/src/locus-info/infoUtils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js
=> fix(meetings): sending meeting locked/unlocked events

packages/node_modules/@webex/plugin-meetings/src/metrics/index.js
[SPARK-231618](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231618) #done
=> feat(metrics): add senderCountryCode to metrics

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
- send additional information to non-media quality metrics endpoint
[SPARK-226455](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-226455) #done
=> fix(metrics): send clientType and subClientType

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Call randomly disconnects after locus migration  SPARK-236905
---
=> fix(plugin-meetings): locus migration for sip calls

.eslintrc.yml, packages/node_modules/@webex/plugin-meetings/README.md, packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-errors.js, packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/transcription/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/transcription/index.js, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-243877
---
https://confluence-eng-gpk2.cisco.com/conf/display/WBXT/Webex+Browser+SDK+Real-time+Transcription
=> feat(plugin-meetings): enable transcription event

packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-multi-party-call/index.html
[SPARK-233151](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233151) #done
=> feat(samples): add renderInfo call to multi-party

packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-errors.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes [SPARK-253397](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-253397)
=> fix(plugin-meetings): SPARK-253397 addMedia

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
[SPARK-244578](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-244578)
=> fix(meeting): create new correlation ID every time

package-lock.json, package.json
Updated resolutions to use https://snyk.io/test/npm/glob-parent/5.1.2.
=> fix(deps): added glob-parent to resolutions

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/roap/handler.js, packages/node_modules/@webex/plugin-meetings/src/roap/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Added event for CNN to handle the transfer scenario
=> feat(plugin-meetings): events for media:serverNegotiatedwith experimental.enableMediaNegotiatedEvent config

packages/node_modules/@webex/plugin-meetings/README.md
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254773
=> docs(plugin-meetings): updated docs with known limitation about remote sharing

karma-ng.conf.js
I already added the env to circleci and set it to DEBUG
---
=> chore(karma): add log level to config

packages/node_modules/@webex/plugin-meetings/src/locus-info/controlsUtils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/locus-info/index.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js
continuation of https://github.com/webex/webex-js-sdk/pull/2192 (just moved here so its a merge from fork)
pertains to: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-255479
=> fix(plugin-meetings): fixed false firing of stop recording event

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
Fixes [SPARK-263738](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263738)
---
=> fix(meetings): always add locus url to metrics payload

packages/node_modules/samples/browser-socket/index.html
Fixes [#SPARK-272804](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-272804)
---
=> docs(): fix hyperlink in browser-socket demo

package-lock.json, package.json, packages/node_modules/@webex/plugin-authorization-browser-first-party/src/authorization.js, packages/node_modules/@webex/plugin-authorization-browser-first-party/test/unit/spec/authorization.js
This implements PCKE code challenge as described in https://datatracker.ietf.org/doc/html/rfc7636
Wikis for the idbroker APIs:
https://wiki.cisco.com/display/CIOAUTH/OAuth2+API+to+Get+Authorization+Code
https://wiki.cisco.com/display/CIOAUTH/OAuth2+API+to+Get+Access+Token+by+Authorization+Code
SPARK-204648
---
=> Pkce code challenge

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266095 
used this pr as reference https://github.com/webex/webex-js-sdk/pull/2166
needs test at the time of this writing
=> feat(metrics): add metrics for sending media delay

packages/node_modules/@webex/plugin-meetings/src/meeting-info/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting-info/util.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meetings/index.js, packages/node_modules/@webex/plugin-meetings/src/meetings/util.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/samples/browser-call-with-screenshare/test/wdio/spec/normal-dialing.js
A combination of fixes, including from these PRs:
- #2206
- #2220
- #2230
Fixes [SPARK-281731](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281731)
Fixes [SPARK-274564](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-274564)
---
=> Wbxappapi fixes

packages/node_modules/@webex/internal-plugin-board/src/board.js, packages/node_modules/@webex/internal-plugin-board/test/integration/spec/board.js, packages/node_modules/@webex/internal-plugin-board/test/integration/spec/realtime.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/mediaSharesUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/members/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
JIRA: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-255158
Feature Doc: https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/Feature+Documentation
Added functions needed for whiteboard in-meeting
a) meetings-plugin
-> meeting
- startWhiteboardShare --> grant meeting floor request for specific whiteboard channel
- stopWhiteboardShare --> release meeting floor request for specific whiteboard channel
- setUpLocusMediaSharesListener --> edited handle whiteboard share status
-> locusInfo
- MediaSharesUtils --> Changed to have whiteboard in payload
-> members
- locusMediaSharesUpdate --> edited to handle whiteboard
b) board-plugin
- authorizeMediaInjector --> needed for mobile client to receive transcoded whiteboard
- unauthorizeMediaInjector --> clean up KMS authorizations made for …
=> Whiteboard

packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/utils/webex-test-users.js
Not ready at the time of this writing. I cannot seem to get the information specified by the corresponding Jira Ticket.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-275415
Sample of what is logged:
=> test(plugin-meetings): added int. test for hydra user id (getDestinationType)

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/journey.js, packages/node_modules/@webex/plugin-meetings/test/utils/testUtils.js
Fixes [SPARK-266096](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266096) and [SPARK-266099](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266099)
---
=> Add Meetings Join Time Delay Metrics

packages/node_modules/@webex/plugin-meetings/src/meeting-info/utilv2.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js
- Add conditional to handle adding `sipUrl` to `body`
- Add spec to test for `meetingNumber
`
=> test(plugin-meetingsV2): add sipUrl to body from sipUri

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/src/metrics/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/metrics/index.js
- Add `ip-anonymize` to handle masking ip address.
- Add unit tests that verify masking in payload
- Fixes https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260056
.
=> fix(plugin-meetings): add anonymize ip address

packages/node_modules/@webex/plugin-meetings/src/meeting-info/utilv2.js, packages/node_modules/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/utilv2.js
Fixes [SPARK-283111](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283111)
---
=> fix(meetings): set supportHostKey parameter when calling wbxappapi

packages/node_modules/@webex/plugin-meetings/src/meeting-info/utilv2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/utilv2.js
Jira card link: [https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-274567](url)
=> fix: webexapi fix for pmr request

packages/node_modules/@webex/plugin-meetings/src/config.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/peerconnection-manager/index.js
http://www.rtcbits.com/2016/11/controlling-bandwidth-usage-in-webrtc.html
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279720)
=> fix(plugin-meetings) :add google bitrate adjustment

.github/PULL_REQUEST_TEMPLATE.md
As part of FedRAMP compliance, we need to have a system of record certifying what has changed and how it has been tested
---
=> docs(templates): pull request template update for FedRAMP

packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-plugin-meetings/style.css, packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293018
Updated ui for meetings management:
- Updated CSS to have styled buttons and inputs, as well as utilities for padding/margin. 
- Updated layout to have fixed streams sidebar.
- Updated create meeting form to handle submissions on enter key
- Updated current meetings list to use radio input.
- Added join button below meetings list to join a meeting that was selected by radio.
- Updated leave meeting logic to leave the meeting of the selected meeting radio input.
- Update wdio test.
=> docs(plugin-meeting): update samples meetings management

packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-plugin-meetings/style.css
Updated the structure and demos for the following sections:
- Locking / Unlocking
- Recording
- Tones
- Transcription
- Devices
- Source Devices
- Mute / Unmute Audio
- Mute / Unmute Video
- Screenshare
- Quality
Performed manual testing on t mobile network i iphone
---
=> docs(plugin-meeting): update samples meeting controls

packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-errors.js, packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/peerconnection-manager/index.js
This Pull request enables client to connect calls with only ipv6 candidates present 
captures any error happening while gathering ipv6 or ipv4 candidates , And makes sure the candidates are always gathered 
Removing the logic to throw error when only ipv6 candidates are present 
adding icegatheringstatechange which will give a precise event when ice gathering is completed 
Established a call with both IPv4 and ipv6 candidates and removed the ipv4 candidates so that the call only has IPv6 in it and established the call and also checked the SDP if only ipv6 candidate are present 
---
=> fix(plugin-meetings): use icegatheringstatechange for ice completed

packages/node_modules/samples/browser-plugin-meetings/index.html
Updated UI for the following device management sections:
- Device list
- Device query
- Device paring
- Audio state
- Volume
- Mute
Updated markup and formatting to be structured correctly.
---
=> docs(plugin-meeting): update samples device management

packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html, packages/node_modules/samples/browser-plugin-meetings/style.css, packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
Updates the plugin-meetings sample authentication form.
Changes to be done to the Authentication section:
Auth:
1. Update form to handle submit for token.
2. Make token input required
Registration:
1. Enable color changing to green when ready to register
2. Enable color change to red when unregister.
3. Clean up padding / structure.
---
=> docs(plugin-meeting): update samples authentication

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js, packages/node_modules/@webex/plugin-meetings/src/meeting/util.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meetings/index.js
Updates the plugin-meetings to pass permission token and use meetingJoinUrl as preference
Pass `meetingJoinUrl` as part of the /call request being sent to the server
Pass 'permissionToken` as part of the /call request 
---
=> fix(plugin-meetings): add  permissions token for unified space meeting

packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js
=> fix(plugin-meetings): remote extmap from the remotetSdp

packages/node_modules/@webex/plugin-meetings/src/constants.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/meeting/request.js
- Adds reference to `LAYOUT_TYPES` to the `changeVideoLayout` method.
- Added link to `LAYOUT_TYPES`
---
=> docs(plugin-meetings): add reference to LAYOUT_TYPES

package-lock.json, package.json
CIAM alert for `hosted-git-info`
Removing dependencies that are no longer needed and force-resolution for `hosted-git-info`
`npm test`
---
=> fix(dependencies): remove unused dependencies

packages/node_modules/samples/browser-multi-party-call/app.js, packages/node_modules/samples/browser-multi-party-call/index.html, packages/node_modules/samples/browser-plugin-meetings/app.js, packages/node_modules/samples/browser-plugin-meetings/index.html
Currently there is no option to pass the integration token to the samples and test it out , Currently adding a small check box to check for production and unchecking will be integration env 
Manually tested the sample app 
---
=> fix(plugin-meetings): add toggle to test integration env

packages/node_modules/@webex/plugin-messages/src/messages.js
Incorrect JS doc example.
Adding missing closing brackets
---
=> doc(plugin-messages): miscellaneous fixes

patches/documentation+13.2.5.patch
=> fix: add decorator path for docs

packages/node_modules/@webex/internal-plugin-conversation/src/decryption-transforms.js, packages/node_modules/@webex/internal-plugin-conversation/test/unit/spec/decrypt-transforms.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313496
Redo of --> https://github.com/webex/webex-js-sdk/pull/2318
Redo of --> https://github.com/webex/webex-js-sdk/pull/2319
Decrypt meeting container activity
Add function to decrypt meeting container activity
1) Decrypt only displayName
2) Decrypt displayName and Topic
---
=> feat(decrypt): meeting container

package-lock.json, package.json
Re arrange dev dependency 
---
=> fix(plugin-meeting): remove not used detectRtc npm module

.circleci/config.yml
Fixes release issue we have when having breaking change
---
=> fix: unblock release on a breaking change

docs/samples/browser-plugin-meetings/index.html, packages/node_modules/@webex/plugin-meetings/src/metrics/config.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/request.js
Unmute button fix in samples app.
Updated function call to unmuteAudio() on unmute button on [samples app](https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings).
---
=> fix: fixed unmute btn function call on samples

.circleci/config.yml, package-lock.json, package.json
=> build: fix the circle ci path issue

docs/samples/browser-auth/app.js, docs/samples/browser-auth/index.html, docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, docs/samples/browser-plugin-meetings/style.css, docs/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
- Updating the plugin-meetings sample to be a kitchen-sink app.
- Merge implicit auth and JWT auth.
- Updating UI of plugin-meetings sample.
- Refactoring existing javascript code.
- Adding more functions.
---
=> Unified sample app for web SDK

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/src/metrics/constants.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Added dropdown selection for conversationURL for Adhoc flowin samples
Added Metrics for - fetchmeeting success, fetchmeeting failure
captcha, password
adhoc meeting failure
Also, Added Tests for same
Below Screenshot from amplitude -
---
=> feat(plugin-meetings): added metrics for actions and failures (USM Flow)

.circleci/config.yml, package-lock.json, package.json
=> build: upgrade ci and internal-media-core

.circleci/config.yml, packages/node_modules/@webex/internal-plugin-board/src/board.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, process
=> build: install certificate needed for cache permission

packages/node_modules/@webex/webex-core/src/config.js
< Adding broadworks domains in  allowedDomains config.js>
---
=> Adding broadworks domains in allowedDomains list

packages/node_modules/@webex/plugin-meetings/src/meeting/effectsState.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/effectsState.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
BNR methods(enable and disable bnr) updated to handle multiple requests.
- Created a effects state and updated enable and disable bnr methods.
---
=> Spark 346778 handle multiple request bnr

packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
=> fix: unit test and meetinginfo

.circleci/config.yml
- Unit test report file was not getting generated and shown on circle ci for passed/failed unit tests. This PR resolves this issue.
- Added a subfolder in path.
---
=> build: added subfolder in path to show unit test results in circle ci

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js
implemented password and captcha flow in samples Web JS SDK
Added Captcha input box
Added Captcha image
Added refresh captcha option
Added status section for updating the dev for actions
Added logs wherever required
Added catch block for refreshCaptcha
Password not required -
Password Required -
Password/Captcha Error -
Password/Captcha verified -
Meeting Joined -
Run the samples locally and test seems to work fine, screenshots attached above.
---
=> feat(samples): implemented password and captcha flow in samples app

packages/node_modules/@webex/plugin-meetings/src/locus-info/index.js, packages/node_modules/@webex/plugin-meetings/src/locus-info/selfUtils.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fixes the issue when user is in lobby of a PMR meeting and tries to add media. Earlier it used to skip that check and go for SDP exchange where it was finally failing.
Fixes the issue and throws proper error.
Screenshot
In the above screenshot we are already showing Admit button implying the user is in lobby
Unit test
---
=> fix(plugin-meetings): should throw user in lobby

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html
Incorporated marcin's review comments
Old PR - https://github.com/webex/webex-js-sdk/pull/2402
---
=> feat(samples): incorporated marcin review comments

package-lock.json, package.json, packages/node_modules/@webex/plugin-meetings/src/meeting/effectsState.js, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/effectsState.js
BNR was not getting enabled upon microphone switch. This PR addresses it.
This issue is fixed by obtaining the BNR status directly from meeting object rather than as parameter
---
=> fix(plugin-meetings): bnr enabled upon microphone switch

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, docs/samples/browser-plugin-meetings/style.css, packages/node_modules/@webex/plugin-meetings/src/constants.ts, packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
- Adds media resolution inputs inside join meeting area
- Adds resolution on top right of local and remote video element
Screenshots
---
=> feat(samples): add media resolution input inside join meeting

packages/node_modules/@webex/plugin-meetings/src/constants.ts, packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-364846
This fix uses the `uri` paramter when creating the request params rather than the non-existent `directURI` parameter
---
=> fix(plugin-meetings): fix direct info uri

packages/node_modules/@webex/plugin-meetings/src/metrics/config.js
Events validation error thrown which is `missing required property name`
Added constant value for name when name value is not  present in error
---
=> fix(metrics): added value for name enum value in events

packages/node_modules/@webex/plugin-meetings/src/media/properties.js, packages/node_modules/@webex/plugin-meetings/src/meeting/muteState.js
There is some old code that's been marked as deprecated 2 years ago and will be inconvenient to maintain when we support multistream.
Removed the deprecated code.
---
=> Removed some old, deprecated API and fixed some jsdoc comments

packages/node_modules/@webex/internal-plugin-llm/README.md, packages/node_modules/@webex/internal-plugin-llm/package.json, packages/node_modules/@webex/internal-plugin-llm/src/constants.ts, packages/node_modules/@webex/internal-plugin-llm/src/index.js, packages/node_modules/@webex/internal-plugin-llm/src/llm.ts, packages/node_modules/@webex/internal-plugin-llm/src/llm.types.ts, packages/node_modules/@webex/internal-plugin-llm/test/unit/spec/llm.js, packages/node_modules/@webex/internal-plugin-voicea/README.md, packages/node_modules/@webex/internal-plugin-voicea/package.json, packages/node_modules/@webex/internal-plugin-voicea/src/constants.ts, packages/node_modules/@webex/internal-plugin-voicea/src/index.js, packages/node_modules/@webex/internal-plugin-voicea/src/utils.ts, packages/node_modules/@webex/internal-plugin-voicea/src/voicea.ts, packages/node_modules/@webex/internal-plugin-voicea/src/voicea.types.ts, packages/node_modules/@webex/internal-plugin-voicea/test/unit/spec/utils.js, packages/node_modules/@webex/internal-plugin-voicea/test/unit/spec/voicea.js, packages/node_modules/@webex/test-helper-mock-webex/src/index.js
Adds plugins for voicea related features.
Extend mercury to LLM plugin
Make LLM open to Voicea plugin and include relevant Locus API calls and socket messaging
---
=> feat: add voicea-plugin [resolve merge conflict]

packages/node_modules/@webex/internal-plugin-llm/package.json, packages/node_modules/@webex/internal-plugin-llm/src/index.ts, packages/node_modules/@webex/internal-plugin-llm/src/llm.ts, packages/node_modules/@webex/internal-plugin-voicea/package.json, packages/node_modules/@webex/internal-plugin-voicea/src/index.js, packages/node_modules/@webex/internal-plugin-voicea/src/index.ts, packages/node_modules/@webex/internal-plugin-voicea/src/voicea.ts, packages/node_modules/@webex/internal-plugin-voicea/test/unit/spec/voicea.js, packages/node_modules/@webex/plugin-meetings/src/index.js
=> Fix Voicea filetype

packages/node_modules/@webex/plugin-meetings/src/meeting/index.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js
The scope of the changes in this pull request are to add the ability to change the layout size without forcing a layout type.
[JIRA](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-370386).
=> feat(meetings/meeting): add size-only layout requests

LICENSE
Updating SDK Licence to point to Cisco EULA as per discussions in [Licence for Web SDK](webexteams://im?space=950c1740-2e12-11ed-841a-ab6746f22a64) Space.
Primary reason for this change is to accommodate BNR library in the SDK.
---
=> chore(licence): update licence to point to cisco eula

packages/node_modules/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.js, packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
If there is no preferred site, do not attempt to create a space instant as it will fail
---
=> fix(plugin-meetings): dont create adhoc meeting if no site

tooling/commands/build.js, tooling/commands/check-testable.js, tooling/commands/list.js, tooling/commands/test.js, tooling/commands/updated.js, tooling/index.js, tooling/lib/build.js, tooling/lib/test/index.js, tooling/util/package.js
How does tooling work in JS SDK?
- Adding comments wherever necessary
- Taking a brown bag session
- Creating a doc for it
---
=> docs(tooling): hints for each flow added

.circleci/config.yml, .circleci/local.config.yml, CONTRIBUTING.md, SCRIPTS.md, documentation/README.md, packages/@webex/plugin-device-manager/README.md, packages/@webex/plugin-meetings/README.md, packages/@webex/plugin-meetings/internal-README.md, sauce.py
Update the documentation to address the move to yarn and remove dependency checks
---
=> docs: update the documentation to use yarn

.lintstagedrc, packages/@webex/http-core/src/request/index.js, packages/@webex/webex-core/src/lib/services/services.js
Sometimes when api is not able to fetch response in a given time then it gives error for eg., this api `https://ds.ciscospark.com/v1/region`. We needed to add a timeout limit after which api calls should be cancelled automatically.
Added a timeout of 5 secs to above api.
---
=> Spark 366191 region api timeout added

CONTRIBUTING.md, SCRIPTS.md, patches/README.md
This PR provides minor Markdown formatting, spacing, and trivial typo fixes to some of the main Markdown in the repo.
For example, references of "SauceLabs" have been changed to "Sauce Labs" just to ensure alignment with how the vendor refers to themselves.  (ref https://saucelabs.com)
Reference to Sauce Labs web site:
Local Markdown linting and `mdspell` running.
---
=> chore: Documentation formatting and typo fixes

packages/@webex/internal-plugin-conversation/src/conversation.js, packages/@webex/internal-plugin-conversation/src/decryption-transforms.js, packages/@webex/internal-plugin-conversation/src/share-activity.js, packages/@webex/internal-plugin-ediscovery/src/transforms.js, packages/@webex/internal-plugin-encryption/src/encryption.js, packages/@webex/internal-plugin-encryption/src/kms-dry-error-interceptor.js, packages/@webex/internal-plugin-presence/src/presence.js, packages/@webex/internal-plugin-user/src/user-uuid-store.js, packages/@webex/plugin-attachment-actions/src/attachmentActions.js, packages/@webex/plugin-meetings/src/peer-connection-manager/index.js, packages/@webex/plugin-memberships/src/memberships.js, packages/@webex/plugin-messages/src/messages.js, packages/@webex/plugin-people/src/config.js, packages/@webex/plugin-people/src/people.js, packages/@webex/plugin-rooms/src/rooms.js, packages/@webex/plugin-team-memberships/src/team-memberships.js
This PR fixes the JSDoc comments in a variety of objects, using a quick scan with the VSCode cSpell extension. (one of my favorites!)
It also identified a single variable typo which was local to the `memberships.js` file and so I refactored that while I was at it.
Given the use of the documentation generation in the pipeline, hope this helps fix some typos in the documentation our users use.
Using the [VSCode cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension, viewing the answers in the Problems panel in VSCode, and accepting the fixes!
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a- …
=> chore(jsdocs): Fix typos in method documentation

.circleci/config.yml, tooling/modified-packages.js
Changes in circle ci config changes to address:
1. changes replacing npm with yarn commands
2. added cache restore step
---
=> build: circle ci cache restore added

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/peer-connection-manager/index.js
Allows to reach remote video stream to 1080p when local stream is set to 1080p and the requested one also set to 1080p (HIGH)
Able to achieve 1080p in the remote stream
Screenshots
---
=> fix(plugin-meetings): allow remote video stream to reach 1080p

.circleci/config.yml, SCRIPTS.md, packages/@webex/internal-plugin-ediscovery/README.md, packages/@webex/plugin-meetings/internal-README.md
Fixes the broken tap test and updated documentation 
---
=> build: update the tap test and documentation for yarn

packages/@webex/webex-core/src/config.js
Remove old unused config param
---
=> chore(config): remove unused config param

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/meeting/index.js, packages/@webex/plugin-meetings/src/statsAnalyzer/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js, yarn.lock
PR for **sdk_v3** branch
The enums changed so thay're camel case not all upper case
[spark-379329](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-379329)
=> fix: update to latest webrtc-media lib that uses ConnectionState from WCME

docs/samples/browser-plugin-meetings/app.js
Fixes the Admit button functionality in the samples app for plugin-meetings.
Admit button works as expected.
---
=> fix(samples): fix admit button functionality

packages/@webex/internal-plugin-voicea/src/voicea.ts, packages/@webex/internal-plugin-voicea/test/unit/spec/voicea.js
Currently the code allows users to register for events multiple times. by adding a flag inside the class, we will register the events only once.
---
=> Fix event listeners for closed captions

packages/@webex/plugin-meetings/package.json, yarn.lock
Bring in newer `@webex/internal-media-core` that has the fix for https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-383407
=> fix: bump @webex/internal-media-core

packages/@webex/plugin-meetings/src/media/index.js, packages/@webex/plugin-meetings/src/media/internal-media-core-wrapper.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts
jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-385742
=> fix: unit tests for Media.createMediaConnection() added

.yarnrc.yml, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, yarn.lock
This PR is for updating SDK beta to latest WCME dependencies - they are all public now.
=> fix: update WCME deps

packages/@webex/internal-plugin-voicea/README.md, packages/@webex/internal-plugin-voicea/src/voicea.ts, packages/@webex/internal-plugin-voicea/test/unit/spec/voicea.js
Triggers should be based on locus state and not local state of the plugin, thereby removing them
Removing local state for transcribing status and following event triggers
---
=> fix(voicea): remove custom state and triggers for webex assistant

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html
Added a "Get stats" button and also showing stats when user does a CTRL+click on a video pane.
=> feat: showing stats results in logs on CTRL+click on a video pane in the sample app

.github/pr-title-checker-config.json, .github/workflows/pr-title-checker.yml
Configured workflow for pull request title checker
Configured workflow for pull request title checker
Added below 2 files - 
.github/pr-title-checker-config.json
.github/workflows/pr-title-checker.yml
---
=> ci: configure workflow for pull request title checker

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Renamed the following private methods from Meeting class:
- stopFloorRequest() renamed to releaseScreenShareFloor()
- share() renamed to requestScreenShareFloor()
because the names were confusing, especially the share() method name which was very vague and generic.
=> refactor(plugin-meetings): renamed methods for requesting/releasing share floor

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/config.ts, packages/@webex/plugin-meetings/src/locus-info/infoUtils.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/infoUtils.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, yarn.lock
As we introduce more meeting features that require LLM we should have a way to automatically connect the data channel when available.
I've added an ensureLLMConnected method that will check the currently connected channel's locus URL and disconnect/reconnect as necessary.
ensureLLMConnected is called initially on join, whenever the locus info changes and on meeting cleanup.
I've added a new meetings config parameter `enableAutomaticLLM` so users of the SDK can opt in to automatically connecting LLM.
---
=> feat(plugin-meetings): automatically connect llm

.circleci/config.yml
This PR is for fixing checkout step which was failing with error `Directory (/home/circleci/webex-js-sdk) you are trying to checkout to is not empty and not a git repository` in integration test step. 
Made the `checkout step` first in integration test as per [this](https://discuss.circleci.com/t/cannot-checkout-anymore/46671/4) discussion on circle ci forum. Verified the changed on circle ci, all steps are now passing.
---
=> ci: checkout step failure fix in circle ci

config/tsconfig.typecheck.json, package.json, packages/@webex/internal-plugin-dss/test/unit/spec/dss.ts, packages/@webex/internal-plugin-llm/src/llm.types.ts, packages/@webex/internal-plugin-voicea/src/voicea.ts, packages/@webex/internal-plugin-voicea/src/voicea.types.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/src/media/properties.ts, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/meetings/request.ts, packages/@webex/plugin-meetings/src/member/util.ts, packages/@webex/plugin-meetings/src/members/request.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/src/reactions/reactions.type.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/index.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts, tooling/lib/test/mocha.js, tsconfig.json
Adds type check during the build process , also runs some basic checks on js files as well 
---
=> build: enable type check on build

packages/@webex/plugin-meetings/src/config.ts
Link for documentation https://github.com/webex/webex-js-sdk/wiki/TLS-443-Support
---
=> feat: enable turn tls support by default

.eslintignore, .gitignore, package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/tsconfig.json, yarn.lock
Exports the plugin-meetings types and fixes the pipeline 
Configure tsconfig to export types
---
=> feat: export types for the meetings SDK

packages/@webex/internal-plugin-llm/src/llm.ts
removes the circular dependecy for plugin llm
---
=> fix: remove logger as circular dependency

package.json
=> fix: run typecheck only on pr checks

package.json
=> fix: script to postbump

packages/@webex/plugin-meetings/package.json
Fix build script in plugin meetings
---
=> chore(plugin-meetings): fix build script

packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/index.js, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/reactions/reactions.ts, packages/@webex/plugin-meetings/src/reactions/reactions.type.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-399316
- export reaction constants
- add types declarations under dist
export constants
change package.josn to point to new destination for types
---
=> feat(reactions): export constants and fix types

packages/@webex/plugin-meetings/src/meetings/util.ts, packages/@webex/plugin-meetings/test/integration/spec/converged-space-meetings.js, packages/@webex/plugin-meetings/test/utils/constants.js, packages/@webex/plugin-meetings/test/utils/testUtils.js, packages/@webex/plugin-meetings/test/utils/webex-config.js, packages/@webex/plugin-meetings/test/utils/webex-test-users.js, packages/@webex/test-users/src/whistler.js
The scope of the changes in this pull request are to add the necessary test to validate if a converged organization operates as expected when used within the `meetings` plugin. The changes include source changes amending the `roapConnectionService` as a key to the `meeting.mediaProperties.webrtcMediaConnection` object for reference in both tests, debugging, and conditional reactions.
**NOTE** - The ENV variable `WEBEX_CONVERGED_ORG_ID` must be set in order for this tests to operate as expected.
[JIRA](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-385748).
=> test(plugin-meetings): converged meetings testing users

.github/CODEOWNERS
Add the meetings sample app to the web client in the codeowners file.
=> chore(codeowners): add meetings sample app to web client in codeowners

packages/@webex/common/src/uuid-utils.js
=> docs(plugin-common): remove unused parameter

packages/@webex/plugin-meetings/src/index.js
Export the RemoteMedia class so it can be used by consuming applications
---
=> feat(meetings): export RemoteMedia class

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlotManager.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-410929
Cyclic dependency in SDK, for example: 
plugin-meetings/src/breakouts/breakout.ts -> plugin-meetings/src/members/index.ts -> plugin-meetings/src/multistream/receiveSlotManager.ts -> plugin-meetings/src/meeting/index.ts -> plugin-meetings/src/breakouts/breakout.ts -> plugin-meetings/src/members/index.ts
Removing the dependency of ReceiveSlotManager on Meeting.
- [] Bug fix (non-breaking change which fixes an issue)
---
=> fix: remove dependency of ReceiveSlotManager on Meeting

packages/@webex/internal-plugin-board/src/board.js, packages/@webex/internal-plugin-board/test/integration/spec/board.js, packages/@webex/internal-plugin-conversation/src/share-activity.js, packages/@webex/internal-plugin-device/src/device.js, packages/@webex/internal-plugin-encryption/package.json, yarn.lock
The scope of the changes in this pull request are to migrate a fix from `master` branch to this `beta` branch.
See [this pull request](https://github.com/webex/webex-js-sdk/pull/2672) for the original implementation.
Updated to fix:
* `internal-plugin-board` tests
* `plugin-browser-authorization` will be fixed with ENV Updates.
=> fix(conversations): various general packages

docs/samples/browser-auth/app.js, docs/samples/browser-auth/index.html, packages/@webex/plugin-authorization-browser/package.json, packages/@webex/plugin-authorization-browser/src/authorization.js, packages/@webex/plugin-authorization-node/package.json, packages/@webex/plugin-authorization-node/src/authorization.js, yarn.lock
In js sdk samples, we needed user to enter only `Guest issuer Id` and `Guest issuer Secret` and our samples should internally create jwt and should authenticate if valid id and secret is provided and should generate access token.
1. Added `createJwt()` method in both `plugin-authorization-browser` and `plugin-authorization-node`.
2.  Updated browser-auth in samples for user to enter Guest issuer Id, Guest issuer secret and display name which will generate access token if valid credentials are provided.
---
=> feat: added create jwt method in authorization

README.md, packages/@webex/internal-plugin-metrics/src/metrics.js, packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js, packages/webex/README.md
This is cherry picked PR to beta Branch for This PR https://github.com/webex/webex-js-sdk/pull/2641 changes
removed org_id, client_id and user_id tags from operational metrics,
added client_id as part of fields instead of tags
added/updated unit test for the same
files - 
packages/@webex/internal-plugin-metrics/src/metrics.js
packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js
removed org_id, client_id and user_id tags from operational metrics,
added client_id as part of fields instead of tags
added/updated unit test for the same
`client_id` has been added to the field, PFA for the same as proof value has been passed in payload.
--- …
=> fix(metrics): remove org_id, client_id and user_id tags from operational metrics

docs/samples/browser-plugin-meetings/index.html
Minor fix for sample app not playing back the local audio back unless someone want to hear the BNR etc 
---
=> chore: mute local audio playback by default

packages/@webex/test-helper-appid/package.json, packages/@webex/test-helper-server/package.json, packages/@webex/webex-core/package.json, yarn.lock
This PR resolves below dependabots-alerts currently we have:
1. `dicer` -  https://github.com/webex/webex-js-sdk/security/dependabot/99
2. `jsonwebtoken` - https://github.com/webex/webex-js-sdk/security/dependabot/113, https://github.com/webex/webex-js-sdk/security/dependabot/115, https://github.com/webex/webex-js-sdk/security/dependabot/119, https://github.com/webex/webex-js-sdk/security/dependabot/120, https://github.com/webex/webex-js-sdk/security/dependabot/121
1. dicer is an indirect dependency of multer so updated multer version to latest which is `1.4.5-lts.1`
2. jsonwebtoken was upgraded to latest which is `9.0.0`
**NOTE**: Those integration tests are failing which fails in master as well. We have a separate Jira to fix them.
Current PR failing tests summary: …
=> build: upgraded multer and jsonwebtoken version

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html
Going forward samples are going to provide you guest tokens when demanded 
---
=> chore: update samples to give guest tokens

docs/samples/browser-plugin-meetings/app.js, packages/@webex/plugin-meetings/src/breakouts/README.md, packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-400360
[fix: add anyoneCanJoin param to assign function]
update assign function、README.MD、unit test
---
=>  fix: add anyoneCanJoin param to assign function

packages/@webex/plugin-meetings/src/meeting/index.ts
partially: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-415545
Missing correlation id in SDK logs
Added correlation id to logs so it's easier to find corresponding server logs
---
=> fix: added correlation id to logs

packages/@webex/plugin-messages/src/messages.js, packages/@webex/plugin-messages/test/integration/spec/messages.js
Support ticket created: 114288 
Add a feature to update existing messages. The update function takes 2 arguments original message and the altered message, and it returns a response from the Webex API call.
Users can update existing messages in the room using JS SDK.
1. Updated Existing Message
2. Updated Existing Message, passed message object, and altMessage object (Result: Message Updated)
3. Update existing message, pass message id and altMessage with roomId (Result: Message Updated)
4. Update existing message, pass message id and altMessage object without roomId (Result: Message not updated)
Manual
- [x ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitt …
=> feat: Add feature to update already created message in the room

packages/@webex/webex-core/package.json, yarn.lock
Removed self import from webex-core package.
---
=> build(webex-core): removed self import

.github/workflows/pull-request.yml
Updating actions to use proper hash.
=> fix(automation): lock hash

.github/workflows/pull-request.yml
=> fix(automation): changed has script

.github/workflows/pull-request.yml
The scope of the changes in this pull request are to fix the automation pipeline hash reference for validation.
=> fix(automation): attempt 3

packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts
We decided to temporarily fix this in the SDK.  Please not that we've discussed this with Brian Baldino and he agreed to have his team fix this in the JMP layer (@webex/json-multistream), but that might take a while and has some other implications.
This is a temp fix to avoid sending duplicate SCRs AND to avoid delays. 
- add logic to compare previous requests to new ones
- unit tests, manual test
---
=> feat(plugin-meetings): duplicate-SCRs - remove duplicates temp fix

packages/@webex/plugin-meetings/test/integration/spec/converged-space-meetings.js, packages/@webex/plugin-meetings/test/utils/testUtils.js
Updated converged-space-meetings test
=> fix: testUtils

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
This handles failed meeting info requests, rejected with 403s due to various policy reasons.
* Introduce new MeetingInfoV2PolicyError
* throw the new error when the specific codes are returned from the meeting info request
* put the code and the failure reason of POLICY on the meeting object
---
=> feat(plugin-meetings): policy error handling

packages/@webex/media-helpers/test/unit/spec/webrtc-core.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js
Part of https://github.com/webex/webex-js-sdk/pull/2694
Added unittests for muteState.ts and webrtc-core.js
=> fix: added unitttests

packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
<ASSOCIATED ISSUE NUMBER/TRACKING LINK (REQUIRED)>
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-422176
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-400364
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-429048
SPARK-422176: append CA event for the case of Many times users abandon meetings by just closing the browser tab.
The SDK should support the post event method for third parties to meet the requirements of Call Analyzer.
SPARK-400364: get pre-assignments info for breakout session.
one issue overwrites the original 'groups', so change to new nodes as 'preAssignments'.
SPARK-429048: When we join a meeting from the page in "Join via browser", the correlationid will be released in the sdk, and the crosslaunch case should keep the …
=> feat(CA): fixed CA & BO issues for the base functions

.circleci/config.yml, webpack.config.js
There is no specific Jira for this. The PR is Ad-hoc
The `versioning_and_publish` CI step is failing due to a webpack issue. It is not able to find the build meeting file in the dist
Corrected the entry point for meetings SDK and removed `yarn build` script from `versioning_and_publish` step
---
=> chore: webpack config entry point update

packages/webex/src/meetings.js
This is an ad-hoc PR. Does not have a Jira
The previous merge did not make a release because of the regeneration of the token.
The token is updated now and this is a dummy PR to make a patch release happen when we merge to master
---
=> fix(meetings): commit for patch release

packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-432497
the installedOrgId must also be passed to the spaceInstant API when creating an instant space meeting
---
=> Installed org id space instant

packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/src/meeting-info/utilv2.ts
Update the jsdoc strings for installedOrgID
---
=> feat(plugin-meetings): jsdoc for installedOrgID

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
This is to bring in a newer version of internal-media-core as it contains some bug fixes,
---
=> fix: upgrade internal-media-core to version 1.38.1

packages/@webex/plugin-meetings/src/annotation/annotation.types.ts, packages/@webex/plugin-meetings/src/annotation/index.ts, packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/annotation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
feat(Live-Annotation): update for new protocol
https://confluence-eng-gpk2.cisco.com/conf/display/WMT/Annotation+Protocol+Detail+Definition
---
=> feat(Live-Annotation): update for new protocol

packages/@webex/media-helpers/README.md, packages/@webex/media-helpers/package.json, packages/@webex/media-helpers/src/index.ts, packages/@webex/media-helpers/src/webrtc-core.ts, packages/@webex/media-helpers/test/unit/spec/webrtc-core.js, yarn.lock
This PR have changes where we are exporting effects from `web-media-effects` repo in the `media-helper` package. Also updated the readme file to explain a very basic usage of VirtualBackground and NoiseReduction effect.
---
=> feat(media-helper): add effects from web media effects

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/util.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meetings/utils.js
Helps: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-435515
-add more behavioural metrics
- add new behavioural metric, improve media failed metric
-unit, manual tests
---
=> feat(media-timeout): add more metrics

.eslintrc.js, packages/@webex/internal-plugin-conversation/test/integration/spec/create.js, packages/@webex/internal-plugin-conversation/test/integration/spec/encryption.js, packages/@webex/internal-plugin-dss/package.json, packages/@webex/internal-plugin-dss/src/dss.ts, packages/@webex/internal-plugin-dss/test/unit/spec/dss.ts, packages/@webex/internal-plugin-encryption/test/integration/spec/kms.js, packages/@webex/plugin-meetings/src/common/logs/logger-proxy.ts, packages/@webex/plugin-meetings/src/locus-info/index.ts, packages/@webex/plugin-meetings/src/locus-info/parser.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meetings/index.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/src/reconnection-manager/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/test-helper-chai/src/assertions/primitives.js, packages/@webex/test-helper-chai/src/assertions/schemas.js, yarn.lock
Fix up some eslint issues particularly with typescript and chai. Changes made while working on https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-378003 but seemed better to make a separate PR.
Mixed bag of eslint fixes.
---
=> chore: eslint improvements

packages/@webex/plugin-meetings/src/annotation/annotation.types.ts, packages/@webex/plugin-meetings/src/annotation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/annotation/index.ts
Fix change annotation options 
---
=> fix(Live-Annotation): fix change annotation options

.circleci/config.yml
The existing [Meetings Sample](https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/) can load two different SDKs.
- The Webex Web SDK (webex.min.js) (https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/)
- The Webex Meetings SDK (meetings.min.js) (https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/?meetings=true)
This works fine in the local build with the command `yarn samples:serve` but on the production sample build, the `meetings.min.js` seems to be missing.
The issue was that `meetings.min.js` was not part of the File System in the `webex.github.io/webex-js-sdk` site because it was not pushed to the repository via the CI scripts. This change stages and pushes the `meetings.min.js` and its related files to GitHub. 
---
Make sure to …
=> docs(samples): push meetings sdk files to git doc commit

packages/@webex/internal-plugin-dss/test/unit/spec/dss.ts, packages/webex/src/calling.js, webpack.config.js
the Calling class in the calling SDK `packages/webex/calling.js` not importing correctly for the umd builds.
in the webpack config to indicate which entry point will have what library name
---
=> chore(webpack): separate library mentions for each entry point

packages/@webex/internal-plugin-encryption/src/kms-certificate-validation.js, packages/@webex/internal-plugin-encryption/test/unit/spec/kms-certificate-validation.js
Fixes KMS certificate name validation when the certificate uses a hostname with mixed case
Since parseUrl automatically does a toLowerCase, I now do the same for the SAN
---
=> fix(internal-plugin-encryption): allow mixed case SAN

packages/webex/package.json, packages/webex/src/meetings.js, packages/webex/src/webex.js
In the existing latest version of SDK, we can only import the meetings SDK as below,
```
import Webex from 'webex/dist/meetings';
```
which is not usual
This PR addresses the above issue by updating the package.json to export index file separately and meetings file separately. Now we are able to import meetings as below,
```
import Webex from 'webex/meetings';
```
---
=> fix(meetings): update package with import paths

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
update of internal-media-core version to have more logging to help with investigation for [SPARK-438031](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-438031)
=> fix: update internal media core

packages/@webex/test-users/src/index.js
Integration tests in meetings plugin often fail at the start - just failing to create a space, so after that everything else will fail too, because all other tests depend on having that space.
This is because the test org has "basicMessage" entitlement, but when we create the test users we don't ask for that entitlement, so the entitlement is assigned to the users automatically from the org, but that takes some time - it requires multiple backend services to talk to each other, so if the test tries to create a space before that entitlement is given to the user, then it will fail - a classic race condition.
I'm fixing this by explicitly asking for the "basicMessage" entitlement when creating the test users. This way they have it from the start and we don't need to worry about waiting for …
=> test: improve integration test stability

packages/@webex/plugin-meetings/src/breakouts/index.ts
I found a typo while reading the code, here is the correction of that.
`ALLOWED` duplicated, one of them should be `ASSIGNED`
---
=> fix(breakouts): typo issue

docs/samples/index.html
=> feat(bump): dummy PR

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fix(Live-Annotation): Trigger Annotation info with meeting ID 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-443312?filter=-1 
---
=> fix(Live-Annotation): Annotation info with meetingid 

package.json
- fix package json to include build of internal plugin metrics
---
=> feat(ca-metrics): fix package json

docs/samples/browser-plugin-meetings/app.js
Resolution and frame rate of the video streams is not displayed correctly on samples when we join another meeting after leaving the first meeting.
**UPDATED REQUIREMENT**:
Also we need to separate local video and remote video resolution check interval because local video can be created without joining a meeting. And remote video resolution interval check should be cleared when we leave a meeting but local video resolution interval check should be when we stop the local video.
Did split meetingsResolutionCheckInterval method in 2 d/f methods which are `localVideoResolutionCheckInterval` and `remoteVideoResolutionCheckInterval`. Former is called when we do `getMediaStreams()` and stopped when we stop local video while later is called after `addMedia()` and stopped when leave a meeting. …
=> fix(samples): video resolution issue fix

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts
- fix latency bugs
- some formulas were wrong
- some formulas used wrong timestamps
---
=> feat(internal-plugin-metrics): fix latency bugs

packages/@webex/plugin-meetings/src/annotation/annotation.types.ts, packages/@webex/plugin-meetings/src/annotation/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/annotation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Fix(Live-Annotation): add annotation info for share
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-447345?filter=-1
---
=> fix(Live-Annotation): add annotation info for share

.github/workflows/deploy.yml, .github/workflows/pull-request.yml, packages/@webex/internal-plugin-flag/README.md
The scope of the changes in this pull request are to update the refs and variables in the deploy script to their correct values.
=> fix(automation): recursive job ids for cd

.github/workflows/deploy.yml, packages/@webex/internal-plugin-flag/README.md
The scope of the changes in this pull request are to validate the proposed tag in the automation CD.
=> fix(automation): print packages and tag before processing

packages/@webex/plugin-meetings/src/controls-options-manager/util.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/controls-options-manager/util.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This includes the users self policy in the calculation of the in meeting actions for share.
Added a hasPolicies util analogous to hasHints util
---
=> feat(plugin-meetings): user share policy

packages/@webex/plugin-meetings/src/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
SPARK-438620
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-438620
---
=> feat(plugin-meetings): can transfer file policy check

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Policies and display hints for share don't apply to locus calling
Policies are also not available if you are not using the v2 app api, so I've disabled that requirement for sharing as well
---
=> feat(meetings): ignore policies for sharing if type is CALL

packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/rtcMetrics/constants.ts, packages/@webex/plugin-meetings/src/rtcMetrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts, yarn.lock
Adding webrtc metrics from wcme.
Adding a RtcMetrics class that sends metrics to the telemetry service on an interval.
=> feat(metrics): add webrtc metrics

CONTRIBUTING.md
Removes html/css style from branch freezing notice.
---
=> chore: remove html & css styles from notice

packages/@webex/plugin-meetings/src/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
issue: SPARK-438603
Handling annotation policy
added necessary checks to handle annotation policy
---
=> feat: add annotation self-policy handling to sdk

packages/@webex/plugin-meetings/src/multistream/receiveSlotManager.ts
=> fix: added mediaType to ReceiveSlotManager logs

packages/@webex/plugin-meetings/src/meeting/util.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-454695
Wrong in parameter effect the updateInterpretation function
change a parameter
---
=> feat: fix a parameter of updateInterpretation

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Start white board in BO then failed end successful
After entering bo, need to update the bo locusUrl in the meeting object
---
=> fix(meeting): trigger message when update locusUrl

packages/@webex/plugin-meetings/src/rtcMetrics/index.ts
Changes in the required data structure of metrics stats.
Updating the metrics' request POST body
---
=> fix: update metrics body for use with telemetry service

packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
=> feat(videorestrict): added test to trigger release

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Feat(Live-Annotation): Remove the annotation info for share
https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/New+Annotation+in+Webex+Web+Client+Design
---
=> fix(Live-Annotation): remove the presenter side annotation info

docs/samples/browser-plugin-meetings/app.js, packages/@webex/media-helpers/src/index.ts, packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts
The `published-state-update` event is not emitted from SDK when we publish or unpublish a stream.
1. Emitted `published-state-update` from SDK from both publish and unpublish method with `isPublished`, `mediaType` and `stream` data on meeting object.
2. Samples page updated to listen for above event with some other small code fixes.
3. Tested samples app with the above triggered. Everything working fine.
TODO: Need to update test cases which will be done after Kesava's UTs refactor [PR](https://github.com/webex/webex-js-sdk/pull/3053) merges. Need to target merge of this PR and UTs will be taken care of in a separate PR.
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/C …
=> feat(plugin-meetings): published state update event emitted

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Spark meetings have meeting info but not policy. This change fixes that by not supporting policy if policy is not there, regardless of the meeting type.
---
=> feat(plugin-meetings): fix canDoVideo

.eslintrc.js, packages/calling/src/CallingClient/CallingClient.test.ts, packages/calling/src/CallingClient/CallingClient.ts, packages/calling/src/CallingClient/callingClientFixtures.ts, packages/calling/src/CallingClient/line/index.ts, packages/calling/src/CallingClient/line/line.test.ts, packages/calling/src/CallingClient/metrics/index.test.ts, packages/calling/src/CallingClient/metrics/index.ts, packages/calling/src/CallingClient/metrics/types.ts, packages/calling/src/CallingClient/registration/register.test.ts, packages/calling/src/CallingClient/registration/register.ts, packages/calling/src/CallingClient/registration/types.ts, packages/calling/src/CallingClient/types.ts, packages/calling/src/common/Utils.ts, packages/calling/src/common/testUtil.ts
NOTE: This PR is duplicate of [PR](https://github.com/webex/webex-js-sdk/pull/3035) which got messed up because of rebasing to next.
Unit test added and refactored for below files:
1. line.test.ts
2. register.test.ts
3. callingClient.test.ts
4. metrics.test.ts
Refactor work done for following files:
1. line.ts
2. register.ts
3. callingClient.ts
4. metrics.ts
5. testUtils.ts
Added and refactored unit tests. Also done refactor work.
---
=> test(calling): test refactored and added

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
- add isConvergedArchitectureEnabled 
- add new metadata
---
=> feat(ca-metrics): add converged architecture flag

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
=> Test pipeline changes locally

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
-fix error handling for locus response
- grab nested error
---
=> feat(ca): fix locus errors

packages/@webex/internal-plugin-dss/src/dss.ts, packages/@webex/internal-plugin-dss/src/types.ts, packages/@webex/internal-plugin-dss/test/unit/spec/dss.ts
Refer to master branch PR for details: https://github.com/webex/webex-js-sdk/pull/2934
This PR is to merge this search places feature from master branch to beta branch.
Refer to master branch PR for details: https://github.com/webex/webex-js-sdk/pull/2934
There are unit tests to cover above functions automatically.
- [] I discussed changes with code owners prior to submitting this pull request
---
=> feat(internal-plugin-dss): support search places feature in beta branch (merge from master)

packages/@webex/internal-plugin-calendar/package.json, packages/@webex/internal-plugin-calendar/src/calendar.decrypt.helper.js, packages/@webex/internal-plugin-calendar/src/calendar.encrypt.helper.js, packages/@webex/internal-plugin-calendar/src/calendar.js, packages/@webex/internal-plugin-calendar/src/index.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.decrypt.helper.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.encrypt.helper.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.js, yarn.lock
Merge code from master branch to beta branch to support unified web scheduler functions
The main functions including:
- create/update/delete calendar event with Webex meeting.
- fetch free/busy status of users.
There are unit test cover above functions automatically.
---
=> feat(internal-plugin-calendar): support unified scheduler in beta branch (merge from master)

.github/workflows/deploy.yml
Adds the npm_token as an environment variable in the deploy pipeline
Adding a step in the deploy.yml to configure the .npmrc with the pipeline deploy npm token
---
=> chore(deploy): add step to configure npm token

.github/workflows/action.yml, .github/workflows/deploy.yml
=> chore(docs): pipeline changes

.github/workflows/deploy.yml
Tests a change in deploy
changed deploy.yml
---
=> chore(deploy): test npm token

packages/calling/package.json
Tests deploy of calling package.
package.json
---
=> chore(calling): test calling deploy

.github/workflows/deploy.yml
Pushing to documentation is failing with the below error:
error Couldn't find a package.json file in "/home/runner/work/webex-js-sdk/webex-js-sdk"
Added the setup steps back
---
=> chore(docs): added steps back

docs/samples/browser-plugin-meetings/app.js, packages/@webex/media-helpers/src/webrtc-core.ts, packages/@webex/plugin-meetings/src/media/index.ts, packages/@webex/plugin-meetings/src/media/properties.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/muteState.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/reconnection-manager/index.js
The fix for the tests that are broken due to stream-classes refactor
=> fix(plugin-meetings): stream-classes refactor and tests

packages/calling/package.json
Adds a contributor in the package.json for calling.
update package.json in calling
---
=> chore(calling): update contributor in calling

packages/calling/package.json
Adds contributors
package.json
---
=> chore(calling): add contributors and test pipeline

packages/calling/package.json
Updates contributors
package.json
---
=> chore(calling): update contributors to test deploy

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, packages/@webex/plugin-meetings/src/meeting/index.ts
Issues in the Webex Web SDK Sample app related to Multistream meetings
=> docs(samples): fix multistream sample app bugs

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Don't use display hints for voip policy
---
=> feat(plugin-meetings): don't use voip display hint

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-462656
There was a bug in WCME causing issues with sending audio and video
Update internal-media-core version to the new one that contains WCME version with the bugfix.
---
=> fix: update internal-media-core to 1.39.2

docs/samples/calling/app.js, docs/samples/calling/index.html
1. Calling an invalid number, disables the makeCall btn.
RC: While ending a call we try to remove the profile img from the page. For users without a profile picture we were getting an error.
2. call disconnect event was not getting 
RC:event name not was correct
3. Couldnt trigger a consult transfer flow.
RC : makeCall was being triggered from callingClient object rather than line object.
https://github.com/webex/webex-js-sdk/assets/72344404/baec1d07-3c02-42e7-9632-379ce0d11d70
https://github.com/webex/webex-js-sdk/assets/72344404/18af4d44-5ba6-4925-a1b8-a122111e0e1e
- Call to invalid number
- Call to valid number
- Call to a busy user
- Consult transfer flow
--- …
=> fix(calling): minor fix in samples page

packages/@webex/media-helpers/package.json, packages/webex/package.json
Fixing deploy issue of webex
Updated deploy:npm command in package.json
---
=> fix(pipeline): added deploy:npm

.github/workflows/deploy.yml, .yarnrc.yml, packages/@webex/media-helpers/package.json, packages/calling/package.json, packages/webex/package.json
Deploy CD pipeline fix for npm publishing
Adde changes in .yarnrc.yml and deploy.yml file
---
=> fix(pipeline): reverted from npm publish to uarn npm publish

.github/workflows/deploy.yml
Fix for previous PR:https://github.com/webex/webex-js-sdk/pull/3133  yaml error in deploy.yml file
---
=> fix(pipeline): fixing syntax error in deploy.yml file

packages/webex/package.json
dependency versions inside package.json on NPM repo
minor changes in package.json for webex
---
=> chore(webex): publish new version of webex to fix versions

packages/@webex/media-helpers/package.json
npm install issues due to dev-dependencies being added to dependencies
moved legacy tool packages into dev-dependencies as they are not needed in regular npm installation
---
=> chore(media-helpers): fix dev deps

.github/workflows/deploy.yml, packages/@webex/media-helpers/package.json
the missing files in dist folder for the packages
adding a section to build all packages locally before publishing them to NPM registry
---
=> chore(deploy): build all packages during deploy

.github/workflows/deploy.yml, package.json, packages/@webex/media-helpers/package.json
build issues within the packages before publishing. Not all the required files are present, causing compilation issues in consumer applications.
created a new command `yarn build:publish` for the purpose of publishing packages.
---
=> chore(deploy): fix the package build for publish

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-458895
---
=> feat(prejoin): added env and launch method

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts
- fix formula for call init join request
- fix unit test
- fix formula
- unit test
---
=> feat(ca): fix formula for call init join rq

docs/index.html, package.json, packages/@webex/media-helpers/package.json, packages/calling/src/CallHistory/CallHistory.ts, packages/calling/src/CallSettings/CallSettings.ts, packages/calling/src/CallSettings/types.ts, packages/calling/src/CallingClient/CallingClient.ts, packages/calling/src/CallingClient/calling/call.test.ts, packages/calling/src/Contacts/ContactsClient.ts, packages/calling/src/Contacts/types.ts, packages/calling/src/api.ts, yarn.lock
Adding descriptions to the exported types properties.
Changes added for below types:
CallForwardSetting
CallForwardAlwaysSetting
VoicemailSetting
Contact
ContactGroup
---
=> fix(calling-docs): adding description for internal type exported

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/index.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/src/utils.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/utils.ts
- refactor latency formula
- fix CA logs
- refactor
- manual test, unit test
---
=> feat(ca): fix logs, refactor formula

packages/calling/src/api.ts
Fix Test Style check from last PR.
---
=> fix(calling-docs): fix style error

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts
- add pre login support for client exit app
- fix pre login body structure for events
- refactor, but fix
- unit test, manual test
---
=> feat(ca): prelogin fixes

packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-468971
---
=> fix(ca): protecting against undefined

.github/workflows/deploy.yml, packages/webex/package.json
an issue with the samples page on https://webex.github.io/webex-js-sdk. The min.js file versions are set to 'undefined'.
Syncing the version of all webex packages before running the command to build docs and samples
---
=> chore(deploy): fix the documentation section in deploy script

packages/@webex/internal-plugin-metrics/package.json, yarn.lock
updates event dictionary to one with a lower node requirement, to avoid having to upgrade node
---
=> fix: upgrade event dictionary

packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
Experiencing a failure when attempting to start an instant space meeting URL: https://co.webex.com/wbxappapi/v2/meetings/spaceInstant.
The error message received is '416 Range Not Satisfiable' with the response '416020' and message 'e2ee decrypt error.'
should pass encrypted title based on APPI API ("/wbxappapi/v2/meetings/spaceInstant) Team.
Updated the code and tests for this.
[Will add]
Tested some basic manual flow and also attached the screen recording -
- Register
- Create ad-hoc meeting with conv URL
- Join with media
- Checked participants
- checked if meeting is started in space or not
- leave
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#subm …
=> fix(meetings): pass encrypted title based on APPI API for conversation

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
This PR is just a copy of PR: https://github.com/webex/webex-js-sdk/pull/3176 merged into next branch.
---
=> fix(plugin-meetings): start transcription when guest user is admitted

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-471365
---
=>  fix(ca-metrics): add specific error handling for locus error code 2423021

packages/@webex/plugin-meetings/test/integration/spec/converged-space-meetings.js, packages/@webex/plugin-meetings/test/integration/spec/journey.js, packages/@webex/plugin-meetings/test/integration/spec/space-meeting.js, packages/@webex/plugin-meetings/test/utils/integrationTestUtils.js
Fixes the failing integration tests
All 52 failing integration tests are passing.
---
=> fix(tests): failing integration tests fixes

package.json
=> fix: upgrade  node to 16 default

packages/@webex/media-helpers/package.json, yarn.lock
In Stable version , will install in nodejs  and run the application
for the beta version , not able to run the application and throws error
error:
ReferenceError: self is not defined
https://github.com/webex/web-media-effects/pull/57
In the samples app, blur, image and video background was tested.
---
=> fix: update-web-media-effects-version

docs/samples/browser-plugin-meetings/index.html
the last merge from latest beta on the stream-classes branch had a conflict and that conflict was not resolved correctly
the conflict was in the sample app index.html file between these 2 PRs:
https://github.com/webex/webex-js-sdk/pull/3125
https://github.com/webex/webex-js-sdk/pull/3172
fixed the conflict
checked sample app manually
---
=> fix: wrong merge conflict resolution from stream-classes branch

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/reachability/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Added reachability results to metrics for addMedia() failure or success
related jira:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-477129
=> fix: added metrics to addMedia success/failure metrics

packages/@webex/plugin-meetings/src/locus-info/mediaSharesUtils.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/locus-info/mediaSharesUtils.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-421238
the issue when a user is joined from different clients (web and native) and shares screen using native client then web client doesn't receive the screen share content. 
Also started comparing `deviceUrl` so we can send the remote share event to same user as well if they are logged in from multiple different devices and sharing locally via web-client.
---
=> fix(plugin-meetings): screen share when shared by same user different client

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
Currently NetworkOrCORSErrors raised by the SDK appear as an unknown error.
Reclassify these errors to be NetworkErrors
---
=> feat(plugin-metrics): classify network errors

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/metrics/constants.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Add metrics to track the latency of the difference steps within addMedia.
---
=> fix(plugin-meetings): add latency metrics for addMedia

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/test-helper-chai/src/index.js
- categorize ice failures with more granular errors
- refactor
- add new client errors codes
-unit test
---
=> feat(media): add ice failure groupings for CA

.github/ISSUE_TEMPLATE/config.yml
not being able to create issues in the webex-js-sdk repository
Providing a new template for issues
None required
---
=> docs(issues): new template for creating issues

.github/ISSUE_TEMPLATE/config.yml
the inability to create an issue. The issues page only allows the opening of the link to Developer support
Fixing the template by removing the contact link block from the yaml.
No tests needed
---
=> docs(issues): fix issue in the new template

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
=> feat(plugin-metrics): payload overrides

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/plugin-meetings/src/meeting-info/index.ts, packages/@webex/plugin-meetings/src/meeting-info/meeting-info-v2.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js
use confIdStr instead of confID if defined
See above
Unit tests with new prop
---
=> fix(metrics): update to confIdStr

docs/samples/browser-plugin-meetings/app.js, docs/samples/browser-plugin-meetings/index.html, docs/samples/browser-plugin-meetings/style.css
Meetings samples page had become a bit clumsy with the addition of new features like multi-stream, allowing to play with local media prior to joining a meeting.
Re-arrange the UI elements and make the UI/UX easy to navigate and reason
https://github.com/webex/webex-js-sdk/assets/131742425/32cf790c-767c-436f-9d4f-ca3524bef125
**New collapse all**
https://github.com/webex/webex-js-sdk/assets/131742425/fb8b6d3e-95db-408c-aa5d-d2816db63ef8
**Global expand and collapse buttons**
https://github.com/webex/webex-js-sdk/assets/131742425/90f2b37f-ed44-450c-b277-7e69286f3850
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before …
=> fix(samples): reorder and group the ui with similar features

packages/@webex/plugin-meetings/src/rtcMetrics/index.ts, packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts
Masking IP addresses in telemetry data.
Checking local and remote candidates in stats-reports and anonymizing their ip address fields. 
---
=> fix(meetings): mask ip address in webrtc metrics

packages/calling/src/CallingClient/registration/register.ts
Registration event is emitted but registration status is inactive.
Registration event is emitted, registration.registrationStatus is updated after the event is triggered. This causes the getStatus API to return an inaccurate status.
We first change the status and then emit the event
**Logging line.getStatus()** 
BEFORE----------------------------------------------------------------------AFTER
---
=> fix(calling): register-event-status-mismatch

packages/@webex/internal-plugin-calendar/src/calendar.js, packages/@webex/internal-plugin-calendar/test/unit/spec/calendar.js
Defer prefetching a encryption key for the calendar plugin until the user is authorized, and only when they are not an unverified user (guest users currently have no use for the calendar, so are unlikely to need to prefetch an encryption key).
Before this change, if the user hadn't authorized within 10s of the SDK becoming "ready", there would be an error, and the prefetch wouldn't work at all.
Note that I didn't add complete tests for the actual key creation as they didn't exist previously, so I considered this outside of the scope of the changes.
---
=> feat: defer calendar encryption key prefetch until authorized

packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
=> fix(internal-plugin-metrics): remove only from test

packages/@webex/plugin-meetings/src/meeting/index.ts
Just adding a comment to trigger deploy
---
=> fix(meetings):Trigger deploy

packages/@webex/plugin-meetings/src/meeting/index.ts
One left out issue of previous PR #3344 from the next branch PR
---
=> fix(plugin-meetings): fix type for stream in emitPublishedStateChange

packages/@webex/plugin-meetings/src/meeting/index.ts
Gets latest beta commit into next branch
Cherry-picking the changes
=> fix(plugin-meetings): fix type for stream in emitPublishedStateChanged

.github/workflows/deploy.yml, .github/workflows/pull-request.yml, package.json, packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/src/meeting/index.ts
The `dist/types` isn't getting generated for both `plugin-meetings` and `internal-plugin-metrics`
This PR addresses that issue by
- Adding the right build command to both package.json scripts
- Building webex-core prior to other packages in the CI scripts
- Build command was executed for the whole package to see if types were generated
- Separate package scripts were also executed to see if types get generated
---
=> fix(plugin-meetings): generate types 

packages/@webex/plugin-meetings/src/statsAnalyzer/mqaUtil.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Updating the MQA value for `isMain`.
Checking the media type when populating the MQA.
Ran a test meeting sending and receiving main audio/video and slides audio/video. Verified the MQE data in clpjfk-automateddiagnostics.webex.com.
---
=> fix(plugin-meetings): update isMain in MQA

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, yarn.lock
fixes: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-497203
---
=> fix(meetings): update internal-media-core

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
Fix JMT issues
Add extra logging
---
=> fix: add latency logging

jest.config.js, packages/@webex/plugin-presence/.eslintrc.js, packages/@webex/plugin-presence/README.md, packages/@webex/plugin-presence/babel.config.js, packages/@webex/plugin-presence/jest.config.js, packages/@webex/plugin-presence/package.json, packages/@webex/plugin-presence/process, packages/@webex/plugin-presence/src/config.ts, packages/@webex/plugin-presence/src/constants.ts, packages/@webex/plugin-presence/src/index.ts, packages/@webex/plugin-presence/src/interface.ts, packages/@webex/plugin-presence/src/presence-batcher.ts, packages/@webex/plugin-presence/src/presence-worker.ts, packages/@webex/plugin-presence/src/presence.ts, packages/@webex/plugin-presence/test/integration/spec/presence.ts, packages/@webex/plugin-presence/test/unit/spec/presence-worker.ts, packages/@webex/plugin-presence/test/unit/spec/presence.ts, packages/@webex/plugin-presence/tsconfig.json, packages/@webex/test-helper-mock-webex/src/index.js, yarn.lock
Add plugin-presence as a public plugin for webex with typescript support
- Adds a `plugin-presence` (public) package cloned from `internal-plugin-presence`
- Convert the package to typescript
- Adds proper types wherever it's clear and `any` where it's not clear
- Update UTs and Integration tests
- Skip UTs and Integration test in `internal-plugin-presence` as the `MockWebex` now adds `presence` as public instead of internal method
- Update the `build` command in the `package.json` file
- Updates README
---
=> feat(presence-plugin): add plugin-presence as a public plugin

packages/tools/cli/package.json, packages/tools/package/package.json
The scope of the changes in this pull request are to add the deploy scripts to the `@webex/*-tools` packages. This allows for the official publication of necessary tools for external products to update the SDK based on a provided branch.
=> fix(tools): deploy scripts

packages/@webex/test-users/src/index.js
- Adding docs to trigger a deploy
---
=> fix(test-users): test user set preferred site docs

packages/@webex/plugin-meetings/src/meeting/request.ts
Adds a comment to the installationId appending section to trigger a deploy of this package.
No testable changes.
=> fix(meetings): deploy-pr

packages/@webex/plugin-meetings/src/roap/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/src/roap/turnDiscovery.ts, packages/@webex/plugin-meetings/test/unit/spec/roap/turnDiscovery.ts
removing dead/misleading code from next branch - this was found by doing a diff with the beta branch
=> fix: remove misleading dead code

package.json
`package.json` files get updated with versions and show up in the changeset due to the `yarn build:local` command.
Removed the `yarn package-tools sync` command from `yarn build:local`.
1. Tested the `yarn build:local` command and do not see the package.json files getting added to the change set.
2. Existing UTs are passing.
---
=> fix(tooling): remove sync command from the build

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/voicea-meeting.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/voicea-meeting.ts
The voicea-meetings.ts file were not tested as part of Meetings UT
- Writing UTs for `getSpeakerFromProxyOrStore` method
- Writing UTs for `processNewCaptions` method
- The `processNewHighlights` method is still not tested or planned for release announcement. Therefore, we will do UTs for that as well as part of this ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-509136
UTs were written for
- getSpeakerFromProxyOrStore gets data from Store
- getSpeakerFromProxyOrStore gets data from Proxy
- processNewCaptions gives back appropriate final caption
- processNewCaptions gives back appropriate interim caption
---
=> fix(plugin-meetings): voicea utils test

packages/@webex/plugin-meetings/src/meetings/index.ts
Removes temporary debug metrics.
Tested manually.
- [] I have updated the documentation accordingly
---
=> fix(metrics): remove debug metrics

.github/workflows/pull-request.yml
Reverts the `browser` integration tests to the older tooling 
Change the command in the browser section of the PR yaml file.
No tests. We will update existing PRs and observe the test results
---
=> fix(pipeline): revert to old tooling for browser integration tests

.github/workflows/deploy.yml
Adds the publish tag section in the deploy script
Create a new section in the deploy.yml file
NA
---
=> fix(deploy): add step to publish tag

packages/calling/package.json
Minor change in contributors in calling package
Changed names of contributors
NA
---
=> fix(calling): update names in calling package

.github/workflows/deploy.yml
Issues in the tag deploy
Made changes to the publish tag section of deploy.yml
NA
---
=> fix(deploy): fix message and version for tag publish

packages/calling/package.json
Names of the contributors in the calling package.
Update package file for calling
NA
---
=> fix(calling): update name in contributors

.github/workflows/deploy.yml
Fix command in the pipeline to create tags
Change command in the deploy yaml script
NA
---
=> fix(deploy): fix command in the deploy

packages/calling/package.json
Update names in contributor list
Update package in calling.
NA
---
=> fix(calling): update contributor list

.github/workflows/deploy.yml
Deploy script contains issues with the output variables
Fix the output names in the deploy script
---
=> fix(deploy): fix output names in publish tag job

packages/calling/package.json
Changes the contributor list on the calling package
Update package file for calling
---
=> fix(calling): update contributor list for calling

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
Returns browser tests to new tooling and starts publishing tags for new commits on `next` branch
Changes in the yaml files for the 2 pipelines
NA
---
=> fix(pipeline): move browser test to new pipeline and make tags live

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
An issue in the tag creation logic.
Adds a 'v' before the tag string to be consistent with the current tags being published
NA
---
=> fix(deploy): fix typo in the tag creation logic

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
The update of author information while creating the tag. Currently, tag creation fails due to missing author information.
Added author information in the step before creation of tag
---
=> fix(deploy): Update git author information while creation of tag

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
The publish-tags job in the deploy.yml fails due to more than one line being present in the commit message. Apart from this, there are no exit conditions for the job in corner cases like no package being published or the tag already being present.
Updated the job to add these conditional exits and avoid failures in the pipeline.
NA
---
=> fix(deploy): add exit conditions to avoid publishing error

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
When tag publish isn't required, remaining steps in the job should be skipped, but they still run
Added conditions in the steps to skip the steps in case the value of `proceed` is set to `0`
NA
---
=> fix(deploy): add skip conditions in remaining steps too

.github/workflows/deploy.yml, .github/workflows/pull-request.yml
Issues in the conditions of the publish tags job of deploy.yml
Fixed the bash conditions
NA
---
=> fix(deploy): remove typo from conditions

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/interpretation/index.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/interpretation/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/sendSlotManager.ts
Cherry-picked latest beta. Updated next branch before starting to create a PR on beta for plugin-meetings.
=> Cherry-pick-27-03

packages/@webex/plugin-meetings/test/integration/spec/journey.js, packages/@webex/plugin-meetings/test/integration/spec/space-meeting.js
=> fix(plguin-meetings): removed-async-from-tests

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/metrics.js, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js
Picks the latest changes from the beta branch to the next branch
Cherry-picking the latest changes of commits
---
=> fix(metrics): unknown error payload & appVersion in behavioral metrics 

packages/@webex/internal-plugin-metrics/src/new-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/new-metrics.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-511912
---
=> fix(internal-plugin-metrics): define latency before ready

CONTRIBUTING.md, SCRIPTS.md
The scope of the changes in this pull request are to update the documentation within the various global contribution articles based on the discussions during the live Question and Answer session of `2024-04-11`.
=> docs(contributing): 2024-04-11 q and a

packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-514797
For third party integration join, we need pass userDisplayName as alias in joinMeeting request body.
https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?spaceKey=WMT&title=Third-Party+Integration+Join+Flow+Support+In+UCF
Add alias in joinMeeting request body
---
=> fix(plugin-meetings): add alias in joinMeeting request body: SPARK-514797

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts, yarn.lock
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-515027
---
=> fix(si): import NamedMediaGroup from internal-media-core lib

packages/@webex/internal-plugin-mercury/README.md, packages/@webex/internal-plugin-mercury/src/mercury.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/internal-plugin-metrics/package.json, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics-latencies.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/prelogin-metrics-batcher.ts, packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/meeting/request.ts, packages/@webex/plugin-meetings/src/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/src/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/src/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts, yarn.lock
=> Update next with beta

packages/@webex/internal-plugin-mercury/src/mercury.js, packages/@webex/internal-plugin-mercury/test/unit/spec/mercury.js, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Cherrypicks the last 3 latest commits from beta branch on April 19.
NA
NA
---
=> Cherrypick commits from April 19

packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
Web media effect library update (https://github.com/webex/webex-js-sdk/pull/3557/files) caused couple of unittests to fail
This PR fixes those tests
---
=> fix(plugin-meetings): fixed unittests after effect lib update

packages/@webex/internal-plugin-metrics/src/client-metrics-prelogin-batcher.ts, packages/@webex/internal-plugin-metrics/src/metrics.js, packages/@webex/internal-plugin-metrics/src/prelogin-metrics-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/client-metrics-prelogin-batcher.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/metrics.js, packages/@webex/internal-plugin-metrics/test/unit/spec/prelogin-metrics-batcher.ts, packages/@webex/media-helpers/src/webrtc-core.ts, packages/@webex/plugin-logger/src/logger.js, packages/@webex/plugin-logger/test/unit/spec/logger.js, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/src/roap/request.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Updated next branch with commits from beta as of 2nd may 2024
=> Cherry-pick commits from beta into next -2-5-2024

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/mediaQualityMetrics/config.ts, packages/@webex/plugin-meetings/src/statsAnalyzer/index.ts, packages/@webex/plugin-meetings/test/unit/spec/stats-analyzer/index.js
Updated next with latest beta.
No conflicts.
=> Cherry-pick-10-may

LICENSE, LICENSE.md
clarifications required in the licensing of the Webex JS SDK for contribution from external developers and wider community.
Update the LICENSE.md file with the required changes.
---
=> docs(license): update license for the webex-js-sdk

packages/@webex/test-users/src/index.js, packages/@webex/test-users/test/integration/spec/index.js
dupe of https://github.com/webex/webex-js-sdk/pull/3595
=> fix(test-users): use correct scopes for oauth test user generation

docs/samples/browser-plugin-meetings/index.html
Changes in samples folder regarding typo of Expandall and DTMF
---
=> fix: typo of expandall and dtmf 

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
update internal-media-core to fix the issue with the types for stats reports
=> fix: update internal-media-core and WCME

.github/CODEOWNERS
the issue of the Web SDK team not being added into reviews automatically as codeowners for packages where the Web Client and WCME teams are making changes.
The older CODEOWNERS file was fine because the teams were using different branches (`beta` and `master`). However, now that all teams are using the `next` branch, there is a need to be careful about breaking changes which can cause issues in applications consuming the SDK (Webex Web Client, Instant Connect, Widgets, 3rd party developer applications).
Update @webex/web-sdk as owner for `@webex/plugin-meetings`, `@webex/internal-plugin-voicea` and all their dependent packages as these are the main packages that the SDK team needs notifications on.
NA
--- …
=> chore(codeowners): update codeowners file

packages/webex/package.json, yarn.lock
Issues with installation of `webex` 3.1.0 due to presence dependency issues.
```
$ npm install --save webex@3.1.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @webex/plugin-presence@0.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist. 
```
Removed the `@webex/plugin-presence` package as a dependency.
---
=> fix(webex): remove plugin-presence as a dependency as it is not public

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
Log updated send parameters in WCME.
Updating the WCME/internal-media-core versions.
Tested on the SDK sample app to make sure the logs appear.
---
=> fix(plugin-meetings): log send parameters

packages/@webex/webex-core/src/lib/services/service-catalog.js, packages/@webex/webex-core/test/unit/spec/services/service-catalog.js
After the latest hostmap parsing refactor, the ordering of the services changed. This exposed a bug in findServiceUrlFromUrl, which would find the first host that matched the URL instead of checking the defaultUrl matched.
I changed the algorithm to do the following:
1. check the defaultUrl of the service, if the URL we are checking starts with this defaultUrl then the service matches
2. for each of the hosts for the service, replace the host within the defaultUrl with this host. Then check to see if the URL we are checking starts with this alternate URL
---
=> fix(webex-core): fix findServiceUrlFromUrl

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
This PR addresses the solution for [SPARK-539663](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539663) that introduces new `MediaConnectionConfig` key `iceCandidatesTimeout`.
dump version of `internal-media-core` to `2.7.1`
PR with changes in [internal-media-core](https://sqbu-github.cisco.com/WebExSquared/webrtc-media-core/pull/233)
---
=> fix: update MediaConnection with iceCandidatesTimeout

package.json, packages/calling/package.json, packages/legacy/tools/package.json, yarn.lock
The browser test failures are caused by karma and are not in an updated version.
Upgraded the version of karma to the latest version in calling/package.json
I tested the calling sample app manually it works fine after upgrading to the newer versions also
The following scenarios were tested in an sample app
- Authentication
- Initialization
- Registration
- Call Initialization (outgoing call, incoming call)
- Call Controls(Hold/Resume, Mute/Unmute, Call Transfer)
---
=> chore(deps): Updated Karma dependency to 6.4.3

package.json, yarn.lock
This pull request address the updation of xml2js to 0.5.0 by upgrading appium-abd to 12.5.0
The changes  in package.json  and yarn.lock of the appium-abd to 12.5.0
After upgrading the dependencies I tested through the Kitchen Sink app (Meetings)
- Initialization
- Registration
- Manage Meeting
- Streams
- Screen share
- Participants section 
---
=> chore(deps): upgraded xml2js to 0.5.0

packages/calling/package.json, yarn.lock
**2)** [https://github.com/webex/webex-js-sdk/security/dependabot/161](https://github.com/webex/webex-js-sdk/security/dependabot/161)
This pull request address the upgrading ip to 2.0.1 by upgrading @web/dev-server to 0.4.5.
The changes  in packages/calling/package.json  and yarn.lock of the @web/dev-server dependencies to 0.4.5.
After Upgrading We tested the Sample App(Meetings), It was working fine to me.
-  Authentication
-  Initialization
-  Registration
-  Call Initialization (outgoing call/incoming call)
-  Call controls (hold/resume, mute/unmute)
-  Call transfer (Blind transfer, Consult transfer)
---
=> chore(deps): bumps ip to 2.0.1

package.json, yarn.lock
This pull request address to upgrade the tar dependency to 6.2.1.
By changing the package.json and yarn.lock of geckodriver dependency to 4.4.2 the tar was upgraded to 6.2.1
After upgrading the dependencies we had tested through Meeting Sample App ,It was working fine for me.
- Initialization
- Registration
- Manage Meeting
- Streams
- Screen share
- Participants section 
---
=> chore(deps): bumps tar to 6.2.1 version

package.json, packages/calling/package.json, yarn.lock
It Contains all the dependabot PRs and manually raised PRs which are used to fix the npm audit on packages that have an security vulnerabilities issues
_"yarn. lock"_ and _"package. json"_ files
After Upgrading We tested the Sample App(Calling), It was working fine 
- Authentication
- Initialization
- Registration
- Call Initialization (outgoing call/incoming call)
- Call controls (hold/resume, mute/unmute)
- Call transfer (Blind transfer, Consult transfer)
After Upgrading We tested the Sample App(Meetings), It was working fine
- Initialization
- Registration
- Manage Meeting
- Streams   (local/remote)
- Screen share
- Participants section
- Advance Meetings control
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.m …
=> fix(deps): upgrading the dependencies to fix security vulnerabilities

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
Forcing WebRTC to use a software encoder for share video to work around https://issues.chromium.org/issues/40935853.
Updating WCME to only retain H.264 codecs in the SDP that have the constrained baseline profile. You can view the WCME changes here: https://sqbu-github.cisco.com/CPaaS/web-client-media-engine/pull/395
Tested on the WCME level. Also tested locally on the SDK sample app to see what H.264 profiles and encoder implementations are being used for share video, and comparing them to what's being used for main video.
---
=> fix(plugin-meetings): force share video to use software encoder

.github/workflows/deploy.yml
Changelog was not getting created because of git failure. 
Reason: While checking out in the github actions only the top commit was being fetched. So in tooling when we try to fetch the commit history it fails. By default fetch-depth is 1 i.e. only 1 commit is fetched.
While checking out the whole commit history is fetched. 
The only drawback is that the checkout process in the 'Publish Documentation' step takes more time. From 3sec it increased to 44secs.
In the below pipelines see the 'Update Changelog' step in the 'Publish Documentation' Step.
Failed Pipeline to reproduce the error - https://github.com/Shreyas281299/webex-js-sdk/actions/runs/10247253275/job/28346370691
Passing Pipeline with fix - https://github.com/Shreyas281299/webex-js-sdk/actions/runs/10249971932
< ENUMERATE TESTS …
=> fix(tooling): fix-changelog-tooling

docs/changelog/logs/v3_3_1.json
One of the PRs went into `next` branch before fixing the timestamp issue resulting in a corrupt timestamp for one log
In this PR we have manually updated the timestamp to the log based on timestamp from the log that was generated due to PR #3768 
| Before | After |
| --- | --- |
| <img width="1717" alt="Old" src="https://github.com/user-attachments/assets/33f3fc63-8de6-4c6f-8a49-5e0e7d355a9e"> | <img width="1717" alt="New" src="https://github.com/user-attachments/assets/049dc483-c190-4e5e-99c9-355a0af79ff8"> |
- Changelog was viewed locally to find everything in order (Screenshot attached)
---
=> fix(changelog): adjsut corrupt timestamp

docs/changelog/assets/js/app.js, docs/changelog/index.html
This PR is to simply add time to existing date stamp for published packages
- Adding time string along with date string in the Handlebar helper
- This PR also removes a `debugger` statement
- Additionally, this PR fixes links in nav bar to point JS SDK directory and not the root
| IST | BST | PDT |
| --- | --- | --- |
| <img width="1719" alt="IST" src="https://github.com/user-attachments/assets/a9fb37f3-14ef-4053-919c-0a0a7eeeee8c"> | <img width="1723" alt="BST" src="https://github.com/user-attachments/assets/b3637399-db6c-4164-b309-9b355bb619bd"> | <img width="1721" alt="PDT" src="https://github.com/user-attachments/assets/bd08c2f6-c900-468b-850e-125f2c11b616"> |
- Tested the time in various timezones by mocking Location from Browser
--- …
=> fix(changelog): add time to published date field

docs/changelog/index.html
The Version URL in the `alongWith` section was giving 404 due to a faulty URL mapping
Updated the anchor tag to search appropriate URL
---
=> chore(changelog): update faulty version url mapping

docs/samples/calling/app.js
Abstracts the guest access token creation logic for calling user into an AWS lambda function hiding all the sensitive info about the Service Apps and giving a simple endpoint to be accessed by Kitchen sink app.
Guest access token could be created by simply making an HTTP request to the lambda endpoint and used in the Kitchen sink app form which is what we have implemented in this PR.
**Screen Recording**
https://github.com/user-attachments/assets/7b140d08-70ef-4aac-9c80-addb73772252
Tested the Kitchen sink app after integrating the Lambda endpoint. It works!
---
=> fix(samples): udpate the guest calling token retrieval to from lambda

docs/changelog/assets/js/app.js, docs/changelog/index.html, docs/index.html
The help section is not available in today's changelog leading to confusion on how to use it. We also had package names not in order.
- Updating change log URLs to work in localhost, PR previews and GH Pages
- Arranging the package names in alphabetical order except for `webex` and `@webex/calling` packages which our customers use
- Adding a help section of sample searches and link to a Demo Vidcast of the whole new change log portal
**Watch the Demo Vidcast here**
https://app.vidcast.io/share/072f82d1-3735-4a13-8c74-1ece59723ff3
---
=> chore(changelog): alphabetical package list and help section

packages/@webex/internal-plugin-metrics/src/call-diagnostic/config.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
when ice and reachability fail with TLS - there is nothing we can do, it is a customer configuration issue. The error code is still surfaced and we can still find these customers with problematic configs and reach out to them. The culture around looking at skips is changing at the join get well program level, and we have been asked to move this to a skip. 
update network to expected
unit testing
---
=> fix(ca): adjust to expected when ice and reachability with TLS fail

docs/samples/calling/app.js, docs/samples/calling/index.html, packages/calling/src/CallingClient/CallingClient.test.ts, packages/calling/src/CallingClient/CallingClient.ts, packages/calling/src/CallingClient/line/index.ts, packages/calling/src/CallingClient/line/line.test.ts, packages/calling/src/CallingClient/registration/register.ts, packages/calling/src/CallingClient/types.ts, packages/calling/src/common/Utils.ts, packages/calling/src/common/types.ts
Adds changes required for registration flow to incorporate guest calling.
JWE and appropriate service data is passed to the registration method.
- Added JWT and guest token and tried to register. Checked with the API docs if the correct body is passed or not. Screen recording, logs and HAR file attached.
- UTs 
- Testd with mobius team with a mobius-server hosted locally.
[testing-with-local-mobius-server.zip](https://github.com/user-attachments/files/16677918/testing-with-local-mobius-server.zip)
---
=> feat(calling): guest-calling-registration

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
The task addresses an issue with wrongly calculated MQE for `availableBitrate` for the client.
Fix `availableBitrate` with exposing this data from WCME `availableOutgoingBitrate`
Tested with SDK test app, MQE and MQR exposes `availableBitrate` correctly.
---
=> fix: availableBitrate in media-core

packages/byods/README.md
This is an initial PR to test PRs into the feat/byods feature branch.
Creating a README file here for reference.
=> docs(byods): added initial readme file for byods

packages/@webex/media-helpers/package.json, packages/@webex/plugin-meetings/package.json, packages/calling/package.json, yarn.lock
This PR contains `webrtc-core` improvements to the device management functionality for conditional device permissions. 
Changes were made for webrtc-core (PR: https://github.com/webex/webrtc-core/pull/86). 
This my PR just upgrades media-core version with these changes.
- SDK test app logic flow works as expected from the description https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539683
---
=> fix: update internal-media-core with conditional device permissions fix

packages/calling/src/Metrics/index.ts
In the MS Teams app and MS Teams Webex calling integration app, the process object is not defined, causing a console error and breaking the voicemail flow. Added check to handle if the process object is not defined fallback to the default version
---
=> fix(voicemail): process check in metrics for voicemail

packages/@webex/internal-plugin-metrics/package.json, packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/src/metrics.types.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts, yarn.lock
sessionCorrelationId
sessionCorrelationId
---
=> feat(metrics): add session correlation id identifier

packages/calling/src/Metrics/index.ts
In the MS Teams app and MS Teams Webex Calling integration, the process object was not defined, which caused a console error and disrupted the voicemail flow. After adding a check for the process object, we still encountered a 'process is not defined' error. To resolve this, we implemented a typeof process !== 'undefined' check. After verifying the fix locally by connecting from MS Teams to the Calling SDK, the issue was resolved, and we are now able to see voicemail results in the MSFT Webex Calling Integration.
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) …
=> fix(voicemail): process-check-for-ms-teams-integration

packages/byods/src/byods/index.ts, packages/byods/src/types.ts, packages/byods/test/unit/spec/byods/index.ts
=> feat(byods): added verify jws token api

packages/calling/src/CallingClient/CallingClient.test.ts, packages/calling/src/CallingClient/CallingClient.ts
We were always using the US mobius cluster without taking into consideration the serviceUrl returned in the hostCatalog.
Infer the host from the serviceUrl and use the correct cluster, else use the default cluster
- I have connected to EU VPN and asserted that I hit the mobius EU cluster
- I connected to US VPN and asserted that I hit the mobius US cluster
[mobius use cluster defined in serviceUrl from hostCatalog.har.zip](https://github.com/user-attachments/files/17198298/mobius.use.cluster.defined.in.serviceUrl.from.hostCatalog.har.zip)
---
=> fix(mobius): mobius cluster should be inferred from serviceUrl in hostCatalog

.github/PULL_REQUEST_TEMPLATE.md, packages/@webex/plugin-meetings/src/breakouts/index.ts, packages/@webex/plugin-meetings/test/integration/spec/converged-space-meetings.js, packages/@webex/plugin-meetings/test/unit/spec/breakouts/index.ts, packages/@webex/plugin-meetings/test/unit/spec/interceptors/locusRetry.ts, packages/@webex/plugin-meetings/test/unit/spec/media/MediaConnectionAwaiter.ts, packages/@webex/plugin-meetings/test/unit/spec/media/index.ts, packages/@webex/plugin-meetings/test/unit/spec/media/properties.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/meetinginfov2.js, packages/@webex/plugin-meetings/test/unit/spec/meeting-info/request.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/connectionStateHandler.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/locusMediaRequest.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/request.js, packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js, packages/@webex/plugin-meetings/test/unit/spec/members/request.js, packages/@webex/plugin-meetings/test/unit/spec/multistream/mediaRequestManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlot.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/receiveSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMedia.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaGroup.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/remoteMediaManager.ts, packages/@webex/plugin-meetings/test/unit/spec/multistream/sendSlotManager.ts, packages/@webex/plugin-meetings/test/unit/spec/personal-meeting-room/personal-meeting-room.js, packages/@webex/plugin-meetings/test/unit/spec/reachability/request.js, packages/@webex/plugin-meetings/test/unit/spec/roap/request.ts
PR addresses issues where test cases run with `yarn workspace @webex/plugin-meetings test:unit ` that command works well until some new folders were added or old folders were removed and an issue with _"window is not defined"_ appeared.
Here is also [the task](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-566398) for further investigation, but this PR just fixes an issue with _"window is not defined"_ issue for existing tests cases that fail when run the command `yarn workspace @webex/plugin-meetings test:unit --targets "filename"`
- add missed imports for stubbing window object
- remove unused variables
- builds sdk successfully
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) …
=> test: fix window undefined issue for tests

packages/@webex/plugin-meetings/src/constants.ts, packages/@webex/plugin-meetings/src/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/in-meeting-actions.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
control interacting with Slido due to the cross org policies
add supportPollingAndQA in selfUserPolicies
---
=> feat(policy): add supportPollingAndQA policy for slido

packages/@webex/plugin-meetings/src/meeting/index.ts, packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
=> fix(ca): typo

packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts, packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
breaking fix change in current SDK version from: https://github.com/webex/webex-js-sdk/pull/3884
=> fix(ca): fix session correlation id unknown

packages/@webex/internal-plugin-encryption/src/kms.js
Add back in the required import removed by #3896 
---
=> fix(plugin-encryption): add back in required import

docs/changelog/assets/css/app.css, docs/changelog/assets/js/app.js, docs/changelog/index.html
A few issues in the change log UI currently:
* We cannot do a stable version search in the search input box
* The stable versions have longer commit list and there's no max height
* There's no link to change log for older versions
* Updated validation for version input to accept both `-next` versions as well as the exact stable version
* Added max height property for commit lists in the change log item and also added a permanently visible scrollbar
* Added a note for links to older change logs and also added a warning to the EoL announcement
* Tested by providing both stable version and `-next` version numbers in the version input field
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) …
=> docs(changelog): fix version search, add old changelogs links

packages/@webex/plugin-meetings/src/meetings/index.ts
This is to address PR comment from PR#3918
=> fix: added type for LocusInfo inside BasicMeetingInformation
